# Jupyter Notebook code
Import basis modules

In [1]:
import pandas as pd
import math
from geopy.distance import distance
import datetime

# Load shippping files

In [2]:
dfCapts = pd.read_csv("capts.csv", delimiter = ";")
dfCapts

,ais_capts_id,ship_id,ais_ship_id,ais_capts_imo,ais_capts_mmsi,ais_capts_name,ais_capts_draft,ais_capts_first,ais_capts_last,FromFile
0,1500818582,9263708,1245,9263708,220407000,TORM CARINA,"12,1",2014-01-01 09:58:09.000,2014-01-01 23:35:51.000,\\dksrv103\BIImportFiles\VesselsValue\capts-20...
1,1518673432,9263708,1245,9263708,220407000,TORM CARINA,"12,1",2014-01-09 01:02:44.000,2014-01-09 01:02:44.000,\\dksrv103\BIImportFiles\VesselsValue\capts-20...
2,1537070707,9263708,1245,9263708,220407000,TORM CARINA,12,2014-01-16 07:09:30.000,2014-01-16 10:57:45.000,\\dksrv103\BIImportFiles\VesselsValue\capts-20...
3,1548158482,9263708,1245,9263708,220407000,TORM CARINA,12,2014-01-20 13:30:16.000,2014-01-20 13:30:16.000,\\dksrv103\BIImportFiles\VesselsValue\capts-20...
4,1548640212,9263708,1245,9263708,220407000,TORM CARINA,12,2014-01-20 18:05:43.000,2014-01-20 18:05:43.000,\\dksrv103\BIImportFiles\VesselsValue\capts-20...
...,...,...,...,...,...,...,...,...,...,...
3596,9010637987,9425502,1314,9425502,220638000,TORM GYDA,"11,1",2019-02-27 07:24:57.000,2019-02-28 09:07:12.000,\\dksrv103\BIImportFiles\VesselsValue\capts-20...
3597,9029901534,9425502,1314,9425502,220638000,TORM GYDA,"11,1",2019-03-03 14:49:05.000,2019-03-06 06:55:18.000,\\dksrv103\BIImportFiles\VesselsValue\capts-20...
3598,9044520288,9425502,1314,9425502,220638000,TORM GYDA,"11,1",2019-03-06 20:05:32.000,2019-03-14 00:05:49.000,\\dksrv103\BIImportFiles\VesselsValue\capts-20...
3599,9084473323,9425502,1314,9425502,220638000,TORM GYDA,"11,1",2019-03-15 16:54:42.000,2019-03-22 18:11:23.000,\\dksrv103\BIImportFiles\VesselsValue\capts-20...
3600,9116314277,9425502,1314,9425502,220638000,TORM GYDA,"8,6",2019-03-22 19:00:38.000,2019-03-24 16:23:06.000,\\dksrv103\BIImportFiles\VesselsValue\capts-20...

In [3]:
dfFleet = pd.read_csv("fleet.csv", delimiter = ";")
dfFleet

,ship_id,ais_ship_id,ship_name,ship_imo,ship_mmsi,ship_type_name,ship_type_general,ship_status,ship_dead,FromFile
0,9263708,1245,Torm Carina,9263708,220407000,MR2 TNKR (Chem / Product) DW,TANKER,Live,NaN,\\dksrv103\BIImportFiles\VesselsValue\fleet_sh...
1,9290660,128867,Torm Platte,9290660,220561000,MR2 TNKR (Chem / Product) DW,TANKER,Live,NaN,\\dksrv103\BIImportFiles\VesselsValue\fleet_sh...
2,9425502,1314,Torm Gyda,9425502,220638000,MR1 TNKR (Chem / Product),TANKER,Live,NaN,\\dksrv103\BIImportFiles\VesselsValue\fleet_sh...

In [39]:
journeyPath = r'C:\Users\Sowaio\Desktop\Research Assistent\new data\journey\fleet_trade_journeys.csv'

dfJourney = pd.read_csv(journeyPath, error_bad_lines=False, delimiter = ",")
print(dfJourney.dtypes )

dfJourney[["journey_start_timestamp", "journey_end_timestamp"]] = dfJourney[["journey_start_timestamp", "journey_end_timestamp"]].apply(pd.to_datetime)
dfJourney ["journey_days"] = (dfJourney['journey_end_timestamp'] - dfJourney['journey_start_timestamp']).dt.days
dfJourney.dtypes

journey_id                           int64
ship_id                              int64
ais_ship_id                          int64
journey_laden                        int64
journey_start_stoppage_id            int64
journey_start_timestamp             object
journey_start_draft                float64
journey_start_latitude             float64
journey_start_longitude            float64
journey_start_location_type         object
journey_start_location_name         object
journey_start_location_country      object
journey_start_location_unlocode     object
journey_end_stoppage_id            float64
journey_end_timestamp               object
journey_end_draft                  float64
journey_end_latitude               float64
journey_end_longitude              float64
journey_end_location_type           object
journey_end_location_name           object
journey_end_location_country        object
journey_end_location_unlocode       object
journey_distance_nm                float64
journey_underway_calc_avg_speed    float64
journey_processed                   object
journey_current                      int64
journey_estimated_cargo_tons         int64
journey_underway_distance          float64
journey_underway_time_hours        float64
dtype: object

journey_id                                  int64
ship_id                                     int64
ais_ship_id                                 int64
journey_laden                               int64
journey_start_stoppage_id                   int64
journey_start_timestamp            datetime64[ns]
journey_start_draft                       float64
journey_start_latitude                    float64
journey_start_longitude                   float64
journey_start_location_type                object
journey_start_location_name                object
journey_start_location_country             object
journey_start_location_unlocode            object
journey_end_stoppage_id                   float64
journey_end_timestamp              datetime64[ns]
journey_end_draft                         float64
journey_end_latitude                      float64
journey_end_longitude                     float64
journey_end_location_type                  object
journey_end_location_name                  object
journey_end_location_country               object
journey_end_location_unlocode              object
journey_distance_nm                       float64
journey_underway_calc_avg_speed           float64
journey_processed                          object
journey_current                             int64
journey_estimated_cargo_tons                int64
journey_underway_distance                 float64
journey_underway_time_hours               float64
journey_days                              float64
dtype: object

In [5]:
dfPos = pd.read_csv("pos.csv", error_bad_lines=False, delimiter = ";")
dfPos

,ais_position_id,ais_ship_id,ais_position_mmsi,ais_position_timestamp,ais_position_latitude,ais_position_longitude,ais_position_course,ais_position_speed,ais_position_heading,nav_status_id,...,ais_position_satellite,ais_position_msg_type,ship_build_year,ship_id,ship_imo,ship_name,ship_size,ship_size_type,ship_status,FromFile
0,6390505,1245,220407000,2014-01-01 22:46:09.000,"25,83383","-79,76767",7,"15,3",7,0,...,999,1,2003,9263708,9263708,Torm Carina,46200,DWT,Live,\\dksrv103\BIImportFiles\VesselsValue\pos-2014...
1,7093068,1245,220407000,2014-01-02 05:10:42.000,"27,405","-79,36817",16,"14,4",18,0,...,0,1,2003,9263708,9263708,Torm Carina,46200,DWT,Live,\\dksrv103\BIImportFiles\VesselsValue\pos-2014...
2,13837840,1245,220407000,2014-01-03 21:08:51.000,"32,17817","-72,12183",73,10,70,0,...,999,3,2003,9263708,9263708,Torm Carina,46200,DWT,Live,\\dksrv103\BIImportFiles\VesselsValue\pos-2014...
3,19216068,1245,220407000,2014-01-04 20:19:18.000,"31,00867","-67,29733",113,"11,7",111,0,...,999,3,2003,9263708,9263708,Torm Carina,46200,DWT,Live,\\dksrv103\BIImportFiles\VesselsValue\pos-2014...
4,24510838,1245,220407000,2014-01-05 19:33:51.000,"30,5055","-62,76467",51,"10,9",55,0,...,999,3,2003,9263708,9263708,Torm Carina,46200,DWT,Live,\\dksrv103\BIImportFiles\VesselsValue\pos-2014...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5066,25890001829,1314,220638000,2019-03-18 23:40:45.000,"11,76032","-70,27425","259,7",0,80,1,...,0,3,2009,9425502,9425502,Torm Gyda,36200,DWT,Live,\\dksrv103\BIImportFiles\VesselsValue\pos-2019...
5067,25904273380,1314,220638000,2019-03-19 23:28:46.000,"11,76081","-70,27495","309,4",0,93,1,...,0,3,2009,9425502,9425502,Torm Gyda,36200,DWT,Live,\\dksrv103\BIImportFiles\VesselsValue\pos-2019...
5068,25918872519,1314,220638000,2019-03-20 23:52:17.000,"11,74888","-70,21685","47,9",0,73,5,...,0,3,2009,9425502,9425502,Torm Gyda,36200,DWT,Live,\\dksrv103\BIImportFiles\VesselsValue\pos-2019...
5069,25933067041,1314,220638000,2019-03-21 23:40:19.000,"11,74887","-70,21681","47,9",0,73,5,...,0,3,2009,9425502,9425502,Torm Gyda,36200,DWT,Live,\\dksrv103\BIImportFiles\VesselsValue\pos-2019...
5070,25947437750,1314,220638000,2019-03-22 23:20:35.000,"11,62025","-70,23299","11,8","0,2",60,0,...,999,1,2009,9425502,9425502,Torm Gyda,36200,DWT,Live,\\dksrv103\BIImportFiles\VesselsValue\pos-2019...

In [3]:
dfStoppages = pd.read_csv("stoppages.csv", error_bad_lines=False, delimiter = ";")
dfStoppages

,stoppage_id,ship_id,ais_ship_id,stoppage_first_time,stoppage_first_draft,stoppage_first_nav_status_id,stoppage_first_nav_status_desc,stoppage_first_lat,stoppage_first_long,stoppage_last_time,...,stoppage_location_name,stoppage_location_country_name,stoppage_location_unlocode,stoppage_modal_draft,stoppage_status_desc,stoppage_dist_since_prev,stoppage_time_since_prev,stoppage_processed,stoppage_current,FromFile
0,875495113,9263708,1245,2014-01-19 13:57:08.000,12,0,Under way using engine,"9,37938","-79,92864",2014-01-20 01:20:33.000,...,Colon,Panama,PAONX,"12,1",Awaiting Transit,5936.191445,1812744,2019-03-28 06:56:36.000,0,\\dksrv103\BIImportFiles\VesselsValue\fleet_tr...
1,875495114,9263708,1245,2014-01-20 02:31:16.000,12,0,Under way using engine,"9,28425","-79,92175",2014-01-20 05:11:27.000,...,Gatun Locks,Panama,NaN,12,In Transit,5.897571,4243,2019-03-28 06:56:36.000,0,\\dksrv103\BIImportFiles\VesselsValue\fleet_tr...
2,875495115,9263708,1245,2014-01-20 06:10:15.000,12,0,Under way using engine,"9,23003","-79,92675",2014-01-20 18:27:17.000,...,Cristobal,Panama,PACTB,12,Awaiting Transit,2.335405,3528,2019-03-28 06:56:36.000,0,\\dksrv103\BIImportFiles\VesselsValue\fleet_tr...
3,875495116,9263708,1245,2014-01-20 22:47:03.000,12,0,Under way using engine,"9,02052","-79,61628",2014-01-21 01:09:42.000,...,Pedro Miguel,Panama,NaN,12,In Transit,24.031691,15586,2019-03-28 06:56:36.000,0,\\dksrv103\BIImportFiles\VesselsValue\fleet_tr...
4,875495117,9263708,1245,2014-01-21 01:57:33.000,12,0,Under way using engine,"9,0006","-79,59581",2014-01-21 03:13:51.000,...,Miraflores Locks,Panama,NaN,12,In Transit,0.896438,2871,2019-03-28 06:56:36.000,0,\\dksrv103\BIImportFiles\VesselsValue\fleet_tr...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1367,898542515,9425502,1314,2019-02-20 04:09:57.000,"7,5",0,Under way using engine,"51,93624","3,76239",2019-02-23 19:36:23.000,...,Rotterdam,Netherlands,NLRTM,"7,5",Waiting to Load,23.046334,9725,2019-03-28 06:56:36.000,0,\\dksrv103\BIImportFiles\VesselsValue\fleet_tr...
1368,898542516,9425502,1314,2019-02-23 22:14:25.000,"7,5",5,Moored,"51,91478","4,22083",2019-02-24 23:02:14.000,...,Chemtrade Terminal,Netherlands,NLRTM,"7,5",Load,20.368785,9482,2019-03-28 06:56:36.000,0,\\dksrv103\BIImportFiles\VesselsValue\fleet_tr...
1369,898542517,9425502,1314,2019-02-24 23:19:27.000,"7,5",0,Under way using engine,"51,92553","4,20224",2019-02-26 20:58:19.000,...,Euro Tank Terminals,Netherlands,NLRTM,"7,5",Load,0.910833,1033,2019-03-28 06:56:36.000,0,\\dksrv103\BIImportFiles\VesselsValue\fleet_tr...
1370,898542518,9425502,1314,2019-03-15 17:22:38.000,"11,1",1,At anchor,"11,76061","-70,27403",2019-03-20 15:32:32.000,...,Amuay Bay,Venezuela,VEAMY,"11,1",Waiting to Discharge,4435.478756,1455859,2019-03-28 06:56:36.000,0,\\dksrv103\BIImportFiles\VesselsValue\fleet_tr...
1371,898542519,9425502,1314,2019-03-20 17:16:16.000,"11,1",0,Under way using engine,"11,74889","-70,21683",2019-03-22 21:21:18.000,...,Amuay Bay,Venezuela,VEAMY,"11,1",Discharge,3.721623,6224,2019-03-28 06:56:36.000,0,\\dksrv103\BIImportFiles\VesselsValue\fleet_tr...

Import port list

In [ ]:
dfCorrPorts = pd.read_excel("\\Users\\Sowaio\\Desktop\\Research Assistent\\RE__[EXTERNAL]_RE__Fairplay_and_AIS_data\\PortList Gang.xlsx")

dfCorrPorts = dfCorrPorts.rename(columns = {"Terminal": "Ports", "Lat": "Latitude", "Lon": "Longtitude", "Region": "Gruppe"})

Import entire folders using glob. Used in folders with multiple files of similar nature

In [3]:
import glob

captPath = r'C:\Users\Sowaio\Desktop\Research Assistent\new data\capts' # use your path
capt_files = glob.glob(captPath + "/*.csv")

capt = []

for filename in capt_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    capt.append(df)

dfCapt = pd.concat(capt, axis=0, ignore_index=True)

dfCapt

,ais_capts_id,ship_id,ais_ship_id,ais_capts_imo,ais_capts_mmsi,ais_capts_name,ais_capts_draft,ais_capts_first,ais_capts_last
0,1501171424,9301421,97,9301421,209110000,VICTOR KONETSKY,9.0,2014-01-01 13:02:41,2014-01-01 13:02:41
1,1504502617,9301421,97,9301421,209110000,VICTOR KONETSKY,14.2,2014-01-03 12:02:41,2014-01-03 23:50:41
2,1505949610,9301421,97,9301421,209110000,VICTOR KONETSKY,14.2,2014-01-04 01:26:39,2014-01-04 13:02:38
3,1516144982,9301421,97,9301421,209110000,VICTOR KONETSKY,9.0,2014-01-08 02:55:42,2014-01-08 23:02:19
4,1526151258,9301421,97,9301421,209110000,VICTOR KONETSKY,9.0,2014-01-12 02:14:14,2014-01-12 23:50:14
...,...,...,...,...,...,...,...,...,...
6107887,9113811022,10093377,1030782,9833656,538000700,NAVIG8 GRACE,0.0,2019-03-22 05:46:11,2019-03-22 05:46:11
6107888,9113909638,10093377,1030782,9833656,538000700,NAVIG8 GRACE,0.0,2019-03-22 06:16:16,2019-03-22 06:16:16
6107889,9114005580,10093377,1030782,9833656,538000700,NAVIG8 GRACE,0.0,2019-03-22 06:46:14,2019-03-22 06:46:14
6107890,9114123027,10093377,1030782,9833656,538000700,NAVIG8 GRACE,0.0,2019-03-22 07:22:14,2019-03-22 07:22:14
6107891,9114221704,10093377,1030782,9833656,538000700,NAVIG8 GRACE,0.0,2019-03-22 07:52:13,2019-03-22 07:52:13

In [4]:
posPath = r'C:\Users\Sowaio\Desktop\Research Assistent\new data\pos' # use your path
pos_files = glob.glob(posPath + "/*.csv")

pos = []

for filename in pos_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    pos.append(df)

dfPos = pd.concat(pos, axis=0, ignore_index=True)
dfPos[["ais_position_timestamp"]] = dfPos[["ais_position_timestamp"]].apply(pd.to_datetime)
#dfPos = dfPos[["ais_position_latitude", "ais_position_longitude", "ais_position_timestamp", "ship_imo", "nav_status_desc"]]



dfPos

,ais_position_id,ais_ship_id,ais_position_mmsi,ais_position_timestamp,ais_position_latitude,ais_position_longitude,ais_position_speed,ais_position_course,ais_position_heading,nav_status_id,...,special_maneuvre_desc,ais_position_satellite,ais_position_msg_type,ship_build_year,ship_id,ship_imo,ship_name,ship_size,ship_size_type,f.ship_status
0,3237546,97,209110000,2014-01-01 13:01:04,51.45500,140.92503,0.0,288.0,233,1,...,Unavailable,999,3,2005,9301421,9301421,Victor Konetsky,101000,DWT,Live
1,8442368,97,209110000,2014-01-02 12:31:21,51.46248,140.90523,0.0,177.0,268,5,...,Unavailable,999,3,2005,9301421,9301421,Victor Konetsky,101000,DWT,Live
2,14080197,97,209110000,2014-01-03 22:18:59,48.74732,140.77492,15.4,203.0,204,0,...,Unavailable,999,1,2005,9301421,9301421,Victor Konetsky,101000,DWT,Live
3,19397589,97,209110000,2014-01-04 23:34:08,43.20852,136.17353,14.8,210.0,212,0,...,Unavailable,999,1,2005,9301421,9301421,Victor Konetsky,101000,DWT,Live
4,24273113,97,209110000,2014-01-05 21:30:08,38.53695,132.48110,15.0,211.0,211,0,...,Unavailable,999,1,2005,9301421,9301421,Victor Konetsky,101000,DWT,Live
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6050007,25909083581,1030385,636019104,2019-03-20 07:32:20,35.50135,129.39545,0.0,263.1,-1,15,...,Unavailable,0,1,2019,10103541,9847451,Doric Courage,50000,DWT,Launched
6050008,25933223141,1030385,636019104,2019-03-21 23:57:39,35.50128,129.39549,0.1,190.6,13,15,...,Unavailable,0,1,2019,10103541,9847451,Doric Courage,50000,DWT,Launched
6050009,25937124405,1030385,636019104,2019-03-22 06:25:58,35.50134,129.39544,0.1,235.2,13,15,...,Unavailable,0,1,2019,10103541,9847451,Doric Courage,50000,DWT,Launched
6050010,25923726259,1030782,538000700,2019-03-21 07:40:57,32.05095,120.42295,0.0,0.0,235,15,...,Unavailable,0,1,2019,10093377,9833656,Navig8 Grace,49000,DWT,Launched
6050011,25938065075,1030782,538000700,2019-03-22 07:50:20,32.05092,120.42295,0.0,0.0,224,15,...,Unavailable,0,3,2019,10093377,9833656,Navig8 Grace,49000,DWT,Launched

# Code for creating leg table

this code is triggered elsewhere.

Many of the values in the legTable are taken from the torm leg table.

The exception is the distance calculations which are calculated using geopy, if there are valid numbers to calculate.

In [40]:
def createLegTable(JourneyDF, posDF, portsDF, LegTable, indexCount):
    count = 0
    for index, row in JourneyDF.iterrows():
        count += 1
        coordDist = 0
        preLat = None
        preLong = None

        startDate = row["journey_start_timestamp"]
        endDate = row["journey_end_timestamp"]
        ImoNr = row["ship_id"]

        #imoNr + port
        LegTable.at[index, "ImoNr"] = row["ship_id"]
        LegTable.at[index, "Departure_Port"] = row["journey_start_location_name"] #
        LegTable.at[index, "Destination_Port"] = row["journey_end_location_name"]

        #Time
        LegTable.at[index, "journey_start_timestamp"] = startDate
        LegTable.at[index, "Min. ReportClosure-updated"] = endDate

        dfDepaPorts = portsDF.loc[portsDF["Ports"] == row["journey_start_location_name"]]
        dfDestPorts = portsDF.loc[portsDF["Ports"] == row["journey_end_location_name"]]

        depaPortLat = 0
        depaPortLong = 0

        destPortLat = 0
        destPortLong = 0
        
        try:
            LegTable.at[index, "RegionDepa"] = dfDepaPorts["Gruppe"].values.item(-1)
            depaPortLat = float(dfDepaPorts["Latitude"].values.item(-1) )
            LegTable.at[index, "Depature_port_latitude"] = str(depaPortLat).replace(".", ",")
            depaPortLong = float(dfDepaPorts["Longtitude"].values.item(-1) )
            LegTable.at[index, "Depature_port_longtitude"] = str(depaPortLong).replace(".", ",")
        except: 
            LegTable.at[index, "RegionDepa"] = 404
            LegTable.at[index, "Depature_port_latitude"] = 404
            LegTable.at[index, "Depature_port_longtitude"] = 404
        try:
            LegTable.at[index, "RegionDest"] = dfDestPorts["Gruppe"].values.item(-1)
            destPortLat = dfDestPorts["Latitude"].values.item(-1)
            LegTable.at[index, "Destination_port_latitude"] = str(destPortLat).replace(".", ",")
            destPortLong = dfDestPorts["Longtitude"].values.item(-1)
            LegTable.at[index, "Destination_port_longtitude"] = str(destPortLong).replace(".", ",")
        except: 
            LegTable.at[index, "RegionDest"] = 404
            LegTable.at[index, "Destination_port_latitude"] = 404
            LegTable.at[index, "Destination_port_longtitude"] = 404

     
        filtDF = posDF.loc[(posDF["ais_position_timestamp"].apply(pd.to_datetime) >= startDate) & (posDF["ais_position_timestamp"].apply(pd.to_datetime) <= endDate) & (posDF["ship_imo"] == ImoNr)]
        realCountOfIndex = 0
        realBestDest = 0
        realLat = 0
        realLong = 0
        realDist = 0
        countOfIndex = 0
        newEndTime = 0
      
        
        for filtIndex, filtRow in filtDF.iterrows():
            #newEndTime = 0
            #countOfIndex += 1
            
            lat = filtRow["ais_position_latitude"]
            long = filtRow["ais_position_longitude"]
            
            if type(lat) != float():
                lat = str(lat).replace(",", ".")
            if type(long) != float():
                long = str(long).replace(",", ".")
            anchorPoint = filtRow["nav_status_desc"]

            if preLat is not None:
                try:
                    dist = distance((lat, long), (preLat, preLong)).miles * 0.868976242
                    coordDist += round(dist, 2)
                except:
                    print("Failure here:")
                    print(lat, long, preLat, preLong)
                    preLat = 0
                    preLong = 0
            

            if anchorPoint == "At anchor" and filtIndex != 1 or anchorPoint == "Moored" and filtIndex != 1 or anchorPoint == "At anchor" and filtIndex != 0 or anchorPoint == "Moored" and filtIndex != 0:
                try:
                    bestDest = distance((lat, long), (destPortLat, destPortLong)).miles * 0.868976242
                except:
                    print("Fail here:")
                    print(lat, long, preLat, preLong)
                    bestDest = 9999
                

                if bestDest <= realBestDest and bestDest != 0:
                    realBestDest = bestDest
                    realLat = lat
                    realLong = long
                    realDist = coordDist
                    realCountOfIndex = countOfIndex
                    newEndTime = filtRow["ais_position_timestamp"]
                if bestDest == 9999:
                    pass
                elif realBestDest == 0:
                    realBestDest = bestDest
                    newEndTime = filtRow["ais_position_timestamp"]
                

            preLat = lat
            preLong = long
            #filtCount = int(countOfIndex)
        #LegTable.at[index, "Leg_id_legs (# of reports)"] = filtCount
        LegTable.at[index, "Leg_id_legs (# of reports)"] = filtDF["ais_position_longitude"].count()
        
        LegTable.at[index, "(closest anchor point to port) journey_end_timestamp"] = newEndTime

        #if realDist != 0:
         #   coordDist = realDist

        dfLegTable.at[index, "Coordinate_distance_sum"] = str(coordDist).replace(".", ",")

        #get days
        legLengthsDay = row["journey_underway_time_hours"]
        legLengthsDay = float(str(legLengthsDay).replace(",", ".")) 
        #print(float(legLengthsDay) )
        legLengthsDay = round(legLengthsDay / 24, 0)

        try:
            newEndTime = newEndTime.split(" ")[0]
            endDate = datetime.datetime.strptime(str(newEndTime), '%Y-%m-%d')
        except: pass


        daysTravelled = (endDate - startDate).days
        LegTable.at[index, "Leg Length (days covered)"] = daysTravelled
        #dfLegTable.at[index, "Leg Length (days covered)"] = row["journey_days"]
        LegTable.at[index, "Loading Condition"] = row["journey_laden"]

        #distance
        LegTable.at[index, "Logged_distance_sum"] = str(row["journey_underway_distance"]).replace(".", ",") #
        LegTable.at[index, "Avg. Speed-Median"] = str(row["journey_underway_calc_avg_speed"]).replace(".", ",")
        
        LegTable.at[index, "journey_id"] = row['journey_id']
        NoFilterDt = False
        try:
            firstRowFilt = filtDF.iloc[0]
            firstRowLat = str(firstRowFilt["ais_position_latitude"]).replace(",", ".")
            firstRowLong = str(firstRowFilt["ais_position_longitude"]).replace(",", ".")
        except:
            NoFilterDt = True


        try:
            if realDist != 0:
                lastRowLat = realLat
                lastRowLong = realLong
            else:
                lastRowFilt = filtDF.iloc[-1]
                lastRowLat = str(lastRowFilt["ais_position_latitude"]).replace(",", ".")
                lastRowLong = str(lastRowFilt["ais_position_longitude"]).replace(",", ".")
        except: 
            pass
        
        if NoFilterDt == False:
            firstRowDist = 0
            
            try:
                if depaPortLat != 404 and depaPortLong != 404 and depaPortLat != 0:
                    firstRowDist = distance((depaPortLat, depaPortLong), (firstRowLat, firstRowLong)).miles * 0.868976242
                    coordDist += firstRowDist
                else:
                    firstRowDist = 404
            except:
                firstRowDist = 404

            lastRowDist = 0
            try: 
                if destPortLat != 404 and destPortLong != 404 and destPortLat != 0:
                    lastRowDist = distance((destPortLat, destPortLong), (lastRowLat, lastRowLong)).miles * 0.868976242
                    coordDist += lastRowDist
                else:
                    lastRowDist = 404
            except: 
                lastRowDist = 404
                
            LegTable.at[index, "Distance to departure port"] = str(firstRowDist).replace(".", ",")
            LegTable.at[index, "Distance to destination port"] = str(lastRowDist).replace(".", ",")
        else:
            pass
        
        LegTable.at[index, "Journey table start Draught"] = row["journey_start_draft"]
        LegTable.at[index, "Journey table start Draught"] = row["journey_end_draft"]
        LegTable.at[index, "Journey table start Draught"] = row["journey_start_draft"]
        
        if count%500 == 0:
            LegTable.to_csv("over 3000 Leg Table.csv", sep = ";", index = False)
            print("=====================================")
            print(index)
        count += 1
    LegTable.to_csv("over 3000 Leg Table.csv", sep = ";", index = False)
    return LegTable

 # quick code for seeing what ship-ids are the same in the journey table and the position table-

In [6]:
col = ["Ship_id", "# of appearences in journey sheet", "# of appearences in pos sheet"]
dfNewTable = pd.DataFrame(columns = col)

test = pd.DataFrame(dfJourney["ship_id"].value_counts().reset_index().values, columns=["Ship_id", "# of appearences in journey sheet"])
test2 = pd.DataFrame(dfPos["ship_id"].value_counts().reset_index().values, columns=["Ship_id", "# of appearences in pos sheet"])

print(len(test))
print(len(test2))

test2["Ship_id"] = test2["Ship_id"].astype(str).astype(int)


#result = pd.merge(test, test2, on=['Ship_id', 'Ship_id'])


for index, row in test.iterrows():
    ship = row["Ship_id"]
    testDF = test2.loc[(test2["Ship_id"] == ship)]
    ks = testDF["# of appearences in pos sheet"].sum()
    test.at[index, "# of appearences in pos sheet"] = ks
    if index % 100 == 0:
        print("iterated through:", index)


test.to_excel("Number of shipID.xlsx")

4266
3974
iterated through: 0
iterated through: 100
iterated through: 200
iterated through: 300
iterated through: 400
iterated through: 500
iterated through: 600
iterated through: 700
iterated through: 800
iterated through: 900
iterated through: 1000
iterated through: 1100
iterated through: 1200
iterated through: 1300
iterated through: 1400
iterated through: 1500
iterated through: 1600
iterated through: 1700
iterated through: 1800
iterated through: 1900
iterated through: 2000
iterated through: 2100
iterated through: 2200
iterated through: 2300
iterated through: 2400
iterated through: 2500
iterated through: 2600
iterated through: 2700
iterated through: 2800
iterated through: 2900
iterated through: 3000
iterated through: 3100
iterated through: 3200
iterated through: 3300
iterated through: 3400
iterated through: 3500
iterated through: 3600
iterated through: 3700
iterated through: 3800
iterated through: 3900
iterated through: 4000
iterated through: 4100
iterated through: 4200

# Trigger the legtable creator

In [42]:
"""
Nyt leg table skal have

ImoNr; Leg_id_legs (# of reports); Leg Length (days covered); Avg. Speed-Median; Avg. speed by time weight; 
std of Speed-Median; # of ME-Power reports; # of valid ME-Power reports; Min_Max_Draft_Normalization;
Loading Condition; Min. ReportClosure-updated; Departure_Port; Destination_Port; DistanceToPilotStation;
Observed_distance_sum; Logged_distance_sum; Coordinate_distance_sum; Median_distance_sum;
Depature_port_latitude ;Depature_port_longtitude ;Destination_port_latitude ;Destination_port_longtitude ;
Distance to departure port ;Distance to destination port ;RegionDepa ;RegionDest
"""


"""
columns = The columns wanted in the new leg table

dfJourney = sorted dfJourney imported from above, this value is later filtered to only include the journeys over 3000nautical miles
dfPos = sorted dfPos imported from above

lenPos = length of position

shipID = unique ship ID

BASIS logic in for loop.

for every unique shipID:
    filter position table on shipID
    filter journey table on shipID
    
    if either of the filtered tables are not empty:
        Using the dates and shipID to take a subset of the torm "leg table"
        trigger leg table creation code, this returns a leg table of the shipID
"""


columns = ["journey_id","ImoNr", "ship type", "Leg_id_legs (# of reports)", "Leg Length (days covered)", "Avg. Speed-Median", "Avg. speed by time weight", 
"std of Speed-Median", "# of ME-Power reports", "# of valid ME-Power reports", "Journey table start Draught", "Journey table end Draught", "Min_Max_Draft_Normalization",
"Loading Condition", "Departure_Port", "Destination_Port", "DistanceToPilotStation",
"Observed_distance_sum", "Logged_distance_sum", "Coordinate_distance_sum", "Median_distance_sum",
"Depature_port_latitude", "Depature_port_longtitude", "Destination_port_latitude", "Destination_port_longtitude",
"Distance to departure port", "Distance to destination port", "RegionDepa", "RegionDest",
"journey_start_timestamp", "Min. ReportClosure-updated", "(closest anchor point to port) journey_end_timestamp"]

dfLegTable = pd.DataFrame(columns = columns)

#dfLegTable = pd.read_csv("Leg Table.csv")

dfJourney = dfJourney.sort_values(['journey_start_timestamp'])
dfPos = dfPos.sort_values(['ais_position_timestamp'])



lenPos = len(dfPos)
dfJourney = dfJourney[dfJourney["journey_distance_nm"] >= 3000]



shipID = dfJourney["ship_id"].unique()

countIm = 0
for i in shipID:
    start = 0
    end = 7000
    dfNewPos = dfPos.loc[(dfPos["ship_imo"] == i)]
    #print(dfNewPos)
    dfNewJourney = dfJourney.loc[(dfJourney["ship_id"] == i)]
    print("dfNewJourney", len(dfNewJourney))
    lenPos = len(dfNewPos)
    print('lenPos', lenPos)
    done = False
    print("I = ", i)
    countIm += 1
    print("number of imo", countIm)
    if dfNewPos.empty == True or dfNewJourney.empty == True:
        pass
    else:
        while not done:

            dfTempPos = dfNewPos[start : end]
            df = dfTempPos
            df[["ais_position_timestamp"]] = dfTempPos[["ais_position_timestamp"]].apply(pd.to_datetime)
            df = df.sort_values(['ais_position_timestamp'])
            startDate = df["ais_position_timestamp"].iloc[0]
            endDate = df["ais_position_timestamp"].iloc[-1]

            print(len(df))

            dfTestTable = dfNewJourney.loc[(dfNewJourney["journey_start_timestamp"] >= startDate) & (dfNewJourney["journey_end_timestamp"].apply(pd.to_datetime) <= endDate)]

            indexCount = dfLegTable["ImoNr"].count()
            indexCount = 0

            dfLegTable = createLegTable(dfTestTable, df, dfCorrPorts, dfLegTable, indexCount)

            if end > lenPos:
                dfLegTable = createLegTable(dfTestTable, df, dfCorrPorts, dfLegTable, indexCount)
                dfLegTable.to_csv("over 3000 Leg Table.csv", sep = ";",  index = False)
                done = True
            else:
                start += 5000
                end += 5000
                percentage = (end / lenPos) * 100
                print("end", end, "percentage", percentage)
        print("===============")

dfNewJourney 3
lenPos 0
I =  8705735
number of imo 1
dfNewJourney 1
lenPos 1093
I =  9198783
number of imo 2
1093
===============
dfNewJourney 1
lenPos 0
I =  7342005
number of imo 3
dfNewJourney 2
lenPos 0
I =  8109668
number of imo 4
dfNewJourney 2
lenPos 0
I =  9138886
number of imo 5
dfNewJourney 1
lenPos 0
I =  8920086
number of imo 6
dfNewJourney 7
lenPos 1259
I =  8302416
number of imo 7
1259
===============
dfNewJourney 11
lenPos 1856
I =  9249099
number of imo 8
1856
===============
dfNewJourney 37
lenPos 1262
I =  9374856
number of imo 9
1262
===============
dfNewJourney 1
lenPos 618
I =  8805004
number of imo 10
618
===============
dfNewJourney 3
lenPos 0
I =  8919116
number of imo 11
dfNewJourney 1
lenPos 0
I =  8421183
number of imo 12
dfNewJourney 1
lenPos 0
I =  8419178
number of imo 13
dfNewJourney 10
lenPos 1341
I =  8822442
number of imo 14
1341
===============
dfNewJourney 34
lenPos 1617
I =  9480162
number of imo 15
1617
===============
dfNewJourney 6
lenPos 1360
I =  8117158
number of imo 16
1360
===============
dfNewJourney 1
lenPos 1280
I =  8413502
number of imo 17
1280
===============
dfNewJourney 1
lenPos 1172
I =  8508292
number of imo 18
1172
===============
dfNewJourney 1
lenPos 404
I =  9422990
number of imo 19
404
===============
dfNewJourney 1
lenPos 0
I =  8026218
number of imo 20
dfNewJourney 2
lenPos 1263
I =  9105061
number of imo 21
1263
===============
dfNewJourney 36
lenPos 1625
I =  9234496
number of imo 22
1625
===============
dfNewJourney 12
lenPos 0
I =  8920866
number of imo 23
dfNewJourney 20
lenPos 1092
I =  9299721
number of imo 24
1092
===============
dfNewJourney 16
lenPos 676
I =  8822466
number of imo 25
676
===============
dfNewJourney 1
lenPos 0
I =  9144770
number of imo 26
dfNewJourney 1
lenPos 0
I =  9105097
number of imo 27
dfNewJourney 1
lenPos 0
I =  8917792
number of imo 28
dfNewJourney 1
lenPos 0
I =  8609644
number of imo 29
dfNewJourney 3
lenPos 1794
I =  9212008
number of imo 30
1794
===============
dfNewJourney 16
lenPos 1864
I =  9293985
number of imo 31
1864
===============
dfNewJourney 3
lenPos 0
I =  8701507
number of imo 32
dfNewJourney 8
lenPos 1136
I =  9187631
number of imo 33
1136
===============
dfNewJourney 1
lenPos 1874
I =  9410882
number of imo 34
1874
===============
dfNewJourney 2
lenPos 1387
I =  8705618
number of imo 35
1387
===============
dfNewJourney 7
lenPos 579
I =  9189122
number of imo 36
579
===============
dfNewJourney 4
lenPos 0
I =  8400933
number of imo 37
dfNewJourney 4
lenPos 1814
I =  9518907
number of imo 38
1814
===============
dfNewJourney 15
lenPos 1810
I =  9414802
number of imo 39
1810
===============
dfNewJourney 1
lenPos 0
I =  8715479
number of imo 40
dfNewJourney 4
lenPos 1830
I =  9172870
number of imo 41
1830
===============
dfNewJourney 2
lenPos 0
I =  8806199
number of imo 42
dfNewJourney 1
lenPos 1648
I =  9211999
number of imo 43
1648
===============
dfNewJourney 10
lenPos 1688
I =  9331153
number of imo 44
1688
===============
dfNewJourney 17
lenPos 0
I =  7816549
number of imo 45
dfNewJourney 22
lenPos 1847
I =  9577111
number of imo 46
1847
===============
dfNewJourney 3
lenPos 1823
I =  9079183
number of imo 47
1823
===============
dfNewJourney 5
lenPos 923
I =  9117507
number of imo 48
923
===============
dfNewJourney 3
lenPos 0
I =  8206947
number of imo 49
dfNewJourney 12
lenPos 1703
I =  9145437
number of imo 50
1703
===============
dfNewJourney 34
lenPos 1795
I =  9254850
number of imo 51
1795
===============
dfNewJourney 38
lenPos 1810
I =  9298325
number of imo 52
1810
===============
dfNewJourney 2
lenPos 0
I =  9008718
number of imo 53
dfNewJourney 29
lenPos 1664
I =  9457713
number of imo 54
1664
===============
dfNewJourney 2
lenPos 0
I =  7925792
number of imo 55
dfNewJourney 18
lenPos 1544
I =  9147447
number of imo 56
1544
===============
dfNewJourney 11
lenPos 0
I =  9111046
number of imo 57
dfNewJourney 1
lenPos 0
I =  8808501
number of imo 58
dfNewJourney 8
lenPos 1873
I =  9331141
number of imo 59
1873
===============
dfNewJourney 5
lenPos 1442
I =  9113551
number of imo 60
1442
===============
dfNewJourney 29
lenPos 1812
I =  9165281
number of imo 61
1812
===============
dfNewJourney 39
lenPos 1787
I =  9332638
number of imo 62
1787
===============
dfNewJourney 4
lenPos 1241
I =  9081382
number of imo 63
1241
===============
dfNewJourney 32
lenPos 1829
I =  9456915
number of imo 64
1829
===============
dfNewJourney 21
lenPos 0
I =  10007594
number of imo 65
dfNewJourney 5
lenPos 1846
I =  8619455
number of imo 66
1846
===============
dfNewJourney 24
lenPos 1614
I =  8314158
number of imo 67
1614
===============
dfNewJourney 15
lenPos 1814
I =  9414838
number of imo 68
1814
===============
dfNewJourney 1
lenPos 1808
I =  9234501
number of imo 69
1808
===============
dfNewJourney 3
lenPos 0
I =  8812784
number of imo 70
dfNewJourney 6
lenPos 1516
I =  8808513
number of imo 71
1516
===============
dfNewJourney 17
lenPos 1725
I =  9285859
number of imo 72
1725
===============
dfNewJourney 19
lenPos 1539
I =  9247390
number of imo 73
1539
===============
dfNewJourney 18
lenPos 1616
I =  9040455
number of imo 74
1616
===============
dfNewJourney 9
lenPos 0
I =  8910706
number of imo 75
dfNewJourney 9
lenPos 0
I =  9083304
number of imo 76
dfNewJourney 57
lenPos 1747
I =  9467732
number of imo 77
1747
===============
dfNewJourney 1
lenPos 0
I =  9006899
number of imo 78
dfNewJourney 34
lenPos 1844
I =  9414278
number of imo 79
1844
===============
dfNewJourney 13
lenPos 1601
I =  9228837
number of imo 80
1601
===============
dfNewJourney 14
lenPos 0
I =  9167033
number of imo 81
dfNewJourney 12
lenPos 758
I =  8906602
number of imo 82
758
===============
dfNewJourney 11
lenPos 1872
I =  9344930
number of imo 83
1872
===============
dfNewJourney 17
lenPos 1265
I =  9455789
number of imo 84
1265
===============
dfNewJourney 2
lenPos 1816
I =  9187772
number of imo 85
1816
===============
dfNewJourney 5
lenPos 0
I =  8817655
number of imo 86
dfNewJourney 4
lenPos 0
I =  8301802
number of imo 87
dfNewJourney 22
lenPos 1866
I =  9431381
number of imo 88
1866
===============
dfNewJourney 39
lenPos 1334
I =  9154000
number of imo 89
1334
===============
dfNewJourney 13
lenPos 1233
I =  9134713
number of imo 90
1233
===============
dfNewJourney 41
lenPos 1835
I =  9280354
number of imo 91
1835
===============
dfNewJourney 2
lenPos 0
I =  8419013
number of imo 92
dfNewJourney 43
lenPos 1794
I =  9434230
number of imo 93
1794
===============
dfNewJourney 3
lenPos 1845
I =  9047386
number of imo 94
1845
===============
dfNewJourney 17
lenPos 1860
I =  9346469
number of imo 95
1860
===============
dfNewJourney 1
lenPos 0
I =  8501804
number of imo 96
dfNewJourney 1
lenPos 0
I =  8900036
number of imo 97
dfNewJourney 6
lenPos 1327
I =  8103432
number of imo 98
1327
===============
dfNewJourney 16
lenPos 1649
I =  8323393
number of imo 99
1649
===============
dfNewJourney 32
lenPos 1666
I =  9358412
number of imo 100
1666
===============
dfNewJourney 6
lenPos 1846
I =  9333670
number of imo 101
1846
===============
dfNewJourney 3
lenPos 0
I =  8819196
number of imo 102
dfNewJourney 9
lenPos 840
I =  9137583
number of imo 103
840
===============
dfNewJourney 31
lenPos 1806
I =  9470131
number of imo 104
1806
===============
dfNewJourney 18
lenPos 1870
I =  9489912
number of imo 105
1870
===============
dfNewJourney 48
lenPos 1693
I =  9299422
number of imo 106
1693
===============
dfNewJourney 34
lenPos 1376
I =  9157765
number of imo 107
1376
===============
dfNewJourney 18
lenPos 0
I =  10007587
number of imo 108
dfNewJourney 42
lenPos 1447
I =  9283758
number of imo 109
1447
===============
dfNewJourney 53
lenPos 1776
I =  9275660
number of imo 110
1776
===============
dfNewJourney 31
lenPos 1750
I =  9242120
number of imo 111
1750
===============
dfNewJourney 10
lenPos 1630
I =  9044499
number of imo 112
1630
===============
dfNewJourney 34
lenPos 1492
I =  9410533
number of imo 113
1492
===============
dfNewJourney 17
lenPos 1675
I =  9162526
number of imo 114
1675
===============
dfNewJourney 31
lenPos 1849
I =  9285732
number of imo 115
1849
===============
dfNewJourney 32
lenPos 1848
I =  9350850
number of imo 116
1848

===============
dfNewJourney 6
lenPos 1114
I =  9071818
number of imo 117
1114
===============
dfNewJourney 40
lenPos 1772
I =  9531636
number of imo 118
1772
===============
dfNewJourney 31
lenPos 1413
I =  9306627
number of imo 119
1413
===============
dfNewJourney 33
lenPos 1736
I =  9239927
number of imo 120
1736
===============
dfNewJourney 42
lenPos 1815
I =  9447756
number of imo 121
1815
===============
dfNewJourney 17
lenPos 1592
I =  9255842
number of imo 122
1592
===============
dfNewJourney 34
lenPos 1744
I =  9265873
number of imo 123
1744
===============
dfNewJourney 13
lenPos 1388
I =  9173654
number of imo 124
1388
===============
dfNewJourney 34
lenPos 1818
I =  9216925
number of imo 125
1818
===============
dfNewJourney 35
lenPos 1781
I =  9343338
number of imo 126
1781
===============
dfNewJourney 42
lenPos 1759
I =  9378620
number of imo 127
1759
===============
dfNewJourney 19
lenPos 1866
I =  9131369
number of imo 128
1866
===============
dfNewJourney 2
lenPos 0
I =  9292993
number of imo 129
dfNewJourney 3
lenPos 0
I =  9015333
number of imo 130
dfNewJourney 47
lenPos 1833
I =  9351438
number of imo 131
1833
===============
dfNewJourney 45
lenPos 1786
I =  9590711
number of imo 132
1786
===============
dfNewJourney 44
lenPos 1765
I =  9328132
number of imo 133
1765
===============
dfNewJourney 19
lenPos 1630
I =  9232905
number of imo 134
1630
===============
dfNewJourney 34
lenPos 1717
I =  9440538
number of imo 135
1717
===============
dfNewJourney 58
lenPos 1740
I =  9267948
number of imo 136
1740
===============
dfNewJourney 22
lenPos 1767
I =  9336414
number of imo 137
1767
===============
dfNewJourney 1
lenPos 1823
I =  9388780
number of imo 138
1823
===============
dfNewJourney 45
lenPos 1636
I =  9288813
number of imo 139
1636
===============
dfNewJourney 28
lenPos 1790
I =  9439541
number of imo 140
1790
===============
dfNewJourney 40
lenPos 1879
I =  9311361
number of imo 141
1879
===============
dfNewJourney 30
lenPos 0
I =  10029040
number of imo 142
dfNewJourney 45
lenPos 1855
I =  9328297
number of imo 143
1855
===============
dfNewJourney 36
lenPos 1631
I =  9315458
number of imo 144
1631
===============
dfNewJourney 42
lenPos 1784
I =  9216901
number of imo 145
1784
===============
dfNewJourney 10
lenPos 1835
I =  9399818
number of imo 146
1835
===============
dfNewJourney 21
lenPos 1613
I =  9323792
number of imo 147
1613
===============
dfNewJourney 47
lenPos 1823
I =  9470260
number of imo 148
1823
===============
dfNewJourney 2
lenPos 0
I =  8617031
number of imo 149
dfNewJourney 9
lenPos 1602
I =  9329318
number of imo 150
1602
===============
dfNewJourney 2
lenPos 1344
I =  9292981
number of imo 151
1344
===============
dfNewJourney 22
lenPos 0
I =  9176022
number of imo 152
dfNewJourney 25
lenPos 1678
I =  9296822
number of imo 153
1678
===============
dfNewJourney 49
lenPos 1871
I =  9539573
number of imo 154
1871
===============
dfNewJourney 41
lenPos 1800
I =  9378618
number of imo 155
1800
===============
dfNewJourney 41
lenPos 1822
I =  9364588
number of imo 156
1822
===============
dfNewJourney 2
lenPos 0
I =  8806876
number of imo 157
dfNewJourney 52
lenPos 1692
I =  9327035
number of imo 158
1692
===============
dfNewJourney 6
lenPos 1617
I =  9470947
number of imo 159
1617
===============
dfNewJourney 33
lenPos 1373
I =  9478717
number of imo 160
1373
===============
dfNewJourney 2
lenPos 0
I =  10007660
number of imo 161
dfNewJourney 11
lenPos 1799
I =  9453975
number of imo 162
1799
===============
dfNewJourney 44
lenPos 1837
I =  9388302
number of imo 163
1837
===============
dfNewJourney 3
lenPos 1705
I =  9038878
number of imo 164
1705
===============
dfNewJourney 1
lenPos 0
I =  7931856
number of imo 165
dfNewJourney 19
lenPos 0
I =  9177947
number of imo 166
dfNewJourney 49
lenPos 0
I =  10007638
number of imo 167
dfNewJourney 44
lenPos 1599
I =  9319686
number of imo 168
1599
===============
dfNewJourney 22
lenPos 0
I =  8112926
number of imo 169
dfNewJourney 8
lenPos 1713
I =  9166558
number of imo 170
1713
===============
dfNewJourney 35
lenPos 1306
I =  8614467
number of imo 171
1306
===============
dfNewJourney 34
lenPos 1735
I =  9198771
number of imo 172
1735
===============
dfNewJourney 16
lenPos 1239
I =  9147435
number of imo 173
1239
===============
dfNewJourney 19
lenPos 1757
I =  9105102
number of imo 174
1757
===============
dfNewJourney 44
lenPos 1811
I =  9310692
number of imo 175
1811
===============
dfNewJourney 3
lenPos 1862
I =  8617081
number of imo 176
1862
===============
dfNewJourney 15
lenPos 1550
I =  9290294
number of imo 177
1550
===============
dfNewJourney 41
lenPos 1823
I =  9389318
number of imo 178
1823
===============
dfNewJourney 56
lenPos 1768
I =  9467720
number of imo 179
1768
===============
dfNewJourney 28
lenPos 1820
I =  9324320
number of imo 180
1820
===============
dfNewJourney 54
lenPos 1693
I =  9335123
number of imo 181
1693
===============
dfNewJourney 47
lenPos 1774
I =  9456927
number of imo 182
1774
===============
dfNewJourney 41
lenPos 1730
I =  9576789
number of imo 183
1730
===============
dfNewJourney 30
lenPos 1806
I =  9440526
number of imo 184
1806
===============
dfNewJourney 47
lenPos 1730
I =  9381732
number of imo 185
1730
===============
dfNewJourney 38
lenPos 1339
I =  9162502
number of imo 186
1339
===============
dfNewJourney 38
lenPos 1795
I =  9393096
number of imo 187
1795
===============
dfNewJourney 30
lenPos 1785
I =  9484912
number of imo 188
1785
===============
dfNewJourney 22
lenPos 1613
I =  9232022
number of imo 189
1613
===============
dfNewJourney 11
lenPos 741
I =  9283760
number of imo 190
741
===============
dfNewJourney 2
lenPos 1649
I =  9038880
number of imo 191
1649
===============
dfNewJourney 2
lenPos 1797
I =  9410870
number of imo 192
1797
===============
dfNewJourney 15
lenPos 0
I =  9164201
number of imo 193
dfNewJourney 28
lenPos 1738
I =  9581667
number of imo 194
1738
===============
dfNewJourney 20
lenPos 1895
I =  9391294
number of imo 195
1895
===============
dfNewJourney 11
lenPos 0
I =  8704365
number of imo 196
dfNewJourney 23
lenPos 1818
I =  9254812
number of imo 197
1818
===============
dfNewJourney 11
lenPos 1660
I =  9339650
number of imo 198
1660
===============
dfNewJourney 21
lenPos 1526
I =  9292589
number of imo 199
1526
===============
dfNewJourney 42
lenPos 1742
I =  9354313
number of imo 200
1742
===============
dfNewJourney 43
lenPos 1781
I =  9402770
number of imo 201
1781
===============
dfNewJourney 15
lenPos 1688
I =  9283796
number of imo 202
1688
===============
dfNewJourney 33
lenPos 1567
I =  9251810
number of imo 203
1567
===============
dfNewJourney 22
lenPos 1603
I =  9408126
number of imo 204
1603
===============
dfNewJourney 23
lenPos 1682
I =  9162928
number of imo 205
1682
===============
dfNewJourney 38
lenPos 1759
I =  9386861
number of imo 206
1759
===============
dfNewJourney 10
lenPos 0
I =  8716734
number of imo 207
dfNewJourney 46
lenPos 1665
I =  9283679
number of imo 208
1665
===============
dfNewJourney 47
lenPos 1715
I =  9123659
number of imo 209
1715
===============
dfNewJourney 42
lenPos 1683
I =  9306639
number of imo 210
1683
===============
dfNewJourney 12
lenPos 1729
I =  9301407
number of imo 211
1729
===============
dfNewJourney 17
lenPos 1301
I =  9162007
number of imo 212
1301
===============
dfNewJourney 2
lenPos 1390
I =  8805470
number of imo 213
1390
===============
dfNewJourney 44
lenPos 1891
I =  9487469
number of imo 214
1891
===============
dfNewJourney 26
lenPos 1840
I =  9405552
number of imo 215
1840
===============
dfNewJourney 1
lenPos 1254
I =  9032666
number of imo 216
1254
===============
dfNewJourney 44
lenPos 1830
I =  9412737
number of imo 217
1830
===============
dfNewJourney 29
lenPos 1786
I =  9395331
number of imo 218
1786
===============
dfNewJourney 48
lenPos 1584
I =  9308948
number of imo 219
1584
===============
dfNewJourney 43
lenPos 1794
I =  9328170
number of imo 220
1794
===============
dfNewJourney 51
lenPos 1757
I =  9240172
number of imo 221
1757
===============
dfNewJourney 7
lenPos 0
I =  9035137
number of imo 222
dfNewJourney 48
lenPos 0
I =  10007633
number of imo 223
dfNewJourney 50
lenPos 1772
I =  9185487
number of imo 224
1772

===============
dfNewJourney 18
lenPos 1732
I =  9198159
number of imo 225
1732
===============
dfNewJourney 53
lenPos 1772
I =  9299757
number of imo 226
1772
===============
dfNewJourney 43
lenPos 1790
I =  9301017
number of imo 227
1790
===============
dfNewJourney 18
lenPos 1745
I =  9379038
number of imo 228
1745
===============
dfNewJourney 36
lenPos 1760
I =  9458822
number of imo 229
1760
===============
dfNewJourney 4
lenPos 1853
I =  9290828
number of imo 230
1853
===============
dfNewJourney 33
lenPos 1843
I =  9307102
number of imo 231
1843
===============
dfNewJourney 44
lenPos 1870
I =  9568031
number of imo 232
1870
===============
dfNewJourney 28
lenPos 1825
I =  9421324
number of imo 233
1825
===============
dfNewJourney 49
lenPos 0
I =  10015394
number of imo 234
dfNewJourney 13
lenPos 1309
I =  9262417
number of imo 235
1309
===============
dfNewJourney 42
lenPos 1619
I =  9283291
number of imo 236
1619
===============
dfNewJourney 24
lenPos 1803
I =  9441855
number of imo 237
1803
===============
dfNewJourney 28
lenPos 1830
I =  9315941
number of imo 238
1830
===============
dfNewJourney 31
lenPos 1857
I =  9484895
number of imo 239
1857
===============
dfNewJourney 23
lenPos 1480
I =  9255933
number of imo 240
1480
===============
dfNewJourney 9
lenPos 0
I =  9045481
number of imo 241
dfNewJourney 59
lenPos 1770
I =  9295270
number of imo 242
1770
===============
dfNewJourney 34
lenPos 1880
I =  9467811
number of imo 243
1880
===============
dfNewJourney 38
lenPos 1635
I =  9439199
number of imo 244
1635
===============
dfNewJourney 13
lenPos 1804
I =  9232448
number of imo 245
1804
===============
dfNewJourney 24
lenPos 1701
I =  9152832
number of imo 246
1701
===============
dfNewJourney 50
lenPos 1834
I =  9478638
number of imo 247
1834
===============
dfNewJourney 13
lenPos 0
I =  9192777
number of imo 248
dfNewJourney 32
lenPos 1684
I =  9326861
number of imo 249
1684
===============
dfNewJourney 49
lenPos 1829
I =  9047491
number of imo 250
1829
===============
dfNewJourney 41
lenPos 1832
I =  9277759
number of imo 251
1832
===============
dfNewJourney 32
lenPos 0
I =  8715508
number of imo 252
dfNewJourney 37
lenPos 1725
I =  9120994
number of imo 253
1725
===============
dfNewJourney 46
lenPos 0
I =  10007616
number of imo 254
dfNewJourney 20
lenPos 1686
I =  9412775
number of imo 255
1686
===============
dfNewJourney 3
lenPos 0
I =  9073737
number of imo 256
dfNewJourney 8
lenPos 0
I =  9015357
number of imo 257
dfNewJourney 39
lenPos 0
I =  10007577
number of imo 258
dfNewJourney 33
lenPos 1747
I =  9440473
number of imo 259
1747
===============
dfNewJourney 2
lenPos 0
I =  9043043
number of imo 260
dfNewJourney 19
lenPos 1568
I =  9313448
number of imo 261
1568
===============
dfNewJourney 40
lenPos 1857
I =  9197296
number of imo 262
1857
===============
dfNewJourney 61
lenPos 1709
I =  9408542
number of imo 263
1709
===============
dfNewJourney 50
lenPos 1655
I =  9419357
number of imo 264
1655
===============
dfNewJourney 36
lenPos 1726
I =  9465978
number of imo 265
1726
===============
dfNewJourney 39
lenPos 1846
I =  9592252
number of imo 266
1846
===============
dfNewJourney 36
lenPos 1772
I =  9377779
number of imo 267
1772
===============
dfNewJourney 40
lenPos 0
I =  10015721
number of imo 268
dfNewJourney 19
lenPos 1796
I =  9360128
number of imo 269
1796
===============
dfNewJourney 3
lenPos 0
I =  9039597
number of imo 270
dfNewJourney 3
lenPos 0
I =  8716356
number of imo 271
dfNewJourney 28
lenPos 1835
I =  9321964
number of imo 272
1835
===============
dfNewJourney 36
lenPos 0
I =  10007655
number of imo 273
dfNewJourney 23
lenPos 1833
I =  9521435
number of imo 274
1833
===============
dfNewJourney 51
lenPos 1653
I =  9250543
number of imo 275
1653
===============
dfNewJourney 38
lenPos 1678
I =  9215256
number of imo 276
1678
===============
dfNewJourney 41
lenPos 1774
I =  9277723
number of imo 277
1774
===============
dfNewJourney 61
lenPos 1701
I =  9335109
number of imo 278
1701
===============
dfNewJourney 39
lenPos 1689
I =  9476824
number of imo 279
1689
===============
dfNewJourney 45
lenPos 1659
I =  9387671
number of imo 280
1659
===============
dfNewJourney 69
lenPos 1854
I =  9299135
number of imo 281
1854
===============
dfNewJourney 28
lenPos 0
I =  9181522
number of imo 282
dfNewJourney 23
lenPos 1237
I =  9252072
number of imo 283
1237
===============
dfNewJourney 40
lenPos 1795
I =  9397559
number of imo 284
1795
===============
dfNewJourney 39
lenPos 1755
I =  9324289
number of imo 285
1755
===============
dfNewJourney 42
lenPos 1768
I =  9343194
number of imo 286
1768
===============
dfNewJourney 36
lenPos 1640
I =  9284374
number of imo 287
1640
===============
dfNewJourney 44
lenPos 1825
I =  9403346
number of imo 288
1825
===============
dfNewJourney 34
lenPos 1801
I =  9351440
number of imo 289
1801
===============
dfNewJourney 2
lenPos 0
I =  8820901
number of imo 290
dfNewJourney 37
lenPos 0
I =  10007590
number of imo 291
dfNewJourney 39
lenPos 1735
I =  9374284
number of imo 292
1735
===============
dfNewJourney 40
lenPos 1849
I =  9594896
number of imo 293
1849
===============
dfNewJourney 48
lenPos 1777
I =  9461831
number of imo 294
1777
===============
dfNewJourney 9
lenPos 1753
I =  9422005
number of imo 295
1753
===============
dfNewJourney 16
lenPos 1379
I =  9110183
number of imo 296
1379
===============
dfNewJourney 50
lenPos 1762
I =  9457268
number of imo 297
1762
===============
dfNewJourney 12
lenPos 1660
I =  9176656
number of imo 298
1660
===============
dfNewJourney 11
lenPos 1860
I =  8617108
number of imo 299
1860
===============
dfNewJourney 37
lenPos 1693
I =  9408310
number of imo 300
1693
===============
dfNewJourney 6
lenPos 1499
I =  9222168
number of imo 301
1499
===============
dfNewJourney 53
lenPos 1652
I =  9441180
number of imo 302
1652
===============
dfNewJourney 56
lenPos 1805
I =  9389863
number of imo 303
1805
===============
dfNewJourney 1
lenPos 0
I =  8920490
number of imo 304
dfNewJourney 59
lenPos 1771
I =  9367530
number of imo 305
1771
===============
dfNewJourney 50
lenPos 1650
I =  9382968
number of imo 306
1650
===============
dfNewJourney 26
lenPos 1799
I =  9256638
number of imo 307
1799
===============
dfNewJourney 29
lenPos 1269
I =  9388792
number of imo 308
1269
===============
dfNewJourney 57
lenPos 0
I =  10007652
number of imo 309
dfNewJourney 28
lenPos 1775
I =  9528378
number of imo 310
1775
===============
dfNewJourney 38
lenPos 1828
I =  9250751
number of imo 311
1828
===============
dfNewJourney 12
lenPos 1402
I =  9191395
number of imo 312
1402
===============
dfNewJourney 35
lenPos 1831
I =  9332640
number of imo 313
1831
===============
dfNewJourney 41
lenPos 1741
I =  9361524
number of imo 314
1741
===============
dfNewJourney 40
lenPos 1212
I =  9341433
number of imo 315
1212
===============
dfNewJourney 40
lenPos 1783
I =  9283629
number of imo 316
1783
===============
dfNewJourney 7
lenPos 0
I =  9131125
number of imo 317
dfNewJourney 31
lenPos 1707
I =  9192258
number of imo 318
1707
===============
dfNewJourney 52
lenPos 1741
I =  9379959
number of imo 319
1741
===============
dfNewJourney 62
lenPos 1563
I =  9568495
number of imo 320
1563
===============
dfNewJourney 49
lenPos 1730
I =  9471329
number of imo 321
1730
===============
dfNewJourney 29
lenPos 1483
I =  9299147
number of imo 322
1483
===============
dfNewJourney 47
lenPos 1672
I =  9441166
number of imo 323
1672
===============
dfNewJourney 42
lenPos 1751
I =  9392793
number of imo 324
1751
===============
dfNewJourney 18
lenPos 1513
I =  9398278
number of imo 325
1513
===============
dfNewJourney 32
lenPos 1622
I =  9390939
number of imo 326
1622
===============
dfNewJourney 44
lenPos 1704
I =  9292034
number of imo 327
1704
===============
dfNewJourney 3
lenPos 0
I =  9006904
number of imo 328
dfNewJourney 43
lenPos 1820
I =  9447744
number of imo 329
1820
===============
dfNewJourney 32
lenPos 1520
I =  9246138
number of imo 330
1520
===============
dfNewJourney 24
lenPos 1621
I =  9112129
number of imo 331
1621
===============
dfNewJourney 29
lenPos 1725
I =  9473066
number of imo 332
1725
===============
dfNewJourney 27
lenPos 1576
I =  9414503
number of imo 333
1576

===============
dfNewJourney 30
lenPos 1711
I =  9247780
number of imo 334
1711
===============
dfNewJourney 24
lenPos 1261
I =  9374868
number of imo 335
1261
===============
dfNewJourney 31
lenPos 1625
I =  9178068
number of imo 336
1625
===============
dfNewJourney 31
lenPos 1626
I =  9237802
number of imo 337
1626
===============
dfNewJourney 20
lenPos 0
I =  9077343
number of imo 338
dfNewJourney 39
lenPos 0
I =  10007644
number of imo 339
dfNewJourney 50
lenPos 1785
I =  9222649
number of imo 340
1785
===============
dfNewJourney 2
lenPos 0
I =  9058828
number of imo 341
dfNewJourney 42
lenPos 1732
I =  9482550
number of imo 342
1732
===============
dfNewJourney 37
lenPos 1768
I =  9397547
number of imo 343
1768
===============
dfNewJourney 12
lenPos 0
I =  9161259
number of imo 344
dfNewJourney 28
lenPos 1773
I =  9410014
number of imo 345
1773
===============
dfNewJourney 44
lenPos 1763
I =  9281425
number of imo 346
1763
===============
dfNewJourney 50
lenPos 1561
I =  9368235
number of imo 347
1561
===============
dfNewJourney 11
lenPos 988
I =  8618891
number of imo 348
988
===============
dfNewJourney 10
lenPos 1688
I =  9034547
number of imo 349
1688
===============
dfNewJourney 30
lenPos 1650
I =  9258480
number of imo 350
1650
===============
dfNewJourney 46
lenPos 1789
I =  9324291
number of imo 351
1789
===============
dfNewJourney 44
lenPos 1834
I =  9335836
number of imo 352
1834
===============
dfNewJourney 47
lenPos 1451
I =  9358400
number of imo 353
1451
===============
dfNewJourney 27
lenPos 1859
I =  9386536
number of imo 354
1859
===============
dfNewJourney 38
lenPos 1736
I =  9379961
number of imo 355
1736
===============
dfNewJourney 31
lenPos 1653
I =  9278686
number of imo 356
1653
===============
dfNewJourney 37
lenPos 1824
I =  9124471
number of imo 357
1824
===============
dfNewJourney 45
lenPos 1473
I =  9247883
number of imo 358
1473
===============
dfNewJourney 48
lenPos 1807
I =  9482847
number of imo 359
1807
===============
dfNewJourney 42
lenPos 1623
I =  9261762
number of imo 360
1623
===============
dfNewJourney 33
lenPos 1815
I =  9279719
number of imo 361
1815
===============
dfNewJourney 21
lenPos 1715
I =  9259290
number of imo 362
1715
===============
dfNewJourney 32
lenPos 1771
I =  9216547
number of imo 363
1771
===============
dfNewJourney 8
lenPos 1602
I =  8822454
number of imo 364
1602
===============
dfNewJourney 34
lenPos 1893
I =  9258466
number of imo 365
1893
===============
dfNewJourney 11
lenPos 1262
I =  9267027
number of imo 366
1262
===============
dfNewJourney 15
lenPos 0
I =  9111058
number of imo 367
dfNewJourney 39
lenPos 1752
I =  9412177
number of imo 368
1752
===============
dfNewJourney 37
lenPos 1783
I =  9379818
number of imo 369
1783
===============
dfNewJourney 26
lenPos 1342
I =  9215098
number of imo 370
1342
===============
dfNewJourney 38
lenPos 0
I =  10015521
number of imo 371
dfNewJourney 50
lenPos 1842
I =  9539585
number of imo 372
1842
===============
dfNewJourney 36
lenPos 1674
I =  9273442
number of imo 373
1674
===============
dfNewJourney 24
lenPos 1774
I =  9319870
number of imo 374
1774
===============
dfNewJourney 11
lenPos 1496
I =  9222560
number of imo 375
1496
===============
dfNewJourney 38
lenPos 1746
I =  9321196
number of imo 376
1746
===============
dfNewJourney 44
lenPos 1775
I =  9602722
number of imo 377
1775
===============
dfNewJourney 13
lenPos 1863
I =  9274630
number of imo 378
1863
===============
dfNewJourney 32
lenPos 1726
I =  9464560
number of imo 379
1726
===============
dfNewJourney 47
lenPos 1568
I =  9595010
number of imo 380
1568
===============
dfNewJourney 36
lenPos 1828
I =  9328285
number of imo 381
1828
===============
dfNewJourney 37
lenPos 1827
I =  9288758
number of imo 382
1827
===============
dfNewJourney 22
lenPos 1866
I =  9428683
number of imo 383
1866
===============
dfNewJourney 22
lenPos 1707
I =  9226140
number of imo 384
1707
===============
dfNewJourney 24
lenPos 1850
I =  9428334
number of imo 385
1850
===============
dfNewJourney 48
lenPos 1739
I =  9288837
number of imo 386
1739
===============
dfNewJourney 29
lenPos 1820
I =  9233234
number of imo 387
1820
===============
dfNewJourney 27
lenPos 1616
I =  9401025
number of imo 388
1616
===============
dfNewJourney 26
lenPos 1220
I =  9289166
number of imo 389
1220
===============
dfNewJourney 9
lenPos 1524
I =  9241798
number of imo 390
1524
===============
dfNewJourney 13
lenPos 1591
I =  9219264
number of imo 391
1591
===============
dfNewJourney 4
lenPos 1535
I =  9007752
number of imo 392
1535
===============
dfNewJourney 42
lenPos 1712
I =  9223851
number of imo 393
1712
===============
dfNewJourney 52
lenPos 1889
I =  9369887
number of imo 394
1889
===============
dfNewJourney 48
lenPos 1775
I =  9382061
number of imo 395
1775
===============
dfNewJourney 43
lenPos 1840
I =  9541306
number of imo 396
1840
===============
dfNewJourney 79
lenPos 1839
I =  9487251
number of imo 397
1839
===============
dfNewJourney 46
lenPos 1850
I =  9407380
number of imo 398
1850
===============
dfNewJourney 30
lenPos 1782
I =  9282522
number of imo 399
1782
===============
dfNewJourney 53
lenPos 1761
I =  9389277
number of imo 400
1761
===============
dfNewJourney 61
lenPos 1700
I =  9387700
number of imo 401
1700
===============
dfNewJourney 40
lenPos 1800
I =  9457763
number of imo 402
1800
===============
dfNewJourney 41
lenPos 1796
I =  9426300
number of imo 403
1796
===============
dfNewJourney 35
lenPos 1487
I =  9258868
number of imo 404
1487
===============
dfNewJourney 24
lenPos 1579
I =  9299719
number of imo 405
1579
===============
dfNewJourney 6
lenPos 1630
I =  9324497
number of imo 406
1630
===============
dfNewJourney 7
lenPos 0
I =  8420608
number of imo 407
dfNewJourney 29
lenPos 0
I =  10007647
number of imo 408
dfNewJourney 9
lenPos 591
I =  8644149
number of imo 409
591
===============
dfNewJourney 16
lenPos 0
I =  8309529
number of imo 410
dfNewJourney 28
lenPos 1731
I =  9395379
number of imo 411
1731
===============
dfNewJourney 44
lenPos 1872
I =  9288289
number of imo 412
1872
===============
dfNewJourney 29
lenPos 1414
I =  9494682
number of imo 413
1414
===============
dfNewJourney 68
lenPos 1787
I =  9299123
number of imo 414
1787
===============
dfNewJourney 44
lenPos 1802
I =  9214305
number of imo 415
1802
===============
dfNewJourney 24
lenPos 1852
I =  9486922
number of imo 416
1852
===============
dfNewJourney 27
lenPos 1541
I =  9368223
number of imo 417
1541
===============
dfNewJourney 6
lenPos 1886
I =  9380477
number of imo 418
1886
===============
dfNewJourney 57
lenPos 1759
I =  9306809
number of imo 419
1759
===============
dfNewJourney 19
lenPos 1874
I =  9311359
number of imo 420
1874
===============
dfNewJourney 26
lenPos 0
I =  10012334
number of imo 421
dfNewJourney 22
lenPos 1443
I =  9398280
number of imo 422
1443
===============
dfNewJourney 12
lenPos 1758
I =  9301885
number of imo 423
1758
===============
dfNewJourney 27
lenPos 1716
I =  9257503
number of imo 424
1716
===============
dfNewJourney 60
lenPos 0
I =  10015445
number of imo 425
dfNewJourney 36
lenPos 1706
I =  9102112
number of imo 426
1706
===============
dfNewJourney 33
lenPos 1581
I =  9268112
number of imo 427
1581
===============
dfNewJourney 52
lenPos 1766
I =  9359363
number of imo 428
1766
===============
dfNewJourney 12
lenPos 1777
I =  9173733
number of imo 429
1777
===============
dfNewJourney 47
lenPos 1695
I =  9458834
number of imo 430
1695
===============
dfNewJourney 38
lenPos 1708
I =  9375329
number of imo 431
1708
===============
dfNewJourney 13
lenPos 1864
I =  9333400
number of imo 432
1864
===============
dfNewJourney 32
lenPos 1787
I =  9374301
number of imo 433
1787
===============
dfNewJourney 34
lenPos 1526
I =  9572264
number of imo 434
1526
===============
dfNewJourney 45
lenPos 1765
I =  9337511
number of imo 435
1765
===============
dfNewJourney 32
lenPos 1840
I =  9332614
number of imo 436
1840
===============
dfNewJourney 55
lenPos 1769
I =  9413561
number of imo 437
1769
===============
dfNewJourney 33
lenPos 1705
I =  9236365
number of imo 438
1705
===============
dfNewJourney 25
lenPos 1408
I =  9273052
number of imo 439
1408

===============
dfNewJourney 48
lenPos 1863
I =  9265689
number of imo 440
1863
===============
dfNewJourney 51
lenPos 1725
I =  9593414
number of imo 441
1725
===============
dfNewJourney 25
lenPos 1612
I =  9417799
number of imo 442
1612
===============
dfNewJourney 39
lenPos 1818
I =  9113147
number of imo 443
1818
===============
dfNewJourney 46
lenPos 1628
I =  9319703
number of imo 444
1628
===============
dfNewJourney 19
lenPos 1526
I =  9329409
number of imo 445
1526
===============
dfNewJourney 25
lenPos 1728
I =  9379052
number of imo 446
1728
===============
dfNewJourney 38
lenPos 1834
I =  9232620
number of imo 447
1834
===============
dfNewJourney 21
lenPos 1735
I =  9205873
number of imo 448
1735
===============
dfNewJourney 38
lenPos 1845
I =  9246449
number of imo 449
1845
===============
dfNewJourney 10
lenPos 1647
I =  9121194
number of imo 450
1647
===============
dfNewJourney 17
lenPos 1537
I =  9223265
number of imo 451
1537
===============
dfNewJourney 27
lenPos 0
I =  9192337
number of imo 452
dfNewJourney 45
lenPos 1674
I =  9319674
number of imo 453
1674
===============
dfNewJourney 46
lenPos 1625
I =  9387683
number of imo 454
1625
===============
dfNewJourney 32
lenPos 1668
I =  9407847
number of imo 455
1668
===============
dfNewJourney 39
lenPos 1778
I =  9410179
number of imo 456
1778
===============
dfNewJourney 36
lenPos 953
I =  9163269
number of imo 457
953
===============
dfNewJourney 1
lenPos 0
I =  8410134
number of imo 458
dfNewJourney 64
lenPos 1613
I =  9343998
number of imo 459
1613
===============
dfNewJourney 45
lenPos 1755
I =  9384992
number of imo 460
1755
===============
dfNewJourney 16
lenPos 0
I =  9074585
number of imo 461
dfNewJourney 19
lenPos 1680
I =  9437672
number of imo 462
1680
===============
dfNewJourney 44
lenPos 1864
I =  9479838
number of imo 463
1864
===============
dfNewJourney 3
lenPos 0
I =  8917821
number of imo 464
dfNewJourney 31
lenPos 1612
I =  9439670
number of imo 465
1612
===============
dfNewJourney 46
lenPos 1714
I =  9596997
number of imo 466
1714
===============
dfNewJourney 29
lenPos 1784
I =  9422639
number of imo 467
1784
===============
dfNewJourney 35
lenPos 1784
I =  9510682
number of imo 468
1784
===============
dfNewJourney 27
lenPos 1766
I =  9360441
number of imo 469
1766
===============
dfNewJourney 49
lenPos 1756
I =  9277773
number of imo 470
1756
===============
dfNewJourney 37
lenPos 1849
I =  9309241
number of imo 471
1849
===============
dfNewJourney 34
lenPos 1129
I =  9187655
number of imo 472
1129
===============
dfNewJourney 41
lenPos 1839
I =  9381768
number of imo 473
1839
===============
dfNewJourney 36
lenPos 1722
I =  9240897
number of imo 474
1722
===============
dfNewJourney 30
lenPos 1691
I =  9390161
number of imo 475
1691
===============
dfNewJourney 44
lenPos 1834
I =  9397511
number of imo 476
1834
===============
dfNewJourney 10
lenPos 1852
I =  9339985
number of imo 477
1852
===============
dfNewJourney 35
lenPos 1573
I =  9144926
number of imo 478
1573
===============
dfNewJourney 36
lenPos 1749
I =  9231511
number of imo 479
1749
===============
dfNewJourney 17
lenPos 1856
I =  9162916
number of imo 480
1856
===============
dfNewJourney 41
lenPos 1736
I =  9478729
number of imo 481
1736
===============
dfNewJourney 39
lenPos 0
I =  10007598
number of imo 482
dfNewJourney 31
lenPos 1484
I =  9213325
number of imo 483
1484
===============
dfNewJourney 16
lenPos 0
I =  9011076
number of imo 484
dfNewJourney 34
lenPos 1679
I =  9276030
number of imo 485
1679
===============
dfNewJourney 7
lenPos 1048
I =  9239642
number of imo 486
1048
===============
dfNewJourney 37
lenPos 1691
I =  9576777
number of imo 487
1691
===============
dfNewJourney 47
lenPos 0
I =  10016026
number of imo 488
dfNewJourney 3
lenPos 0
I =  9074561
number of imo 489
dfNewJourney 34
lenPos 1817
I =  9417464
number of imo 490
1817
===============
dfNewJourney 65
lenPos 1660
I =  9228710
number of imo 491
1660
===============
dfNewJourney 47
lenPos 1844
I =  9273832
number of imo 492
1844
===============
dfNewJourney 38
lenPos 1638
I =  9489089
number of imo 493
1638
===============
dfNewJourney 41
lenPos 0
I =  10015169
number of imo 494
dfNewJourney 18
lenPos 1344
I =  9192765
number of imo 495
1344
===============
dfNewJourney 49
lenPos 1748
I =  9405057
number of imo 496
1748
===============
dfNewJourney 42
lenPos 1839
I =  9594884
number of imo 497
1839
===============
dfNewJourney 43
lenPos 1682
I =  9325843
number of imo 498
1682
===============
dfNewJourney 30
lenPos 1661
I =  9543524
number of imo 499
1661
===============
dfNewJourney 13
lenPos 1734
I =  9144914
number of imo 500
1734
===============
dfNewJourney 14
lenPos 0
I =  9041435
number of imo 501
dfNewJourney 19
lenPos 0
I =  9313151
number of imo 502
dfNewJourney 52
lenPos 1868
I =  9303417
number of imo 503
1868
===============
dfNewJourney 39
lenPos 0
I =  9005390
number of imo 504
dfNewJourney 27
lenPos 1790
I =  9258002
number of imo 505
1790
===============
dfNewJourney 43
lenPos 1762
I =  9352250
number of imo 506
1762
===============
dfNewJourney 26
lenPos 1689
I =  9251896
number of imo 507
1689
===============
dfNewJourney 48
lenPos 1627
I =  9389514
number of imo 508
1627
===============
dfNewJourney 32
lenPos 1771
I =  9361512
number of imo 509
1771
===============
dfNewJourney 17
lenPos 1394
I =  9524920
number of imo 510
1394
===============
dfNewJourney 52
lenPos 1745
I =  9335135
number of imo 511
1745
===============
dfNewJourney 36
lenPos 1862
I =  9387920
number of imo 512
1862
===============
dfNewJourney 43
lenPos 1721
I =  9414228
number of imo 513
1721
===============
dfNewJourney 43
lenPos 1507
I =  9550694
number of imo 514
1507
===============
dfNewJourney 44
lenPos 1695
I =  9384021
number of imo 515
1695
===============
dfNewJourney 40
lenPos 1776
I =  9392808
number of imo 516
1776
===============
dfNewJourney 29
lenPos 1747
I =  9465992
number of imo 517
1747
===============
dfNewJourney 43
lenPos 1875
I =  9459060
number of imo 518
1875
===============
dfNewJourney 32
lenPos 1390
I =  9390721
number of imo 519
1390
===============
dfNewJourney 32
lenPos 1727
I =  9283710
number of imo 520
1727
===============
dfNewJourney 33
lenPos 1721
I =  9595008
number of imo 521
1721
===============
dfNewJourney 31
lenPos 1769
I =  9236248
number of imo 522
1769
===============
dfNewJourney 38
lenPos 1860
I =  9408530
number of imo 523
1860
===============
dfNewJourney 21
lenPos 1759
I =  9143673
number of imo 524
1759
===============
dfNewJourney 40
lenPos 1834
I =  9215282
number of imo 525
1834
===============
dfNewJourney 29
lenPos 1696
I =  9340594
number of imo 526
1696
===============
dfNewJourney 36
lenPos 1836
I =  9272400
number of imo 527
1836
===============
dfNewJourney 9
lenPos 1735
I =  9417892
number of imo 528
1735
===============
dfNewJourney 44
lenPos 1812
I =  9233973
number of imo 529
1812
===============
dfNewJourney 43
lenPos 1715
I =  9317846
number of imo 530
1715
===============
dfNewJourney 24
lenPos 1589
I =  9288930
number of imo 531
1589
===============
dfNewJourney 12
lenPos 1753
I =  9374234
number of imo 532
1753
===============
dfNewJourney 8
lenPos 1807
I =  9443425
number of imo 533
1807
===============
dfNewJourney 42
lenPos 1870
I =  9317860
number of imo 534
1870
===============
dfNewJourney 61
lenPos 1673
I =  9299886
number of imo 535
1673
===============
dfNewJourney 23
lenPos 1649
I =  9312872
number of imo 536
1649
===============
dfNewJourney 1
lenPos 0
I =  8506191
number of imo 537
dfNewJourney 55
lenPos 0
I =  10007603
number of imo 538
dfNewJourney 40
lenPos 1821
I =  9573658
number of imo 539
1821
===============
dfNewJourney 35
lenPos 1783
I =  9178202
number of imo 540
1783
===============
dfNewJourney 16
lenPos 0
I =  9147265
number of imo 541
dfNewJourney 20
lenPos 1872
I =  9353565
number of imo 542
1872
===============
dfNewJourney 38
lenPos 1794
I =  9326938
number of imo 543
1794
===============
dfNewJourney 41
lenPos 1749
I =  9285706
number of imo 544
1749
===============
dfNewJourney 35
lenPos 1779
I =  9395329
number of imo 545
1779
===============
dfNewJourney 57
lenPos 1730
I =  9532161
number of imo 546
1730

===============
dfNewJourney 19
lenPos 1784
I =  9413028
number of imo 547
1784
===============
dfNewJourney 42
lenPos 1751
I =  9364215
number of imo 548
1751
===============
dfNewJourney 27
lenPos 1802
I =  9230854
number of imo 549
1802
===============
dfNewJourney 39
lenPos 1759
I =  9336517
number of imo 550
1759
===============
dfNewJourney 38
lenPos 1769
I =  9478688
number of imo 551
1769
===============
dfNewJourney 41
lenPos 1751
I =  9470909
number of imo 552
1751
===============
dfNewJourney 10
lenPos 0
I =  9113408
number of imo 553
dfNewJourney 51
lenPos 1793
I =  9505819
number of imo 554
1793
===============
dfNewJourney 38
lenPos 1858
I =  9466025
number of imo 555
1858
===============
dfNewJourney 59
lenPos 1838
I =  9396737
number of imo 556
1838
===============
dfNewJourney 10
lenPos 1591
I =  9350654
number of imo 557
1591
===============
dfNewJourney 54
lenPos 1507
I =  9228722
number of imo 558
1507
===============
dfNewJourney 11
lenPos 0
I =  9171840
number of imo 559
dfNewJourney 25
lenPos 1584
I =  9431305
number of imo 560
1584
===============
dfNewJourney 40
lenPos 1785
I =  9301964
number of imo 561
1785
===============
dfNewJourney 47
lenPos 1814
I =  9416824
number of imo 562
1814
===============
dfNewJourney 10
lenPos 1557
I =  9187643
number of imo 563
1557
===============
dfNewJourney 40
lenPos 1738
I =  9288265
number of imo 564
1738
===============
dfNewJourney 40
lenPos 1525
I =  9489091
number of imo 565
1525
===============
dfNewJourney 32
lenPos 1805
I =  9168647
number of imo 566
1805
===============
dfNewJourney 21
lenPos 1664
I =  9259886
number of imo 567
1664
===============
dfNewJourney 8
lenPos 0
I =  9009138
number of imo 568
dfNewJourney 14
lenPos 1772
I =  9391311
number of imo 569
1772
===============
dfNewJourney 37
lenPos 1524
I =  9399363
number of imo 570
1524
===============
dfNewJourney 40
lenPos 1803
I =  9332315
number of imo 571
1803
===============
dfNewJourney 44
lenPos 1736
I =  9389978
number of imo 572
1736
===============
dfNewJourney 24
lenPos 1799
I =  9225330
number of imo 573
1799
===============
dfNewJourney 47
lenPos 1788
I =  9314208
number of imo 574
1788
===============
dfNewJourney 24
lenPos 1788
I =  9407251
number of imo 575
1788
===============
dfNewJourney 33
lenPos 1688
I =  9237618
number of imo 576
1688
===============
dfNewJourney 2
lenPos 0
I =  9086708
number of imo 577
dfNewJourney 15
lenPos 1419
I =  9335915
number of imo 578
1419
===============
dfNewJourney 24
lenPos 1695
I =  9394040
number of imo 579
1695
===============
dfNewJourney 27
lenPos 1702
I =  9232034
number of imo 580
1702
===============
dfNewJourney 26
lenPos 1811
I =  9589944
number of imo 581
1811
===============
dfNewJourney 40
lenPos 1857
I =  9379894
number of imo 582
1857
===============
dfNewJourney 23
lenPos 1789
I =  9240720
number of imo 583
1789
===============
dfNewJourney 42
lenPos 1816
I =  9112117
number of imo 584
1816
===============
dfNewJourney 43
lenPos 1809
I =  9327463
number of imo 585
1809
===============
dfNewJourney 44
lenPos 1817
I =  9375604
number of imo 586
1817
===============
dfNewJourney 34
lenPos 0
I =  10007653
number of imo 587
dfNewJourney 54
lenPos 1860
I =  9601833
number of imo 588
1860
===============
dfNewJourney 8
lenPos 0
I =  9149263
number of imo 589
dfNewJourney 42
lenPos 1859
I =  9392482
number of imo 590
1859
===============
dfNewJourney 24
lenPos 1776
I =  9411305
number of imo 591
1776
===============
dfNewJourney 42
lenPos 1177
I =  9283289
number of imo 592
1177
===============
dfNewJourney 2
lenPos 0
I =  9182655
number of imo 593
dfNewJourney 30
lenPos 1772
I =  9260275
number of imo 594
1772
===============
dfNewJourney 14
lenPos 1803
I =  9301897
number of imo 595
1803
===============
dfNewJourney 48
lenPos 1570
I =  9218181
number of imo 596
1570
===============
dfNewJourney 18
lenPos 1675
I =  9285847
number of imo 597
1675
===============
dfNewJourney 38
lenPos 1807
I =  9215294
number of imo 598
1807
===============
dfNewJourney 46
lenPos 1820
I =  9385142
number of imo 599
1820
===============
dfNewJourney 43
lenPos 1704
I =  9240847
number of imo 600
1704
===============
dfNewJourney 47
lenPos 1763
I =  9365817
number of imo 601
1763
===============
dfNewJourney 27
lenPos 1725
I =  9300996
number of imo 602
1725
===============
dfNewJourney 39
lenPos 1824
I =  9422512
number of imo 603
1824
===============
dfNewJourney 50
lenPos 1863
I =  9592240
number of imo 604
1863
===============
dfNewJourney 43
lenPos 1721
I =  9323388
number of imo 605
1721
===============
dfNewJourney 42
lenPos 1777
I =  9242338
number of imo 606
1777
===============
dfNewJourney 19
lenPos 1450
I =  9354272
number of imo 607
1450
===============
dfNewJourney 45
lenPos 1715
I =  9289776
number of imo 608
1715
===============
dfNewJourney 48
lenPos 1826
I =  9379519
number of imo 609
1826
===============
dfNewJourney 50
lenPos 1579
I =  9308950
number of imo 610
1579
===============
dfNewJourney 16
lenPos 1725
I =  9484077
number of imo 611
1725
===============
dfNewJourney 46
lenPos 1793
I =  9311024
number of imo 612
1793
===============
dfNewJourney 35
lenPos 1469
I =  9485631
number of imo 613
1469
===============
dfNewJourney 60
lenPos 1851
I =  9527403
number of imo 614
1851
===============
dfNewJourney 47
lenPos 1763
I =  9282481
number of imo 615
1763
===============
dfNewJourney 38
lenPos 1601
I =  9232606
number of imo 616
1601
===============
dfNewJourney 12
lenPos 1663
I =  9407354
number of imo 617
1663
===============
dfNewJourney 50
lenPos 1743
I =  9327011
number of imo 618
1743
===============
dfNewJourney 33
lenPos 1788
I =  9412452
number of imo 619
1788
===============
dfNewJourney 23
lenPos 1572
I =  9388730
number of imo 620
1572
===============
dfNewJourney 43
lenPos 1709
I =  9273650
number of imo 621
1709
===============
dfNewJourney 28
lenPos 1763
I =  9410650
number of imo 622
1763
===============
dfNewJourney 24
lenPos 1755
I =  9333436
number of imo 623
1755
===============
dfNewJourney 27
lenPos 1542
I =  9512185
number of imo 624
1542
===============
dfNewJourney 50
lenPos 1634
I =  9520869
number of imo 625
1634
===============
dfNewJourney 43
lenPos 1825
I =  9400849
number of imo 626
1825
===============
dfNewJourney 22
lenPos 1701
I =  9251028
number of imo 627
1701
===============
dfNewJourney 37
lenPos 1793
I =  9568184
number of imo 628
1793
===============
dfNewJourney 49
lenPos 1695
I =  9601194
number of imo 629
1695
===============
dfNewJourney 16
lenPos 1742
I =  9436006
number of imo 630
1742
===============
dfNewJourney 7
lenPos 1711
I =  9290830
number of imo 631
1711
===============
dfNewJourney 30
lenPos 0
I =  8911657
number of imo 632
dfNewJourney 3
lenPos 1613
I =  8117093
number of imo 633
1613
===============
dfNewJourney 40
lenPos 1574
I =  9388766
number of imo 634
1574
===============
dfNewJourney 29
lenPos 1865
I =  9171498
number of imo 635
1865
===============
dfNewJourney 23
lenPos 0
I =  10007600
number of imo 636
dfNewJourney 56
lenPos 1834
I =  9213909
number of imo 637
1834
===============
dfNewJourney 35
lenPos 1866
I =  9308091
number of imo 638
1866
===============
dfNewJourney 43
lenPos 1684
I =  9489106
number of imo 639
1684
===============
dfNewJourney 12
lenPos 1143
I =  9164536
number of imo 640
1143
===============
dfNewJourney 46
lenPos 1588
I =  9396660
number of imo 641
1588
===============
dfNewJourney 52
lenPos 1820
I =  9291248
number of imo 642
1820
===============
dfNewJourney 39
lenPos 1765
I =  9266877
number of imo 643
1765
===============
dfNewJourney 13
lenPos 1649
I =  9145853
number of imo 644
1649
===============
dfNewJourney 42
lenPos 1650
I =  9299355
number of imo 645
1650
===============
dfNewJourney 6
lenPos 1744
I =  9422196
number of imo 646
1744
===============
dfNewJourney 34
lenPos 1846
I =  9271406
number of imo 647
1846
===============
dfNewJourney 40
lenPos 1826
I =  9393084
number of imo 648
1826
===============
dfNewJourney 27
lenPos 1678
I =  9319882
number of imo 649
1678
===============
dfNewJourney 40
lenPos 1766
I =  9428982
number of imo 650
1766
===============
dfNewJourney 24
lenPos 1546
I =  9308170
number of imo 651
1546
===============
dfNewJourney 28
lenPos 1835
I =  9382750
number of imo 652
1835

===============
dfNewJourney 11
lenPos 0
I =  10007604
number of imo 653
dfNewJourney 34
lenPos 1781
I =  9326914
number of imo 654
1781
===============
dfNewJourney 57
lenPos 1677
I =  9433585
number of imo 655
1677
===============
dfNewJourney 44
lenPos 1752
I =  9330355
number of imo 656
1752
===============
dfNewJourney 33
lenPos 1852
I =  9316608
number of imo 657
1852
===============
dfNewJourney 37
lenPos 1666
I =  9272204
number of imo 658
1666
===============
dfNewJourney 15
lenPos 0
I =  10007602
number of imo 659
dfNewJourney 17
lenPos 0
I =  9186651
number of imo 660
dfNewJourney 51
lenPos 1653
I =  9279757
number of imo 661
1653
===============
dfNewJourney 49
lenPos 1735
I =  9459280
number of imo 662
1735
===============
dfNewJourney 37
lenPos 1730
I =  9337418
number of imo 663
1730
===============
dfNewJourney 38
lenPos 1842
I =  9544607
number of imo 664
1842
===============
dfNewJourney 45
lenPos 1858
I =  9374521
number of imo 665
1858
===============
dfNewJourney 4
lenPos 0
I =  8421169
number of imo 666
dfNewJourney 35
lenPos 1846
I =  9528031
number of imo 667
1846
===============
dfNewJourney 14
lenPos 1552
I =  9344100
number of imo 668
1552
===============
dfNewJourney 15
lenPos 1621
I =  9259197
number of imo 669
1621
===============
dfNewJourney 33
lenPos 1845
I =  9311036
number of imo 670
1845
===============
dfNewJourney 48
lenPos 1788
I =  9388314
number of imo 671
1788
===============
dfNewJourney 35
lenPos 0
I =  10015170
number of imo 672
dfNewJourney 36
lenPos 1858
I =  9197284
number of imo 673
1858
===============
dfNewJourney 45
lenPos 1868
I =  9413523
number of imo 674
1868
===============
dfNewJourney 9
lenPos 1636
I =  9388754
number of imo 675
1636
===============
dfNewJourney 48
lenPos 1767
I =  9531648
number of imo 676
1767
===============
dfNewJourney 57
lenPos 1664
I =  9404948
number of imo 677
1664
===============
dfNewJourney 8
lenPos 0
I =  8313116
number of imo 678
dfNewJourney 20
lenPos 1358
I =  9242481
number of imo 679
1358
===============
dfNewJourney 44
lenPos 1799
I =  9433846
number of imo 680
1799
===============
dfNewJourney 11
lenPos 0
I =  9131113
number of imo 681
dfNewJourney 34
lenPos 1184
I =  9110638
number of imo 682
1184
===============
dfNewJourney 49
lenPos 1815
I =  9589932
number of imo 683
1815
===============
dfNewJourney 43
lenPos 1780
I =  9321184
number of imo 684
1780
===============
dfNewJourney 33
lenPos 1784
I =  9323962
number of imo 685
1784
===============
dfNewJourney 31
lenPos 1719
I =  9242118
number of imo 686
1719
===============
dfNewJourney 5
lenPos 1703
I =  9232711
number of imo 687
1703
===============
dfNewJourney 42
lenPos 0
I =  10006705
number of imo 688
dfNewJourney 50
lenPos 1830
I =  9381835
number of imo 689
1830
===============
dfNewJourney 40
lenPos 1800
I =  9311000
number of imo 690
1800
===============
dfNewJourney 12
lenPos 1818
I =  9232876
number of imo 691
1818
===============
dfNewJourney 38
lenPos 1854
I =  9315757
number of imo 692
1854
===============
dfNewJourney 12
lenPos 1856
I =  9259185
number of imo 693
1856
===============
dfNewJourney 49
lenPos 1755
I =  9577056
number of imo 694
1755
===============
dfNewJourney 39
lenPos 1652
I =  9550709
number of imo 695
1652
===============
dfNewJourney 1
lenPos 1878
I =  9126003
number of imo 696
1878
===============
dfNewJourney 12
lenPos 1737
I =  9329784
number of imo 697
1737
===============
dfNewJourney 51
lenPos 1797
I =  9402213
number of imo 698
1797
===============
dfNewJourney 45
lenPos 1601
I =  9307152
number of imo 699
1601
===============
dfNewJourney 40
lenPos 1361
I =  9292503
number of imo 700
1361
===============
dfNewJourney 39
lenPos 1860
I =  9380831
number of imo 701
1860
===============
dfNewJourney 43
lenPos 1827
I =  9328144
number of imo 702
1827
===============
dfNewJourney 6
lenPos 1457
I =  9183257
number of imo 703
1457
===============
dfNewJourney 12
lenPos 1802
I =  9157777
number of imo 704
1802
===============
dfNewJourney 26
lenPos 1628
I =  9308986
number of imo 705
1628
===============
dfNewJourney 62
lenPos 1761
I =  9223722
number of imo 706
1761
===============
dfNewJourney 23
lenPos 1677
I =  9308223
number of imo 707
1677
===============
dfNewJourney 17
lenPos 1617
I =  9247443
number of imo 708
1617
===============
dfNewJourney 2
lenPos 1807
I =  9438860
number of imo 709
1807
===============
dfNewJourney 45
lenPos 1853
I =  9272668
number of imo 710
1853
===============
dfNewJourney 39
lenPos 1701
I =  9269257
number of imo 711
1701
===============
dfNewJourney 55
lenPos 1850
I =  9349203
number of imo 712
1850
===============
dfNewJourney 21
lenPos 1801
I =  9278492
number of imo 713
1801
===============
dfNewJourney 40
lenPos 1689
I =  9302970
number of imo 714
1689
===============
dfNewJourney 22
lenPos 1823
I =  9360427
number of imo 715
1823
===============
dfNewJourney 26
lenPos 1727
I =  9281932
number of imo 716
1727
===============
dfNewJourney 48
lenPos 1779
I =  9367695
number of imo 717
1779
===============
dfNewJourney 28
lenPos 1755
I =  9280586
number of imo 718
1755
===============
dfNewJourney 40
lenPos 1761
I =  9243318
number of imo 719
1761
===============
dfNewJourney 30
lenPos 1712
I =  9243033
number of imo 720
1712
===============
dfNewJourney 51
lenPos 1732
I =  9274317
number of imo 721
1732
===============
dfNewJourney 46
lenPos 1790
I =  9577070
number of imo 722
1790
===============
dfNewJourney 33
lenPos 1729
I =  9278715
number of imo 723
1729
===============
dfNewJourney 18
lenPos 1667
I =  9212383
number of imo 724
1667
===============
dfNewJourney 39
lenPos 1665
I =  9505821
number of imo 725
1665
===============
dfNewJourney 7
lenPos 1344
I =  9038751
number of imo 726
1344
===============
dfNewJourney 50
lenPos 1705
I =  9401154
number of imo 727
1705
===============
dfNewJourney 41
lenPos 1654
I =  9410894
number of imo 728
1654
===============
dfNewJourney 44
lenPos 0
I =  10007490
number of imo 729
dfNewJourney 48
lenPos 1859
I =  9262912
number of imo 730
1859
===============
dfNewJourney 28
lenPos 1803
I =  9302671
number of imo 731
1803
===============
dfNewJourney 36
lenPos 1843
I =  9460564
number of imo 732
1843
===============
dfNewJourney 33
lenPos 1744
I =  9288370
number of imo 733
1744
===============
dfNewJourney 9
lenPos 1752
I =  9270737
number of imo 734
1752
===============
dfNewJourney 36
lenPos 1535
I =  9544281
number of imo 735
1535
===============
dfNewJourney 47
lenPos 0
I =  10007610
number of imo 736
dfNewJourney 19
lenPos 1664
I =  9439383
number of imo 737
1664
===============
dfNewJourney 42
lenPos 1846
I =  9540807
number of imo 738
1846
===============
dfNewJourney 45
lenPos 1791
I =  9429003
number of imo 739
1791
===============
dfNewJourney 44
lenPos 1824
I =  9399894
number of imo 740
1824
===============
dfNewJourney 41
lenPos 1458
I =  9346873
number of imo 741
1458
===============
dfNewJourney 18
lenPos 1547
I =  9388778
number of imo 742
1547
===============
dfNewJourney 38
lenPos 1428
I =  9434204
number of imo 743
1428
===============
dfNewJourney 29
lenPos 1596
I =  9478690
number of imo 744
1596
===============
dfNewJourney 14
lenPos 1833
I =  9346720
number of imo 745
1833
===============
dfNewJourney 2
lenPos 0
I =  9030204
number of imo 746
dfNewJourney 61
lenPos 1744
I =  9487249
number of imo 747
1744
===============
dfNewJourney 79
lenPos 1907
I =  9564384
number of imo 748
1907
===============
dfNewJourney 41
lenPos 0
I =  10007571
number of imo 749
dfNewJourney 45
lenPos 1824
I =  9186625
number of imo 750
1824
===============
dfNewJourney 2
lenPos 1516
I =  8909472
number of imo 751
1516
===============
dfNewJourney 43
lenPos 0
I =  10007639
number of imo 752
dfNewJourney 8
lenPos 1802
I =  9232709
number of imo 753
1802
===============
dfNewJourney 9
lenPos 1844
I =  9237008
number of imo 754
1844
===============
dfNewJourney 36
lenPos 1739
I =  9402249
number of imo 755
1739
===============
dfNewJourney 8
lenPos 1826
I =  9360453
number of imo 756
1826
===============
dfNewJourney 47
lenPos 1834
I =  9565649
number of imo 757
1834
===============
dfNewJourney 35
lenPos 1837
I =  9522128
number of imo 758
1837
===============
dfNewJourney 23
lenPos 1700
I =  9282493
number of imo 759
1700

===============
dfNewJourney 29
lenPos 1785
I =  9397793
number of imo 760
1785
===============
dfNewJourney 15
lenPos 1794
I =  9259173
number of imo 761
1794
===============
dfNewJourney 5
lenPos 1817
I =  9416551
number of imo 762
1817
===============
dfNewJourney 32
lenPos 1724
I =  9388376
number of imo 763
1724
===============
dfNewJourney 8
lenPos 1826
I =  9258014
number of imo 764
1826
===============
dfNewJourney 38
lenPos 1891
I =  9367736
number of imo 765
1891
===============
dfNewJourney 49
lenPos 1727
I =  9172260
number of imo 766
1727
===============
dfNewJourney 15
lenPos 1844
I =  9396000
number of imo 767
1844
===============
dfNewJourney 44
lenPos 1586
I =  9344033
number of imo 768
1586
===============
dfNewJourney 27
lenPos 1883
I =  9540833
number of imo 769
1883
===============
dfNewJourney 5
lenPos 1757
I =  9275995
number of imo 770
1757
===============
dfNewJourney 33
lenPos 1726
I =  9514171
number of imo 771
1726
===============
dfNewJourney 41
lenPos 1648
I =  9414254
number of imo 772
1648
===============
dfNewJourney 43
lenPos 1816
I =  9389837
number of imo 773
1816
===============
dfNewJourney 46
lenPos 1804
I =  9292060
number of imo 774
1804
===============
dfNewJourney 43
lenPos 0
I =  10007624
number of imo 775
dfNewJourney 24
lenPos 1561
I =  9285718
number of imo 776
1561
===============
dfNewJourney 19
lenPos 1577
I =  9408138
number of imo 777
1577
===============
dfNewJourney 33
lenPos 1793
I =  9308857
number of imo 778
1793
===============
dfNewJourney 11
lenPos 0
I =  9047374
number of imo 779
dfNewJourney 41
lenPos 1214
I =  9174622
number of imo 780
1214
===============
dfNewJourney 13
lenPos 1819
I =  9352303
number of imo 781
1819
===============
dfNewJourney 38
lenPos 1833
I =  9569841
number of imo 782
1833
===============
dfNewJourney 15
lenPos 1747
I =  9328168
number of imo 783
1747
===============
dfNewJourney 37
lenPos 1763
I =  9249116
number of imo 784
1763
===============
dfNewJourney 52
lenPos 1728
I =  9401221
number of imo 785
1728
===============
dfNewJourney 42
lenPos 1569
I =  9520857
number of imo 786
1569
===============
dfNewJourney 13
lenPos 1619
I =  9179127
number of imo 787
1619
===============
dfNewJourney 47
lenPos 1781
I =  9393010
number of imo 788
1781
===============
dfNewJourney 39
lenPos 1683
I =  9568196
number of imo 789
1683
===============
dfNewJourney 36
lenPos 1732
I =  9363792
number of imo 790
1732
===============
dfNewJourney 42
lenPos 1763
I =  9384306
number of imo 791
1763
===============
dfNewJourney 11
lenPos 1362
I =  9271236
number of imo 792
1362
===============
dfNewJourney 34
lenPos 1696
I =  9276688
number of imo 793
1696
===============
dfNewJourney 21
lenPos 1685
I =  9285835
number of imo 794
1685
===============
dfNewJourney 32
lenPos 1848
I =  9459096
number of imo 795
1848
===============
dfNewJourney 30
lenPos 1535
I =  9430313
number of imo 796
1535
===============
dfNewJourney 47
lenPos 1853
I =  9336490
number of imo 797
1853
===============
dfNewJourney 31
lenPos 1761
I =  9486934
number of imo 798
1761
===============
dfNewJourney 16
lenPos 0
I =  10007588
number of imo 799
dfNewJourney 64
lenPos 1831
I =  9074420
number of imo 800
1831
===============
dfNewJourney 50
lenPos 1795
I =  9332183
number of imo 801
1795
===============
dfNewJourney 36
lenPos 1782
I =  9479840
number of imo 802
1782
===============
dfNewJourney 35
lenPos 1774
I =  9330343
number of imo 803
1774
===============
dfNewJourney 41
lenPos 1794
I =  9273624
number of imo 804
1794
===============
dfNewJourney 49
lenPos 1826
I =  9379313
number of imo 805
1826
===============
dfNewJourney 44
lenPos 1754
I =  9239939
number of imo 806
1754
===============
dfNewJourney 35
lenPos 1599
I =  9389502
number of imo 807
1599
===============
dfNewJourney 41
lenPos 1757
I =  9285756
number of imo 808
1757
===============
dfNewJourney 31
lenPos 1754
I =  9271327
number of imo 809
1754
===============
dfNewJourney 69
lenPos 1685
I =  9405849
number of imo 810
1685
===============
dfNewJourney 18
lenPos 1709
I =  9129940
number of imo 811
1709
===============
dfNewJourney 50
lenPos 1652
I =  9360130
number of imo 812
1652
===============
dfNewJourney 55
lenPos 1844
I =  9278624
number of imo 813
1844
===============
dfNewJourney 4
lenPos 0
I =  9197131
number of imo 814
dfNewJourney 49
lenPos 1829
I =  9278650
number of imo 815
1829
===============
dfNewJourney 36
lenPos 1818
I =  9102100
number of imo 816
1818
===============
dfNewJourney 37
lenPos 1808
I =  9326500
number of imo 817
1808
===============
dfNewJourney 44
lenPos 1667
I =  9358929
number of imo 818
1667
===============
dfNewJourney 46
lenPos 1826
I =  9482873
number of imo 819
1826
===============
dfNewJourney 24
lenPos 1515
I =  9388364
number of imo 820
1515
===============
dfNewJourney 34
lenPos 1790
I =  9400980
number of imo 821
1790
===============
dfNewJourney 47
lenPos 1788
I =  9539561
number of imo 822
1788
===============
dfNewJourney 46
lenPos 1816
I =  9442562
number of imo 823
1816
===============
dfNewJourney 43
lenPos 1874
I =  9512757
number of imo 824
1874
===============
dfNewJourney 38
lenPos 1740
I =  9326897
number of imo 825
1740
===============
dfNewJourney 17
lenPos 1827
I =  9417440
number of imo 826
1827
===============
dfNewJourney 37
lenPos 1703
I =  9308534
number of imo 827
1703
===============
dfNewJourney 42
lenPos 1805
I =  9274329
number of imo 828
1805
===============
dfNewJourney 43
lenPos 1841
I =  9299159
number of imo 829
1841
===============
dfNewJourney 36
lenPos 1699
I =  9333412
number of imo 830
1699
===============
dfNewJourney 40
lenPos 1808
I =  9278052
number of imo 831
1808
===============
dfNewJourney 44
lenPos 1768
I =  9388027
number of imo 832
1768
===============
dfNewJourney 42
lenPos 1736
I =  9380374
number of imo 833
1736
===============
dfNewJourney 18
lenPos 1792
I =  9260055
number of imo 834
1792
===============
dfNewJourney 32
lenPos 1805
I =  9321861
number of imo 835
1805
===============
dfNewJourney 36
lenPos 1410
I =  9183300
number of imo 836
1410
===============
dfNewJourney 15
lenPos 1510
I =  9221683
number of imo 837
1510
===============
dfNewJourney 20
lenPos 1537
I =  9282986
number of imo 838
1537
===============
dfNewJourney 25
lenPos 1829
I =  9299733
number of imo 839
1829
===============
dfNewJourney 25
lenPos 1691
I =  9407263
number of imo 840
1691
===============
dfNewJourney 18
lenPos 1798
I =  9339624
number of imo 841
1798
===============
dfNewJourney 37
lenPos 1636
I =  8919049
number of imo 842
1636
===============
dfNewJourney 47
lenPos 0
I =  10007492
number of imo 843
dfNewJourney 34
lenPos 1840
I =  9528380
number of imo 844
1840
===============
dfNewJourney 39
lenPos 1814
I =  9246798
number of imo 845
1814
===============
dfNewJourney 18
lenPos 1662
I =  9236999
number of imo 846
1662
===============
dfNewJourney 46
lenPos 1652
I =  9480150
number of imo 847
1652
===============
dfNewJourney 19
lenPos 1856
I =  9592305
number of imo 848
1856
===============
dfNewJourney 10
lenPos 1848
I =  9257022
number of imo 849
1848
===============
dfNewJourney 32
lenPos 1630
I =  9292577
number of imo 850
1630
===============
dfNewJourney 41
lenPos 1777
I =  9250165
number of imo 851
1777
===============
dfNewJourney 24
lenPos 1779
I =  9289788
number of imo 852
1779
===============
dfNewJourney 46
lenPos 1596
I =  9346885
number of imo 853
1596
===============
dfNewJourney 15
lenPos 1834
I =  9482603
number of imo 854
1834
===============
dfNewJourney 37
lenPos 1705
I =  9288021
number of imo 855
1705
===============
dfNewJourney 41
lenPos 1842
I =  9324459
number of imo 856
1842
===============
dfNewJourney 15
lenPos 1864
I =  9183582
number of imo 857
1864
===============
dfNewJourney 40
lenPos 1767
I =  9489077
number of imo 858
1767
===============
dfNewJourney 25
lenPos 1527
I =  9387059
number of imo 859
1527
===============
dfNewJourney 42
lenPos 1875
I =  9396749
number of imo 860
1875
===============
dfNewJourney 48
lenPos 1842
I =  9418119
number of imo 861
1842
===============
dfNewJourney 23
lenPos 1697
I =  9231626
number of imo 862
1697
===============
dfNewJourney 38
lenPos 1789
I =  9314909
number of imo 863
1789

===============
dfNewJourney 43
lenPos 1547
I =  9105085
number of imo 864
1547
===============
dfNewJourney 35
lenPos 1704
I =  9221671
number of imo 865
1704
===============
dfNewJourney 18
lenPos 0
I =  9183647
number of imo 866
dfNewJourney 46
lenPos 1707
I =  9284685
number of imo 867
1707
===============
dfNewJourney 33
lenPos 1701
I =  9485629
number of imo 868
1701
===============
dfNewJourney 2
lenPos 0
I =  9112064
number of imo 869
dfNewJourney 49
lenPos 1761
I =  9414266
number of imo 870
1761
===============
dfNewJourney 38
lenPos 0
I =  10015396
number of imo 871
dfNewJourney 51
lenPos 1781
I =  9583653
number of imo 872
1781
===============
dfNewJourney 7
lenPos 0
I =  9122916
number of imo 873
dfNewJourney 11
lenPos 1811
I =  9305609
number of imo 874
1811
===============
dfNewJourney 31
lenPos 1701
I =  9383869
number of imo 875
1701
===============
dfNewJourney 41
lenPos 0
I =  10007619
number of imo 876
dfNewJourney 28
lenPos 1689
I =  9570008
number of imo 877
1689
===============
dfNewJourney 26
lenPos 1680
I =  9229427
number of imo 878
1680
===============
dfNewJourney 45
lenPos 1796
I =  9461661
number of imo 879
1796
===============
dfNewJourney 48
lenPos 0
I =  10007646
number of imo 880
dfNewJourney 43
lenPos 1760
I =  9341940
number of imo 881
1760
===============
dfNewJourney 22
lenPos 1888
I =  9298507
number of imo 882
1888
===============
dfNewJourney 19
lenPos 1681
I =  9288863
number of imo 883
1681
===============
dfNewJourney 40
lenPos 1782
I =  9262194
number of imo 884
1782
===============
dfNewJourney 50
lenPos 1790
I =  9524762
number of imo 885
1790
===============
dfNewJourney 43
lenPos 1784
I =  9263916
number of imo 886
1784
===============
dfNewJourney 37
lenPos 1813
I =  9351414
number of imo 887
1813
===============
dfNewJourney 52
lenPos 1840
I =  9333242
number of imo 888
1840
===============
dfNewJourney 2
lenPos 0
I =  8806371
number of imo 889
dfNewJourney 10
lenPos 1435
I =  9105073
number of imo 890
1435
===============
dfNewJourney 35
lenPos 1269
I =  9105114
number of imo 891
1269
===============
dfNewJourney 19
lenPos 1799
I =  9288916
number of imo 892
1799
===============
dfNewJourney 42
lenPos 1506
I =  9278507
number of imo 893
1506
===============
dfNewJourney 25
lenPos 1718
I =  9436941
number of imo 894
1718
===============
dfNewJourney 45
lenPos 1710
I =  9282479
number of imo 895
1710
===============
dfNewJourney 31
lenPos 1752
I =  9296585
number of imo 896
1752
===============
dfNewJourney 22
lenPos 1338
I =  9258351
number of imo 897
1338
===============
dfNewJourney 23
lenPos 1623
I =  9337339
number of imo 898
1623
===============
dfNewJourney 38
lenPos 1857
I =  9460136
number of imo 899
1857
===============
dfNewJourney 20
lenPos 1552
I =  9376816
number of imo 900
1552
===============
dfNewJourney 47
lenPos 1807
I =  9396751
number of imo 901
1807
===============
dfNewJourney 39
lenPos 1748
I =  9334040
number of imo 902
1748
===============
dfNewJourney 15
lenPos 0
I =  8309531
number of imo 903
dfNewJourney 50
lenPos 1830
I =  9359399
number of imo 904
1830
===============
dfNewJourney 34
lenPos 1886
I =  9256028
number of imo 905
1886
===============
dfNewJourney 42
lenPos 1731
I =  9399272
number of imo 906
1731
===============
dfNewJourney 30
lenPos 1662
I =  9428841
number of imo 907
1662
===============
dfNewJourney 38
lenPos 1740
I =  9242326
number of imo 908
1740
===============
dfNewJourney 36
lenPos 1812
I =  9455052
number of imo 909
1812
===============
dfNewJourney 27
lenPos 1835
I =  9528366
number of imo 910
1835
===============
dfNewJourney 35
lenPos 1542
I =  9458858
number of imo 911
1542
===============
dfNewJourney 41
lenPos 1619
I =  9489065
number of imo 912
1619
===============
dfNewJourney 20
lenPos 1748
I =  9271365
number of imo 913
1748
===============
dfNewJourney 29
lenPos 1743
I =  9411991
number of imo 914
1743
===============
dfNewJourney 41
lenPos 1873
I =  9214317
number of imo 915
1873
===============
dfNewJourney 24
lenPos 1601
I =  9293002
number of imo 916
1601
===============
dfNewJourney 47
lenPos 1802
I =  9424649
number of imo 917
1802
===============
dfNewJourney 50
lenPos 1868
I =  9592692
number of imo 918
1868
===============
dfNewJourney 36
lenPos 1721
I =  9457593
number of imo 919
1721
===============
dfNewJourney 40
lenPos 1482
I =  9407823
number of imo 920
1482
===============
dfNewJourney 14
lenPos 1791
I =  9231171
number of imo 921
1791
===============
dfNewJourney 19
lenPos 1475
I =  9274082
number of imo 922
1475
===============
dfNewJourney 66
lenPos 1804
I =  9296597
number of imo 923
1804
===============
dfNewJourney 40
lenPos 0
I =  10015842
number of imo 924
dfNewJourney 13
lenPos 0
I =  9136046
number of imo 925
dfNewJourney 47
lenPos 1629
I =  9409259
number of imo 926
1629
===============
dfNewJourney 22
lenPos 1581
I =  9308132
number of imo 927
1581
===============
dfNewJourney 58
lenPos 1677
I =  9359870
number of imo 928
1677
===============
dfNewJourney 23
lenPos 1773
I =  9360439
number of imo 929
1773
===============
dfNewJourney 51
lenPos 1867
I =  9419723
number of imo 930
1867
===============
dfNewJourney 35
lenPos 1632
I =  9326885
number of imo 931
1632
===============
dfNewJourney 42
lenPos 1853
I =  9352212
number of imo 932
1853
===============
dfNewJourney 35
lenPos 1795
I =  9428372
number of imo 933
1795
===============
dfNewJourney 42
lenPos 1429
I =  9388728
number of imo 934
1429
===============
dfNewJourney 34
lenPos 1840
I =  9307346
number of imo 935
1840
===============
dfNewJourney 44
lenPos 1799
I =  9334569
number of imo 936
1799
===============
dfNewJourney 38
lenPos 1820
I =  9433509
number of imo 937
1820
===============
dfNewJourney 44
lenPos 1604
I =  9263643
number of imo 938
1604
===============
dfNewJourney 32
lenPos 1641
I =  9399868
number of imo 939
1641
===============
dfNewJourney 33
lenPos 1869
I =  9521447
number of imo 940
1869
===============
dfNewJourney 5
lenPos 980
I =  9289154
number of imo 941
980
===============
dfNewJourney 45
lenPos 1747
I =  9379301
number of imo 942
1747
===============
dfNewJourney 27
lenPos 1826
I =  9394959
number of imo 943
1826
===============
dfNewJourney 38
lenPos 1703
I =  9459008
number of imo 944
1703
===============
dfNewJourney 63
lenPos 1721
I =  9367528
number of imo 945
1721
===============
dfNewJourney 5
lenPos 1862
I =  9327360
number of imo 946
1862
===============
dfNewJourney 50
lenPos 1883
I =  9592238
number of imo 947
1883
===============
dfNewJourney 44
lenPos 1224
I =  9258894
number of imo 948
1224
===============
dfNewJourney 18
lenPos 1560
I =  9257723
number of imo 949
1560
===============
dfNewJourney 10
lenPos 1793
I =  9414814
number of imo 950
1793
===============
dfNewJourney 53
lenPos 1776
I =  9312860
number of imo 951
1776
===============
dfNewJourney 50
lenPos 0
I =  10007627
number of imo 952
dfNewJourney 40
lenPos 1647
I =  9403554
number of imo 953
1647
===============
dfNewJourney 30
lenPos 1601
I =  9080493
number of imo 954
1601
===============
dfNewJourney 42
lenPos 1814
I =  9265885
number of imo 955
1814
===============
dfNewJourney 9
lenPos 1851
I =  9336842
number of imo 956
1851
===============
dfNewJourney 34
lenPos 1738
I =  9540821
number of imo 957
1738
===============
dfNewJourney 25
lenPos 1631
I =  9215103
number of imo 958
1631
===============
dfNewJourney 52
lenPos 1701
I =  9359387
number of imo 959
1701
===============
dfNewJourney 30
lenPos 1570
I =  9284805
number of imo 960
1570
===============
dfNewJourney 44
lenPos 1806
I =  9571038
number of imo 961
1806
===============
dfNewJourney 21
lenPos 1706
I =  9472634
number of imo 962
1706
===============
dfNewJourney 46
lenPos 1791
I =  9327023
number of imo 963
1791
===============
dfNewJourney 44
lenPos 1708
I =  9417206
number of imo 964
1708
===============
dfNewJourney 56
lenPos 1856
I =  9102069
number of imo 965
1856
===============
dfNewJourney 85
lenPos 1865
I =  9370719
number of imo 966
1865
===============
dfNewJourney 41
lenPos 1846
I =  9461685
number of imo 967
1846
===============
dfNewJourney 28
lenPos 1751
I =  9306457
number of imo 968
1751
===============
dfNewJourney 25
lenPos 1854
I =  9390692
number of imo 969
1854

===============
dfNewJourney 14
lenPos 1739
I =  9265407
number of imo 970
1739
===============
dfNewJourney 62
lenPos 1619
I =  9488023
number of imo 971
1619
===============
dfNewJourney 31
lenPos 1819
I =  9250488
number of imo 972
1819
===============
dfNewJourney 32
lenPos 1760
I =  9326926
number of imo 973
1760
===============
dfNewJourney 24
lenPos 1235
I =  9212400
number of imo 974
1235
===============
dfNewJourney 22
lenPos 1396
I =  9224568
number of imo 975
1396
===============
dfNewJourney 13
lenPos 1448
I =  9234680
number of imo 976
1448
===============
dfNewJourney 20
lenPos 0
I =  10007513
number of imo 977
dfNewJourney 37
lenPos 1828
I =  9315939
number of imo 978
1828
===============
dfNewJourney 37
lenPos 1803
I =  9461843
number of imo 979
1803
===============
dfNewJourney 42
lenPos 1708
I =  9566162
number of imo 980
1708
===============
dfNewJourney 24
lenPos 1688
I =  9133070
number of imo 981
1688
===============
dfNewJourney 43
lenPos 1568
I =  9299599
number of imo 982
1568
===============
dfNewJourney 23
lenPos 1799
I =  9247077
number of imo 983
1799
===============
dfNewJourney 41
lenPos 1748
I =  9304588
number of imo 984
1748
===============
dfNewJourney 40
lenPos 1868
I =  9573660
number of imo 985
1868
===============
dfNewJourney 34
lenPos 1688
I =  9332822
number of imo 986
1688
===============
dfNewJourney 17
lenPos 1536
I =  9370850
number of imo 987
1536
===============
dfNewJourney 36
lenPos 1437
I =  9167150
number of imo 988
1437
===============
dfNewJourney 27
lenPos 1391
I =  9423906
number of imo 989
1391
===============
dfNewJourney 20
lenPos 1621
I =  9307920
number of imo 990
1621
===============
dfNewJourney 45
lenPos 1808
I =  9555319
number of imo 991
1808
===============
dfNewJourney 38
lenPos 1846
I =  9392468
number of imo 992
1846
===============
dfNewJourney 46
lenPos 1740
I =  9413573
number of imo 993
1740
===============
dfNewJourney 6
lenPos 1794
I =  9274666
number of imo 994
1794
===============
dfNewJourney 41
lenPos 1773
I =  9321160
number of imo 995
1773
===============
dfNewJourney 32
lenPos 1740
I =  9510462
number of imo 996
1740
===============
dfNewJourney 85
lenPos 1855
I =  9228370
number of imo 997
1855
===============
dfNewJourney 9
lenPos 1728
I =  9301287
number of imo 998
1728
===============
dfNewJourney 68
lenPos 1691
I =  9487263
number of imo 999
1691
===============
dfNewJourney 16
lenPos 1826
I =  9391373
number of imo 1000
1826
===============
dfNewJourney 39
lenPos 1860
I =  9275749
number of imo 1001
1860
===============
dfNewJourney 13
lenPos 1791
I =  9428815
number of imo 1002
1791
===============
dfNewJourney 21
lenPos 1797
I =  9420617
number of imo 1003
1797
===============
dfNewJourney 36
lenPos 1804
I =  9313266
number of imo 1004
1804
===============
dfNewJourney 63
lenPos 1801
I =  9250531
number of imo 1005
1801
===============
dfNewJourney 54
lenPos 1846
I =  9333280
number of imo 1006
1846
===============
dfNewJourney 56
lenPos 1835
I =  9467794
number of imo 1007
1835
===============
dfNewJourney 44
lenPos 1757
I =  9259329
number of imo 1008
1757
===============
dfNewJourney 24
lenPos 1546
I =  9262493
number of imo 1009
1546
===============
dfNewJourney 12
lenPos 1716
I =  9263203
number of imo 1010
1716
===============
dfNewJourney 28
lenPos 1810
I =  9291250
number of imo 1011
1810
===============
dfNewJourney 26
lenPos 1693
I =  9383962
number of imo 1012
1693
===============
dfNewJourney 63
lenPos 0
I =  10007630
number of imo 1013
dfNewJourney 44
lenPos 1834
I =  9273636
number of imo 1014
1834
===============
dfNewJourney 43
lenPos 1848
I =  9423724
number of imo 1015
1848
===============
dfNewJourney 11
lenPos 1210
I =  9147253
number of imo 1016
1210
===============
dfNewJourney 35
lenPos 1830
I =  9583665
number of imo 1017
1830
===============
dfNewJourney 40
lenPos 1783
I =  9313474
number of imo 1018
1783
===============
dfNewJourney 31
lenPos 1848
I =  9396787
number of imo 1019
1848
===============
dfNewJourney 29
lenPos 1629
I =  9388742
number of imo 1020
1629
===============
dfNewJourney 41
lenPos 1775
I =  9354909
number of imo 1021
1775
===============
dfNewJourney 27
lenPos 1585
I =  9491836
number of imo 1022
1585
===============
dfNewJourney 42
lenPos 1727
I =  9422550
number of imo 1023
1727
===============
dfNewJourney 24
lenPos 1575
I =  9258870
number of imo 1024
1575
===============
dfNewJourney 44
lenPos 1827
I =  9326873
number of imo 1025
1827
===============
dfNewJourney 34
lenPos 1799
I =  9301976
number of imo 1026
1799
===============
dfNewJourney 41
lenPos 1862
I =  9351426
number of imo 1027
1862
===============
dfNewJourney 40
lenPos 1616
I =  9417763
number of imo 1028
1616
===============
dfNewJourney 16
lenPos 1848
I =  9212474
number of imo 1029
1848
===============
dfNewJourney 24
lenPos 1749
I =  9312884
number of imo 1030
1749
===============
dfNewJourney 42
lenPos 1851
I =  9274305
number of imo 1031
1851
===============
dfNewJourney 42
lenPos 1670
I =  9172246
number of imo 1032
1670
===============
dfNewJourney 52
lenPos 1812
I =  9323376
number of imo 1033
1812
===============
dfNewJourney 49
lenPos 1880
I =  9367671
number of imo 1034
1880
===============
dfNewJourney 34
lenPos 1852
I =  9307994
number of imo 1035
1852
===============
dfNewJourney 49
lenPos 1770
I =  9252436
number of imo 1036
1770
===============
dfNewJourney 15
lenPos 1516
I =  9145841
number of imo 1037
1516
===============
dfNewJourney 34
lenPos 1846
I =  9234472
number of imo 1038
1846
===============
dfNewJourney 20
lenPos 1660
I =  9174488
number of imo 1039
1660
===============
dfNewJourney 31
lenPos 0
I =  10015826
number of imo 1040
dfNewJourney 37
lenPos 1755
I =  9295086
number of imo 1041
1755
===============
dfNewJourney 41
lenPos 1820
I =  9296731
number of imo 1042
1820
===============
dfNewJourney 48
lenPos 1789
I =  9565699
number of imo 1043
1789
===============
dfNewJourney 42
lenPos 1866
I =  9423736
number of imo 1044
1866
===============
dfNewJourney 44
lenPos 1731
I =  9381756
number of imo 1045
1731
===============
dfNewJourney 16
lenPos 1833
I =  9453999
number of imo 1046
1833
===============
dfNewJourney 40
lenPos 1743
I =  9254939
number of imo 1047
1743
===============
dfNewJourney 47
lenPos 1792
I =  9289740
number of imo 1048
1792
===============
dfNewJourney 31
lenPos 1859
I =  9399923
number of imo 1049
1859
===============
dfNewJourney 73
lenPos 0
I =  10007595
number of imo 1050
dfNewJourney 27
lenPos 1784
I =  9274654
number of imo 1051
1784
===============
dfNewJourney 29
lenPos 1564
I =  9279587
number of imo 1052
1564
===============
dfNewJourney 37
lenPos 1725
I =  9292515
number of imo 1053
1725
===============
dfNewJourney 17
lenPos 1840
I =  9592290
number of imo 1054
1840
===============
dfNewJourney 18
lenPos 1750
I =  9208095
number of imo 1055
1750
===============
dfNewJourney 64
lenPos 1827
I =  9294666
number of imo 1056
1827
===============
dfNewJourney 49
lenPos 1802
I =  9289738
number of imo 1057
1802
===============
dfNewJourney 47
lenPos 1854
I =  9573696
number of imo 1058
1854
===============
dfNewJourney 42
lenPos 0
I =  10007641
number of imo 1059
dfNewJourney 34
lenPos 1641
I =  9181534
number of imo 1060
1641
===============
dfNewJourney 54
lenPos 1682
I =  9359868
number of imo 1061
1682
===============
dfNewJourney 19
lenPos 0
I =  9136694
number of imo 1062
dfNewJourney 4
lenPos 1793
I =  9432218
number of imo 1063
1793
===============
dfNewJourney 45
lenPos 1807
I =  9467768
number of imo 1064
1807
===============
dfNewJourney 17
lenPos 1857
I =  9353577
number of imo 1065
1857
===============
dfNewJourney 23
lenPos 1775
I =  9304356
number of imo 1066
1775
===============
dfNewJourney 9
lenPos 1798
I =  9306653
number of imo 1067
1798
===============
dfNewJourney 36
lenPos 1762
I =  9314167
number of imo 1068
1762
===============
dfNewJourney 42
lenPos 1651
I =  9275402
number of imo 1069
1651
===============
dfNewJourney 35
lenPos 1803
I =  9233349
number of imo 1070
1803
===============
dfNewJourney 12
lenPos 1640
I =  9209295
number of imo 1071
1640
===============
dfNewJourney 42
lenPos 1843
I =  9307827
number of imo 1072
1843
===============
dfNewJourney 30
lenPos 1800
I =  9439797
number of imo 1073
1800

===============
dfNewJourney 17
lenPos 1758
I =  9334739
number of imo 1074
1758
===============
dfNewJourney 31
lenPos 1867
I =  9242156
number of imo 1075
1867
===============
dfNewJourney 52
lenPos 1739
I =  9367712
number of imo 1076
1739
===============
dfNewJourney 9
lenPos 1079
I =  9359636
number of imo 1077
1079
===============
dfNewJourney 30
lenPos 1813
I =  9315068
number of imo 1078
1813
===============
dfNewJourney 49
lenPos 1818
I =  9397468
number of imo 1079
1818
===============
dfNewJourney 47
lenPos 1695
I =  9387695
number of imo 1080
1695
===============
dfNewJourney 38
lenPos 1810
I =  9335824
number of imo 1081
1810
===============
dfNewJourney 58
lenPos 1720
I =  9370707
number of imo 1082
1720
===============
dfNewJourney 43
lenPos 1788
I =  9391426
number of imo 1083
1788
===============
dfNewJourney 15
lenPos 1802
I =  9339636
number of imo 1084
1802
===============
dfNewJourney 24
lenPos 1637
I =  9258686
number of imo 1085
1637
===============
dfNewJourney 57
lenPos 1671
I =  9417452
number of imo 1086
1671
===============
dfNewJourney 39
lenPos 1695
I =  9330599
number of imo 1087
1695
===============
dfNewJourney 40
lenPos 1839
I =  9391505
number of imo 1088
1839
===============
dfNewJourney 50
lenPos 1860
I =  9380075
number of imo 1089
1860
===============
dfNewJourney 35
lenPos 1578
I =  9267364
number of imo 1090
1578
===============
dfNewJourney 55
lenPos 1827
I =  9380049
number of imo 1091
1827
===============
dfNewJourney 2
lenPos 0
I =  8716722
number of imo 1092
dfNewJourney 40
lenPos 1645
I =  9278519
number of imo 1093
1645
===============
dfNewJourney 46
lenPos 1795
I =  9310161
number of imo 1094
1795
===============
dfNewJourney 49
lenPos 1786
I =  9602710
number of imo 1095
1786
===============
dfNewJourney 42
lenPos 1750
I =  9448164
number of imo 1096
1750
===============
dfNewJourney 43
lenPos 1641
I =  9112753
number of imo 1097
1641
===============
dfNewJourney 18
lenPos 1755
I =  9282297
number of imo 1098
1755
===============
dfNewJourney 29
lenPos 1819
I =  9299745
number of imo 1099
1819
===============
dfNewJourney 22
lenPos 1853
I =  9251286
number of imo 1100
1853
===============
dfNewJourney 9
lenPos 1371
I =  8717245
number of imo 1101
1371
===============
dfNewJourney 36
lenPos 0
I =  9166572
number of imo 1102
dfNewJourney 16
lenPos 1824
I =  9419450
number of imo 1103
1824
===============
dfNewJourney 20
lenPos 0
I =  9195315
number of imo 1104
dfNewJourney 5
lenPos 1625
I =  9292838
number of imo 1105
1625
===============
dfNewJourney 25
lenPos 1827
I =  9470997
number of imo 1106
1827
===============
dfNewJourney 41
lenPos 1650
I =  9337212
number of imo 1107
1650
===============
dfNewJourney 23
lenPos 1684
I =  9149213
number of imo 1108
1684
===============
dfNewJourney 60
lenPos 1737
I =  9299874
number of imo 1109
1737
===============
dfNewJourney 27
lenPos 1710
I =  9234587
number of imo 1110
1710
===============
dfNewJourney 48
lenPos 1792
I =  9576765
number of imo 1111
1792
===============
dfNewJourney 25
lenPos 1732
I =  9232917
number of imo 1112
1732
===============
dfNewJourney 58
lenPos 1699
I =  9335094
number of imo 1113
1699
===============
dfNewJourney 24
lenPos 1830
I =  9353125
number of imo 1114
1830
===============
dfNewJourney 47
lenPos 1840
I =  9309588
number of imo 1115
1840
===============
dfNewJourney 44
lenPos 1842
I =  9490313
number of imo 1116
1842
===============
dfNewJourney 30
lenPos 1772
I =  9312858
number of imo 1117
1772
===============
dfNewJourney 26
lenPos 1626
I =  9189134
number of imo 1118
1626
===============
dfNewJourney 67
lenPos 1674
I =  9383950
number of imo 1119
1674
===============
dfNewJourney 56
lenPos 0
I =  10007649
number of imo 1120
dfNewJourney 32
lenPos 1806
I =  9422548
number of imo 1121
1806
===============
dfNewJourney 33
lenPos 1695
I =  9455818
number of imo 1122
1695
===============
dfNewJourney 37
lenPos 1492
I =  9417751
number of imo 1123
1492
===============
dfNewJourney 44
lenPos 1865
I =  9383895
number of imo 1124
1865
===============
dfNewJourney 47
lenPos 1827
I =  9354519
number of imo 1125
1827
===============
dfNewJourney 29
lenPos 1625
I =  9402469
number of imo 1126
1625
===============
dfNewJourney 41
lenPos 1850
I =  9388209
number of imo 1127
1850
===============
dfNewJourney 48
lenPos 1866
I =  9382970
number of imo 1128
1866
===============
dfNewJourney 45
lenPos 1785
I =  8911669
number of imo 1129
1785
===============
dfNewJourney 17
lenPos 1820
I =  9235701
number of imo 1130
1820
===============
dfNewJourney 19
lenPos 0
I =  9200756
number of imo 1131
dfNewJourney 47
lenPos 1725
I =  9428994
number of imo 1132
1725
===============
dfNewJourney 38
lenPos 1737
I =  9228320
number of imo 1133
1737
===============
dfNewJourney 45
lenPos 1802
I =  9387281
number of imo 1134
1802
===============
dfNewJourney 14
lenPos 1870
I =  9353084
number of imo 1135
1870
===============
dfNewJourney 32
lenPos 1753
I =  9247508
number of imo 1136
1753
===============
dfNewJourney 53
lenPos 1855
I =  9301940
number of imo 1137
1855
===============
dfNewJourney 43
lenPos 1838
I =  9324318
number of imo 1138
1838
===============
dfNewJourney 16
lenPos 1850
I =  9380063
number of imo 1139
1850
===============
dfNewJourney 41
lenPos 0
I =  10010684
number of imo 1140
dfNewJourney 45
lenPos 1854
I =  9539597
number of imo 1141
1854
===============
dfNewJourney 44
lenPos 1809
I =  9420710
number of imo 1142
1809
===============
dfNewJourney 48
lenPos 1663
I =  9258882
number of imo 1143
1663
===============
dfNewJourney 18
lenPos 1426
I =  9299214
number of imo 1144
1426
===============
dfNewJourney 28
lenPos 1768
I =  9387956
number of imo 1145
1768
===============
dfNewJourney 27
lenPos 0
I =  9265720
number of imo 1146
dfNewJourney 37
lenPos 1811
I =  9399935
number of imo 1147
1811
===============
dfNewJourney 40
lenPos 1828
I =  9275658
number of imo 1148
1828
===============
dfNewJourney 36
lenPos 1820
I =  9215268
number of imo 1149
1820
===============
dfNewJourney 37
lenPos 1771
I =  9251884
number of imo 1150
1771
===============
dfNewJourney 38
lenPos 1765
I =  9298973
number of imo 1151
1765
===============
dfNewJourney 33
lenPos 1800
I =  9266841
number of imo 1152
1800
===============
dfNewJourney 19
lenPos 1670
I =  9379806
number of imo 1153
1670
===============
dfNewJourney 55
lenPos 1563
I =  9266372
number of imo 1154
1563
===============
dfNewJourney 44
lenPos 1785
I =  9321201
number of imo 1155
1785
===============
dfNewJourney 44
lenPos 1846
I =  9326512
number of imo 1156
1846
===============
dfNewJourney 14
lenPos 1312
I =  9150767
number of imo 1157
1312
===============
dfNewJourney 47
lenPos 1871
I =  9318022
number of imo 1158
1871
===============
dfNewJourney 21
lenPos 1538
I =  9403475
number of imo 1159
1538
===============
dfNewJourney 29
lenPos 1652
I =  9455703
number of imo 1160
1652
===============
dfNewJourney 38
lenPos 1554
I =  9266853
number of imo 1161
1554
===============
dfNewJourney 46
lenPos 1779
I =  9266243
number of imo 1162
1779
===============
dfNewJourney 7
lenPos 1825
I =  9414826
number of imo 1163
1825
===============
dfNewJourney 49
lenPos 1531
I =  9172258
number of imo 1164
1531
===============
dfNewJourney 43
lenPos 1786
I =  9499371
number of imo 1165
1786
===============
dfNewJourney 30
lenPos 1796
I =  9435600
number of imo 1166
1796
===============
dfNewJourney 45
lenPos 1746
I =  9435569
number of imo 1167
1746
===============
dfNewJourney 28
lenPos 1519
I =  9241085
number of imo 1168
1519
===============
dfNewJourney 32
lenPos 1699
I =  9231212
number of imo 1169
1699
===============
dfNewJourney 40
lenPos 1855
I =  9460576
number of imo 1170
1855
===============
dfNewJourney 15
lenPos 1746
I =  9297357
number of imo 1171
1746
===============
dfNewJourney 30
lenPos 1743
I =  9281580
number of imo 1172
1743
===============
dfNewJourney 49
lenPos 1751
I =  9288825
number of imo 1173
1751
===============
dfNewJourney 58
lenPos 1851
I =  9292967
number of imo 1174
1851
===============
dfNewJourney 16
lenPos 1703
I =  9222170
number of imo 1175
1703
===============
dfNewJourney 48
lenPos 1736
I =  9164677
number of imo 1176
1736
===============
dfNewJourney 45
lenPos 1860
I =  9351543
number of imo 1177
1860

===============
dfNewJourney 46
lenPos 1730
I =  9428970
number of imo 1178
1730
===============
dfNewJourney 22
lenPos 1866
I =  9299771
number of imo 1179
1866
===============
dfNewJourney 9
lenPos 1696
I =  9295098
number of imo 1180
1696
===============
dfNewJourney 42
lenPos 1853
I =  9262584
number of imo 1181
1853
===============
dfNewJourney 35
lenPos 1748
I =  9489118
number of imo 1182
1748
===============
dfNewJourney 77
lenPos 1866
I =  9392391
number of imo 1183
1866
===============
dfNewJourney 40
lenPos 0
I =  10007489
number of imo 1184
dfNewJourney 58
lenPos 1783
I =  9351531
number of imo 1185
1783
===============
dfNewJourney 36
lenPos 1825
I =  9555292
number of imo 1186
1825
===============
dfNewJourney 53
lenPos 1768
I =  9448152
number of imo 1187
1768
===============
dfNewJourney 27
lenPos 1513
I =  9246463
number of imo 1188
1513
===============
dfNewJourney 20
lenPos 0
I =  8906925
number of imo 1189
dfNewJourney 26
lenPos 1527
I =  9233208
number of imo 1190
1527
===============
dfNewJourney 32
lenPos 1566
I =  9376828
number of imo 1191
1566
===============
dfNewJourney 43
lenPos 1807
I =  9476812
number of imo 1192
1807
===============
dfNewJourney 43
lenPos 1718
I =  9299458
number of imo 1193
1718
===============
dfNewJourney 48
lenPos 1755
I =  9258595
number of imo 1194
1755
===============
dfNewJourney 30
lenPos 1793
I =  9392781
number of imo 1195
1793
===============
dfNewJourney 30
lenPos 1807
I =  9390769
number of imo 1196
1807
===============
dfNewJourney 42
lenPos 1653
I =  9455820
number of imo 1197
1653
===============
dfNewJourney 52
lenPos 1522
I =  9243320
number of imo 1198
1522
===============
dfNewJourney 48
lenPos 1796
I =  9290646
number of imo 1199
1796
===============
dfNewJourney 29
lenPos 1803
I =  9334038
number of imo 1200
1803
===============
dfNewJourney 29
lenPos 1155
I =  9144782
number of imo 1201
1155
===============
dfNewJourney 31
lenPos 0
I =  10007608
number of imo 1202
dfNewJourney 30
lenPos 1833
I =  9183611
number of imo 1203
1833
===============
dfNewJourney 54
lenPos 0
I =  10015433
number of imo 1204
dfNewJourney 60
lenPos 1860
I =  9422225
number of imo 1205
1860
===============
dfNewJourney 53
lenPos 1863
I =  9278698
number of imo 1206
1863
===============
dfNewJourney 27
lenPos 1831
I =  9399624
number of imo 1207
1831
===============
dfNewJourney 49
lenPos 1811
I =  9288356
number of imo 1208
1811
===============
dfNewJourney 38
lenPos 1779
I =  9407287
number of imo 1209
1779
===============
dfNewJourney 46
lenPos 1752
I =  9314181
number of imo 1210
1752
===============
dfNewJourney 20
lenPos 1666
I =  9246786
number of imo 1211
1666
===============
dfNewJourney 24
lenPos 1617
I =  9256236
number of imo 1212
1617
===============
dfNewJourney 37
lenPos 1646
I =  9443140
number of imo 1213
1646
===============
dfNewJourney 40
lenPos 1779
I =  9239628
number of imo 1214
1779
===============
dfNewJourney 38
lenPos 1744
I =  9266865
number of imo 1215
1744
===============
dfNewJourney 39
lenPos 1784
I =  9399911
number of imo 1216
1784
===============
dfNewJourney 43
lenPos 1841
I =  9047764
number of imo 1217
1841
===============
dfNewJourney 51
lenPos 1852
I =  9435894
number of imo 1218
1852
===============
dfNewJourney 18
lenPos 0
I =  10007592
number of imo 1219
dfNewJourney 49
lenPos 1743
I =  9397896
number of imo 1220
1743
===============
dfNewJourney 57
lenPos 1690
I =  9359882
number of imo 1221
1690
===============
dfNewJourney 22
lenPos 1804
I =  9476135
number of imo 1222
1804
===============
dfNewJourney 107
lenPos 1907
I =  9230995
number of imo 1223
1907
===============
dfNewJourney 35
lenPos 1822
I =  9305867
number of imo 1224
1822
===============
dfNewJourney 41
lenPos 1767
I =  9387712
number of imo 1225
1767
===============
dfNewJourney 20
lenPos 1836
I =  9313498
number of imo 1226
1836
===============
dfNewJourney 30
lenPos 1345
I =  9203796
number of imo 1227
1345
===============
dfNewJourney 52
lenPos 1805
I =  9482859
number of imo 1228
1805
===============
dfNewJourney 29
lenPos 1851
I =  9391529
number of imo 1229
1851
===============
dfNewJourney 43
lenPos 1734
I =  9292357
number of imo 1230
1734
===============
dfNewJourney 54
lenPos 1729
I =  9392365
number of imo 1231
1729
===============
dfNewJourney 30
lenPos 1789
I =  9447768
number of imo 1232
1789
===============
dfNewJourney 17
lenPos 1819
I =  9360415
number of imo 1233
1819
===============
dfNewJourney 36
lenPos 1737
I =  9425265
number of imo 1234
1737
===============
dfNewJourney 52
lenPos 1749
I =  9565730
number of imo 1235
1749
===============
dfNewJourney 40
lenPos 1882
I =  9470272
number of imo 1236
1882
===============
dfNewJourney 35
lenPos 1818
I =  9327451
number of imo 1237
1818
===============
dfNewJourney 41
lenPos 1813
I =  9282041
number of imo 1238
1813
===============
dfNewJourney 37
lenPos 1842
I =  9396713
number of imo 1239
1842
===============
dfNewJourney 5
lenPos 1450
I =  9284582
number of imo 1240
1450
===============
dfNewJourney 14
lenPos 0
I =  8416322
number of imo 1241
dfNewJourney 40
lenPos 1755
I =  9344007
number of imo 1242
1755
===============
dfNewJourney 17
lenPos 1461
I =  9262429
number of imo 1243
1461
===============
dfNewJourney 48
lenPos 1779
I =  9565637
number of imo 1244
1779
===============
dfNewJourney 24
lenPos 1822
I =  9263186
number of imo 1245
1822
===============
dfNewJourney 36
lenPos 1757
I =  9332303
number of imo 1246
1757
===============
dfNewJourney 40
lenPos 1843
I =  9358307
number of imo 1247
1843
===============
dfNewJourney 11
lenPos 1452
I =  9200744
number of imo 1248
1452
===============
dfNewJourney 33
lenPos 1827
I =  9323352
number of imo 1249
1827
===============
dfNewJourney 20
lenPos 1817
I =  9281011
number of imo 1250
1817
===============
dfNewJourney 11
lenPos 0
I =  9079171
number of imo 1251
dfNewJourney 49
lenPos 1781
I =  9552800
number of imo 1252
1781
===============
dfNewJourney 49
lenPos 1749
I =  9387724
number of imo 1253
1749
===============
dfNewJourney 49
lenPos 1827
I =  9381823
number of imo 1254
1827
===============
dfNewJourney 34
lenPos 1192
I =  9265861
number of imo 1255
1192
===============
dfNewJourney 39
lenPos 1723
I =  9419541
number of imo 1256
1723
===============
dfNewJourney 60
lenPos 1782
I =  9487275
number of imo 1257
1782
===============
dfNewJourney 41
lenPos 1735
I =  9288760
number of imo 1258
1735
===============
dfNewJourney 37
lenPos 803
I =  9125190
number of imo 1259
803
===============
dfNewJourney 63
lenPos 1721
I =  9295282
number of imo 1260
1721
===============
dfNewJourney 34
lenPos 1644
I =  9256937
number of imo 1261
1644
===============
dfNewJourney 23
lenPos 0
I =  10007515
number of imo 1262
dfNewJourney 35
lenPos 1752
I =  9379612
number of imo 1263
1752
===============
dfNewJourney 50
lenPos 1839
I =  9374272
number of imo 1264
1839
===============
dfNewJourney 41
lenPos 1650
I =  9114244
number of imo 1265
1650
===============
dfNewJourney 39
lenPos 1824
I =  9580405
number of imo 1266
1824
===============
dfNewJourney 55
lenPos 1864
I =  9363493
number of imo 1267
1864
===============
dfNewJourney 53
lenPos 1852
I =  9378371
number of imo 1268
1852
===============
dfNewJourney 13
lenPos 1279
I =  9508732
number of imo 1269
1279
===============
dfNewJourney 37
lenPos 1878
I =  9596258
number of imo 1270
1878
===============
dfNewJourney 19
lenPos 0
I =  9167215
number of imo 1271
dfNewJourney 34
lenPos 1835
I =  9309253
number of imo 1272
1835
===============
dfNewJourney 39
lenPos 1863
I =  9143207
number of imo 1273
1863
===============
dfNewJourney 34
lenPos 1775
I =  9346079
number of imo 1274
1775
===============
dfNewJourney 38
lenPos 1782
I =  9374337
number of imo 1275
1782
===============
dfNewJourney 26
lenPos 1801
I =  9462354
number of imo 1276
1801
===============
dfNewJourney 20
lenPos 1842
I =  9458016
number of imo 1277
1842
===============
dfNewJourney 50
lenPos 1784
I =  9298296
number of imo 1278
1784
===============
dfNewJourney 26
lenPos 1553
I =  9178317
number of imo 1279
1553
===============
dfNewJourney 37
lenPos 1829
I =  9263693
number of imo 1280
1829
===============
dfNewJourney 29
lenPos 1623
I =  9187435
number of imo 1281
1623

===============
dfNewJourney 43
lenPos 1739
I =  9388936
number of imo 1282
1739
===============
dfNewJourney 40
lenPos 1826
I =  9382798
number of imo 1283
1826
===============
dfNewJourney 50
lenPos 1809
I =  9289532
number of imo 1284
1809
===============
dfNewJourney 40
lenPos 1763
I =  9457610
number of imo 1285
1763
===============
dfNewJourney 60
lenPos 1796
I =  9433810
number of imo 1286
1796
===============
dfNewJourney 50
lenPos 1825
I =  9197155
number of imo 1287
1825
===============
dfNewJourney 43
lenPos 1795
I =  9459242
number of imo 1288
1795
===============
dfNewJourney 46
lenPos 1776
I =  9405904
number of imo 1289
1776
===============
dfNewJourney 35
lenPos 1530
I =  9487184
number of imo 1290
1530
===============
dfNewJourney 28
lenPos 0
I =  10007650
number of imo 1291
dfNewJourney 46
lenPos 1828
I =  9379909
number of imo 1292
1828
===============
dfNewJourney 22
lenPos 1859
I =  9274628
number of imo 1293
1859
===============
dfNewJourney 36
lenPos 1789
I =  9343352
number of imo 1294
1789
===============
dfNewJourney 53
lenPos 1737
I =  9435612
number of imo 1295
1737
===============
dfNewJourney 12
lenPos 1388
I =  9138604
number of imo 1296
1388
===============
dfNewJourney 46
lenPos 1754
I =  9277761
number of imo 1297
1754
===============
dfNewJourney 27
lenPos 1793
I =  9272503
number of imo 1298
1793
===============
dfNewJourney 44
lenPos 1723
I =  9461855
number of imo 1299
1723
===============
dfNewJourney 31
lenPos 1690
I =  9126273
number of imo 1300
1690
===============
dfNewJourney 56
lenPos 1849
I =  9102071
number of imo 1301
1849
===============
dfNewJourney 19
lenPos 1674
I =  9396335
number of imo 1302
1674
===============
dfNewJourney 1
lenPos 0
I =  8711095
number of imo 1303
dfNewJourney 69
lenPos 1881
I =  9581447
number of imo 1304
1881
===============
dfNewJourney 12
lenPos 1869
I =  9312896
number of imo 1305
1869
===============
dfNewJourney 13
lenPos 1833
I =  9382712
number of imo 1306
1833
===============
dfNewJourney 38
lenPos 1829
I =  9367669
number of imo 1307
1829
===============
dfNewJourney 34
lenPos 1681
I =  9384069
number of imo 1308
1681
===============
dfNewJourney 35
lenPos 1823
I =  9592680
number of imo 1309
1823
===============
dfNewJourney 31
lenPos 1598
I =  9489285
number of imo 1310
1598
===============
dfNewJourney 56
lenPos 1663
I =  9382085
number of imo 1311
1663
===============
dfNewJourney 44
lenPos 1845
I =  9047518
number of imo 1312
1845
===============
dfNewJourney 36
lenPos 1697
I =  9425552
number of imo 1313
1697
===============
dfNewJourney 11
lenPos 0
I =  10007512
number of imo 1314
dfNewJourney 31
lenPos 0
I =  10015828
number of imo 1315
dfNewJourney 46
lenPos 1826
I =  9470258
number of imo 1316
1826
===============
dfNewJourney 11
lenPos 1821
I =  9587843
number of imo 1317
1821
===============
dfNewJourney 37
lenPos 1783
I =  9283617
number of imo 1318
1783
===============
dfNewJourney 15
lenPos 1680
I =  9143532
number of imo 1319
1680
===============
dfNewJourney 41
lenPos 1808
I =  9467770
number of imo 1320
1808
===============
dfNewJourney 50
lenPos 0
I =  10007637
number of imo 1321
dfNewJourney 43
lenPos 1792
I =  9489209
number of imo 1322
1792
===============
dfNewJourney 58
lenPos 1687
I =  9335068
number of imo 1323
1687
===============
dfNewJourney 42
lenPos 1808
I =  9275969
number of imo 1324
1808
===============
dfNewJourney 20
lenPos 1816
I =  9587831
number of imo 1325
1816
===============
dfNewJourney 41
lenPos 1762
I =  9388948
number of imo 1326
1762
===============
dfNewJourney 38
lenPos 1753
I =  9258600
number of imo 1327
1753
===============
dfNewJourney 45
lenPos 1794
I =  9354894
number of imo 1328
1794
===============
dfNewJourney 58
lenPos 1717
I =  9359894
number of imo 1329
1717
===============
dfNewJourney 13
lenPos 1688
I =  9251406
number of imo 1330
1688
===============
dfNewJourney 47
lenPos 1853
I =  9467809
number of imo 1331
1853
===============
dfNewJourney 21
lenPos 1722
I =  9272709
number of imo 1332
1722
===============
dfNewJourney 12
lenPos 1689
I =  9396098
number of imo 1333
1689
===============
dfNewJourney 40
lenPos 1647
I =  9304825
number of imo 1334
1647
===============
dfNewJourney 33
lenPos 1857
I =  9263708
number of imo 1335
1857
===============
dfNewJourney 30
lenPos 1800
I =  9198094
number of imo 1336
1800
===============
dfNewJourney 21
lenPos 1607
I =  9112222
number of imo 1337
1607
===============
dfNewJourney 9
lenPos 1861
I =  9183623
number of imo 1338
1861
===============
dfNewJourney 42
lenPos 1875
I =  9595632
number of imo 1339
1875
===============
dfNewJourney 57
lenPos 0
I =  10015467
number of imo 1340
dfNewJourney 50
lenPos 1814
I =  9301902
number of imo 1341
1814
===============
dfNewJourney 35
lenPos 1760
I =  9414060
number of imo 1342
1760
===============
dfNewJourney 24
lenPos 1789
I =  9264271
number of imo 1343
1789
===============
dfNewJourney 5
lenPos 1807
I =  9260079
number of imo 1344
1807
===============
dfNewJourney 40
lenPos 1621
I =  9284386
number of imo 1345
1621
===============
dfNewJourney 37
lenPos 1871
I =  9584102
number of imo 1346
1871
===============
dfNewJourney 67
lenPos 1349
I =  9202388
number of imo 1347
1349
===============
dfNewJourney 25
lenPos 1855
I =  9516959
number of imo 1348
1855
===============
dfNewJourney 54
lenPos 1816
I =  9274484
number of imo 1349
1816
===============
dfNewJourney 13
lenPos 1241
I =  9168439
number of imo 1350
1241
===============
dfNewJourney 20
lenPos 0
I =  8309543
number of imo 1351
dfNewJourney 44
lenPos 1790
I =  9277797
number of imo 1352
1790
===============
dfNewJourney 32
lenPos 1764
I =  9451707
number of imo 1353
1764
===============
dfNewJourney 42
lenPos 1710
I =  9344112
number of imo 1354
1710
===============
dfNewJourney 40
lenPos 1791
I =  9425318
number of imo 1355
1791
===============
dfNewJourney 48
lenPos 1675
I =  9321562
number of imo 1356
1675
===============
dfNewJourney 24
lenPos 1722
I =  9172715
number of imo 1357
1722
===============
dfNewJourney 12
lenPos 0
I =  9200926
number of imo 1358
dfNewJourney 50
lenPos 1710
I =  9512484
number of imo 1359
1710
===============
dfNewJourney 44
lenPos 1797
I =  9312444
number of imo 1360
1797
===============
dfNewJourney 32
lenPos 1645
I =  9221011
number of imo 1361
1645
===============
dfNewJourney 40
lenPos 1690
I =  9380518
number of imo 1362
1690
===============
dfNewJourney 43
lenPos 1739
I =  9123661
number of imo 1363
1739
===============
dfNewJourney 20
lenPos 1375
I =  9112234
number of imo 1364
1375
===============
dfNewJourney 35
lenPos 1705
I =  9316593
number of imo 1365
1705
===============
dfNewJourney 45
lenPos 1669
I =  9282053
number of imo 1366
1669
===============
dfNewJourney 4
lenPos 1631
I =  9187629
number of imo 1367
1631
===============
dfNewJourney 38
lenPos 1871
I =  9143219
number of imo 1368
1871
===============
dfNewJourney 23
lenPos 1789
I =  9323560
number of imo 1369
1789
===============
dfNewJourney 15
lenPos 1527
I =  9156591
number of imo 1370
1527
===============
dfNewJourney 29
lenPos 1837
I =  9285861
number of imo 1371
1837
===============
dfNewJourney 39
lenPos 1697
I =  9433016
number of imo 1372
1697
===============
dfNewJourney 17
lenPos 1586
I =  9239460
number of imo 1373
1586
===============
dfNewJourney 34
lenPos 1812
I =  9176773
number of imo 1374
1812
===============
dfNewJourney 14
lenPos 1642
I =  9402471
number of imo 1375
1642
===============
dfNewJourney 28
lenPos 1784
I =  8819081
number of imo 1376
1784
===============
dfNewJourney 31
lenPos 1810
I =  9577032
number of imo 1377
1810
===============
dfNewJourney 31
lenPos 1815
I =  9279733
number of imo 1378
1815
===============
dfNewJourney 2
lenPos 0
I =  9015060
number of imo 1379
dfNewJourney 41
lenPos 1709
I =  9325855
number of imo 1380
1709
===============
dfNewJourney 19
lenPos 1657
I =  9255244
number of imo 1381
1657
===============
dfNewJourney 44
lenPos 1825
I =  9437658
number of imo 1382
1825
===============
dfNewJourney 35
lenPos 1839
I =  9290579
number of imo 1383
1839
===============
dfNewJourney 5
lenPos 0
I =  8413851
number of imo 1384
dfNewJourney 19
lenPos 1365
I =  9126015
number of imo 1385
1365
===============
dfNewJourney 24
lenPos 1582
I =  9337389
number of imo 1386
1582

===============
dfNewJourney 40
lenPos 1756
I =  9459010
number of imo 1387
1756
===============
dfNewJourney 68
lenPos 1764
I =  9595644
number of imo 1388
1764
===============
dfNewJourney 22
lenPos 1786
I =  9256298
number of imo 1389
1786
===============
dfNewJourney 6
lenPos 0
I =  9006708
number of imo 1390
dfNewJourney 49
lenPos 1852
I =  9380051
number of imo 1391
1852
===============
dfNewJourney 39
lenPos 1793
I =  9414072
number of imo 1392
1793
===============
dfNewJourney 38
lenPos 1728
I =  9297412
number of imo 1393
1728
===============
dfNewJourney 40
lenPos 1728
I =  9337901
number of imo 1394
1728
===============
dfNewJourney 47
lenPos 1869
I =  9087013
number of imo 1395
1869
===============
dfNewJourney 21
lenPos 1696
I =  9321847
number of imo 1396
1696
===============
dfNewJourney 15
lenPos 1652
I =  9295048
number of imo 1397
1652
===============
dfNewJourney 3
lenPos 1532
I =  8121173
number of imo 1398
1532
===============
dfNewJourney 36
lenPos 0
I =  10007615
number of imo 1399
dfNewJourney 32
lenPos 1715
I =  9288851
number of imo 1400
1715
===============
dfNewJourney 38
lenPos 1707
I =  9309502
number of imo 1401
1707
===============
dfNewJourney 38
lenPos 1720
I =  9266750
number of imo 1402
1720
===============
dfNewJourney 42
lenPos 1667
I =  9207728
number of imo 1403
1667
===============
dfNewJourney 36
lenPos 1768
I =  9333785
number of imo 1404
1768
===============
dfNewJourney 49
lenPos 1791
I =  9429039
number of imo 1405
1791
===============
dfNewJourney 8
lenPos 0
I =  9018414
number of imo 1406
dfNewJourney 62
lenPos 1637
I =  9345623
number of imo 1407
1637
===============
dfNewJourney 20
lenPos 1681
I =  9448334
number of imo 1408
1681
===============
dfNewJourney 25
lenPos 1577
I =  9292606
number of imo 1409
1577
===============
dfNewJourney 35
lenPos 1854
I =  9461702
number of imo 1410
1854
===============
dfNewJourney 29
lenPos 0
I =  9265732
number of imo 1411
dfNewJourney 60
lenPos 1880
I =  9403310
number of imo 1412
1880
===============
dfNewJourney 32
lenPos 1822
I =  9317951
number of imo 1413
1822
===============
dfNewJourney 31
lenPos 1811
I =  9277735
number of imo 1414
1811
===============
dfNewJourney 45
lenPos 1818
I =  9336505
number of imo 1415
1818
===============
dfNewJourney 37
lenPos 1633
I =  9290608
number of imo 1416
1633
===============
dfNewJourney 34
lenPos 980
I =  9212369
number of imo 1417
980
===============
dfNewJourney 35
lenPos 1779
I =  9343780
number of imo 1418
1779
===============
dfNewJourney 30
lenPos 1720
I =  9243021
number of imo 1419
1720
===============
dfNewJourney 62
lenPos 1721
I =  9323974
number of imo 1420
1721
===============
dfNewJourney 36
lenPos 1611
I =  9281554
number of imo 1421
1611
===============
dfNewJourney 13
lenPos 1610
I =  9116383
number of imo 1422
1610
===============
dfNewJourney 33
lenPos 1870
I =  9351452
number of imo 1423
1870
===============
dfNewJourney 39
lenPos 1742
I =  9307798
number of imo 1424
1742
===============
dfNewJourney 48
lenPos 1722
I =  9597147
number of imo 1425
1722
===============
dfNewJourney 38
lenPos 1832
I =  9215270
number of imo 1426
1832
===============
dfNewJourney 111
lenPos 1903
I =  9242089
number of imo 1427
1903
===============
dfNewJourney 29
lenPos 1759
I =  9405928
number of imo 1428
1759
===============
dfNewJourney 6
lenPos 0
I =  8000915
number of imo 1429
dfNewJourney 31
lenPos 1770
I =  9363467
number of imo 1430
1770
===============
dfNewJourney 50
lenPos 1787
I =  9425538
number of imo 1431
1787
===============
dfNewJourney 43
lenPos 1559
I =  9235062
number of imo 1432
1559
===============
dfNewJourney 45
lenPos 1776
I =  9363481
number of imo 1433
1776
===============
dfNewJourney 20
lenPos 1366
I =  9187760
number of imo 1434
1366
===============
dfNewJourney 42
lenPos 1841
I =  9435909
number of imo 1435
1841
===============
dfNewJourney 7
lenPos 1805
I =  9261401
number of imo 1436
1805
===============
dfNewJourney 46
lenPos 1755
I =  9496032
number of imo 1437
1755
===============
dfNewJourney 39
lenPos 1811
I =  9315056
number of imo 1438
1811
===============
dfNewJourney 12
lenPos 1116
I =  9217448
number of imo 1439
1116
===============
dfNewJourney 61
lenPos 1674
I =  9290311
number of imo 1440
1674
===============
dfNewJourney 7
lenPos 0
I =  9215139
number of imo 1441
dfNewJourney 50
lenPos 0
I =  10007609
number of imo 1442
dfNewJourney 30
lenPos 1638
I =  9332781
number of imo 1443
1638
===============
dfNewJourney 4
lenPos 1764
I =  9308974
number of imo 1444
1764
===============
dfNewJourney 52
lenPos 1795
I =  9448724
number of imo 1445
1795
===============
dfNewJourney 47
lenPos 1750
I =  9222132
number of imo 1446
1750
===============
dfNewJourney 16
lenPos 0
I =  10007596
number of imo 1447
dfNewJourney 40
lenPos 1770
I =  9456939
number of imo 1448
1770
===============
dfNewJourney 29
lenPos 1481
I =  9273246
number of imo 1449
1481
===============
dfNewJourney 26
lenPos 0
I =  10016039
number of imo 1450
dfNewJourney 17
lenPos 1834
I =  9259915
number of imo 1451
1834
===============
dfNewJourney 45
lenPos 1594
I =  9417177
number of imo 1452
1594
===============
dfNewJourney 42
lenPos 1761
I =  9323986
number of imo 1453
1761
===============
dfNewJourney 30
lenPos 1558
I =  9337391
number of imo 1454
1558
===============
dfNewJourney 47
lenPos 1859
I =  9311048
number of imo 1455
1859
===============
dfNewJourney 46
lenPos 0
I =  10014061
number of imo 1456
dfNewJourney 44
lenPos 1801
I =  9552472
number of imo 1457
1801
===============
dfNewJourney 35
lenPos 1809
I =  9391531
number of imo 1458
1809
===============
dfNewJourney 43
lenPos 1714
I =  9572276
number of imo 1459
1714
===============
dfNewJourney 40
lenPos 1633
I =  9365386
number of imo 1460
1633
===============
dfNewJourney 39
lenPos 0
I =  10007573
number of imo 1461
dfNewJourney 46
lenPos 1730
I =  9538440
number of imo 1462
1730
===============
dfNewJourney 25
lenPos 1601
I =  9434890
number of imo 1463
1601
===============
dfNewJourney 34
lenPos 1583
I =  9397755
number of imo 1464
1583
===============
dfNewJourney 57
lenPos 1599
I =  9354492
number of imo 1465
1599
===============
dfNewJourney 37
lenPos 1822
I =  9365001
number of imo 1466
1822
===============
dfNewJourney 4
lenPos 1836
I =  9352298
number of imo 1467
1836
===============
dfNewJourney 31
lenPos 1740
I =  9374844
number of imo 1468
1740
===============
dfNewJourney 67
lenPos 0
I =  10007643
number of imo 1469
dfNewJourney 43
lenPos 1822
I =  9414280
number of imo 1470
1822
===============
dfNewJourney 44
lenPos 1804
I =  9292058
number of imo 1471
1804
===============
dfNewJourney 28
lenPos 1820
I =  9418573
number of imo 1472
1820
===============
dfNewJourney 44
lenPos 0
I =  10007578
number of imo 1473
dfNewJourney 30
lenPos 1772
I =  9346861
number of imo 1474
1772
===============
dfNewJourney 34
lenPos 1758
I =  9351464
number of imo 1475
1758
===============
dfNewJourney 40
lenPos 1688
I =  9459709
number of imo 1476
1688
===============
dfNewJourney 32
lenPos 1841
I =  9307982
number of imo 1477
1841
===============
dfNewJourney 39
lenPos 1836
I =  9391476
number of imo 1478
1836
===============
dfNewJourney 11
lenPos 1767
I =  9408102
number of imo 1479
1767
===============
dfNewJourney 24
lenPos 1685
I =  9396385
number of imo 1480
1685
===============
dfNewJourney 22
lenPos 1847
I =  9595125
number of imo 1481
1847
===============
dfNewJourney 28
lenPos 1845
I =  9343986
number of imo 1482
1845
===============
dfNewJourney 16
lenPos 1857
I =  9442158
number of imo 1483
1857
===============
dfNewJourney 43
lenPos 1841
I =  9590905
number of imo 1484
1841
===============
dfNewJourney 38
lenPos 1735
I =  9242211
number of imo 1485
1735
===============
dfNewJourney 38
lenPos 1591
I =  9461934
number of imo 1486
1591
===============
dfNewJourney 41
lenPos 1700
I =  9508160
number of imo 1487
1700
===============
dfNewJourney 41
lenPos 1598
I =  9407835
number of imo 1488
1598
===============
dfNewJourney 39
lenPos 1682
I =  9298272
number of imo 1489
1682
===============
dfNewJourney 49
lenPos 0
I =  10007628
number of imo 1490
dfNewJourney 24
lenPos 1815
I =  9428360
number of imo 1491
1815
===============
dfNewJourney 35
lenPos 1548
I =  9354301
number of imo 1492
1548

===============
dfNewJourney 42
lenPos 1831
I =  9310848
number of imo 1493
1831
===============
dfNewJourney 1
lenPos 0
I =  8810932
number of imo 1494
dfNewJourney 48
lenPos 0
I =  8618877
number of imo 1495
dfNewJourney 61
lenPos 1879
I =  9594664
number of imo 1496
1879
===============
dfNewJourney 43
lenPos 1655
I =  9275751
number of imo 1497
1655
===============
dfNewJourney 10
lenPos 1815
I =  9253258
number of imo 1498
1815
===============
dfNewJourney 39
lenPos 1815
I =  9258674
number of imo 1499
1815
===============
dfNewJourney 42
lenPos 1878
I =  9363780
number of imo 1500
1878
===============
dfNewJourney 50
lenPos 0
I =  10007491
number of imo 1501
dfNewJourney 37
lenPos 1681
I =  9434216
number of imo 1502
1681
===============
dfNewJourney 43
lenPos 1766
I =  9451288
number of imo 1503
1766
===============
dfNewJourney 33
lenPos 1799
I =  9409467
number of imo 1504
1799
===============
dfNewJourney 48
lenPos 1756
I =  9396799
number of imo 1505
1756
===============
dfNewJourney 43
lenPos 1725
I =  9335056
number of imo 1506
1725
===============
dfNewJourney 40
lenPos 1577
I =  9267132
number of imo 1507
1577
===============
dfNewJourney 44
lenPos 1788
I =  9440033
number of imo 1508
1788
===============
dfNewJourney 42
lenPos 1849
I =  9087025
number of imo 1509
1849
===============
dfNewJourney 37
lenPos 1724
I =  9240407
number of imo 1510
1724
===============
dfNewJourney 12
lenPos 0
I =  9215127
number of imo 1511
dfNewJourney 55
lenPos 1801
I =  9333278
number of imo 1512
1801
===============
dfNewJourney 5
lenPos 1895
I =  9327401
number of imo 1513
1895
===============
dfNewJourney 16
lenPos 0
I =  8309555
number of imo 1514
dfNewJourney 38
lenPos 1758
I =  9457024
number of imo 1515
1758
===============
dfNewJourney 23
lenPos 1817
I =  9308962
number of imo 1516
1817
===============
dfNewJourney 46
lenPos 1864
I =  9425526
number of imo 1517
1864
===============
dfNewJourney 50
lenPos 1851
I =  9359375
number of imo 1518
1851
===============
dfNewJourney 35
lenPos 1815
I =  9281853
number of imo 1519
1815
===============
dfNewJourney 62
lenPos 1645
I =  9323326
number of imo 1520
1645
===============
dfNewJourney 45
lenPos 1875
I =  9375575
number of imo 1521
1875
===============
dfNewJourney 41
lenPos 1827
I =  9337523
number of imo 1522
1827
===============
dfNewJourney 23
lenPos 1695
I =  9219276
number of imo 1523
1695
===============
dfNewJourney 19
lenPos 1778
I =  9364239
number of imo 1524
1778
===============
dfNewJourney 6
lenPos 0
I =  10003538
number of imo 1525
dfNewJourney 81
lenPos 1903
I =  9342580
number of imo 1526
1903
===============
dfNewJourney 39
lenPos 1883
I =  9319480
number of imo 1527
1883
===============
dfNewJourney 34
lenPos 1706
I =  9278727
number of imo 1528
1706
===============
dfNewJourney 32
lenPos 1711
I =  9365362
number of imo 1529
1711
===============
dfNewJourney 42
lenPos 1857
I =  9402794
number of imo 1530
1857
===============
dfNewJourney 9
lenPos 1539
I =  9118628
number of imo 1531
1539
===============
dfNewJourney 19
lenPos 1853
I =  9489900
number of imo 1532
1853
===============
dfNewJourney 40
lenPos 1702
I =  9262091
number of imo 1533
1702
===============
dfNewJourney 57
lenPos 1847
I =  9426283
number of imo 1534
1847
===============
dfNewJourney 28
lenPos 1749
I =  9411135
number of imo 1535
1749
===============
dfNewJourney 30
lenPos 1702
I =  9442720
number of imo 1536
1702
===============
dfNewJourney 42
lenPos 1551
I =  9440497
number of imo 1537
1551
===============
dfNewJourney 20
lenPos 1781
I =  9241827
number of imo 1538
1781
===============
dfNewJourney 31
lenPos 1826
I =  9315733
number of imo 1539
1826
===============
dfNewJourney 36
lenPos 1874
I =  9387279
number of imo 1540
1874
===============
dfNewJourney 44
lenPos 1852
I =  9234513
number of imo 1541
1852
===============
dfNewJourney 39
lenPos 1803
I =  9265366
number of imo 1542
1803
===============
dfNewJourney 48
lenPos 1795
I =  9256626
number of imo 1543
1795
===============
dfNewJourney 35
lenPos 1779
I =  9393101
number of imo 1544
1779
===============
dfNewJourney 45
lenPos 1767
I =  9457749
number of imo 1545
1767
===============
dfNewJourney 44
lenPos 1826
I =  9324306
number of imo 1546
1826
===============
dfNewJourney 37
lenPos 1859
I =  9396775
number of imo 1547
1859
===============
dfNewJourney 38
lenPos 1866
I =  9367724
number of imo 1548
1866
===============
dfNewJourney 15
lenPos 1832
I =  9247986
number of imo 1549
1832
===============
dfNewJourney 38
lenPos 1740
I =  9550682
number of imo 1550
1740
===============
dfNewJourney 46
lenPos 1687
I =  9314179
number of imo 1551
1687
===============
dfNewJourney 36
lenPos 1764
I =  9389100
number of imo 1552
1764
===============
dfNewJourney 36
lenPos 1781
I =  9232450
number of imo 1553
1781
===============
dfNewJourney 42
lenPos 1791
I =  9397535
number of imo 1554
1791
===============
dfNewJourney 43
lenPos 1787
I =  9284697
number of imo 1555
1787
===============
dfNewJourney 29
lenPos 1835
I =  9402316
number of imo 1556
1835
===============
dfNewJourney 26
lenPos 1710
I =  9325817
number of imo 1557
1710
===============
dfNewJourney 46
lenPos 0
I =  10007612
number of imo 1558
dfNewJourney 34
lenPos 1746
I =  9556181
number of imo 1559
1746
===============
dfNewJourney 16
lenPos 1882
I =  9352315
number of imo 1560
1882
===============
dfNewJourney 54
lenPos 1880
I =  9464326
number of imo 1561
1880
===============
dfNewJourney 26
lenPos 0
I =  9144079
number of imo 1562
dfNewJourney 19
lenPos 1702
I =  9341079
number of imo 1563
1702
===============
dfNewJourney 6
lenPos 1751
I =  9178329
number of imo 1564
1751
===============
dfNewJourney 44
lenPos 1510
I =  9203930
number of imo 1565
1510
===============
dfNewJourney 45
lenPos 1766
I =  9402225
number of imo 1566
1766
===============
dfNewJourney 35
lenPos 1588
I =  9406910
number of imo 1567
1588
===============
dfNewJourney 23
lenPos 1831
I =  9388704
number of imo 1568
1831
===============
dfNewJourney 30
lenPos 1818
I =  9270517
number of imo 1569
1818
===============
dfNewJourney 35
lenPos 1774
I =  9345659
number of imo 1570
1774
===============
dfNewJourney 11
lenPos 1619
I =  9290634
number of imo 1571
1619
===============
dfNewJourney 33
lenPos 1859
I =  9230098
number of imo 1572
1859
===============
dfNewJourney 56
lenPos 1668
I =  9532159
number of imo 1573
1668
===============
dfNewJourney 46
lenPos 1767
I =  9288849
number of imo 1574
1767
===============
dfNewJourney 51
lenPos 1723
I =  9419369
number of imo 1575
1723
===============
dfNewJourney 35
lenPos 1714
I =  9189952
number of imo 1576
1714
===============
dfNewJourney 26
lenPos 1826
I =  9314868
number of imo 1577
1826
===============
dfNewJourney 54
lenPos 1825
I =  9573672
number of imo 1578
1825
===============
dfNewJourney 43
lenPos 0
I =  10007611
number of imo 1579
dfNewJourney 47
lenPos 1706
I =  9301029
number of imo 1580
1706
===============
dfNewJourney 42
lenPos 1649
I =  9489027
number of imo 1581
1649
===============
dfNewJourney 32
lenPos 1597
I =  9430167
number of imo 1582
1597
===============
dfNewJourney 29
lenPos 1851
I =  9317949
number of imo 1583
1851
===============
dfNewJourney 44
lenPos 1786
I =  9565754
number of imo 1584
1786
===============
dfNewJourney 27
lenPos 1663
I =  9127693
number of imo 1585
1663
===============
dfNewJourney 22
lenPos 1473
I =  9289489
number of imo 1586
1473
===============
dfNewJourney 39
lenPos 1784
I =  9311725
number of imo 1587
1784
===============
dfNewJourney 24
lenPos 1684
I =  9443164
number of imo 1588
1684
===============
dfNewJourney 21
lenPos 1708
I =  9482562
number of imo 1589
1708
===============
dfNewJourney 26
lenPos 1735
I =  9281578
number of imo 1590
1735
===============
dfNewJourney 17
lenPos 1720
I =  9436666
number of imo 1591
1720
===============
dfNewJourney 54
lenPos 1734
I =  9335044
number of imo 1592
1734
===============
dfNewJourney 6
lenPos 1399
I =  9117478
number of imo 1593
1399
===============
dfNewJourney 19
lenPos 1808
I =  9286061
number of imo 1594
1808
===============
dfNewJourney 56
lenPos 1661
I =  9524774
number of imo 1595
1661
===============
dfNewJourney 45
lenPos 1770
I =  9390032
number of imo 1596
1770

===============
dfNewJourney 52
lenPos 1744
I =  9594872
number of imo 1597
1744
===============
dfNewJourney 32
lenPos 1715
I =  9443152
number of imo 1598
1715
===============
dfNewJourney 41
lenPos 1850
I =  9367700
number of imo 1599
1850
===============
dfNewJourney 34
lenPos 1742
I =  9102124
number of imo 1600
1742
===============
dfNewJourney 32
lenPos 0
I =  8618889
number of imo 1601
dfNewJourney 38
lenPos 0
I =  10007629
number of imo 1602
dfNewJourney 49
lenPos 1875
I =  9317248
number of imo 1603
1875
===============
dfNewJourney 48
lenPos 1820
I =  9403322
number of imo 1604
1820
===============
dfNewJourney 25
lenPos 0
I =  9161314
number of imo 1605
dfNewJourney 38
lenPos 1795
I =  9332626
number of imo 1606
1795
===============
dfNewJourney 48
lenPos 1849
I =  9414292
number of imo 1607
1849
===============
dfNewJourney 38
lenPos 1882
I =  9439773
number of imo 1608
1882
===============
dfNewJourney 24
lenPos 1768
I =  9251523
number of imo 1609
1768
===============
dfNewJourney 9
lenPos 1732
I =  9417335
number of imo 1610
1732
===============
dfNewJourney 39
lenPos 1730
I =  9443877
number of imo 1611
1730
===============
dfNewJourney 37
lenPos 1667
I =  9408762
number of imo 1612
1667
===============
dfNewJourney 6
lenPos 0
I =  9052642
number of imo 1613
dfNewJourney 41
lenPos 1874
I =  9256016
number of imo 1614
1874
===============
dfNewJourney 61
lenPos 1514
I =  9568512
number of imo 1615
1514
===============
dfNewJourney 34
lenPos 1790
I =  9391438
number of imo 1616
1790
===============
dfNewJourney 45
lenPos 1817
I =  9266267
number of imo 1617
1817
===============
dfNewJourney 37
lenPos 1803
I =  9543548
number of imo 1618
1803
===============
dfNewJourney 39
lenPos 1777
I =  9168635
number of imo 1619
1777
===============
dfNewJourney 44
lenPos 1755
I =  9379624
number of imo 1620
1755
===============
dfNewJourney 39
lenPos 1818
I =  9321873
number of imo 1621
1818
===============
dfNewJourney 35
lenPos 1552
I =  9319698
number of imo 1622
1552
===============
dfNewJourney 44
lenPos 1888
I =  9523835
number of imo 1623
1888
===============
dfNewJourney 41
lenPos 1659
I =  9303649
number of imo 1624
1659
===============
dfNewJourney 36
lenPos 1781
I =  9301914
number of imo 1625
1781
===============
dfNewJourney 8
lenPos 1776
I =  9389966
number of imo 1626
1776
===============
dfNewJourney 41
lenPos 1830
I =  9459084
number of imo 1627
1830
===============
dfNewJourney 3
lenPos 0
I =  8920505
number of imo 1628
dfNewJourney 22
lenPos 1860
I =  9396024
number of imo 1629
1860
===============
dfNewJourney 27
lenPos 1708
I =  7816551
number of imo 1630
1708
===============
dfNewJourney 57
lenPos 1687
I =  9390599
number of imo 1631
1687
===============
dfNewJourney 44
lenPos 1745
I =  9277785
number of imo 1632
1745
===============
dfNewJourney 39
lenPos 1819
I =  9387944
number of imo 1633
1819
===============
dfNewJourney 43
lenPos 1818
I =  9367750
number of imo 1634
1818
===============
dfNewJourney 40
lenPos 0
I =  10015722
number of imo 1635
dfNewJourney 51
lenPos 1833
I =  9422237
number of imo 1636
1833
===============
dfNewJourney 41
lenPos 1524
I =  9312456
number of imo 1637
1524
===============
dfNewJourney 56
lenPos 1792
I =  9536832
number of imo 1638
1792
===============
dfNewJourney 4
lenPos 1804
I =  9315800
number of imo 1639
1804
===============
dfNewJourney 11
lenPos 1865
I =  9288708
number of imo 1640
1865
===============
dfNewJourney 18
lenPos 1793
I =  9399909
number of imo 1641
1793
===============
dfNewJourney 40
lenPos 1685
I =  9411989
number of imo 1642
1685
===============
dfNewJourney 26
lenPos 1573
I =  9234678
number of imo 1643
1573
===============
dfNewJourney 49
lenPos 1647
I =  9568500
number of imo 1644
1647
===============
dfNewJourney 11
lenPos 1829
I =  9348479
number of imo 1645
1829
===============
dfNewJourney 13
lenPos 1277
I =  9143685
number of imo 1646
1277
===============
dfNewJourney 36
lenPos 1673
I =  9278674
number of imo 1647
1673
===============
dfNewJourney 40
lenPos 1695
I =  9196709
number of imo 1648
1695
===============
dfNewJourney 34
lenPos 1786
I =  9366275
number of imo 1649
1786
===============
dfNewJourney 6
lenPos 1832
I =  9568469
number of imo 1650
1832
===============
dfNewJourney 27
lenPos 1780
I =  9305348
number of imo 1651
1780
===============
dfNewJourney 26
lenPos 1703
I =  9294551
number of imo 1652
1703
===============
dfNewJourney 33
lenPos 1794
I =  9306562
number of imo 1653
1794
===============
dfNewJourney 16
lenPos 1622
I =  9379040
number of imo 1654
1622
===============
dfNewJourney 25
lenPos 1665
I =  9437983
number of imo 1655
1665
===============
dfNewJourney 46
lenPos 1785
I =  9401128
number of imo 1656
1785
===============
dfNewJourney 26
lenPos 1858
I =  9404223
number of imo 1657
1858
===============
dfNewJourney 32
lenPos 1820
I =  9299434
number of imo 1658
1820
===============
dfNewJourney 56
lenPos 1796
I =  9389849
number of imo 1659
1796
===============
dfNewJourney 6
lenPos 1816
I =  9220926
number of imo 1660
1816
===============
dfNewJourney 47
lenPos 1828
I =  9566150
number of imo 1661
1828
===============
dfNewJourney 42
lenPos 1816
I =  9346445
number of imo 1662
1816
===============
dfNewJourney 30
lenPos 1748
I =  9240885
number of imo 1663
1748
===============
dfNewJourney 35
lenPos 1750
I =  9258612
number of imo 1664
1750
===============
dfNewJourney 30
lenPos 1729
I =  9192260
number of imo 1665
1729
===============
dfNewJourney 54
lenPos 1828
I =  9512173
number of imo 1666
1828
===============
dfNewJourney 38
lenPos 1636
I =  9155767
number of imo 1667
1636
===============
dfNewJourney 43
lenPos 1714
I =  9488413
number of imo 1668
1714
===============
dfNewJourney 33
lenPos 0
I =  10003545
number of imo 1669
dfNewJourney 38
lenPos 1750
I =  9273387
number of imo 1670
1750
===============
dfNewJourney 21
lenPos 1861
I =  9405564
number of imo 1671
1861
===============
dfNewJourney 34
lenPos 1782
I =  9215309
number of imo 1672
1782
===============
dfNewJourney 44
lenPos 1769
I =  9264570
number of imo 1673
1769
===============
dfNewJourney 18
lenPos 1781
I =  9259898
number of imo 1674
1781
===============
dfNewJourney 43
lenPos 1769
I =  9430296
number of imo 1675
1769
===============
dfNewJourney 34
lenPos 1735
I =  9325324
number of imo 1676
1735
===============
dfNewJourney 9
lenPos 1550
I =  9337303
number of imo 1677
1550
===============
dfNewJourney 35
lenPos 1840
I =  9323340
number of imo 1678
1840
===============
dfNewJourney 59
lenPos 1722
I =  9580390
number of imo 1679
1722
===============
dfNewJourney 34
lenPos 1740
I =  8919037
number of imo 1680
1740
===============
dfNewJourney 46
lenPos 1730
I =  9332028
number of imo 1681
1730
===============
dfNewJourney 50
lenPos 1795
I =  9576753
number of imo 1682
1795
===============
dfNewJourney 52
lenPos 1608
I =  9390587
number of imo 1683
1608
===============
dfNewJourney 37
lenPos 1517
I =  9358917
number of imo 1684
1517
===============
dfNewJourney 40
lenPos 1837
I =  9577094
number of imo 1685
1837
===============
dfNewJourney 42
lenPos 1846
I =  9047752
number of imo 1686
1846
===============
dfNewJourney 2
lenPos 0
I =  8915328
number of imo 1687
dfNewJourney 36
lenPos 1838
I =  9366287
number of imo 1688
1838
===============
dfNewJourney 13
lenPos 1684
I =  9235713
number of imo 1689
1684
===============
dfNewJourney 40
lenPos 1803
I =  9420758
number of imo 1690
1803
===============
dfNewJourney 42
lenPos 1876
I =  9318034
number of imo 1691
1876
===============
dfNewJourney 32
lenPos 1761
I =  8919051
number of imo 1692
1761
===============
dfNewJourney 34
lenPos 1687
I =  9276028
number of imo 1693
1687
===============
dfNewJourney 5
lenPos 1740
I =  9563275
number of imo 1694
1740
===============
dfNewJourney 30
lenPos 1864
I =  9407392
number of imo 1695
1864
===============
dfNewJourney 39
lenPos 1765
I =  9272931
number of imo 1696
1765
===============
dfNewJourney 17
lenPos 0
I =  10007642
number of imo 1697
dfNewJourney 40
lenPos 0
I =  10007495
number of imo 1698
dfNewJourney 27
lenPos 1666
I =  9420631
number of imo 1699
1666
===============
dfNewJourney 52
lenPos 1859
I =  9594901
number of imo 1700
1859
===============
dfNewJourney 47
lenPos 1823
I =  9318333
number of imo 1701
1823

===============
dfNewJourney 24
lenPos 1691
I =  9240718
number of imo 1702
1691
===============
dfNewJourney 30
lenPos 1843
I =  9547520
number of imo 1703
1843
===============
dfNewJourney 42
lenPos 0
I =  10007618
number of imo 1704
dfNewJourney 22
lenPos 1460
I =  9284790
number of imo 1705
1460
===============
dfNewJourney 62
lenPos 1860
I =  9380532
number of imo 1706
1860
===============
dfNewJourney 36
lenPos 1565
I =  9144067
number of imo 1707
1565
===============
dfNewJourney 26
lenPos 1695
I =  9299111
number of imo 1708
1695
===============
dfNewJourney 45
lenPos 1738
I =  9411317
number of imo 1709
1738
===============
dfNewJourney 44
lenPos 1818
I =  9467756
number of imo 1710
1818
===============
dfNewJourney 38
lenPos 1837
I =  9352200
number of imo 1711
1837
===============
dfNewJourney 10
lenPos 1845
I =  9339648
number of imo 1712
1845
===============
dfNewJourney 30
lenPos 1712
I =  9253313
number of imo 1713
1712
===============
dfNewJourney 30
lenPos 1790
I =  9442550
number of imo 1714
1790
===============
dfNewJourney 14
lenPos 0
I =  9173305
number of imo 1715
dfNewJourney 29
lenPos 1719
I =  9354521
number of imo 1716
1719
===============
dfNewJourney 48
lenPos 1835
I =  9391488
number of imo 1717
1835
===============
dfNewJourney 37
lenPos 1665
I =  9384564
number of imo 1718
1665
===============
dfNewJourney 28
lenPos 1814
I =  9230971
number of imo 1719
1814
===============
dfNewJourney 18
lenPos 1387
I =  9145425
number of imo 1720
1387
===============
dfNewJourney 30
lenPos 1775
I =  9308833
number of imo 1721
1775
===============
dfNewJourney 38
lenPos 1792
I =  9198563
number of imo 1722
1792
===============
dfNewJourney 24
lenPos 1804
I =  9308821
number of imo 1723
1804
===============
dfNewJourney 30
lenPos 1537
I =  9282443
number of imo 1724
1537
===============
dfNewJourney 15
lenPos 1808
I =  9240706
number of imo 1725
1808
===============
dfNewJourney 3
lenPos 1378
I =  9154957
number of imo 1726
1378
===============
dfNewJourney 32
lenPos 1852
I =  9282792
number of imo 1727
1852
===============
dfNewJourney 31
lenPos 0
I =  10028615
number of imo 1728
dfNewJourney 38
lenPos 1833
I =  9443853
number of imo 1729
1833
===============
dfNewJourney 31
lenPos 1831
I =  9216913
number of imo 1730
1831
===============
dfNewJourney 63
lenPos 1837
I =  9392327
number of imo 1731
1837
===============
dfNewJourney 47
lenPos 1872
I =  9490325
number of imo 1732
1872
===============
dfNewJourney 38
lenPos 1746
I =  9297369
number of imo 1733
1746
===============
dfNewJourney 19
lenPos 1699
I =  9389332
number of imo 1734
1699
===============
dfNewJourney 79
lenPos 1892
I =  9581693
number of imo 1735
1892
===============
dfNewJourney 13
lenPos 1858
I =  9431264
number of imo 1736
1858
===============
dfNewJourney 42
lenPos 1841
I =  9294288
number of imo 1737
1841
===============
dfNewJourney 26
lenPos 1792
I =  9232888
number of imo 1738
1792
===============
dfNewJourney 42
lenPos 1778
I =  9402328
number of imo 1739
1778
===============
dfNewJourney 47
lenPos 1779
I =  9292345
number of imo 1740
1779
===============
dfNewJourney 10
lenPos 1833
I =  9252371
number of imo 1741
1833
===============
dfNewJourney 25
lenPos 1751
I =  9419448
number of imo 1742
1751
===============
dfNewJourney 8
lenPos 1881
I =  9275737
number of imo 1743
1881
===============
dfNewJourney 40
lenPos 1840
I =  9447732
number of imo 1744
1840
===============
dfNewJourney 7
lenPos 1786
I =  9252400
number of imo 1745
1786
===============
dfNewJourney 20
lenPos 1679
I =  9213313
number of imo 1746
1679
===============
dfNewJourney 44
lenPos 1736
I =  9252955
number of imo 1747
1736
===============
dfNewJourney 38
lenPos 1835
I =  9255684
number of imo 1748
1835
===============
dfNewJourney 43
lenPos 1743
I =  9335032
number of imo 1749
1743
===============
dfNewJourney 34
lenPos 1817
I =  9506069
number of imo 1750
1817
===============
dfNewJourney 35
lenPos 1648
I =  9262481
number of imo 1751
1648
===============
dfNewJourney 36
lenPos 1338
I =  9172727
number of imo 1752
1338
===============
dfNewJourney 38
lenPos 1883
I =  9470284
number of imo 1753
1883
===============
dfNewJourney 34
lenPos 1757
I =  9422524
number of imo 1754
1757
===============
dfNewJourney 47
lenPos 1863
I =  9301952
number of imo 1755
1863
===============
dfNewJourney 22
lenPos 1778
I =  9310812
number of imo 1756
1778
===============
dfNewJourney 36
lenPos 1732
I =  9327413
number of imo 1757
1732
===============
dfNewJourney 34
lenPos 1495
I =  9231224
number of imo 1758
1495
===============
dfNewJourney 26
lenPos 1547
I =  9389071
number of imo 1759
1547
===============
dfNewJourney 39
lenPos 1731
I =  9246451
number of imo 1760
1731
===============
dfNewJourney 27
lenPos 1341
I =  9173642
number of imo 1761
1341
===============
dfNewJourney 41
lenPos 1807
I =  9252187
number of imo 1762
1807
===============
dfNewJourney 34
lenPos 1651
I =  9356438
number of imo 1763
1651
===============
dfNewJourney 38
lenPos 1545
I =  9127667
number of imo 1764
1545
===============
dfNewJourney 3
lenPos 425
I =  9120918
number of imo 1765
425
===============
dfNewJourney 29
lenPos 1635
I =  9392822
number of imo 1766
1635
===============
dfNewJourney 53
lenPos 1822
I =  9332169
number of imo 1767
1822
===============
dfNewJourney 38
lenPos 1831
I =  9236640
number of imo 1768
1831
===============
dfNewJourney 34
lenPos 1741
I =  9150315
number of imo 1769
1741
===============
dfNewJourney 5
lenPos 1786
I =  9228801
number of imo 1770
1786
===============
dfNewJourney 10
lenPos 1822
I =  9353149
number of imo 1771
1822
===============
dfNewJourney 42
lenPos 1731
I =  9409479
number of imo 1772
1731
===============
dfNewJourney 22
lenPos 1836
I =  9276004
number of imo 1773
1836
===============
dfNewJourney 18
lenPos 1240
I =  9180982
number of imo 1774
1240
===============
dfNewJourney 47
lenPos 1857
I =  9506693
number of imo 1775
1857
===============
dfNewJourney 43
lenPos 1750
I =  9390173
number of imo 1776
1750
===============
dfNewJourney 31
lenPos 1775
I =  9425992
number of imo 1777
1775
===============
dfNewJourney 56
lenPos 1698
I =  9306811
number of imo 1778
1698
===============
dfNewJourney 51
lenPos 1851
I =  9516258
number of imo 1779
1851
===============
dfNewJourney 34
lenPos 1820
I =  9465980
number of imo 1780
1820
===============
dfNewJourney 37
lenPos 1846
I =  9333187
number of imo 1781
1846
===============
dfNewJourney 67
lenPos 1864
I =  9135547
number of imo 1782
1864
===============
dfNewJourney 34
lenPos 1806
I =  9321938
number of imo 1783
1806
===============
dfNewJourney 19
lenPos 1782
I =  9183635
number of imo 1784
1782
===============
dfNewJourney 29
lenPos 1824
I =  9254927
number of imo 1785
1824
===============
dfNewJourney 53
lenPos 1862
I =  9102083
number of imo 1786
1862
===============
dfNewJourney 55
lenPos 1758
I =  9298674
number of imo 1787
1758
===============
dfNewJourney 40
lenPos 1872
I =  9403334
number of imo 1788
1872
===============
dfNewJourney 27
lenPos 1692
I =  9417191
number of imo 1789
1692
===============
dfNewJourney 38
lenPos 1701
I =  9458808
number of imo 1790
1701
===============
dfNewJourney 45
lenPos 1855
I =  9490296
number of imo 1791
1855
===============
dfNewJourney 57
lenPos 1595
I =  9404936
number of imo 1792
1595
===============
dfNewJourney 46
lenPos 1837
I =  9325831
number of imo 1793
1837
===============
dfNewJourney 49
lenPos 1770
I =  9570101
number of imo 1794
1770
===============
dfNewJourney 35
lenPos 1719
I =  9396763
number of imo 1795
1719
===============
dfNewJourney 11
lenPos 1765
I =  9487483
number of imo 1796
1765
===============
dfNewJourney 31
lenPos 1707
I =  9380104
number of imo 1797
1707
===============
dfNewJourney 15
lenPos 1739
I =  9203928
number of imo 1798
1739
===============
dfNewJourney 48
lenPos 1802
I =  9392779
number of imo 1799
1802
===============
dfNewJourney 29
lenPos 1657
I =  9379143
number of imo 1800
1657
===============
dfNewJourney 34
lenPos 1848
I =  9247778
number of imo 1801
1848
===============
dfNewJourney 29
lenPos 1827
I =  9420643
number of imo 1802
1827
===============
dfNewJourney 30
lenPos 1653
I =  9120932
number of imo 1803
1653
===============
dfNewJourney 44
lenPos 1558
I =  9172272
number of imo 1804
1558

===============
dfNewJourney 11
lenPos 0
I =  8812772
number of imo 1805
dfNewJourney 24
lenPos 1806
I =  9482627
number of imo 1806
1806
===============
dfNewJourney 39
lenPos 1769
I =  9259317
number of imo 1807
1769
===============
dfNewJourney 40
lenPos 1848
I =  9439785
number of imo 1808
1848
===============
dfNewJourney 32
lenPos 1723
I =  9441192
number of imo 1809
1723
===============
dfNewJourney 47
lenPos 1815
I =  9360324
number of imo 1810
1815
===============
dfNewJourney 50
lenPos 0
I =  10007575
number of imo 1811
dfNewJourney 44
lenPos 1711
I =  9284726
number of imo 1812
1711
===============
dfNewJourney 37
lenPos 1471
I =  9399349
number of imo 1813
1471
===============
dfNewJourney 7
lenPos 1644
I =  9292826
number of imo 1814
1644
===============
dfNewJourney 16
lenPos 1743
I =  9200964
number of imo 1815
1743
===============
dfNewJourney 21
lenPos 1592
I =  9251456
number of imo 1816
1592
===============
dfNewJourney 17
lenPos 1136
I =  9180920
number of imo 1817
1136
===============
dfNewJourney 22
lenPos 1710
I =  9282558
number of imo 1818
1710
===============
dfNewJourney 4
lenPos 1669
I =  9116632
number of imo 1819
1669
===============
dfNewJourney 28
lenPos 1788
I =  9577082
number of imo 1820
1788
===============
dfNewJourney 35
lenPos 1830
I =  9367683
number of imo 1821
1830
===============
dfNewJourney 52
lenPos 1752
I =  9459292
number of imo 1822
1752
===============
dfNewJourney 12
lenPos 1284
I =  9180097
number of imo 1823
1284
===============
dfNewJourney 16
lenPos 1862
I =  9247455
number of imo 1824
1862
===============
dfNewJourney 11
lenPos 1874
I =  9261396
number of imo 1825
1874
===============
dfNewJourney 18
lenPos 1634
I =  9334698
number of imo 1826
1634
===============
dfNewJourney 59
lenPos 1861
I =  9540819
number of imo 1827
1861
===============
dfNewJourney 32
lenPos 1850
I =  9515917
number of imo 1828
1850
===============
dfNewJourney 39
lenPos 1828
I =  9581423
number of imo 1829
1828
===============
dfNewJourney 15
lenPos 1816
I =  9338905
number of imo 1830
1816
===============
dfNewJourney 45
lenPos 1780
I =  9234484
number of imo 1831
1780
===============
dfNewJourney 7
lenPos 0
I =  9166390
number of imo 1832
dfNewJourney 25
lenPos 1731
I =  9431276
number of imo 1833
1731
===============
dfNewJourney 49
lenPos 1843
I =  9379911
number of imo 1834
1843
===============
dfNewJourney 10
lenPos 1685
I =  9380087
number of imo 1835
1685
===============
dfNewJourney 73
lenPos 1768
I =  9405851
number of imo 1836
1768
===============
dfNewJourney 25
lenPos 0
I =  9121003
number of imo 1837
dfNewJourney 37
lenPos 1822
I =  9343211
number of imo 1838
1822
===============
dfNewJourney 50
lenPos 1791
I =  9323390
number of imo 1839
1791
===============
dfNewJourney 23
lenPos 1797
I =  9453030
number of imo 1840
1797
===============
dfNewJourney 39
lenPos 1891
I =  9390020
number of imo 1841
1891
===============
dfNewJourney 32
lenPos 1767
I =  9375317
number of imo 1842
1767
===============
dfNewJourney 53
lenPos 1854
I =  9338814
number of imo 1843
1854
===============
dfNewJourney 40
lenPos 1759
I =  9439802
number of imo 1844
1759
===============
dfNewJourney 38
lenPos 1800
I =  9436343
number of imo 1845
1800
===============
dfNewJourney 41
lenPos 0
I =  10007614
number of imo 1846
dfNewJourney 46
lenPos 0
I =  10007632
number of imo 1847
dfNewJourney 42
lenPos 1824
I =  9290658
number of imo 1848
1824
===============
dfNewJourney 34
lenPos 1814
I =  9414058
number of imo 1849
1814
===============
dfNewJourney 17
lenPos 1822
I =  9391414
number of imo 1850
1822
===============
dfNewJourney 38
lenPos 1868
I =  9596272
number of imo 1851
1868
===============
dfNewJourney 37
lenPos 1417
I =  9426441
number of imo 1852
1417
===============
dfNewJourney 42
lenPos 1799
I =  9405899
number of imo 1853
1799
===============
dfNewJourney 35
lenPos 1644
I =  9306469
number of imo 1854
1644
===============
dfNewJourney 23
lenPos 1877
I =  9246475
number of imo 1855
1877
===============
dfNewJourney 33
lenPos 1806
I =  9412464
number of imo 1856
1806
===============
dfNewJourney 33
lenPos 1842
I =  9391490
number of imo 1857
1842
===============
dfNewJourney 8
lenPos 1670
I =  9470935
number of imo 1858
1670
===============
dfNewJourney 42
lenPos 1740
I =  9375616
number of imo 1859
1740
===============
dfNewJourney 37
lenPos 1801
I =  9246803
number of imo 1860
1801
===============
dfNewJourney 41
lenPos 1440
I =  9487172
number of imo 1861
1440
===============
dfNewJourney 48
lenPos 1794
I =  9310850
number of imo 1862
1794
===============
dfNewJourney 11
lenPos 0
I =  8618231
number of imo 1863
dfNewJourney 50
lenPos 1821
I =  9282510
number of imo 1864
1821
===============
dfNewJourney 32
lenPos 1788
I =  9298313
number of imo 1865
1788
===============
dfNewJourney 37
lenPos 1818
I =  9185499
number of imo 1866
1818
===============
dfNewJourney 54
lenPos 1608
I =  9102095
number of imo 1867
1608
===============
dfNewJourney 24
lenPos 0
I =  9179622
number of imo 1868
dfNewJourney 24
lenPos 1843
I =  9543536
number of imo 1869
1843
===============
dfNewJourney 33
lenPos 1748
I =  9126285
number of imo 1870
1748
===============
dfNewJourney 57
lenPos 1734
I =  9407275
number of imo 1871
1734
===============
dfNewJourney 42
lenPos 1811
I =  9490301
number of imo 1872
1811
===============
dfNewJourney 45
lenPos 1784
I =  9590723
number of imo 1873
1784
===============
dfNewJourney 17
lenPos 1741
I =  9339301
number of imo 1874
1741
===============
dfNewJourney 35
lenPos 1813
I =  9317858
number of imo 1875
1813
===============
dfNewJourney 68
lenPos 1785
I =  9347310
number of imo 1876
1785
===============
dfNewJourney 31
lenPos 1854
I =  9291640
number of imo 1877
1854
===============
dfNewJourney 16
lenPos 1866
I =  9351921
number of imo 1878
1866
===============
dfNewJourney 34
lenPos 1758
I =  9248837
number of imo 1879
1758
===============
dfNewJourney 19
lenPos 1868
I =  9288746
number of imo 1880
1868
===============
dfNewJourney 28
lenPos 1765
I =  9587829
number of imo 1881
1765
===============
dfNewJourney 31
lenPos 1470
I =  9323807
number of imo 1882
1470
===============
dfNewJourney 35
lenPos 1840
I =  9308998
number of imo 1883
1840
===============
dfNewJourney 46
lenPos 1790
I =  9408554
number of imo 1884
1790
===============
dfNewJourney 21
lenPos 1424
I =  9302114
number of imo 1885
1424
===============
dfNewJourney 30
lenPos 1622
I =  9456070
number of imo 1886
1622
===============
dfNewJourney 27
lenPos 1818
I =  9181869
number of imo 1887
1818
===============
dfNewJourney 4
lenPos 1643
I =  9165293
number of imo 1888
1643
===============
dfNewJourney 3
lenPos 0
I =  9060601
number of imo 1889
dfNewJourney 35
lenPos 1437
I =  9299343
number of imo 1890
1437
===============
dfNewJourney 46
lenPos 1794
I =  9354911
number of imo 1891
1794
===============
dfNewJourney 38
lenPos 1793
I =  9299563
number of imo 1892
1793
===============
dfNewJourney 45
lenPos 0
I =  10007634
number of imo 1893
dfNewJourney 47
lenPos 1844
I =  9422407
number of imo 1894
1844
===============
dfNewJourney 33
lenPos 1362
I =  9250490
number of imo 1895
1362
===============
dfNewJourney 30
lenPos 0
I =  10028478
number of imo 1896
dfNewJourney 42
lenPos 1827
I =  9423750
number of imo 1897
1827
===============
dfNewJourney 29
lenPos 1631
I =  9237228
number of imo 1898
1631
===============
dfNewJourney 38
lenPos 1862
I =  9418133
number of imo 1899
1862
===============
dfNewJourney 25
lenPos 1504
I =  9430284
number of imo 1900
1504
===============
dfNewJourney 6
lenPos 1862
I =  9256078
number of imo 1901
1862
===============
dfNewJourney 5
lenPos 0
I =  9004607
number of imo 1902
dfNewJourney 36
lenPos 1832
I =  9573684
number of imo 1903
1832
===============
dfNewJourney 23
lenPos 0
I =  9184603
number of imo 1904
dfNewJourney 17
lenPos 1859
I =  9302669
number of imo 1905
1859
===============
dfNewJourney 14
lenPos 1463
I =  9209972
number of imo 1906
1463
===============
dfNewJourney 52
lenPos 1812
I =  9426312
number of imo 1907
1812
===============
dfNewJourney 3
lenPos 1482
I =  9209300
number of imo 1908
1482
===============
dfNewJourney 17
lenPos 1645
I =  9432672
number of imo 1909
1645
===============
dfNewJourney 39
lenPos 1722
I =  9461659
number of imo 1910
1722

===============
dfNewJourney 5
lenPos 1800
I =  9251652
number of imo 1911
1800
===============
dfNewJourney 33
lenPos 1807
I =  9380386
number of imo 1912
1807
===============
dfNewJourney 39
lenPos 1816
I =  9561382
number of imo 1913
1816
===============
dfNewJourney 35
lenPos 1716
I =  9401647
number of imo 1914
1716
===============
dfNewJourney 32
lenPos 1782
I =  9544592
number of imo 1915
1782
===============
dfNewJourney 27
lenPos 1844
I =  9251822
number of imo 1916
1844
===============
dfNewJourney 40
lenPos 1759
I =  9239630
number of imo 1917
1759
===============
dfNewJourney 13
lenPos 1807
I =  9299692
number of imo 1918
1807
===============
dfNewJourney 31
lenPos 1686
I =  9231468
number of imo 1919
1686
===============
dfNewJourney 46
lenPos 1838
I =  9478705
number of imo 1920
1838
===============
dfNewJourney 4
lenPos 1833
I =  9297436
number of imo 1921
1833
===============
dfNewJourney 48
lenPos 1817
I =  9309576
number of imo 1922
1817
===============
dfNewJourney 32
lenPos 0
I =  8819093
number of imo 1923
dfNewJourney 37
lenPos 1658
I =  9430181
number of imo 1924
1658
===============
dfNewJourney 29
lenPos 1769
I =  9257498
number of imo 1925
1769
===============
dfNewJourney 40
lenPos 1759
I =  9405916
number of imo 1926
1759
===============
dfNewJourney 36
lenPos 1706
I =  9459034
number of imo 1927
1706
===============
dfNewJourney 15
lenPos 1491
I =  9242479
number of imo 1928
1491
===============
dfNewJourney 42
lenPos 0
I =  10007493
number of imo 1929
dfNewJourney 33
lenPos 1772
I =  9215050
number of imo 1930
1772
===============
dfNewJourney 49
lenPos 1796
I =  9298492
number of imo 1931
1796
===============
dfNewJourney 27
lenPos 1813
I =  9262900
number of imo 1932
1813
===============
dfNewJourney 62
lenPos 1786
I =  9257711
number of imo 1933
1786
===============
dfNewJourney 48
lenPos 1815
I =  9387970
number of imo 1934
1815
===============
dfNewJourney 8
lenPos 1658
I =  9085390
number of imo 1935
1658
===============
dfNewJourney 10
lenPos 1769
I =  9426207
number of imo 1936
1769
===============
dfNewJourney 9
lenPos 1837
I =  9210892
number of imo 1937
1837
===============
dfNewJourney 42
lenPos 1794
I =  9275763
number of imo 1938
1794
===============
dfNewJourney 18
lenPos 1788
I =  9260031
number of imo 1939
1788
===============
dfNewJourney 40
lenPos 1814
I =  9467744
number of imo 1940
1814
===============
dfNewJourney 44
lenPos 1862
I =  9366299
number of imo 1941
1862
===============
dfNewJourney 48
lenPos 1856
I =  9407366
number of imo 1942
1856
===============
dfNewJourney 15
lenPos 1680
I =  9302657
number of imo 1943
1680
===============
dfNewJourney 39
lenPos 1730
I =  9256913
number of imo 1944
1730
===============
dfNewJourney 26
lenPos 1806
I =  9581679
number of imo 1945
1806
===============
dfNewJourney 48
lenPos 1745
I =  9425514
number of imo 1946
1745
===============
dfNewJourney 33
lenPos 1594
I =  9430272
number of imo 1947
1594
===============
dfNewJourney 33
lenPos 1701
I =  9346859
number of imo 1948
1701
===============
dfNewJourney 35
lenPos 1730
I =  9311531
number of imo 1949
1730
===============
dfNewJourney 34
lenPos 1702
I =  9465966
number of imo 1950
1702
===============
dfNewJourney 40
lenPos 1707
I =  9247065
number of imo 1951
1707
===============
dfNewJourney 42
lenPos 1750
I =  9292046
number of imo 1952
1750
===============
dfNewJourney 44
lenPos 1785
I =  9577123
number of imo 1953
1785
===============
dfNewJourney 28
lenPos 1738
I =  9422536
number of imo 1954
1738
===============
dfNewJourney 51
lenPos 1689
I =  9604380
number of imo 1955
1689
===============
dfNewJourney 27
lenPos 1807
I =  9307334
number of imo 1956
1807
===============
dfNewJourney 2
lenPos 1830
I =  9263174
number of imo 1957
1830
===============
dfNewJourney 30
lenPos 1521
I =  9323314
number of imo 1958
1521
===============
dfNewJourney 17
lenPos 1525
I =  9212395
number of imo 1959
1525
===============
dfNewJourney 42
lenPos 1783
I =  9273260
number of imo 1960
1783
===============
dfNewJourney 42
lenPos 1824
I =  9272395
number of imo 1961
1824
===============
dfNewJourney 25
lenPos 1682
I =  9406386
number of imo 1962
1682
===============
dfNewJourney 42
lenPos 1715
I =  9389526
number of imo 1963
1715
===============
dfNewJourney 20
lenPos 1794
I =  9185516
number of imo 1964
1794
===============
dfNewJourney 26
lenPos 1483
I =  9302865
number of imo 1965
1483
===============
dfNewJourney 20
lenPos 0
I =  8112914
number of imo 1966
dfNewJourney 8
lenPos 1897
I =  9230426
number of imo 1967
1897
===============
dfNewJourney 19
lenPos 1689
I =  9253325
number of imo 1968
1689
===============
dfNewJourney 38
lenPos 1727
I =  9314193
number of imo 1969
1727
===============
dfNewJourney 11
lenPos 1841
I =  9288710
number of imo 1970
1841
===============
dfNewJourney 12
lenPos 1242
I =  9359624
number of imo 1971
1242
===============
dfNewJourney 50
lenPos 1739
I =  9334557
number of imo 1972
1739
===============
dfNewJourney 43
lenPos 1840
I =  9451460
number of imo 1973
1840
===============
dfNewJourney 47
lenPos 1864
I =  9547506
number of imo 1974
1864
===============
dfNewJourney 61
lenPos 1875
I =  9592226
number of imo 1975
1875
===============
dfNewJourney 19
lenPos 1247
I =  9178056
number of imo 1976
1247
===============
dfNewJourney 5
lenPos 1855
I =  9327372
number of imo 1977
1855
===============
dfNewJourney 29
lenPos 1862
I =  9379129
number of imo 1978
1862
===============
dfNewJourney 33
lenPos 1728
I =  9124469
number of imo 1979
1728
===============
dfNewJourney 37
lenPos 1684
I =  9307140
number of imo 1980
1684
===============
dfNewJourney 35
lenPos 1776
I =  9433808
number of imo 1981
1776
===============
dfNewJourney 21
lenPos 1691
I =  9364928
number of imo 1982
1691
===============
dfNewJourney 42
lenPos 1875
I =  9539925
number of imo 1983
1875
===============
dfNewJourney 13
lenPos 1484
I =  9167186
number of imo 1984
1484
===============
dfNewJourney 30
lenPos 1803
I =  9394935
number of imo 1985
1803
===============
dfNewJourney 19
lenPos 1669
I =  9402237
number of imo 1986
1669
===============
dfNewJourney 18
lenPos 1730
I =  9365635
number of imo 1987
1730
===============
dfNewJourney 38
lenPos 1833
I =  9418145
number of imo 1988
1833
===============
dfNewJourney 31
lenPos 1843
I =  9232591
number of imo 1989
1843
===============
dfNewJourney 56
lenPos 1861
I =  9380520
number of imo 1990
1861
===============
dfNewJourney 43
lenPos 1744
I =  9382956
number of imo 1991
1744
===============
dfNewJourney 13
lenPos 1879
I =  9379325
number of imo 1992
1879
===============
dfNewJourney 34
lenPos 1721
I =  9379985
number of imo 1993
1721
===============
dfNewJourney 24
lenPos 1756
I =  9457608
number of imo 1994
1756
===============
dfNewJourney 41
lenPos 1527
I =  9396672
number of imo 1995
1527
===============
dfNewJourney 11
lenPos 1870
I =  9327437
number of imo 1996
1870
===============
dfNewJourney 38
lenPos 1625
I =  9288681
number of imo 1997
1625
===============
dfNewJourney 6
lenPos 0
I =  8800511
number of imo 1998
dfNewJourney 31
lenPos 1897
I =  9388003
number of imo 1999
1897
===============
dfNewJourney 17
lenPos 1799
I =  9399612
number of imo 2000
1799
===============
dfNewJourney 45
lenPos 1694
I =  9367554
number of imo 2001
1694
===============
dfNewJourney 53
lenPos 1879
I =  9311012
number of imo 2002
1879
===============
dfNewJourney 40
lenPos 1825
I =  9321172
number of imo 2003
1825
===============
dfNewJourney 37
lenPos 1710
I =  9380362
number of imo 2004
1710
===============
dfNewJourney 32
lenPos 1595
I =  9318553
number of imo 2005
1595
===============
dfNewJourney 43
lenPos 1842
I =  9382700
number of imo 2006
1842
===============
dfNewJourney 1
lenPos 0
I =  8706193
number of imo 2007
dfNewJourney 28
lenPos 1795
I =  9276690
number of imo 2008
1795
===============
dfNewJourney 24
lenPos 1797
I =  9343340
number of imo 2009
1797
===============
dfNewJourney 33
lenPos 1840
I =  9555307
number of imo 2010
1840
===============
dfNewJourney 51
lenPos 1682
I =  9256925
number of imo 2011
1682
===============
dfNewJourney 12
lenPos 1691
I =  9357559
number of imo 2012
1691
===============
dfNewJourney 7
lenPos 0
I =  8906937
number of imo 2013
dfNewJourney 28
lenPos 1810
I =  9280366
number of imo 2014
1810

===============
dfNewJourney 21
lenPos 1850
I =  9327425
number of imo 2015
1850
===============
dfNewJourney 39
lenPos 1900
I =  9596260
number of imo 2016
1900
===============
dfNewJourney 2
lenPos 997
I =  9422988
number of imo 2017
997
===============
dfNewJourney 21
lenPos 1715
I =  9441207
number of imo 2018
1715
===============
dfNewJourney 26
lenPos 1524
I =  9374416
number of imo 2019
1524
===============
dfNewJourney 38
lenPos 1600
I =  9183312
number of imo 2020
1600
===============
dfNewJourney 36
lenPos 1636
I =  9221023
number of imo 2021
1636
===============
dfNewJourney 11
lenPos 1833
I =  9347308
number of imo 2022
1833
===============
dfNewJourney 8
lenPos 1191
I =  9101182
number of imo 2023
1191
===============
dfNewJourney 33
lenPos 1712
I =  9272199
number of imo 2024
1712
===============
dfNewJourney 39
lenPos 1877
I =  9114232
number of imo 2025
1877
===============
dfNewJourney 19
lenPos 0
I =  8320119
number of imo 2026
dfNewJourney 28
lenPos 1666
I =  9439539
number of imo 2027
1666
===============
dfNewJourney 40
lenPos 0
I =  10015841
number of imo 2028
dfNewJourney 7
lenPos 1797
I =  9199127
number of imo 2029
1797
===============
dfNewJourney 27
lenPos 1729
I =  9256901
number of imo 2030
1729
===============
dfNewJourney 44
lenPos 1642
I =  9282912
number of imo 2031
1642
===============
dfNewJourney 8
lenPos 0
I =  9032680
number of imo 2032
dfNewJourney 49
lenPos 0
I =  10007631
number of imo 2033
dfNewJourney 42
lenPos 0
I =  10007597
number of imo 2034
dfNewJourney 49
lenPos 1807
I =  9323364
number of imo 2035
1807
===============
dfNewJourney 48
lenPos 1859
I =  9482861
number of imo 2036
1859
===============
dfNewJourney 29
lenPos 1752
I =  9383974
number of imo 2037
1752
===============
dfNewJourney 33
lenPos 1680
I =  9283722
number of imo 2038
1680
===============
dfNewJourney 31
lenPos 1699
I =  9237412
number of imo 2039
1699
===============
dfNewJourney 26
lenPos 1746
I =  9323338
number of imo 2040
1746
===============
dfNewJourney 2
lenPos 0
I =  10014447
number of imo 2041
dfNewJourney 40
lenPos 1708
I =  9289752
number of imo 2042
1708
===============
dfNewJourney 32
lenPos 1507
I =  9143697
number of imo 2043
1507
===============
dfNewJourney 8
lenPos 1746
I =  9596363
number of imo 2044
1746
===============
dfNewJourney 47
lenPos 1723
I =  9172234
number of imo 2045
1723
===============
dfNewJourney 18
lenPos 1675
I =  9233313
number of imo 2046
1675
===============
dfNewJourney 39
lenPos 0
I =  10015168
number of imo 2047
dfNewJourney 49
lenPos 1799
I =  9469687
number of imo 2048
1799
===============
dfNewJourney 24
lenPos 1795
I =  9419137
number of imo 2049
1795
===============
dfNewJourney 43
lenPos 1650
I =  9281009
number of imo 2050
1650
===============
dfNewJourney 16
lenPos 1860
I =  9387255
number of imo 2051
1860
===============
dfNewJourney 38
lenPos 1819
I =  9343209
number of imo 2052
1819
===============
dfNewJourney 24
lenPos 1500
I =  9374428
number of imo 2053
1500
===============
dfNewJourney 12
lenPos 0
I =  9074987
number of imo 2054
dfNewJourney 19
lenPos 1853
I =  9440485
number of imo 2055
1853
===============
dfNewJourney 41
lenPos 1788
I =  9169512
number of imo 2056
1788
===============
dfNewJourney 37
lenPos 1797
I =  9221657
number of imo 2057
1797
===============
dfNewJourney 29
lenPos 1601
I =  9484089
number of imo 2058
1601
===============
dfNewJourney 45
lenPos 1862
I =  9564671
number of imo 2059
1862
===============
dfNewJourney 32
lenPos 1769
I =  9494668
number of imo 2060
1769
===============
dfNewJourney 32
lenPos 1849
I =  9182045
number of imo 2061
1849
===============
dfNewJourney 9
lenPos 0
I =  10015712
number of imo 2062
dfNewJourney 63
lenPos 1622
I =  9433597
number of imo 2063
1622
===============
dfNewJourney 38
lenPos 1809
I =  9442017
number of imo 2064
1809
===============
dfNewJourney 20
lenPos 1830
I =  9293947
number of imo 2065
1830
===============
dfNewJourney 52
lenPos 1790
I =  9298301
number of imo 2066
1790
===============
dfNewJourney 21
lenPos 1833
I =  9391402
number of imo 2067
1833
===============
dfNewJourney 40
lenPos 1554
I =  9228318
number of imo 2068
1554
===============
dfNewJourney 12
lenPos 1874
I =  9353113
number of imo 2069
1874
===============
dfNewJourney 41
lenPos 1791
I =  9313462
number of imo 2070
1791
===============
dfNewJourney 30
lenPos 1805
I =  9417220
number of imo 2071
1805
===============
dfNewJourney 41
lenPos 0
I =  10015399
number of imo 2072
dfNewJourney 43
lenPos 1846
I =  9400394
number of imo 2073
1846
===============
dfNewJourney 8
lenPos 1832
I =  9255488
number of imo 2074
1832
===============
dfNewJourney 43
lenPos 0
I =  10007636
number of imo 2075
dfNewJourney 23
lenPos 1717
I =  9290919
number of imo 2076
1717
===============
dfNewJourney 4
lenPos 1786
I =  9270555
number of imo 2077
1786
===============
dfNewJourney 20
lenPos 1594
I =  9335903
number of imo 2078
1594
===============
dfNewJourney 39
lenPos 0
I =  10007621
number of imo 2079
dfNewJourney 32
lenPos 1848
I =  9296195
number of imo 2080
1848
===============
dfNewJourney 32
lenPos 1771
I =  9346744
number of imo 2081
1771
===============
dfNewJourney 2
lenPos 0
I =  9009009
number of imo 2082
dfNewJourney 35
lenPos 1744
I =  9397808
number of imo 2083
1744
===============
dfNewJourney 33
lenPos 1723
I =  9414084
number of imo 2084
1723
===============
dfNewJourney 16
lenPos 1073
I =  9118056
number of imo 2085
1073
===============
dfNewJourney 36
lenPos 1862
I =  9382982
number of imo 2086
1862
===============
dfNewJourney 39
lenPos 1658
I =  9260823
number of imo 2087
1658
===============
dfNewJourney 38
lenPos 1741
I =  9539913
number of imo 2088
1741
===============
dfNewJourney 44
lenPos 1824
I =  9346433
number of imo 2089
1824
===============
dfNewJourney 21
lenPos 0
I =  9176034
number of imo 2090
dfNewJourney 40
lenPos 1832
I =  9428358
number of imo 2091
1832
===============
dfNewJourney 28
lenPos 1749
I =  9365374
number of imo 2092
1749
===============
dfNewJourney 13
lenPos 1830
I =  9305611
number of imo 2093
1830
===============
dfNewJourney 33
lenPos 1852
I =  9568043
number of imo 2094
1852
===============
dfNewJourney 33
lenPos 1683
I =  9421336
number of imo 2095
1683
===============
dfNewJourney 33
lenPos 1768
I =  9543550
number of imo 2096
1768
===============
dfNewJourney 37
lenPos 1803
I =  9327449
number of imo 2097
1803
===============
dfNewJourney 29
lenPos 1215
I =  9468815
number of imo 2098
1215
===============
dfNewJourney 20
lenPos 1776
I =  9418121
number of imo 2099
1776
===============
dfNewJourney 17
lenPos 1706
I =  9250892
number of imo 2100
1706
===============
dfNewJourney 23
lenPos 1717
I =  9410648
number of imo 2101
1717
===============
dfNewJourney 16
lenPos 1557
I =  9483736
number of imo 2102
1557
===============
dfNewJourney 31
lenPos 1735
I =  9402483
number of imo 2103
1735
===============
dfNewJourney 46
lenPos 1827
I =  9473717
number of imo 2104
1827
===============
dfNewJourney 29
lenPos 1827
I =  9472763
number of imo 2105
1827
===============
dfNewJourney 33
lenPos 1610
I =  9428865
number of imo 2106
1610
===============
dfNewJourney 10
lenPos 1126
I =  9255830
number of imo 2107
1126
===============
dfNewJourney 15
lenPos 1794
I =  9299707
number of imo 2108
1794
===============
dfNewJourney 13
lenPos 1750
I =  9252967
number of imo 2109
1750
===============
dfNewJourney 22
lenPos 1866
I =  9353589
number of imo 2110
1866
===============
dfNewJourney 20
lenPos 1860
I =  9290921
number of imo 2111
1860
===============
dfNewJourney 50
lenPos 1895
I =  9382073
number of imo 2112
1895
===============
dfNewJourney 12
lenPos 1419
I =  9398266
number of imo 2113
1419
===============
dfNewJourney 57
lenPos 1846
I =  9426295
number of imo 2114
1846
===============
dfNewJourney 52
lenPos 1714
I =  9378632
number of imo 2115
1714
===============
dfNewJourney 7
lenPos 1890
I =  9380489
number of imo 2116
1890
===============
dfNewJourney 24
lenPos 1553
I =  9274094
number of imo 2117
1553
===============
dfNewJourney 8
lenPos 1610
I =  9250153
number of imo 2118
1610
===============
dfNewJourney 47
lenPos 1847
I =  9410911
number of imo 2119
1847
===============
dfNewJourney 23
lenPos 1851
I =  9314844
number of imo 2120
1851

===============
dfNewJourney 37
lenPos 0
I =  10015395
number of imo 2121
dfNewJourney 2
lenPos 1615
I =  8421171
number of imo 2122
1615
===============
dfNewJourney 18
lenPos 1887
I =  9358541
number of imo 2123
1887
===============
dfNewJourney 15
lenPos 1751
I =  9169536
number of imo 2124
1751
===============
dfNewJourney 37
lenPos 1804
I =  9577044
number of imo 2125
1804
===============
dfNewJourney 44
lenPos 1680
I =  9427471
number of imo 2126
1680
===============
dfNewJourney 19
lenPos 1456
I =  9167174
number of imo 2127
1456
===============
dfNewJourney 32
lenPos 1590
I =  9402263
number of imo 2128
1590
===============
dfNewJourney 43
lenPos 1793
I =  9384033
number of imo 2129
1793
===============
dfNewJourney 41
lenPos 1713
I =  9399260
number of imo 2130
1713
===============
dfNewJourney 33
lenPos 1837
I =  9402809
number of imo 2131
1837
===============
dfNewJourney 46
lenPos 1802
I =  9290957
number of imo 2132
1802
===============
dfNewJourney 19
lenPos 1139
I =  9182667
number of imo 2133
1139
===============
dfNewJourney 51
lenPos 0
I =  10006833
number of imo 2134
dfNewJourney 39
lenPos 1754
I =  9409493
number of imo 2135
1754
===============
dfNewJourney 41
lenPos 1743
I =  9207716
number of imo 2136
1743
===============
dfNewJourney 40
lenPos 0
I =  10015591
number of imo 2137
dfNewJourney 3
lenPos 0
I =  9108697
number of imo 2138
dfNewJourney 37
lenPos 1815
I =  9433834
number of imo 2139
1815
===============
dfNewJourney 45
lenPos 1805
I =  9332171
number of imo 2140
1805
===============
dfNewJourney 29
lenPos 1769
I =  9286023
number of imo 2141
1769
===============
dfNewJourney 10
lenPos 1856
I =  9314818
number of imo 2142
1856
===============
dfNewJourney 50
lenPos 1818
I =  9281920
number of imo 2143
1818
===============
dfNewJourney 9
lenPos 1474
I =  9081837
number of imo 2144
1474
===============
dfNewJourney 59
lenPos 1794
I =  9385831
number of imo 2145
1794
===============
dfNewJourney 40
lenPos 1857
I =  9315783
number of imo 2146
1857
===============
dfNewJourney 27
lenPos 1816
I =  9396012
number of imo 2147
1816
===============
dfNewJourney 17
lenPos 1815
I =  6806444
number of imo 2148
1815
===============
dfNewJourney 41
lenPos 1825
I =  9366263
number of imo 2149
1825
===============
dfNewJourney 33
lenPos 1816
I =  9273351
number of imo 2150
1816
===============
dfNewJourney 16
lenPos 1817
I =  9253234
number of imo 2151
1817
===============
dfNewJourney 16
lenPos 1840
I =  9391397
number of imo 2152
1840
===============
dfNewJourney 5
lenPos 1397
I =  9313450
number of imo 2153
1397
===============
dfNewJourney 16
lenPos 1840
I =  9303730
number of imo 2154
1840
===============
dfNewJourney 38
lenPos 1730
I =  9283306
number of imo 2155
1730
===============
dfNewJourney 6
lenPos 0
I =  9214654
number of imo 2156
dfNewJourney 18
lenPos 1815
I =  9391361
number of imo 2157
1815
===============
dfNewJourney 34
lenPos 1688
I =  9337315
number of imo 2158
1688
===============
dfNewJourney 20
lenPos 1743
I =  9256468
number of imo 2159
1743
===============
dfNewJourney 13
lenPos 1744
I =  9314870
number of imo 2160
1744
===============
dfNewJourney 12
lenPos 1560
I =  9221891
number of imo 2161
1560
===============
dfNewJourney 42
lenPos 1884
I =  9422392
number of imo 2162
1884
===============
dfNewJourney 35
lenPos 1704
I =  9254240
number of imo 2163
1704
===============
dfNewJourney 36
lenPos 1802
I =  9326902
number of imo 2164
1802
===============
dfNewJourney 32
lenPos 1769
I =  9133587
number of imo 2165
1769
===============
dfNewJourney 20
lenPos 1794
I =  9299680
number of imo 2166
1794
===============
dfNewJourney 25
lenPos 1731
I =  9295323
number of imo 2167
1731
===============
dfNewJourney 9
lenPos 1749
I =  9236743
number of imo 2168
1749
===============
dfNewJourney 19
lenPos 1846
I =  9478614
number of imo 2169
1846
===============
dfNewJourney 27
lenPos 1705
I =  9212371
number of imo 2170
1705
===============
dfNewJourney 14
lenPos 0
I =  9182930
number of imo 2171
dfNewJourney 39
lenPos 1772
I =  9414216
number of imo 2172
1772
===============
dfNewJourney 32
lenPos 1749
I =  9310707
number of imo 2173
1749
===============
dfNewJourney 22
lenPos 1608
I =  9308156
number of imo 2174
1608
===============
dfNewJourney 13
lenPos 1770
I =  9208473
number of imo 2175
1770
===============
dfNewJourney 14
lenPos 1640
I =  9171503
number of imo 2176
1640
===============
dfNewJourney 17
lenPos 1861
I =  9423449
number of imo 2177
1861
===============
dfNewJourney 50
lenPos 1826
I =  9573701
number of imo 2178
1826
===============
dfNewJourney 43
lenPos 1728
I =  9259599
number of imo 2179
1728
===============
dfNewJourney 17
lenPos 1419
I =  9322451
number of imo 2180
1419
===============
dfNewJourney 20
lenPos 1779
I =  9248849
number of imo 2181
1779
===============
dfNewJourney 16
lenPos 1799
I =  9340104
number of imo 2182
1799
===============
dfNewJourney 39
lenPos 0
I =  10018451
number of imo 2183
dfNewJourney 32
lenPos 1703
I =  9273844
number of imo 2184
1703
===============
dfNewJourney 27
lenPos 1846
I =  9318010
number of imo 2185
1846
===============
dfNewJourney 26
lenPos 0
I =  9041447
number of imo 2186
dfNewJourney 36
lenPos 0
I =  10007620
number of imo 2187
dfNewJourney 45
lenPos 1733
I =  9284817
number of imo 2188
1733
===============
dfNewJourney 26
lenPos 1747
I =  9308778
number of imo 2189
1747
===============
dfNewJourney 36
lenPos 1787
I =  9379155
number of imo 2190
1787
===============
dfNewJourney 48
lenPos 1795
I =  9392377
number of imo 2191
1795
===============
dfNewJourney 31
lenPos 1811
I =  9425564
number of imo 2192
1811
===============
dfNewJourney 15
lenPos 1821
I =  9425497
number of imo 2193
1821
===============
dfNewJourney 40
lenPos 1824
I =  9334571
number of imo 2194
1824
===============
dfNewJourney 44
lenPos 1758
I =  9298284
number of imo 2195
1758
===============
dfNewJourney 27
lenPos 1618
I =  9413779
number of imo 2196
1618
===============
dfNewJourney 51
lenPos 1862
I =  9374533
number of imo 2197
1862
===============
dfNewJourney 35
lenPos 1745
I =  9434228
number of imo 2198
1745
===============
dfNewJourney 20
lenPos 1352
I =  9236729
number of imo 2199
1352
===============
dfNewJourney 42
lenPos 1839
I =  9278662
number of imo 2200
1839
===============
dfNewJourney 10
lenPos 1722
I =  9582439
number of imo 2201
1722
===============
dfNewJourney 39
lenPos 1789
I =  9472737
number of imo 2202
1789
===============
dfNewJourney 46
lenPos 1747
I =  9424596
number of imo 2203
1747
===============
dfNewJourney 9
lenPos 1708
I =  9384447
number of imo 2204
1708
===============
dfNewJourney 35
lenPos 1818
I =  9178197
number of imo 2205
1818
===============
dfNewJourney 6
lenPos 1789
I =  9222704
number of imo 2206
1789
===============
dfNewJourney 40
lenPos 1763
I =  9317078
number of imo 2207
1763
===============
dfNewJourney 35
lenPos 1752
I =  9321952
number of imo 2208
1752
===============
dfNewJourney 18
lenPos 1652
I =  9340128
number of imo 2209
1652
===============
dfNewJourney 38
lenPos 1502
I =  9399351
number of imo 2210
1502
===============
dfNewJourney 30
lenPos 0
I =  10029646
number of imo 2211
dfNewJourney 1
lenPos 0
I =  8319902
number of imo 2212
dfNewJourney 15
lenPos 1841
I =  9592288
number of imo 2213
1841
===============
dfNewJourney 2
lenPos 0
I =  9044413
number of imo 2214
dfNewJourney 50
lenPos 1862
I =  9425540
number of imo 2215
1862
===============
dfNewJourney 25
lenPos 1715
I =  9417309
number of imo 2216
1715
===============
dfNewJourney 14
lenPos 1667
I =  9406350
number of imo 2217
1667
===============
dfNewJourney 33
lenPos 1537
I =  9364227
number of imo 2218
1537
===============
dfNewJourney 1
lenPos 0
I =  8319914
number of imo 2219
dfNewJourney 22
lenPos 1792
I =  9229350
number of imo 2220
1792
===============
dfNewJourney 16
lenPos 1817
I =  9334727
number of imo 2221
1817
===============
dfNewJourney 15
lenPos 1756
I =  9302683
number of imo 2222
1756
===============
dfNewJourney 32
lenPos 1758
I =  9418638
number of imo 2223
1758
===============
dfNewJourney 16
lenPos 1852
I =  9405538
number of imo 2224
1852
===============
dfNewJourney 19
lenPos 1864
I =  9489895
number of imo 2225
1864
===============
dfNewJourney 15
lenPos 1806
I =  9389679
number of imo 2226
1806

===============
dfNewJourney 41
lenPos 1756
I =  9307944
number of imo 2227
1756
===============
dfNewJourney 40
lenPos 1835
I =  9321940
number of imo 2228
1835
===============
dfNewJourney 30
lenPos 1691
I =  9340116
number of imo 2229
1691
===============
dfNewJourney 30
lenPos 1837
I =  9325336
number of imo 2230
1837
===============
dfNewJourney 20
lenPos 1675
I =  9332834
number of imo 2231
1675
===============
dfNewJourney 27
lenPos 1816
I =  9448310
number of imo 2232
1816
===============
dfNewJourney 39
lenPos 1809
I =  9424651
number of imo 2233
1809
===============
dfNewJourney 44
lenPos 1719
I =  9489194
number of imo 2234
1719
===============
dfNewJourney 33
lenPos 1712
I =  9254070
number of imo 2235
1712
===============
dfNewJourney 24
lenPos 1760
I =  9459230
number of imo 2236
1760
===============
dfNewJourney 47
lenPos 1800
I =  9358955
number of imo 2237
1800
===============
dfNewJourney 38
lenPos 1767
I =  9304590
number of imo 2238
1767
===============
dfNewJourney 35
lenPos 1608
I =  9389564
number of imo 2239
1608
===============
dfNewJourney 44
lenPos 1810
I =  9459266
number of imo 2240
1810
===============
dfNewJourney 18
lenPos 1776
I =  9239472
number of imo 2241
1776
===============
dfNewJourney 28
lenPos 1850
I =  9305855
number of imo 2242
1850
===============
dfNewJourney 40
lenPos 0
I =  10015393
number of imo 2243
dfNewJourney 17
lenPos 0
I =  9167021
number of imo 2244
dfNewJourney 35
lenPos 1642
I =  9256248
number of imo 2245
1642
===============
dfNewJourney 44
lenPos 1719
I =  9536923
number of imo 2246
1719
===============
dfNewJourney 27
lenPos 1542
I =  9431290
number of imo 2247
1542
===============
dfNewJourney 28
lenPos 1706
I =  9406362
number of imo 2248
1706
===============
dfNewJourney 20
lenPos 1295
I =  9185279
number of imo 2249
1295
===============
dfNewJourney 5
lenPos 1739
I =  9436719
number of imo 2250
1739
===============
dfNewJourney 49
lenPos 1737
I =  9428346
number of imo 2251
1737
===============
dfNewJourney 11
lenPos 1869
I =  9255268
number of imo 2252
1869
===============
dfNewJourney 9
lenPos 1824
I =  9228813
number of imo 2253
1824
===============
dfNewJourney 19
lenPos 1430
I =  9431458
number of imo 2254
1430
===============
dfNewJourney 46
lenPos 1660
I =  9446116
number of imo 2255
1660
===============
dfNewJourney 42
lenPos 1874
I =  9392470
number of imo 2256
1874
===============
dfNewJourney 46
lenPos 1841
I =  9258026
number of imo 2257
1841
===============
dfNewJourney 13
lenPos 1887
I =  8617093
number of imo 2258
1887
===============
dfNewJourney 37
lenPos 1809
I =  9335147
number of imo 2259
1809
===============
dfNewJourney 20
lenPos 0
I =  9150389
number of imo 2260
dfNewJourney 28
lenPos 1756
I =  9373656
number of imo 2261
1756
===============
dfNewJourney 43
lenPos 1813
I =  9459072
number of imo 2262
1813
===============
dfNewJourney 26
lenPos 1748
I =  9288928
number of imo 2263
1748
===============
dfNewJourney 49
lenPos 1801
I =  9400801
number of imo 2264
1801
===============
dfNewJourney 37
lenPos 1713
I =  9239989
number of imo 2265
1713
===============
dfNewJourney 17
lenPos 1720
I =  9417311
number of imo 2266
1720
===============
dfNewJourney 31
lenPos 1768
I =  9391440
number of imo 2267
1768
===============
dfNewJourney 15
lenPos 1839
I =  9290438
number of imo 2268
1839
===============
dfNewJourney 3
lenPos 1370
I =  9038892
number of imo 2269
1370
===============
dfNewJourney 32
lenPos 1540
I =  9165542
number of imo 2270
1540
===============
dfNewJourney 3
lenPos 1730
I =  9518892
number of imo 2271
1730
===============
dfNewJourney 37
lenPos 1840
I =  9374507
number of imo 2272
1840
===============
dfNewJourney 29
lenPos 1705
I =  9379789
number of imo 2273
1705
===============
dfNewJourney 27
lenPos 1810
I =  9274678
number of imo 2274
1810
===============
dfNewJourney 18
lenPos 1620
I =  9173721
number of imo 2275
1620
===============
dfNewJourney 34
lenPos 1667
I =  9329760
number of imo 2276
1667
===============
dfNewJourney 32
lenPos 1828
I =  9363479
number of imo 2277
1828
===============
dfNewJourney 41
lenPos 1672
I =  9294678
number of imo 2278
1672
===============
dfNewJourney 29
lenPos 1825
I =  9345441
number of imo 2279
1825
===============
dfNewJourney 41
lenPos 1693
I =  9341146
number of imo 2280
1693
===============
dfNewJourney 38
lenPos 1814
I =  9312913
number of imo 2281
1814
===============
dfNewJourney 26
lenPos 1802
I =  9396488
number of imo 2282
1802
===============
dfNewJourney 43
lenPos 1696
I =  9414242
number of imo 2283
1696
===============
dfNewJourney 18
lenPos 1682
I =  9538177
number of imo 2284
1682
===============
dfNewJourney 8
lenPos 1766
I =  9301392
number of imo 2285
1766
===============
dfNewJourney 38
lenPos 1787
I =  9275725
number of imo 2286
1787
===============
dfNewJourney 29
lenPos 1788
I =  9307815
number of imo 2287
1788
===============
dfNewJourney 28
lenPos 1774
I =  9365623
number of imo 2288
1774
===============
dfNewJourney 41
lenPos 1811
I =  9047506
number of imo 2289
1811
===============
dfNewJourney 29
lenPos 1622
I =  9308168
number of imo 2290
1622
===============
dfNewJourney 34
lenPos 1553
I =  9307786
number of imo 2291
1553
===============
dfNewJourney 28
lenPos 1764
I =  9388924
number of imo 2292
1764
===============
dfNewJourney 9
lenPos 1766
I =  9464352
number of imo 2293
1766
===============
dfNewJourney 20
lenPos 1508
I =  9224570
number of imo 2294
1508
===============
dfNewJourney 43
lenPos 1831
I =  9325611
number of imo 2295
1831
===============
dfNewJourney 35
lenPos 1765
I =  9270488
number of imo 2296
1765
===============
dfNewJourney 16
lenPos 1793
I =  9297345
number of imo 2297
1793
===============
dfNewJourney 32
lenPos 1834
I =  9388015
number of imo 2298
1834
===============
dfNewJourney 57
lenPos 1810
I =  9489039
number of imo 2299
1810
===============
dfNewJourney 40
lenPos 1812
I =  9273088
number of imo 2300
1812
===============
dfNewJourney 16
lenPos 1826
I =  9436678
number of imo 2301
1826
===============
dfNewJourney 37
lenPos 1668
I =  9344136
number of imo 2302
1668
===============
dfNewJourney 5
lenPos 1494
I =  9236731
number of imo 2303
1494
===============
dfNewJourney 15
lenPos 1812
I =  9247895
number of imo 2304
1812
===============
dfNewJourney 25
lenPos 1614
I =  9370848
number of imo 2305
1614
===============
dfNewJourney 39
lenPos 1757
I =  9341445
number of imo 2306
1757
===============
dfNewJourney 30
lenPos 1720
I =  9417218
number of imo 2307
1720
===============
dfNewJourney 26
lenPos 1687
I =  9174608
number of imo 2308
1687
===============
dfNewJourney 29
lenPos 1812
I =  9414034
number of imo 2309
1812
===============
dfNewJourney 13
lenPos 1510
I =  9167162
number of imo 2310
1510
===============
dfNewJourney 20
lenPos 0
I =  9191333
number of imo 2311
dfNewJourney 21
lenPos 1812
I =  9391385
number of imo 2312
1812
===============
dfNewJourney 35
lenPos 1674
I =  9514169
number of imo 2313
1674
===============
dfNewJourney 3
lenPos 1780
I =  9164213
number of imo 2314
1780
===============
dfNewJourney 7
lenPos 1795
I =  9353591
number of imo 2315
1795
===============
dfNewJourney 43
lenPos 1814
I =  9271951
number of imo 2316
1814
===============
dfNewJourney 43
lenPos 1813
I =  9561368
number of imo 2317
1813
===============
dfNewJourney 43
lenPos 1853
I =  9528392
number of imo 2318
1853
===============
dfNewJourney 21
lenPos 1792
I =  9321976
number of imo 2319
1792
===============
dfNewJourney 30
lenPos 1839
I =  9276561
number of imo 2320
1839
===============
dfNewJourney 21
lenPos 1548
I =  9213301
number of imo 2321
1548
===============
dfNewJourney 37
lenPos 1723
I =  9437684
number of imo 2322
1723
===============
dfNewJourney 11
lenPos 1744
I =  9336402
number of imo 2323
1744
===============
dfNewJourney 33
lenPos 1833
I =  9325609
number of imo 2324
1833
===============
dfNewJourney 24
lenPos 1801
I =  9290361
number of imo 2325
1801
===============
dfNewJourney 44
lenPos 0
I =  10017884
number of imo 2326
dfNewJourney 36
lenPos 1806
I =  9289520
number of imo 2327
1806
===============
dfNewJourney 19
lenPos 1833
I =  9444508
number of imo 2328
1833
===============
dfNewJourney 18
lenPos 1697
I =  9290309
number of imo 2329
1697

===============
dfNewJourney 45
lenPos 1733
I =  9272929
number of imo 2330
1733
===============
dfNewJourney 27
lenPos 1579
I =  9396373
number of imo 2331
1579
===============
dfNewJourney 33
lenPos 1461
I =  9308845
number of imo 2332
1461
===============
dfNewJourney 69
lenPos 1701
I =  9488011
number of imo 2333
1701
===============
dfNewJourney 22
lenPos 1692
I =  9448322
number of imo 2334
1692
===============
dfNewJourney 21
lenPos 1531
I =  9439395
number of imo 2335
1531
===============
dfNewJourney 15
lenPos 1570
I =  9289506
number of imo 2336
1570
===============
dfNewJourney 21
lenPos 1675
I =  9389320
number of imo 2337
1675
===============
dfNewJourney 1
lenPos 1806
I =  9251664
number of imo 2338
1806
===============
dfNewJourney 40
lenPos 1768
I =  9196711
number of imo 2339
1768
===============
dfNewJourney 22
lenPos 1705
I =  9308819
number of imo 2340
1705
===============
dfNewJourney 27
lenPos 1701
I =  9380398
number of imo 2341
1701
===============
dfNewJourney 20
lenPos 1577
I =  9308144
number of imo 2342
1577
===============
dfNewJourney 43
lenPos 1719
I =  9411329
number of imo 2343
1719
===============
dfNewJourney 24
lenPos 1809
I =  9289764
number of imo 2344
1809
===============
dfNewJourney 23
lenPos 1591
I =  9215048
number of imo 2345
1591
===============
dfNewJourney 19
lenPos 1809
I =  9133082
number of imo 2346
1809
===============
dfNewJourney 35
lenPos 0
I =  10007617
number of imo 2347
dfNewJourney 9
lenPos 0
I =  9174581
number of imo 2348
dfNewJourney 34
lenPos 1651
I =  9414840
number of imo 2349
1651
===============
dfNewJourney 43
lenPos 1839
I =  9494670
number of imo 2350
1839
===============
dfNewJourney 39
lenPos 1688
I =  9362372
number of imo 2351
1688
===============
dfNewJourney 30
lenPos 1812
I =  9342217
number of imo 2352
1812
===============
dfNewJourney 21
lenPos 0
I =  10007586
number of imo 2353
dfNewJourney 36
lenPos 1757
I =  9435595
number of imo 2354
1757
===============
dfNewJourney 36
lenPos 1858
I =  9350862
number of imo 2355
1858
===============
dfNewJourney 14
lenPos 0
I =  9185504
number of imo 2356
dfNewJourney 8
lenPos 1846
I =  9380350
number of imo 2357
1846
===============
dfNewJourney 18
lenPos 1786
I =  9388297
number of imo 2358
1786
===============
dfNewJourney 14
lenPos 0
I =  10007591
number of imo 2359
dfNewJourney 32
lenPos 1602
I =  9529346
number of imo 2360
1602
===============
dfNewJourney 8
lenPos 1617
I =  9295074
number of imo 2361
1617
===============
dfNewJourney 24
lenPos 0
I =  9180279
number of imo 2362
dfNewJourney 28
lenPos 1724
I =  9455806
number of imo 2363
1724
===============
dfNewJourney 36
lenPos 1721
I =  9401659
number of imo 2364
1721
===============
dfNewJourney 25
lenPos 1743
I =  9256858
number of imo 2365
1743
===============
dfNewJourney 27
lenPos 1701
I =  9406374
number of imo 2366
1701
===============
dfNewJourney 6
lenPos 1876
I =  9350642
number of imo 2367
1876
===============
dfNewJourney 16
lenPos 1578
I =  9293961
number of imo 2368
1578
===============
dfNewJourney 6
lenPos 0
I =  9066174
number of imo 2369
dfNewJourney 35
lenPos 1796
I =  9269245
number of imo 2370
1796
===============
dfNewJourney 32
lenPos 1674
I =  9338802
number of imo 2371
1674
===============
dfNewJourney 25
lenPos 1768
I =  9264283
number of imo 2372
1768
===============
dfNewJourney 25
lenPos 1739
I =  9260263
number of imo 2373
1739
===============
dfNewJourney 21
lenPos 1411
I =  9306938
number of imo 2374
1411
===============
dfNewJourney 1
lenPos 0
I =  9018660
number of imo 2375
dfNewJourney 9
lenPos 1731
I =  9596375
number of imo 2376
1731
===============
dfNewJourney 32
lenPos 1739
I =  9275983
number of imo 2377
1739
===============
dfNewJourney 40
lenPos 1717
I =  9459022
number of imo 2378
1717
===============
dfNewJourney 31
lenPos 1776
I =  9316232
number of imo 2379
1776
===============
dfNewJourney 36
lenPos 1758
I =  9455739
number of imo 2380
1758
===============
dfNewJourney 15
lenPos 0
I =  10015713
number of imo 2381
dfNewJourney 41
lenPos 0
I =  10015719
number of imo 2382
dfNewJourney 32
lenPos 1736
I =  9379791
number of imo 2383
1736
===============
dfNewJourney 34
lenPos 1651
I =  9344150
number of imo 2384
1651
===============
dfNewJourney 13
lenPos 1610
I =  9247479
number of imo 2385
1610
===============
dfNewJourney 40
lenPos 1622
I =  9426594
number of imo 2386
1622
===============
dfNewJourney 16
lenPos 1757
I =  9420629
number of imo 2387
1757
===============
dfNewJourney 15
lenPos 1809
I =  9384100
number of imo 2388
1809
===============
dfNewJourney 26
lenPos 1809
I =  9451733
number of imo 2389
1809
===============
dfNewJourney 24
lenPos 1399
I =  9290660
number of imo 2390
1399
===============
dfNewJourney 33
lenPos 1502
I =  9569994
number of imo 2391
1502
===============
dfNewJourney 30
lenPos 1581
I =  9341081
number of imo 2392
1581
===============
dfNewJourney 30
lenPos 1794
I =  9176761
number of imo 2393
1794
===============
dfNewJourney 31
lenPos 1707
I =  9346732
number of imo 2394
1707
===============
dfNewJourney 4
lenPos 0
I =  9127708
number of imo 2395
dfNewJourney 35
lenPos 1809
I =  9257993
number of imo 2396
1809
===============
dfNewJourney 40
lenPos 1765
I =  9397781
number of imo 2397
1765
===============
dfNewJourney 15
lenPos 1837
I =  9391957
number of imo 2398
1837
===============
dfNewJourney 24
lenPos 1662
I =  9317717
number of imo 2399
1662
===============
dfNewJourney 28
lenPos 1826
I =  9537927
number of imo 2400
1826
===============
dfNewJourney 37
lenPos 1861
I =  9448712
number of imo 2401
1861
===============
dfNewJourney 74
lenPos 0
I =  10015416
number of imo 2402
dfNewJourney 16
lenPos 1818
I =  9411185
number of imo 2403
1818
===============
dfNewJourney 26
lenPos 1763
I =  9373668
number of imo 2404
1763
===============
dfNewJourney 8
lenPos 1791
I =  9231901
number of imo 2405
1791
===============
dfNewJourney 35
lenPos 1744
I =  9389083
number of imo 2406
1744
===============
dfNewJourney 41
lenPos 1683
I =  9443865
number of imo 2407
1683
===============
dfNewJourney 42
lenPos 1760
I =  9381744
number of imo 2408
1760
===============
dfNewJourney 19
lenPos 1770
I =  9312925
number of imo 2409
1770
===============
dfNewJourney 48
lenPos 1533
I =  9149237
number of imo 2410
1533
===============
dfNewJourney 14
lenPos 1844
I =  9407445
number of imo 2411
1844
===============
dfNewJourney 13
lenPos 1474
I =  9160530
number of imo 2412
1474
===============
dfNewJourney 6
lenPos 532
I =  9426946
number of imo 2413
532
===============
dfNewJourney 24
lenPos 1368
I =  9111632
number of imo 2414
1368
===============
dfNewJourney 3
lenPos 0
I =  8615980
number of imo 2415
dfNewJourney 4
lenPos 0
I =  9033969
number of imo 2416
dfNewJourney 28
lenPos 1878
I =  9527855
number of imo 2417
1878
===============
dfNewJourney 40
lenPos 1561
I =  9309007
number of imo 2418
1561
===============
dfNewJourney 7
lenPos 1712
I =  9417024
number of imo 2419
1712
===============
dfNewJourney 39
lenPos 1730
I =  9441154
number of imo 2420
1730
===============
dfNewJourney 49
lenPos 1760
I =  9389851
number of imo 2421
1760
===============
dfNewJourney 32
lenPos 1779
I =  9384435
number of imo 2422
1779
===============
dfNewJourney 34
lenPos 1742
I =  9298961
number of imo 2423
1742
===============
dfNewJourney 42
lenPos 0
I =  10015488
number of imo 2424
dfNewJourney 21
lenPos 1854
I =  9252292
number of imo 2425
1854
===============
dfNewJourney 37
lenPos 1822
I =  9254862
number of imo 2426
1822
===============
dfNewJourney 35
lenPos 1843
I =  9318541
number of imo 2427
1843
===============
dfNewJourney 36
lenPos 0
I =  10007613
number of imo 2428
dfNewJourney 31
lenPos 1797
I =  9380506
number of imo 2429
1797
===============
dfNewJourney 33
lenPos 0
I =  8002078
number of imo 2430
dfNewJourney 23
lenPos 1618
I =  9420253
number of imo 2431
1618
===============
dfNewJourney 9
lenPos 1820
I =  9315771
number of imo 2432
1820
===============
dfNewJourney 37
lenPos 1809
I =  9466013
number of imo 2433
1809
===============
dfNewJourney 19
lenPos 1679
I =  9370836
number of imo 2434
1679
===============
dfNewJourney 30
lenPos 1566
I =  9330604
number of imo 2435
1566
===============
dfNewJourney 37
lenPos 1874
I =  9487471
number of imo 2436
1874

===============
dfNewJourney 41
lenPos 0
I =  10015520
number of imo 2437
dfNewJourney 24
lenPos 1766
I =  9255672
number of imo 2438
1766
===============
dfNewJourney 28
lenPos 1703
I =  9183295
number of imo 2439
1703
===============
dfNewJourney 24
lenPos 1395
I =  9417165
number of imo 2440
1395
===============
dfNewJourney 39
lenPos 1714
I =  9314911
number of imo 2441
1714
===============
dfNewJourney 16
lenPos 1671
I =  9563251
number of imo 2442
1671
===============
dfNewJourney 28
lenPos 1849
I =  9394947
number of imo 2443
1849
===============
dfNewJourney 2
lenPos 1436
I =  8011304
number of imo 2444
1436
===============
dfNewJourney 30
lenPos 1567
I =  9380661
number of imo 2445
1567
===============
dfNewJourney 17
lenPos 1883
I =  9210907
number of imo 2446
1883
===============
dfNewJourney 1
lenPos 1747
I =  9251418
number of imo 2447
1747
===============
dfNewJourney 29
lenPos 0
I =  10015829
number of imo 2448
dfNewJourney 1
lenPos 1794
I =  9178044
number of imo 2449
1794
===============
dfNewJourney 5
lenPos 1812
I =  9435571
number of imo 2450
1812
===============
dfNewJourney 28
lenPos 1779
I =  9376945
number of imo 2451
1779
===============
dfNewJourney 12
lenPos 1699
I =  9288796
number of imo 2452
1699
===============
dfNewJourney 52
lenPos 0
I =  10015827
number of imo 2453
dfNewJourney 19
lenPos 1717
I =  9341093
number of imo 2454
1717
===============
dfNewJourney 21
lenPos 1540
I =  9258179
number of imo 2455
1540
===============
dfNewJourney 17
lenPos 1786
I =  9431317
number of imo 2456
1786
===============
dfNewJourney 45
lenPos 1796
I =  9384019
number of imo 2457
1796
===============
dfNewJourney 11
lenPos 0
I =  9032678
number of imo 2458
dfNewJourney 20
lenPos 1685
I =  9229362
number of imo 2459
1685
===============
dfNewJourney 34
lenPos 1520
I =  9247821
number of imo 2460
1520
===============
dfNewJourney 12
lenPos 1830
I =  9338917
number of imo 2461
1830
===============
dfNewJourney 11
lenPos 1684
I =  9215115
number of imo 2462
1684
===============
dfNewJourney 33
lenPos 1696
I =  9344148
number of imo 2463
1696
===============
dfNewJourney 4
lenPos 1865
I =  9299367
number of imo 2464
1865
===============
dfNewJourney 18
lenPos 1759
I =  9420851
number of imo 2465
1759
===============
dfNewJourney 5
lenPos 1866
I =  9179634
number of imo 2466
1866
===============
dfNewJourney 28
lenPos 1701
I =  9311713
number of imo 2467
1701
===============
dfNewJourney 34
lenPos 1810
I =  9397456
number of imo 2468
1810
===============
dfNewJourney 4
lenPos 0
I =  9015345
number of imo 2469
dfNewJourney 24
lenPos 1820
I =  9592276
number of imo 2470
1820
===============
dfNewJourney 51
lenPos 1625
I =  9149249
number of imo 2471
1625
===============
dfNewJourney 15
lenPos 1783
I =  9252979
number of imo 2472
1783
===============
dfNewJourney 27
lenPos 1725
I =  9216559
number of imo 2473
1725
===============
dfNewJourney 23
lenPos 1760
I =  9295335
number of imo 2474
1760
===============
dfNewJourney 17
lenPos 1742
I =  9260029
number of imo 2475
1742
===============
dfNewJourney 11
lenPos 0
I =  10007584
number of imo 2476
dfNewJourney 56
lenPos 1818
I =  9288382
number of imo 2477
1818
===============
dfNewJourney 8
lenPos 1501
I =  9110482
number of imo 2478
1501
===============
dfNewJourney 1
lenPos 0
I =  8715546
number of imo 2479
dfNewJourney 8
lenPos 1750
I =  9412995
number of imo 2480
1750
===============
dfNewJourney 29
lenPos 1799
I =  9380099
number of imo 2481
1799
===============
dfNewJourney 9
lenPos 1767
I =  9306677
number of imo 2482
1767
===============
dfNewJourney 22
lenPos 1748
I =  9214745
number of imo 2483
1748
===============
dfNewJourney 4
lenPos 0
I =  9012719
number of imo 2484
dfNewJourney 9
lenPos 0
I =  8705981
number of imo 2485
dfNewJourney 26
lenPos 1756
I =  9314088
number of imo 2486
1756
===============
dfNewJourney 42
lenPos 1804
I =  9433901
number of imo 2487
1804
===============
dfNewJourney 12
lenPos 1708
I =  9344825
number of imo 2488
1708
===============
dfNewJourney 39
lenPos 1806
I =  9466001
number of imo 2489
1806
===============
dfNewJourney 18
lenPos 1713
I =  9215086
number of imo 2490
1713
===============
dfNewJourney 22
lenPos 1802
I =  9412000
number of imo 2491
1802
===============
dfNewJourney 65
lenPos 1865
I =  9561930
number of imo 2492
1865
===============
dfNewJourney 12
lenPos 0
I =  9111620
number of imo 2493
dfNewJourney 37
lenPos 1815
I =  9402495
number of imo 2494
1815
===============
dfNewJourney 20
lenPos 1492
I =  9247493
number of imo 2495
1492
===============
dfNewJourney 5
lenPos 1875
I =  9464376
number of imo 2496
1875
===============
dfNewJourney 5
lenPos 1662
I =  9248801
number of imo 2497
1662
===============
dfNewJourney 21
lenPos 1824
I =  9260043
number of imo 2498
1824
===============
dfNewJourney 34
lenPos 1807
I =  9367748
number of imo 2499
1807
===============
dfNewJourney 37
lenPos 1702
I =  9354258
number of imo 2500
1702
===============
dfNewJourney 29
lenPos 1794
I =  9341512
number of imo 2501
1794
===============
dfNewJourney 37
lenPos 1718
I =  9392389
number of imo 2502
1718
===============
dfNewJourney 6
lenPos 1660
I =  9260005
number of imo 2503
1660
===============
dfNewJourney 16
lenPos 1753
I =  9259903
number of imo 2504
1753
===============
dfNewJourney 11
lenPos 1646
I =  9247833
number of imo 2505
1646
===============
dfNewJourney 4
lenPos 1894
I =  9305568
number of imo 2506
1894
===============
dfNewJourney 13
lenPos 1769
I =  9538165
number of imo 2507
1769
===============
dfNewJourney 1
lenPos 1811
I =  9446427
number of imo 2508
1811
===============
dfNewJourney 10
lenPos 1611
I =  9252307
number of imo 2509
1611
===============
dfNewJourney 55
lenPos 1836
I =  9459254
number of imo 2510
1836
===============
dfNewJourney 33
lenPos 1844
I =  9419735
number of imo 2511
1844
===============
dfNewJourney 5
lenPos 1803
I =  9259769
number of imo 2512
1803
===============
dfNewJourney 6
lenPos 1456
I =  9018684
number of imo 2513
1456
===============
dfNewJourney 77
lenPos 1836
I =  9400382
number of imo 2514
1836
===============
dfNewJourney 12
lenPos 1808
I =  9339325
number of imo 2515
1808
===============
dfNewJourney 3
lenPos 1854
I =  9225328
number of imo 2516
1854
===============
dfNewJourney 1
lenPos 0
I =  9214642
number of imo 2517
dfNewJourney 38
lenPos 1409
I =  9389497
number of imo 2518
1409
===============
dfNewJourney 21
lenPos 1769
I =  9255945
number of imo 2519
1769
===============
dfNewJourney 34
lenPos 0
I =  10015400
number of imo 2520
dfNewJourney 40
lenPos 1830
I =  9346457
number of imo 2521
1830
===============
dfNewJourney 4
lenPos 0
I =  8817643
number of imo 2522
dfNewJourney 7
lenPos 1598
I =  9170432
number of imo 2523
1598
===============
dfNewJourney 25
lenPos 1838
I =  9241815
number of imo 2524
1838
===============
dfNewJourney 1
lenPos 0
I =  10027198
number of imo 2525
dfNewJourney 43
lenPos 1785
I =  9399882
number of imo 2526
1785
===============
dfNewJourney 16
lenPos 1665
I =  9399870
number of imo 2527
1665
===============
dfNewJourney 18
lenPos 1861
I =  9416836
number of imo 2528
1861
===============
dfNewJourney 18
lenPos 1861
I =  9473729
number of imo 2529
1861
===============
dfNewJourney 13
lenPos 1670
I =  9408322
number of imo 2530
1670
===============
dfNewJourney 6
lenPos 1901
I =  9255294
number of imo 2531
1901
===============
dfNewJourney 22
lenPos 0
I =  9177820
number of imo 2532
dfNewJourney 25
lenPos 1601
I =  9174610
number of imo 2533
1601
===============
dfNewJourney 10
lenPos 1831
I =  9259991
number of imo 2534
1831
===============
dfNewJourney 25
lenPos 0
I =  9268904
number of imo 2535
dfNewJourney 28
lenPos 1714
I =  9235696
number of imo 2536
1714
===============
dfNewJourney 36
lenPos 1754
I =  9349631
number of imo 2537
1754
===============
dfNewJourney 43
lenPos 1792
I =  9428384
number of imo 2538
1792
===============
dfNewJourney 34
lenPos 1745
I =  9289178
number of imo 2539
1745
===============
dfNewJourney 37
lenPos 1852
I =  9561370
number of imo 2540
1852
===============
dfNewJourney 4
lenPos 0
I =  9110597
number of imo 2541
dfNewJourney 2
lenPos 0
I =  9051363
number of imo 2542
dfNewJourney 28
lenPos 1733
I =  9306782
number of imo 2543
1733

===============
dfNewJourney 21
lenPos 1822
I =  9239654
number of imo 2544
1822
===============
dfNewJourney 3
lenPos 1326
I =  8619443
number of imo 2545
1326
===============
dfNewJourney 44
lenPos 1670
I =  9277747
number of imo 2546
1670
===============
dfNewJourney 27
lenPos 1837
I =  9307097
number of imo 2547
1837
===============
dfNewJourney 23
lenPos 1868
I =  9379131
number of imo 2548
1868
===============
dfNewJourney 25
lenPos 1795
I =  9282508
number of imo 2549
1795
===============
dfNewJourney 3
lenPos 0
I =  8217958
number of imo 2550
dfNewJourney 1
lenPos 0
I =  9040625
number of imo 2551
dfNewJourney 35
lenPos 1746
I =  9455741
number of imo 2552
1746
===============
dfNewJourney 10
lenPos 1802
I =  9315745
number of imo 2553
1802
===============
dfNewJourney 17
lenPos 1637
I =  9251561
number of imo 2554
1637
===============
dfNewJourney 8
lenPos 1765
I =  9228849
number of imo 2555
1765
===============
dfNewJourney 1
lenPos 0
I =  8512437
number of imo 2556
dfNewJourney 21
lenPos 1795
I =  9203801
number of imo 2557
1795
===============
dfNewJourney 6
lenPos 1855
I =  9103831
number of imo 2558
1855
===============
dfNewJourney 8
lenPos 1702
I =  9171838
number of imo 2559
1702
===============
dfNewJourney 36
lenPos 0
I =  10007622
number of imo 2560
dfNewJourney 16
lenPos 1625
I =  9165762
number of imo 2561
1625
===============
dfNewJourney 31
lenPos 1726
I =  9379777
number of imo 2562
1726
===============
dfNewJourney 26
lenPos 1770
I =  9231614
number of imo 2563
1770
===============
dfNewJourney 17
lenPos 1564
I =  9411197
number of imo 2564
1564
===============
dfNewJourney 44
lenPos 1584
I =  9403542
number of imo 2565
1584
===============
dfNewJourney 46
lenPos 1849
I =  9440136
number of imo 2566
1849
===============
dfNewJourney 4
lenPos 0
I =  9156345
number of imo 2567
dfNewJourney 20
lenPos 1541
I =  9356763
number of imo 2568
1541
===============
dfNewJourney 13
lenPos 0
I =  9178343
number of imo 2569
dfNewJourney 3
lenPos 1744
I =  9353606
number of imo 2570
1744
===============
dfNewJourney 25
lenPos 1744
I =  9382762
number of imo 2571
1744
===============
dfNewJourney 10
lenPos 1878
I =  9256054
number of imo 2572
1878
===============
dfNewJourney 37
lenPos 1713
I =  9252448
number of imo 2573
1713
===============
dfNewJourney 3
lenPos 1878
I =  9598268
number of imo 2574
1878
===============
dfNewJourney 26
lenPos 1738
I =  9129952
number of imo 2575
1738
===============
dfNewJourney 60
lenPos 0
I =  10015618
number of imo 2576
dfNewJourney 11
lenPos 1855
I =  9312901
number of imo 2577
1855
===============
dfNewJourney 17
lenPos 1746
I =  9265744
number of imo 2578
1746
===============
dfNewJourney 24
lenPos 1759
I =  9384095
number of imo 2579
1759
===============
dfNewJourney 16
lenPos 0
I =  9192349
number of imo 2580
dfNewJourney 50
lenPos 1862
I =  9387580
number of imo 2581
1862
===============
dfNewJourney 2
lenPos 1335
I =  9314856
number of imo 2582
1335
===============
dfNewJourney 44
lenPos 1856
I =  9358321
number of imo 2583
1856
===============
dfNewJourney 34
lenPos 1699
I =  9209283
number of imo 2584
1699
===============
dfNewJourney 12
lenPos 1292
I =  8644034
number of imo 2585
1292
===============
dfNewJourney 30
lenPos 1783
I =  9419553
number of imo 2586
1783
===============
dfNewJourney 1
lenPos 0
I =  9110626
number of imo 2587
dfNewJourney 6
lenPos 1801
I =  9180102
number of imo 2588
1801
===============
dfNewJourney 14
lenPos 1334
I =  9309978
number of imo 2589
1334
===============
dfNewJourney 16
lenPos 1746
I =  9171345
number of imo 2590
1746
===============
dfNewJourney 25
lenPos 1711
I =  9258478
number of imo 2591
1711
===============
dfNewJourney 40
lenPos 1714
I =  9389289
number of imo 2592
1714
===============
dfNewJourney 38
lenPos 1642
I =  9313175
number of imo 2593
1642
===============
dfNewJourney 12
lenPos 1792
I =  9290490
number of imo 2594
1792
===============
dfNewJourney 45
lenPos 1825
I =  9470911
number of imo 2595
1825
===============
dfNewJourney 27
lenPos 1762
I =  9283784
number of imo 2596
1762
===============
dfNewJourney 5
lenPos 1838
I =  9407562
number of imo 2597
1838
===============
dfNewJourney 18
lenPos 1856
I =  9436707
number of imo 2598
1856
===============
dfNewJourney 1
lenPos 0
I =  9051351
number of imo 2599
dfNewJourney 45
lenPos 0
I =  10029355
number of imo 2600
dfNewJourney 30
lenPos 1671
I =  9259264
number of imo 2601
1671
===============
dfNewJourney 19
lenPos 1061
I =  9208136
number of imo 2602
1061
===============
dfNewJourney 11
lenPos 1590
I =  9214757
number of imo 2603
1590
===============
dfNewJourney 13
lenPos 824
I =  9208485
number of imo 2604
824
===============
dfNewJourney 14
lenPos 1857
I =  9305623
number of imo 2605
1857
===============
dfNewJourney 8
lenPos 1725
I =  9144794
number of imo 2606
1725
===============
dfNewJourney 9
lenPos 1834
I =  9380570
number of imo 2607
1834
===============
dfNewJourney 8
lenPos 1523
I =  9081825
number of imo 2608
1523
===============
dfNewJourney 15
lenPos 0
I =  9186089
number of imo 2609
dfNewJourney 33
lenPos 1708
I =  9261657
number of imo 2610
1708
===============
dfNewJourney 35
lenPos 1658
I =  9457385
number of imo 2611
1658
===============
dfNewJourney 13
lenPos 1790
I =  9271377
number of imo 2612
1790
===============
dfNewJourney 34
lenPos 1843
I =  9322396
number of imo 2613
1843
===============
dfNewJourney 30
lenPos 1762
I =  9473054
number of imo 2614
1762
===============
dfNewJourney 36
lenPos 1642
I =  9252060
number of imo 2615
1642
===============
dfNewJourney 66
lenPos 0
I =  10007514
number of imo 2616
dfNewJourney 11
lenPos 866
I =  9038749
number of imo 2617
866
===============
dfNewJourney 11
lenPos 1876
I =  9413559
number of imo 2618
1876
===============
dfNewJourney 12
lenPos 1850
I =  9592264
number of imo 2619
1850
===============
dfNewJourney 16
lenPos 1807
I =  9296119
number of imo 2620
1807
===============
dfNewJourney 2
lenPos 0
I =  8706167
number of imo 2621
dfNewJourney 43
lenPos 0
I =  10015720
number of imo 2622
dfNewJourney 41
lenPos 0
I =  10015716
number of imo 2623
dfNewJourney 24
lenPos 1839
I =  9528043
number of imo 2624
1839
===============
dfNewJourney 27
lenPos 1822
I =  9381500
number of imo 2625
1822
===============
dfNewJourney 23
lenPos 1809
I =  9315721
number of imo 2626
1809
===============
dfNewJourney 4
lenPos 1841
I =  9291262
number of imo 2627
1841
===============
dfNewJourney 25
lenPos 1788
I =  9309382
number of imo 2628
1788
===============
dfNewJourney 23
lenPos 1840
I =  9288734
number of imo 2629
1840
===============
dfNewJourney 32
lenPos 1666
I =  9387138
number of imo 2630
1666
===============
dfNewJourney 33
lenPos 1665
I =  9296810
number of imo 2631
1665
===============
dfNewJourney 43
lenPos 0
I =  10015489
number of imo 2632
dfNewJourney 42
lenPos 0
I =  10029037
number of imo 2633
dfNewJourney 16
lenPos 1463
I =  9295050
number of imo 2634
1463
===============
dfNewJourney 7
lenPos 1639
I =  9223253
number of imo 2635
1639
===============
dfNewJourney 25
lenPos 1388
I =  9166417
number of imo 2636
1388
===============
dfNewJourney 12
lenPos 1827
I =  9522324
number of imo 2637
1827
===============
dfNewJourney 4
lenPos 1839
I =  9298181
number of imo 2638
1839
===============
dfNewJourney 2
lenPos 1844
I =  8617079
number of imo 2639
1844
===============
dfNewJourney 32
lenPos 1739
I =  9374296
number of imo 2640
1739
===============
dfNewJourney 37
lenPos 1834
I =  9577068
number of imo 2641
1834
===============
dfNewJourney 21
lenPos 1861
I =  9397212
number of imo 2642
1861
===============
dfNewJourney 14
lenPos 1874
I =  9351634
number of imo 2643
1874
===============
dfNewJourney 43
lenPos 0
I =  10007623
number of imo 2644
dfNewJourney 33
lenPos 1860
I =  9523287
number of imo 2645
1860
===============
dfNewJourney 16
lenPos 1809
I =  9412036
number of imo 2646
1809
===============
dfNewJourney 28
lenPos 1636
I =  9332810
number of imo 2647
1636
===============
dfNewJourney 15
lenPos 1715
I =  9263198
number of imo 2648
1715
===============
dfNewJourney 29
lenPos 1801
I =  9297371
number of imo 2649
1801
===============
dfNewJourney 10
lenPos 1596
I =  9081813
number of imo 2650
1596

===============
dfNewJourney 25
lenPos 1846
I =  9405540
number of imo 2651
1846
===============
dfNewJourney 8
lenPos 1794
I =  9199828
number of imo 2652
1794
===============
dfNewJourney 10
lenPos 0
I =  8819184
number of imo 2653
dfNewJourney 26
lenPos 1605
I =  9242223
number of imo 2654
1605
===============
dfNewJourney 22
lenPos 1775
I =  9266762
number of imo 2655
1775
===============
dfNewJourney 7
lenPos 1625
I =  9413004
number of imo 2656
1625
===============
dfNewJourney 52
lenPos 1847
I =  9326524
number of imo 2657
1847
===============
dfNewJourney 21
lenPos 1551
I =  9388807
number of imo 2658
1551
===============
dfNewJourney 6
lenPos 1893
I =  9183609
number of imo 2659
1893
===============
dfNewJourney 36
lenPos 1809
I =  9308089
number of imo 2660
1809
===============
dfNewJourney 9
lenPos 1783
I =  9337341
number of imo 2661
1783
===============
dfNewJourney 36
lenPos 1739
I =  9310680
number of imo 2662
1739
===============
dfNewJourney 2
lenPos 0
I =  8617067
number of imo 2663
dfNewJourney 33
lenPos 1822
I =  9389095
number of imo 2664
1822
===============
dfNewJourney 19
lenPos 1710
I =  9258167
number of imo 2665
1710
===============
dfNewJourney 12
lenPos 1787
I =  9112131
number of imo 2666
1787
===============
dfNewJourney 2
lenPos 0
I =  8600973
number of imo 2667
dfNewJourney 30
lenPos 1694
I =  9421403
number of imo 2668
1694
===============
dfNewJourney 34
lenPos 1728
I =  9234599
number of imo 2669
1728
===============
dfNewJourney 28
lenPos 1552
I =  9384007
number of imo 2670
1552
===============
dfNewJourney 13
lenPos 1712
I =  8808525
number of imo 2671
1712
===============
dfNewJourney 15
lenPos 1761
I =  9312846
number of imo 2672
1761
===============
dfNewJourney 17
lenPos 1823
I =  9260067
number of imo 2673
1823
===============
dfNewJourney 34
lenPos 1810
I =  9276597
number of imo 2674
1810
===============
dfNewJourney 35
lenPos 1853
I =  9354260
number of imo 2675
1853
===============
dfNewJourney 25
lenPos 1495
I =  9247792
number of imo 2676
1495
===============
dfNewJourney 29
lenPos 1817
I =  9318008
number of imo 2677
1817
===============
dfNewJourney 35
lenPos 1603
I =  9416408
number of imo 2678
1603
===============
dfNewJourney 18
lenPos 1850
I =  9334703
number of imo 2679
1850
===============
dfNewJourney 34
lenPos 0
I =  10017883
number of imo 2680
dfNewJourney 37
lenPos 1844
I =  9252943
number of imo 2681
1844
===============
dfNewJourney 30
lenPos 1825
I =  9413688
number of imo 2682
1825
===============
dfNewJourney 21
lenPos 1631
I =  9422641
number of imo 2683
1631
===============
dfNewJourney 42
lenPos 0
I =  10007635
number of imo 2684
dfNewJourney 14
lenPos 1687
I =  9396086
number of imo 2685
1687
===============
dfNewJourney 15
lenPos 1457
I =  9284788
number of imo 2686
1457
===============
dfNewJourney 6
lenPos 1838
I =  9352195
number of imo 2687
1838
===============
dfNewJourney 12
lenPos 1851
I =  9595137
number of imo 2688
1851
===============
dfNewJourney 34
lenPos 1572
I =  9270490
number of imo 2689
1572
===============
dfNewJourney 11
lenPos 0
I =  9186596
number of imo 2690
dfNewJourney 44
lenPos 0
I =  10015468
number of imo 2691
dfNewJourney 32
lenPos 1659
I =  9201592
number of imo 2692
1659
===============
dfNewJourney 25
lenPos 1753
I =  9524982
number of imo 2693
1753
===============
dfNewJourney 20
lenPos 1665
I =  9158161
number of imo 2694
1665
===============
dfNewJourney 37
lenPos 1756
I =  9316244
number of imo 2695
1756
===============
dfNewJourney 14
lenPos 1871
I =  9413547
number of imo 2696
1871
===============
dfNewJourney 16
lenPos 1837
I =  9391945
number of imo 2697
1837
===============
dfNewJourney 27
lenPos 1721
I =  9313163
number of imo 2698
1721
===============
dfNewJourney 12
lenPos 1855
I =  9330472
number of imo 2699
1855
===============
dfNewJourney 21
lenPos 1492
I =  9327009
number of imo 2700
1492
===============
dfNewJourney 24
lenPos 0
I =  10017874
number of imo 2701
dfNewJourney 23
lenPos 1854
I =  9418482
number of imo 2702
1854
===============
dfNewJourney 16
lenPos 0
I =  9116254
number of imo 2703
dfNewJourney 19
lenPos 0
I =  10007607
number of imo 2704
dfNewJourney 5
lenPos 1308
I =  9313424
number of imo 2705
1308
===============
dfNewJourney 4
lenPos 1889
I =  9204776
number of imo 2706
1889
===============
dfNewJourney 11
lenPos 1801
I =  9360465
number of imo 2707
1801
===============
dfNewJourney 25
lenPos 1801
I =  9271834
number of imo 2708
1801
===============
dfNewJourney 37
lenPos 0
I =  10015715
number of imo 2709
dfNewJourney 7
lenPos 1891
I =  9369875
number of imo 2710
1891
===============
dfNewJourney 37
lenPos 1687
I =  9258363
number of imo 2711
1687
===============
dfNewJourney 5
lenPos 1817
I =  9314894
number of imo 2712
1817
===============
dfNewJourney 32
lenPos 1851
I =  9297333
number of imo 2713
1851
===============
dfNewJourney 25
lenPos 1865
I =  9410909
number of imo 2714
1865
===============
dfNewJourney 44
lenPos 1663
I =  9323405
number of imo 2715
1663
===============
dfNewJourney 14
lenPos 0
I =  9182942
number of imo 2716
dfNewJourney 1
lenPos 1855
I =  9298789
number of imo 2717
1855
===============
dfNewJourney 28
lenPos 1882
I =  9309423
number of imo 2718
1882
===============
dfNewJourney 46
lenPos 1459
I =  9401233
number of imo 2719
1459
===============
dfNewJourney 27
lenPos 1297
I =  9342097
number of imo 2720
1297
===============
dfNewJourney 9
lenPos 1853
I =  9290610
number of imo 2721
1853
===============
dfNewJourney 6
lenPos 1844
I =  9253129
number of imo 2722
1844
===============
dfNewJourney 1
lenPos 0
I =  9183594
number of imo 2723
dfNewJourney 20
lenPos 1852
I =  9285720
number of imo 2724
1852
===============
dfNewJourney 40
lenPos 1795
I =  9387918
number of imo 2725
1795
===============
dfNewJourney 3
lenPos 0
I =  9011868
number of imo 2726
dfNewJourney 17
lenPos 1878
I =  9322839
number of imo 2727
1878
===============
dfNewJourney 12
lenPos 1626
I =  9188764
number of imo 2728
1626
===============
dfNewJourney 19
lenPos 1652
I =  9364930
number of imo 2729
1652
===============
dfNewJourney 16
lenPos 0
I =  10022379
number of imo 2730
dfNewJourney 51
lenPos 1847
I =  9278064
number of imo 2731
1847
===============
dfNewJourney 7
lenPos 1850
I =  9334789
number of imo 2732
1850
===============
dfNewJourney 27
lenPos 1827
I =  9470985
number of imo 2733
1827
===============
dfNewJourney 31
lenPos 1680
I =  9344124
number of imo 2734
1680
===============
dfNewJourney 47
lenPos 0
I =  10029356
number of imo 2735
dfNewJourney 56
lenPos 1547
I =  9539523
number of imo 2736
1547
===============
dfNewJourney 19
lenPos 1861
I =  9274616
number of imo 2737
1861
===============
dfNewJourney 8
lenPos 1677
I =  9298818
number of imo 2738
1677
===============
dfNewJourney 1
lenPos 0
I =  9001590
number of imo 2739
dfNewJourney 6
lenPos 1875
I =  9283734
number of imo 2740
1875
===============
dfNewJourney 11
lenPos 1599
I =  9346067
number of imo 2741
1599
===============
dfNewJourney 6
lenPos 1816
I =  9298193
number of imo 2742
1816
===============
dfNewJourney 40
lenPos 1847
I =  9472751
number of imo 2743
1847
===============
dfNewJourney 42
lenPos 0
I =  10007626
number of imo 2744
dfNewJourney 4
lenPos 0
I =  8806888
number of imo 2745
dfNewJourney 11
lenPos 1732
I =  9235725
number of imo 2746
1732
===============
dfNewJourney 24
lenPos 1667
I =  9239977
number of imo 2747
1667
===============
dfNewJourney 23
lenPos 1813
I =  9384459
number of imo 2748
1813
===============
dfNewJourney 17
lenPos 1266
I =  9168740
number of imo 2749
1266
===============
dfNewJourney 18
lenPos 0
I =  9191345
number of imo 2750
dfNewJourney 23
lenPos 1727
I =  9257802
number of imo 2751
1727
===============
dfNewJourney 20
lenPos 1691
I =  9171357
number of imo 2752
1691
===============
dfNewJourney 27
lenPos 0
I =  10015389
number of imo 2753
dfNewJourney 1
lenPos 1867
I =  9333682
number of imo 2754
1867
===============
dfNewJourney 32
lenPos 1688
I =  9261619
number of imo 2755
1688
===============
dfNewJourney 45
lenPos 1881
I =  9349198
number of imo 2756
1881
===============
dfNewJourney 6
lenPos 1872
I =  9392315
number of imo 2757
1872
===============
dfNewJourney 9
lenPos 1674
I =  9309980
number of imo 2758
1674

===============
dfNewJourney 13
lenPos 1852
I =  9305051
number of imo 2759
1852
===============
dfNewJourney 16
lenPos 1742
I =  9305532
number of imo 2760
1742
===============
dfNewJourney 27
lenPos 1793
I =  9306940
number of imo 2761
1793
===============
dfNewJourney 1
lenPos 0
I =  9053115
number of imo 2762
dfNewJourney 30
lenPos 1846
I =  9298662
number of imo 2763
1846
===============
dfNewJourney 16
lenPos 1662
I =  9270749
number of imo 2764
1662
===============
dfNewJourney 81
lenPos 0
I =  10015417
number of imo 2765
dfNewJourney 9
lenPos 1798
I =  9470959
number of imo 2766
1798
===============
dfNewJourney 3
lenPos 1721
I =  9357561
number of imo 2767
1721
===============
dfNewJourney 28
lenPos 1479
I =  9315446
number of imo 2768
1479
===============
dfNewJourney 21
lenPos 1849
I =  9265354
number of imo 2769
1849
===============
dfNewJourney 24
lenPos 1802
I =  9381847
number of imo 2770
1802
===============
dfNewJourney 25
lenPos 1489
I =  9149251
number of imo 2771
1489
===============
dfNewJourney 21
lenPos 1480
I =  9249178
number of imo 2772
1480
===============
dfNewJourney 27
lenPos 1831
I =  9255696
number of imo 2773
1831
===============
dfNewJourney 21
lenPos 1762
I =  9436018
number of imo 2774
1762
===============
dfNewJourney 35
lenPos 1713
I =  9451692
number of imo 2775
1713
===============
dfNewJourney 1
lenPos 734
I =  8420232
number of imo 2776
734
===============
dfNewJourney 16
lenPos 1827
I =  9291236
number of imo 2777
1827
===============
dfNewJourney 10
lenPos 1833
I =  9511387
number of imo 2778
1833
===============
dfNewJourney 21
lenPos 1781
I =  9414022
number of imo 2779
1781
===============
dfNewJourney 9
lenPos 1654
I =  9466142
number of imo 2780
1654
===============
dfNewJourney 8
lenPos 1301
I =  9111175
number of imo 2781
1301
===============
dfNewJourney 38
lenPos 0
I =  10015881
number of imo 2782
dfNewJourney 40
lenPos 1857
I =  9289518
number of imo 2783
1857
===============
dfNewJourney 4
lenPos 0
I =  10005215
number of imo 2784
dfNewJourney 37
lenPos 1860
I =  9402782
number of imo 2785
1860
===============
dfNewJourney 26
lenPos 1651
I =  9265756
number of imo 2786
1651
===============
dfNewJourney 35
lenPos 1791
I =  9337406
number of imo 2787
1791
===============
dfNewJourney 7
lenPos 1702
I =  9417323
number of imo 2788
1702
===============
dfNewJourney 23
lenPos 1781
I =  9262924
number of imo 2789
1781
===============
dfNewJourney 6
lenPos 1279
I =  9117480
number of imo 2790
1279
===============
dfNewJourney 4
lenPos 1456
I =  8121161
number of imo 2791
1456
===============
dfNewJourney 5
lenPos 0
I =  10007583
number of imo 2792
dfNewJourney 31
lenPos 1528
I =  9187667
number of imo 2793
1528
===============
dfNewJourney 4
lenPos 0
I =  10007570
number of imo 2794
dfNewJourney 10
lenPos 1757
I =  9316610
number of imo 2795
1757
===============
dfNewJourney 4
lenPos 1859
I =  9293997
number of imo 2796
1859
===============
dfNewJourney 28
lenPos 0
I =  10017882
number of imo 2797
dfNewJourney 32
lenPos 1805
I =  9299446
number of imo 2798
1805
===============
dfNewJourney 34
lenPos 1798
I =  9282998
number of imo 2799
1798
===============
dfNewJourney 25
lenPos 1769
I =  9423712
number of imo 2800
1769
===============
dfNewJourney 14
lenPos 1791
I =  9413016
number of imo 2801
1791
===============
dfNewJourney 5
lenPos 1521
I =  9038866
number of imo 2802
1521
===============
dfNewJourney 13
lenPos 0
I =  10015898
number of imo 2803
dfNewJourney 4
lenPos 0
I =  9040443
number of imo 2804
dfNewJourney 15
lenPos 1671
I =  9188776
number of imo 2805
1671
===============
dfNewJourney 8
lenPos 0
I =  10007593
number of imo 2806
dfNewJourney 4
lenPos 1603
I =  8617055
number of imo 2807
1603
===============
dfNewJourney 11
lenPos 1633
I =  9336426
number of imo 2808
1633
===============
dfNewJourney 23
lenPos 1755
I =  9356751
number of imo 2809
1755
===============
dfNewJourney 12
lenPos 1017
I =  9333254
number of imo 2810
1017
===============
dfNewJourney 4
lenPos 1868
I =  9372561
number of imo 2811
1868
===============
dfNewJourney 12
lenPos 0
I =  10022383
number of imo 2812
dfNewJourney 29
lenPos 0
I =  10017881
number of imo 2813
dfNewJourney 30
lenPos 1815
I =  9425502
number of imo 2814
1815
===============
dfNewJourney 27
lenPos 1530
I =  9308120
number of imo 2815
1530
===============
dfNewJourney 42
lenPos 0
I =  10027414
number of imo 2816
dfNewJourney 82
lenPos 0
I =  10015418
number of imo 2817
dfNewJourney 12
lenPos 1725
I =  9254915
number of imo 2818
1725
===============
dfNewJourney 25
lenPos 1737
I =  9260809
number of imo 2819
1737
===============
dfNewJourney 11
lenPos 0
I =  9187497
number of imo 2820
dfNewJourney 47
lenPos 0
I =  10029357
number of imo 2821
dfNewJourney 52
lenPos 1812
I =  9381562
number of imo 2822
1812
===============
dfNewJourney 2
lenPos 0
I =  9053660
number of imo 2823
dfNewJourney 26
lenPos 1877
I =  9309435
number of imo 2824
1877
===============
dfNewJourney 17
lenPos 1665
I =  9292204
number of imo 2825
1665
===============
dfNewJourney 18
lenPos 1763
I =  9111644
number of imo 2826
1763
===============
dfNewJourney 12
lenPos 1703
I =  9450789
number of imo 2827
1703
===============
dfNewJourney 39
lenPos 1802
I =  9461697
number of imo 2828
1802
===============
dfNewJourney 22
lenPos 1856
I =  9276016
number of imo 2829
1856
===============
dfNewJourney 24
lenPos 1808
I =  9274642
number of imo 2830
1808
===============
dfNewJourney 22
lenPos 1790
I =  9255660
number of imo 2831
1790
===============
dfNewJourney 10
lenPos 0
I =  9031961
number of imo 2832
dfNewJourney 9
lenPos 1820
I =  9247481
number of imo 2833
1820
===============
dfNewJourney 27
lenPos 1818
I =  9333424
number of imo 2834
1818
===============
dfNewJourney 42
lenPos 0
I =  10015329
number of imo 2835
dfNewJourney 18
lenPos 1626
I =  9259707
number of imo 2836
1626
===============
dfNewJourney 41
lenPos 1819
I =  9516222
number of imo 2837
1819
===============
dfNewJourney 22
lenPos 1721
I =  9379064
number of imo 2838
1721
===============
dfNewJourney 5
lenPos 0
I =  8225010
number of imo 2839
dfNewJourney 20
lenPos 1810
I =  9285744
number of imo 2840
1810
===============
dfNewJourney 34
lenPos 0
I =  10017879
number of imo 2841
dfNewJourney 8
lenPos 1866
I =  9321677
number of imo 2842
1866
===============
dfNewJourney 2
lenPos 0
I =  8904264
number of imo 2843
dfNewJourney 37
lenPos 1703
I =  9358319
number of imo 2844
1703
===============
dfNewJourney 45
lenPos 0
I =  10028913
number of imo 2845
dfNewJourney 1
lenPos 0
I =  10007582
number of imo 2846
dfNewJourney 39
lenPos 1767
I =  9387932
number of imo 2847
1767
===============
dfNewJourney 21
lenPos 1819
I =  9489924
number of imo 2848
1819
===============
dfNewJourney 3
lenPos 0
I =  9047362
number of imo 2849
dfNewJourney 19
lenPos 1846
I =  9297541
number of imo 2850
1846
===============
dfNewJourney 13
lenPos 0
I =  10022382
number of imo 2851
dfNewJourney 5
lenPos 1794
I =  9408114
number of imo 2852
1794
===============
dfNewJourney 17
lenPos 0
I =  9083316
number of imo 2853
dfNewJourney 11
lenPos 0
I =  9165530
number of imo 2854
dfNewJourney 24
lenPos 1503
I =  9308443
number of imo 2855
1503
===============
dfNewJourney 17
lenPos 0
I =  10022378
number of imo 2856
dfNewJourney 2
lenPos 701
I =  9167203
number of imo 2857
701
===============
dfNewJourney 5
lenPos 1464
I =  9509891
number of imo 2858
1464
===============
dfNewJourney 1
lenPos 1025
I =  9486910
number of imo 2859
1025
===============
dfNewJourney 21
lenPos 1691
I =  9149225
number of imo 2860
1691
===============
dfNewJourney 59
lenPos 0
I =  10015384
number of imo 2861
dfNewJourney 20
lenPos 1828
I =  9436020
number of imo 2862
1828
===============
dfNewJourney 5
lenPos 1560
I =  9253478
number of imo 2863
1560
===============
dfNewJourney 32
lenPos 1820
I =  9462897
number of imo 2864
1820
===============
dfNewJourney 4
lenPos 1813
I =  9249130
number of imo 2865
1813
===============
dfNewJourney 7
lenPos 1867
I =  9511521
number of imo 2866
1867
===============
dfNewJourney 20
lenPos 1840
I =  9297553
number of imo 2867
1840
===============
dfNewJourney 9
lenPos 1654
I =  9441178
number of imo 2868
1654
===============
dfNewJourney 11
lenPos 1579
I =  9198290
number of imo 2869
1579

===============
dfNewJourney 5
lenPos 1773
I =  9257814
number of imo 2870
1773
===============
dfNewJourney 34
lenPos 1835
I =  9322827
number of imo 2871
1835
===============
dfNewJourney 15
lenPos 0
I =  9171826
number of imo 2872
dfNewJourney 2
lenPos 1742
I =  9282821
number of imo 2873
1742
===============
dfNewJourney 9
lenPos 1678
I =  9303728
number of imo 2874
1678
===============
dfNewJourney 47
lenPos 0
I =  10022369
number of imo 2875
dfNewJourney 40
lenPos 0
I =  10022371
number of imo 2876
dfNewJourney 7
lenPos 1860
I =  9288693
number of imo 2877
1860
===============
dfNewJourney 16
lenPos 0
I =  10015746
number of imo 2878
dfNewJourney 33
lenPos 1873
I =  9274800
number of imo 2879
1873
===============
dfNewJourney 7
lenPos 1797
I =  9353096
number of imo 2880
1797
===============
dfNewJourney 22
lenPos 0
I =  10017880
number of imo 2881
dfNewJourney 24
lenPos 0
I =  10017878
number of imo 2882
dfNewJourney 23
lenPos 1738
I =  9251274
number of imo 2883
1738
===============
dfNewJourney 26
lenPos 1792
I =  9391517
number of imo 2884
1792
===============
dfNewJourney 32
lenPos 0
I =  10017873
number of imo 2885
dfNewJourney 11
lenPos 1699
I =  9236975
number of imo 2886
1699
===============
dfNewJourney 24
lenPos 1757
I =  9213296
number of imo 2887
1757
===============
dfNewJourney 8
lenPos 1858
I =  9288722
number of imo 2888
1858
===============
dfNewJourney 38
lenPos 0
I =  10015882
number of imo 2889
dfNewJourney 17
lenPos 1627
I =  9270529
number of imo 2890
1627
===============
dfNewJourney 11
lenPos 1833
I =  9391309
number of imo 2891
1833
===============
dfNewJourney 40
lenPos 0
I =  10017835
number of imo 2892
dfNewJourney 26
lenPos 1688
I =  9241073
number of imo 2893
1688
===============
dfNewJourney 4
lenPos 1791
I =  9260017
number of imo 2894
1791
===============
dfNewJourney 10
lenPos 0
I =  10022381
number of imo 2895
dfNewJourney 3
lenPos 0
I =  9074999
number of imo 2896
dfNewJourney 24
lenPos 0
I =  10022372
number of imo 2897
dfNewJourney 8
lenPos 1889
I =  9306641
number of imo 2898
1889
===============
dfNewJourney 4
lenPos 1881
I =  9255490
number of imo 2899
1881
===============
dfNewJourney 20
lenPos 0
I =  10007606
number of imo 2900
dfNewJourney 8
lenPos 1813
I =  9249128
number of imo 2901
1813
===============
dfNewJourney 23
lenPos 0
I =  9197739
number of imo 2902
dfNewJourney 43
lenPos 0
I =  10007640
number of imo 2903
dfNewJourney 40
lenPos 0
I =  10015717
number of imo 2904
dfNewJourney 37
lenPos 0
I =  10034411
number of imo 2905
dfNewJourney 30
lenPos 1785
I =  9419151
number of imo 2906
1785
===============
dfNewJourney 14
lenPos 1694
I =  9257010
number of imo 2907
1694
===============
dfNewJourney 22
lenPos 1697
I =  9118630
number of imo 2908
1697
===============
dfNewJourney 8
lenPos 1829
I =  9199713
number of imo 2909
1829
===============
dfNewJourney 18
lenPos 1737
I =  9302126
number of imo 2910
1737
===============
dfNewJourney 7
lenPos 0
I =  10022374
number of imo 2911
dfNewJourney 3
lenPos 1519
I =  9299496
number of imo 2912
1519
===============
dfNewJourney 40
lenPos 0
I =  10022370
number of imo 2913
dfNewJourney 50
lenPos 1708
I =  9447770
number of imo 2914
1708
===============
dfNewJourney 12
lenPos 1755
I =  9464364
number of imo 2915
1755
===============
dfNewJourney 31
lenPos 0
I =  10007662
number of imo 2916
dfNewJourney 10
lenPos 1885
I =  9299898
number of imo 2917
1885
===============
dfNewJourney 3
lenPos 1814
I =  9436692
number of imo 2918
1814
===============
dfNewJourney 16
lenPos 1461
I =  9187681
number of imo 2919
1461
===============
dfNewJourney 42
lenPos 0
I =  10015415
number of imo 2920
dfNewJourney 41
lenPos 0
I =  10022298
number of imo 2921
dfNewJourney 19
lenPos 1660
I =  9293155
number of imo 2922
1660
===============
dfNewJourney 16
lenPos 0
I =  10022373
number of imo 2923
dfNewJourney 28
lenPos 1801
I =  9172193
number of imo 2924
1801
===============
dfNewJourney 4
lenPos 1722
I =  9292278
number of imo 2925
1722
===============
dfNewJourney 1
lenPos 1183
I =  8619431
number of imo 2926
1183
===============
dfNewJourney 27
lenPos 1838
I =  9577109
number of imo 2927
1838
===============
dfNewJourney 32
lenPos 0
I =  10022362
number of imo 2928
dfNewJourney 28
lenPos 1855
I =  9322384
number of imo 2929
1855
===============
dfNewJourney 40
lenPos 0
I =  10017872
number of imo 2930
dfNewJourney 12
lenPos 1823
I =  9398723
number of imo 2931
1823
===============
dfNewJourney 27
lenPos 1812
I =  9298650
number of imo 2932
1812
===============
dfNewJourney 1
lenPos 0
I =  9006916
number of imo 2933
dfNewJourney 9
lenPos 1625
I =  9583299
number of imo 2934
1625
===============
dfNewJourney 2
lenPos 1890
I =  9305556
number of imo 2935
1890
===============
dfNewJourney 2
lenPos 0
I =  9158551
number of imo 2936
dfNewJourney 21
lenPos 1787
I =  9429182
number of imo 2937
1787
===============
dfNewJourney 12
lenPos 1828
I =  9293210
number of imo 2938
1828
===============
dfNewJourney 13
lenPos 1637
I =  9253595
number of imo 2939
1637
===============
dfNewJourney 28
lenPos 1816
I =  9354179
number of imo 2940
1816
===============
dfNewJourney 10
lenPos 1820
I =  9453987
number of imo 2941
1820
===============
dfNewJourney 25
lenPos 1655
I =  9281891
number of imo 2942
1655
===============
dfNewJourney 1
lenPos 1820
I =  9303699
number of imo 2943
1820
===============
dfNewJourney 3
lenPos 0
I =  8301814
number of imo 2944
dfNewJourney 14
lenPos 0
I =  10022380
number of imo 2945
dfNewJourney 36
lenPos 1820
I =  9360336
number of imo 2946
1820
===============
dfNewJourney 36
lenPos 0
I =  10028914
number of imo 2947
dfNewJourney 7
lenPos 1744
I =  9336397
number of imo 2948
1744
===============
dfNewJourney 3
lenPos 1740
I =  9283265
number of imo 2949
1740
===============
dfNewJourney 8
lenPos 0
I =  10007605
number of imo 2950
dfNewJourney 8
lenPos 1795
I =  9417012
number of imo 2951
1795
===============
dfNewJourney 9
lenPos 1156
I =  9085388
number of imo 2952
1156
===============
dfNewJourney 15
lenPos 1672
I =  9133068
number of imo 2953
1672
===============
dfNewJourney 16
lenPos 0
I =  10017836
number of imo 2954
dfNewJourney 16
lenPos 0
I =  10028116
number of imo 2955
dfNewJourney 24
lenPos 0
I =  10028816
number of imo 2956
dfNewJourney 1
lenPos 0
I =  8315138
number of imo 2957
dfNewJourney 2
lenPos 0
I =  9002154
number of imo 2958
dfNewJourney 15
lenPos 1237
I =  9247974
number of imo 2959
1237
===============
dfNewJourney 11
lenPos 1422
I =  9284594
number of imo 2960
1422
===============
dfNewJourney 4
lenPos 0
I =  9178331
number of imo 2961
dfNewJourney 36
lenPos 1616
I =  9489297
number of imo 2962
1616
===============
dfNewJourney 45
lenPos 0
I =  10015414
number of imo 2963
dfNewJourney 15
lenPos 1897
I =  9253753
number of imo 2964
1897
===============
dfNewJourney 60
lenPos 0
I =  10029038
number of imo 2965
dfNewJourney 37
lenPos 0
I =  10027415
number of imo 2966
dfNewJourney 4
lenPos 0
I =  9086344
number of imo 2967
dfNewJourney 11
lenPos 1873
I =  9381512
number of imo 2968
1873
===============
dfNewJourney 44
lenPos 1800
I =  9390927
number of imo 2969
1800
===============
dfNewJourney 45
lenPos 0
I =  10022368
number of imo 2970
dfNewJourney 8
lenPos 1731
I =  9422835
number of imo 2971
1731
===============
dfNewJourney 20
lenPos 1803
I =  9315769
number of imo 2972
1803
===============
dfNewJourney 30
lenPos 1616
I =  9406348
number of imo 2973
1616
===============
dfNewJourney 38
lenPos 0
I =  10034410
number of imo 2974
dfNewJourney 12
lenPos 1871
I =  9299903
number of imo 2975
1871
===============
dfNewJourney 20
lenPos 1533
I =  9136058
number of imo 2976
1533
===============
dfNewJourney 7
lenPos 1721
I =  9249104
number of imo 2977
1721
===============
dfNewJourney 37
lenPos 1778
I =  9536820
number of imo 2978
1778
===============
dfNewJourney 32
lenPos 1770
I =  9299769
number of imo 2979
1770
===============
dfNewJourney 35
lenPos 0
I =  10017877
number of imo 2980
dfNewJourney 34
lenPos 1607
I =  9307932
number of imo 2981
1607
===============
dfNewJourney 23
lenPos 1294
I =  9256860
number of imo 2982
1294
===============
dfNewJourney 13
lenPos 1751
I =  9329667
number of imo 2983
1751
===============
dfNewJourney 11
lenPos 1543
I =  9210919
number of imo 2984
1543

===============
dfNewJourney 44
lenPos 0
I =  10029359
number of imo 2985
dfNewJourney 6
lenPos 1546
I =  9084516
number of imo 2986
1546
===============
dfNewJourney 6
lenPos 1876
I =  9208112
number of imo 2987
1876
===============
dfNewJourney 62
lenPos 0
I =  10015419
number of imo 2988
dfNewJourney 5
lenPos 1471
I =  9117492
number of imo 2989
1471
===============
dfNewJourney 32
lenPos 0
I =  10017876
number of imo 2990
dfNewJourney 15
lenPos 0
I =  10015747
number of imo 2991
dfNewJourney 5
lenPos 1591
I =  9116371
number of imo 2992
1591
===============
dfNewJourney 38
lenPos 0
I =  10017861
number of imo 2993
dfNewJourney 4
lenPos 1736
I =  9251676
number of imo 2994
1736
===============
dfNewJourney 23
lenPos 1840
I =  9568172
number of imo 2995
1840
===============
dfNewJourney 14
lenPos 1765
I =  9356244
number of imo 2996
1765
===============
dfNewJourney 39
lenPos 0
I =  10029358
number of imo 2997
dfNewJourney 4
lenPos 0
I =  8912613
number of imo 2998
dfNewJourney 1
lenPos 1711
I =  9047398
number of imo 2999
1711
===============
dfNewJourney 45
lenPos 0
I =  10022361
number of imo 3000
dfNewJourney 4
lenPos 1692
I =  9312602
number of imo 3001
1692
===============
dfNewJourney 4
lenPos 0
I =  9180267
number of imo 3002
dfNewJourney 4
lenPos 1842
I =  9372559
number of imo 3003
1842
===============
dfNewJourney 22
lenPos 1812
I =  9325348
number of imo 3004
1812
===============
dfNewJourney 3
lenPos 1696
I =  9509035
number of imo 3005
1696
===============
dfNewJourney 29
lenPos 1745
I =  9282625
number of imo 3006
1745
===============
dfNewJourney 39
lenPos 0
I =  10015592
number of imo 3007
dfNewJourney 25
lenPos 1644
I =  9188477
number of imo 3008
1644
===============
dfNewJourney 9
lenPos 1735
I =  9417000
number of imo 3009
1735
===============
dfNewJourney 32
lenPos 1820
I =  9297321
number of imo 3010
1820
===============
dfNewJourney 5
lenPos 1861
I =  9314820
number of imo 3011
1861
===============
dfNewJourney 45
lenPos 0
I =  10028915
number of imo 3012
dfNewJourney 26
lenPos 1480
I =  9105906
number of imo 3013
1480
===============
dfNewJourney 41
lenPos 0
I =  10023545
number of imo 3014
dfNewJourney 9
lenPos 0
I =  10028072
number of imo 3015
dfNewJourney 25
lenPos 1822
I =  9407457
number of imo 3016
1822
===============
dfNewJourney 13
lenPos 1781
I =  9236755
number of imo 3017
1781
===============
dfNewJourney 10
lenPos 1819
I =  9204764
number of imo 3018
1819
===============
dfNewJourney 40
lenPos 0
I =  10022367
number of imo 3019
dfNewJourney 7
lenPos 1819
I =  9293973
number of imo 3020
1819
===============
dfNewJourney 9
lenPos 0
I =  10028117
number of imo 3021
dfNewJourney 22
lenPos 1851
I =  9461673
number of imo 3022
1851
===============
dfNewJourney 18
lenPos 0
I =  10022375
number of imo 3023
dfNewJourney 1
lenPos 0
I =  9044487
number of imo 3024
dfNewJourney 18
lenPos 1717
I =  9223318
number of imo 3025
1717
===============
dfNewJourney 5
lenPos 1540
I =  9235000
number of imo 3026
1540
===============
dfNewJourney 6
lenPos 1771
I =  9197715
number of imo 3027
1771
===============
dfNewJourney 41
lenPos 0
I =  10017862
number of imo 3028
dfNewJourney 2
lenPos 1832
I =  9242443
number of imo 3029
1832
===============
dfNewJourney 40
lenPos 0
I =  10023541
number of imo 3030
dfNewJourney 11
lenPos 1872
I =  9314806
number of imo 3031
1872
===============
dfNewJourney 11
lenPos 1742
I =  9310525
number of imo 3032
1742
===============
dfNewJourney 35
lenPos 0
I =  10028088
number of imo 3033
dfNewJourney 1
lenPos 719
I =  8623937
number of imo 3034
719
===============
dfNewJourney 28
lenPos 1882
I =  9276585
number of imo 3035
1882
===============
dfNewJourney 11
lenPos 1846
I =  9314832
number of imo 3036
1846
===============
dfNewJourney 37
lenPos 0
I =  10028089
number of imo 3037
dfNewJourney 13
lenPos 1457
I =  9292979
number of imo 3038
1457
===============
dfNewJourney 12
lenPos 1875
I =  9290505
number of imo 3039
1875
===============
dfNewJourney 3
lenPos 1736
I =  9435583
number of imo 3040
1736
===============
dfNewJourney 3
lenPos 0
I =  9116917
number of imo 3041
dfNewJourney 33
lenPos 0
I =  10022377
number of imo 3042
dfNewJourney 2
lenPos 1841
I =  9384112
number of imo 3043
1841
===============
dfNewJourney 7
lenPos 1788
I =  9322944
number of imo 3044
1788
===============
dfNewJourney 21
lenPos 1641
I =  9396725
number of imo 3045
1641
===============
dfNewJourney 16
lenPos 1886
I =  9298777
number of imo 3046
1886
===============
dfNewJourney 13
lenPos 1590
I =  9322449
number of imo 3047
1590
===============
dfNewJourney 5
lenPos 0
I =  10004586
number of imo 3048
dfNewJourney 35
lenPos 0
I =  10029360
number of imo 3049
dfNewJourney 9
lenPos 0
I =  10027005
number of imo 3050
dfNewJourney 10
lenPos 1710
I =  9259927
number of imo 3051
1710
===============
dfNewJourney 33
lenPos 0
I =  10022376
number of imo 3052
dfNewJourney 17
lenPos 0
I =  10027006
number of imo 3053
dfNewJourney 5
lenPos 1403
I =  9301732
number of imo 3054
1403
===============
dfNewJourney 3
lenPos 1452
I =  9283746
number of imo 3055
1452
===============
dfNewJourney 13
lenPos 1828
I =  9365283
number of imo 3056
1828
===============
dfNewJourney 35
lenPos 0
I =  10017871
number of imo 3057
dfNewJourney 26
lenPos 1494
I =  9411290
number of imo 3058
1494
===============
dfNewJourney 30
lenPos 1828
I =  9276573
number of imo 3059
1828
===============
dfNewJourney 8
lenPos 1733
I =  9120944
number of imo 3060
1733
===============
dfNewJourney 29
lenPos 0
I =  10017875
number of imo 3061
dfNewJourney 46
lenPos 0
I =  10022291
number of imo 3062
dfNewJourney 32
lenPos 0
I =  10023348
number of imo 3063
dfNewJourney 6
lenPos 1826
I =  9299410
number of imo 3064
1826
===============
dfNewJourney 6
lenPos 1862
I =  9256066
number of imo 3065
1862
===============
dfNewJourney 6
lenPos 1762
I =  9169548
number of imo 3066
1762
===============
dfNewJourney 4
lenPos 0
I =  9075008
number of imo 3067
dfNewJourney 35
lenPos 1541
I =  9281566
number of imo 3068
1541
===============
dfNewJourney 39
lenPos 0
I =  10006827
number of imo 3069
dfNewJourney 8
lenPos 1711
I =  9306794
number of imo 3070
1711
===============
dfNewJourney 4
lenPos 1690
I =  9435296
number of imo 3071
1690
===============
dfNewJourney 6
lenPos 1808
I =  9301421
number of imo 3072
1808
===============
dfNewJourney 8
lenPos 1710
I =  9301380
number of imo 3073
1710
===============
dfNewJourney 20
lenPos 1573
I =  9295036
number of imo 3074
1573
===============
dfNewJourney 8
lenPos 1846
I =  9299862
number of imo 3075
1846
===============
dfNewJourney 8
lenPos 1713
I =  9192741
number of imo 3076
1713
===============
dfNewJourney 25
lenPos 0
I =  10017870
number of imo 3077
dfNewJourney 16
lenPos 0
I =  10028118
number of imo 3078
dfNewJourney 41
lenPos 0
I =  10023544
number of imo 3079
dfNewJourney 4
lenPos 0
I =  10035126
number of imo 3080
dfNewJourney 27
lenPos 1702
I =  9116905
number of imo 3081
1702
===============
dfNewJourney 11
lenPos 1521
I =  9167136
number of imo 3082
1521
===============
dfNewJourney 30
lenPos 1674
I =  9232618
number of imo 3083
1674
===============
dfNewJourney 22
lenPos 0
I =  10028815
number of imo 3084
dfNewJourney 6
lenPos 1421
I =  9509918
number of imo 3085
1421
===============
dfNewJourney 4
lenPos 1821
I =  9286059
number of imo 3086
1821
===============
dfNewJourney 35
lenPos 1846
I =  9319545
number of imo 3087
1846
===============
dfNewJourney 1
lenPos 0
I =  8300808
number of imo 3088
dfNewJourney 7
lenPos 1737
I =  9278480
number of imo 3089
1737
===============
dfNewJourney 2
lenPos 1277
I =  9298820
number of imo 3090
1277
===============
dfNewJourney 38
lenPos 0
I =  10023542
number of imo 3091
dfNewJourney 30
lenPos 0
I =  10015718
number of imo 3092
dfNewJourney 32
lenPos 0
I =  10029844
number of imo 3093
dfNewJourney 35
lenPos 0
I =  10022365
number of imo 3094
dfNewJourney 1
lenPos 1784
I =  9566356
number of imo 3095
1784
===============
dfNewJourney 2
lenPos 1843
I =  9436680
number of imo 3096
1843
===============
dfNewJourney 43
lenPos 0
I =  10023543
number of imo 3097
dfNewJourney 3
lenPos 1709
I =  9220914
number of imo 3098
1709
===============
dfNewJourney 9
lenPos 1776
I =  9420863
number of imo 3099
1776

===============
dfNewJourney 6
lenPos 1762
I =  9564578
number of imo 3100
1762
===============
dfNewJourney 1
lenPos 1796
I =  9251432
number of imo 3101
1796
===============
dfNewJourney 16
lenPos 1821
I =  9453963
number of imo 3102
1821
===============
dfNewJourney 13
lenPos 1697
I =  9306665
number of imo 3103
1697
===============
dfNewJourney 38
lenPos 0
I =  10023349
number of imo 3104
dfNewJourney 8
lenPos 1662
I =  9301299
number of imo 3105
1662
===============
dfNewJourney 3
lenPos 1772
I =  9171321
number of imo 3106
1772
===============
dfNewJourney 2
lenPos 1435
I =  9416381
number of imo 3107
1435
===============
dfNewJourney 6
lenPos 1666
I =  9323596
number of imo 3108
1666
===============
dfNewJourney 37
lenPos 0
I =  10029846
number of imo 3109
dfNewJourney 13
lenPos 0
I =  10028119
number of imo 3110
dfNewJourney 6
lenPos 1851
I =  9255517
number of imo 3111
1851
===============
dfNewJourney 1
lenPos 0
I =  9006136
number of imo 3112
dfNewJourney 28
lenPos 1846
I =  9306574
number of imo 3113
1846
===============
dfNewJourney 27
lenPos 1647
I =  9314105
number of imo 3114
1647
===============
dfNewJourney 2
lenPos 1399
I =  8917467
number of imo 3115
1399
===============
dfNewJourney 18
lenPos 0
I =  10017869
number of imo 3116
dfNewJourney 8
lenPos 0
I =  9169718
number of imo 3117
dfNewJourney 11
lenPos 1725
I =  9189110
number of imo 3118
1725
===============
dfNewJourney 2
lenPos 1672
I =  9192753
number of imo 3119
1672
===============
dfNewJourney 4
lenPos 0
I =  9174579
number of imo 3120
dfNewJourney 33
lenPos 0
I =  10029642
number of imo 3121
dfNewJourney 38
lenPos 0
I =  10022366
number of imo 3122
dfNewJourney 8
lenPos 1791
I =  9380673
number of imo 3123
1791
===============
dfNewJourney 31
lenPos 0
I =  10029020
number of imo 3124
dfNewJourney 40
lenPos 0
I =  10015593
number of imo 3125
dfNewJourney 2
lenPos 0
I =  10006208
number of imo 3126
dfNewJourney 8
lenPos 0
I =  10028903
number of imo 3127
dfNewJourney 14
lenPos 0
I =  10028902
number of imo 3128
dfNewJourney 31
lenPos 0
I =  10017868
number of imo 3129
dfNewJourney 31
lenPos 0
I =  10029842
number of imo 3130
dfNewJourney 2
lenPos 0
I =  9181003
number of imo 3131
dfNewJourney 31
lenPos 0
I =  10027330
number of imo 3132
dfNewJourney 31
lenPos 0
I =  10022364
number of imo 3133
dfNewJourney 22
lenPos 0
I =  10027872
number of imo 3134
dfNewJourney 14
lenPos 0
I =  9127411
number of imo 3135
dfNewJourney 4
lenPos 1183
I =  9222699
number of imo 3136
1183
===============
dfNewJourney 3
lenPos 0
I =  10015874
number of imo 3137
dfNewJourney 4
lenPos 0
I =  10029543
number of imo 3138
dfNewJourney 18
lenPos 1721
I =  9123192
number of imo 3139
1721
===============
dfNewJourney 33
lenPos 0
I =  10022292
number of imo 3140
dfNewJourney 5
lenPos 1103
I =  9275256
number of imo 3141
1103
===============
dfNewJourney 30
lenPos 0
I =  10015669
number of imo 3142
dfNewJourney 36
lenPos 0
I =  10029091
number of imo 3143
dfNewJourney 37
lenPos 0
I =  10027608
number of imo 3144
dfNewJourney 2
lenPos 1735
I =  9259757
number of imo 3145
1735
===============
dfNewJourney 8
lenPos 1582
I =  9266475
number of imo 3146
1582
===============
dfNewJourney 31
lenPos 0
I =  10029018
number of imo 3147
dfNewJourney 16
lenPos 1831
I =  9340582
number of imo 3148
1831
===============
dfNewJourney 4
lenPos 0
I =  8309567
number of imo 3149
dfNewJourney 2
lenPos 0
I =  8808537
number of imo 3150
dfNewJourney 34
lenPos 0
I =  10028798
number of imo 3151
dfNewJourney 13
lenPos 1879
I =  9339337
number of imo 3152
1879
===============
dfNewJourney 37
lenPos 0
I =  10015668
number of imo 3153
dfNewJourney 10
lenPos 1666
I =  9248796
number of imo 3154
1666
===============
dfNewJourney 37
lenPos 0
I =  10007580
number of imo 3155
dfNewJourney 4
lenPos 1837
I =  9298703
number of imo 3156
1837
===============
dfNewJourney 33
lenPos 0
I =  10023546
number of imo 3157
dfNewJourney 40
lenPos 0
I =  10029039
number of imo 3158
dfNewJourney 1
lenPos 0
I =  9045376
number of imo 3159
dfNewJourney 7
lenPos 1803
I =  9208100
number of imo 3160
1803
===============
dfNewJourney 13
lenPos 1825
I =  9353527
number of imo 3161
1825
===============
dfNewJourney 43
lenPos 1812
I =  9329758
number of imo 3162
1812
===============
dfNewJourney 42
lenPos 0
I =  10027871
number of imo 3163
dfNewJourney 2
lenPos 0
I =  8913588
number of imo 3164
dfNewJourney 3
lenPos 0
I =  8301826
number of imo 3165
dfNewJourney 30
lenPos 0
I =  10027329
number of imo 3166
dfNewJourney 10
lenPos 1862
I =  9353137
number of imo 3167
1862
===============
dfNewJourney 5
lenPos 1832
I =  9241803
number of imo 3168
1832
===============
dfNewJourney 5
lenPos 0
I =  10028073
number of imo 3169
dfNewJourney 15
lenPos 1854
I =  9353101
number of imo 3170
1854
===============
dfNewJourney 9
lenPos 1421
I =  9212412
number of imo 3171
1421
===============
dfNewJourney 41
lenPos 0
I =  10034405
number of imo 3172
dfNewJourney 2
lenPos 1875
I =  9238052
number of imo 3173
1875
===============
dfNewJourney 44
lenPos 0
I =  10029361
number of imo 3174
dfNewJourney 33
lenPos 0
I =  10029024
number of imo 3175
dfNewJourney 10
lenPos 1549
I =  9249180
number of imo 3176
1549
===============
dfNewJourney 1
lenPos 1293
I =  9080508
number of imo 3177
1293
===============
dfNewJourney 31
lenPos 0
I =  10029019
number of imo 3178
dfNewJourney 4
lenPos 1547
I =  9198305
number of imo 3179
1547
===============
dfNewJourney 40
lenPos 0
I =  10027609
number of imo 3180
dfNewJourney 40
lenPos 0
I =  10015594
number of imo 3181
dfNewJourney 13
lenPos 1803
I =  9472622
number of imo 3182
1803
===============
dfNewJourney 11
lenPos 1842
I =  9304368
number of imo 3183
1842
===============
dfNewJourney 8
lenPos 1883
I =  9131371
number of imo 3184
1883
===============
dfNewJourney 10
lenPos 1842
I =  9321689
number of imo 3185
1842
===============
dfNewJourney 32
lenPos 0
I =  10030198
number of imo 3186
dfNewJourney 2
lenPos 0
I =  10015875
number of imo 3187
dfNewJourney 33
lenPos 0
I =  10029843
number of imo 3188
dfNewJourney 4
lenPos 1619
I =  9509906
number of imo 3189
1619
===============
dfNewJourney 39
lenPos 0
I =  10028799
number of imo 3190
dfNewJourney 34
lenPos 0
I =  10044264
number of imo 3191
dfNewJourney 45
lenPos 0
I =  10031827
number of imo 3192
dfNewJourney 20
lenPos 1865
I =  9524994
number of imo 3193
1865
===============
dfNewJourney 3
lenPos 1809
I =  9231690
number of imo 3194
1809
===============
dfNewJourney 34
lenPos 0
I =  10029016
number of imo 3195
dfNewJourney 31
lenPos 0
I =  10029090
number of imo 3196
dfNewJourney 1
lenPos 1859
I =  9315903
number of imo 3197
1859
===============
dfNewJourney 5
lenPos 0
I =  10035127
number of imo 3198
dfNewJourney 28
lenPos 0
I =  10027418
number of imo 3199
dfNewJourney 1
lenPos 0
I =  10007654
number of imo 3200
dfNewJourney 5
lenPos 1083
I =  8103420
number of imo 3201
1083
===============
dfNewJourney 2
lenPos 1881
I =  9039121
number of imo 3202
1881
===============
dfNewJourney 17
lenPos 0
I =  10029542
number of imo 3203
dfNewJourney 1
lenPos 0
I =  8618920
number of imo 3204
dfNewJourney 33
lenPos 0
I =  10029362
number of imo 3205
dfNewJourney 37
lenPos 0
I =  10029847
number of imo 3206
dfNewJourney 4
lenPos 1619
I =  8916255
number of imo 3207
1619
FEJL HER:
91.0 181.0 11.64813 43.181309999999996
FEJL HER:
91.0 181.0 0 0
FEJL HER:
91.0 181.0 91.0 181.0
FEJL HER:
91.0 181.0 0 0
FEJL HER:
91.0 181.0 91.0 181.0
FEJL HER:
91.0 181.0 0 0
FEJL HER:
91.0 181.0 91.0 181.0
FEJL HER:
91.0 181.0 0 0
FEJL HER:
13.408129999999998 42.8668 91.0 181.0
FEJL HER:
91.0 181.0 11.64813 43.181309999999996
FEJL HER:
91.0 181.0 0 0
FEJL HER:
91.0 181.0 91.0 181.0
FEJL HER:
91.0 181.0 0 0
FEJL HER:
91.0 181.0 91.0 181.0
FEJL HER:
91.0 181.0 0 0
FEJL HER:
91.0 181.0 91.0 181.0
FEJL HER:
91.0 181.0 0 0
FEJL HER:
13.408129999999998 42.8668 91.0 181.0
===============
dfNewJourney 26
lenPos 0
I =  10032951
number of imo 3208
dfNewJourney 33
lenPos 0
I =  10029023
number of imo 3209
dfNewJourney 30
lenPos 0
I =  10027416
number of imo 3210
dfNewJourney 30
lenPos 0
I =  10022297
number of imo 3211
dfNewJourney 32
lenPos 0
I =  10028900
number of imo 3212
dfNewJourney 44
lenPos 1839
I =  9292620
number of imo 3213
1839

===============
dfNewJourney 7
lenPos 1690
I =  9396323
number of imo 3214
1690
===============
dfNewJourney 1
lenPos 0
I =  8706088
number of imo 3215
dfNewJourney 36
lenPos 0
I =  10028524
number of imo 3216
dfNewJourney 3
lenPos 1807
I =  9220940
number of imo 3217
1807
===============
dfNewJourney 35
lenPos 0
I =  10028904
number of imo 3218
dfNewJourney 41
lenPos 0
I =  10029015
number of imo 3219
dfNewJourney 35
lenPos 0
I =  10029530
number of imo 3220
dfNewJourney 36
lenPos 0
I =  10027873
number of imo 3221
dfNewJourney 34
lenPos 0
I =  10029845
number of imo 3222
dfNewJourney 4
lenPos 1763
I =  9422201
number of imo 3223
1763
===============
dfNewJourney 32
lenPos 0
I =  10028070
number of imo 3224
dfNewJourney 3
lenPos 1566
I =  9295062
number of imo 3225
1566
===============
dfNewJourney 6
lenPos 1747
I =  9254903
number of imo 3226
1747
===============
dfNewJourney 12
lenPos 1824
I =  9420760
number of imo 3227
1824
===============
dfNewJourney 22
lenPos 0
I =  10007663
number of imo 3228
dfNewJourney 33
lenPos 0
I =  10029848
number of imo 3229
dfNewJourney 4
lenPos 1788
I =  9438858
number of imo 3230
1788
===============
dfNewJourney 42
lenPos 0
I =  10036459
number of imo 3231
dfNewJourney 11
lenPos 0
I =  10017866
number of imo 3232
dfNewJourney 30
lenPos 0
I =  10029092
number of imo 3233
dfNewJourney 32
lenPos 0
I =  10035017
number of imo 3234
dfNewJourney 58
lenPos 0
I =  10031826
number of imo 3235
dfNewJourney 1
lenPos 0
I =  8601836
number of imo 3236
dfNewJourney 32
lenPos 0
I =  10028525
number of imo 3237
dfNewJourney 26
lenPos 1579
I =  9337327
number of imo 3238
1579
===============
dfNewJourney 1
lenPos 0
I =  8308238
number of imo 3239
dfNewJourney 31
lenPos 0
I =  10046346
number of imo 3240
dfNewJourney 33
lenPos 0
I =  10022391
number of imo 3241
dfNewJourney 23
lenPos 0
I =  10006828
number of imo 3242
dfNewJourney 10
lenPos 1733
I =  9430179
number of imo 3243
1733
===============
dfNewJourney 30
lenPos 0
I =  10029093
number of imo 3244
dfNewJourney 7
lenPos 1734
I =  9353553
number of imo 3245
1734
===============
dfNewJourney 25
lenPos 0
I =  10035009
number of imo 3246
dfNewJourney 12
lenPos 1375
I =  9288277
number of imo 3247
1375
===============
dfNewJourney 38
lenPos 0
I =  10028402
number of imo 3248
dfNewJourney 31
lenPos 0
I =  10027328
number of imo 3249
dfNewJourney 15
lenPos 1845
I =  9587817
number of imo 3250
1845
===============
dfNewJourney 8
lenPos 0
I =  10027417
number of imo 3251
dfNewJourney 3
lenPos 1742
I =  9103843
number of imo 3252
1742
===============
dfNewJourney 34
lenPos 0
I =  10028905
number of imo 3253
dfNewJourney 30
lenPos 0
I =  10028084
number of imo 3254
dfNewJourney 2
lenPos 0
I =  9162033
number of imo 3255
dfNewJourney 35
lenPos 0
I =  10029816
number of imo 3256
dfNewJourney 33
lenPos 0
I =  10030530
number of imo 3257
dfNewJourney 31
lenPos 0
I =  10028901
number of imo 3258
dfNewJourney 35
lenPos 0
I =  10029815
number of imo 3259
dfNewJourney 32
lenPos 0
I =  10028071
number of imo 3260
dfNewJourney 33
lenPos 0
I =  10015595
number of imo 3261
dfNewJourney 4
lenPos 1701
I =  9279721
number of imo 3262
1701
===============
dfNewJourney 36
lenPos 0
I =  10029835
number of imo 3263
dfNewJourney 33
lenPos 0
I =  10030197
number of imo 3264
dfNewJourney 2
lenPos 1887
I =  9299941
number of imo 3265
1887
===============
dfNewJourney 39
lenPos 0
I =  10023325
number of imo 3266
dfNewJourney 18
lenPos 0
I =  10032952
number of imo 3267
dfNewJourney 8
lenPos 0
I =  9144017
number of imo 3268
dfNewJourney 29
lenPos 0
I =  10027419
number of imo 3269
dfNewJourney 37
lenPos 0
I =  10036460
number of imo 3270
dfNewJourney 15
lenPos 0
I =  10017867
number of imo 3271
dfNewJourney 3
lenPos 1097
I =  9030591
number of imo 3272
1097
===============
dfNewJourney 56
lenPos 0
I =  10023326
number of imo 3273
dfNewJourney 7
lenPos 0
I =  10015412
number of imo 3274
dfNewJourney 16
lenPos 0
I =  10033509
number of imo 3275
dfNewJourney 28
lenPos 0
I =  10029017
number of imo 3276
dfNewJourney 24
lenPos 0
I =  10027420
number of imo 3277
dfNewJourney 31
lenPos 0
I =  10029849
number of imo 3278
dfNewJourney 29
lenPos 0
I =  10033234
number of imo 3279
dfNewJourney 1
lenPos 1286
I =  9181857
number of imo 3280
1286
===============
dfNewJourney 29
lenPos 0
I =  10006829
number of imo 3281
dfNewJourney 27
lenPos 0
I =  10027874
number of imo 3282
dfNewJourney 3
lenPos 0
I =  9077331
number of imo 3283
dfNewJourney 7
lenPos 1589
I =  9226011
number of imo 3284
1589
===============
dfNewJourney 36
lenPos 0
I =  10029188
number of imo 3285
dfNewJourney 28
lenPos 0
I =  10015670
number of imo 3286
dfNewJourney 8
lenPos 1799
I =  9339313
number of imo 3287
1799
===============
dfNewJourney 33
lenPos 0
I =  10030527
number of imo 3288
dfNewJourney 18
lenPos 0
I =  10029529
number of imo 3289
dfNewJourney 37
lenPos 0
I =  10028879
number of imo 3290
dfNewJourney 8
lenPos 1103
I =  8801527
number of imo 3291
1103
===============
dfNewJourney 29
lenPos 0
I =  10017865
number of imo 3292
dfNewJourney 31
lenPos 0
I =  10036486
number of imo 3293
dfNewJourney 34
lenPos 0
I =  10035018
number of imo 3294
dfNewJourney 4
lenPos 1825
I =  9286047
number of imo 3295
1825
===============
dfNewJourney 20
lenPos 0
I =  10027875
number of imo 3296
dfNewJourney 28
lenPos 0
I =  10030200
number of imo 3297
dfNewJourney 9
lenPos 0
I =  10031069
number of imo 3298
dfNewJourney 31
lenPos 0
I =  10029094
number of imo 3299
dfNewJourney 31
lenPos 0
I =  10030528
number of imo 3300
dfNewJourney 30
lenPos 0
I =  10029818
number of imo 3301
dfNewJourney 30
lenPos 0
I =  10029022
number of imo 3302
dfNewJourney 14
lenPos 1765
I =  9294123
number of imo 3303
1765
===============
dfNewJourney 1
lenPos 0
I =  10007651
number of imo 3304
dfNewJourney 24
lenPos 0
I =  10027421
number of imo 3305
dfNewJourney 55
lenPos 0
I =  10050838
number of imo 3306
dfNewJourney 20
lenPos 0
I =  9174672
number of imo 3307
dfNewJourney 18
lenPos 1846
I =  9301005
number of imo 3308
1846
===============
dfNewJourney 8
lenPos 1771
I =  9439400
number of imo 3309
1771
===============
dfNewJourney 25
lenPos 0
I =  10022392
number of imo 3310
dfNewJourney 22
lenPos 0
I =  10028085
number of imo 3311
dfNewJourney 28
lenPos 0
I =  10029834
number of imo 3312
dfNewJourney 29
lenPos 0
I =  10028526
number of imo 3313
dfNewJourney 15
lenPos 1800
I =  9439204
number of imo 3314
1800
===============
dfNewJourney 9
lenPos 0
I =  10044266
number of imo 3315
dfNewJourney 13
lenPos 1693
I =  9250907
number of imo 3316
1693
===============
dfNewJourney 2
lenPos 0
I =  10007572
number of imo 3317
dfNewJourney 18
lenPos 0
I =  10027327
number of imo 3318
dfNewJourney 35
lenPos 0
I =  10030529
number of imo 3319
dfNewJourney 24
lenPos 0
I =  10033507
number of imo 3320
dfNewJourney 36
lenPos 0
I =  10030856
number of imo 3321
dfNewJourney 13
lenPos 0
I =  10033508
number of imo 3322
dfNewJourney 34
lenPos 0
I =  10018384
number of imo 3323
dfNewJourney 28
lenPos 0
I =  10028090
number of imo 3324
dfNewJourney 4
lenPos 1861
I =  9298739
number of imo 3325
1861
===============
dfNewJourney 1
lenPos 1553
I =  9198082
number of imo 3326
1553
===============
dfNewJourney 34
lenPos 1735
I =  9580417
number of imo 3327
1735
===============
dfNewJourney 28
lenPos 0
I =  10033237
number of imo 3328
dfNewJourney 17
lenPos 0
I =  10035118
number of imo 3329
dfNewJourney 32
lenPos 0
I =  10029975
number of imo 3330
dfNewJourney 27
lenPos 0
I =  10033236
number of imo 3331
dfNewJourney 33
lenPos 0
I =  10031605
number of imo 3332
dfNewJourney 33
lenPos 0
I =  10027422
number of imo 3333
dfNewJourney 1
lenPos 1428
I =  7396238
number of imo 3334
1428
===============
dfNewJourney 10
lenPos 0
I =  10029541
number of imo 3335
dfNewJourney 27
lenPos 0
I =  10056501
number of imo 3336
dfNewJourney 8
lenPos 1817
I =  9322956
number of imo 3337
1817
===============
dfNewJourney 3
lenPos 0
I =  8706090
number of imo 3338
dfNewJourney 3
lenPos 1865
I =  9298727
number of imo 3339
1865
===============
dfNewJourney 2
lenPos 1814
I =  9063108
number of imo 3340
1814
===============
dfNewJourney 29
lenPos 0
I =  10029644
number of imo 3341
dfNewJourney 31
lenPos 0
I =  10027423
number of imo 3342
dfNewJourney 13
lenPos 1860
I =  9380594
number of imo 3343
1860

===============
dfNewJourney 11
lenPos 0
I =  10028880
number of imo 3344
dfNewJourney 6
lenPos 1729
I =  9341067
number of imo 3345
1729
===============
dfNewJourney 2
lenPos 1636
I =  9038828
number of imo 3346
1636
===============
dfNewJourney 39
lenPos 0
I =  10036461
number of imo 3347
dfNewJourney 1
lenPos 0
I =  8002030
number of imo 3348
dfNewJourney 2
lenPos 1769
I =  9283277
number of imo 3349
1769
===============
dfNewJourney 28
lenPos 0
I =  10030199
number of imo 3350
dfNewJourney 35
lenPos 0
I =  10029189
number of imo 3351
dfNewJourney 9
lenPos 0
I =  9103829
number of imo 3352
dfNewJourney 8
lenPos 1840
I =  9377652
number of imo 3353
1840
===============
dfNewJourney 1
lenPos 1842
I =  9344837
number of imo 3354
1842
===============
dfNewJourney 6
lenPos 1830
I =  9260081
number of imo 3355
1830
===============
dfNewJourney 3
lenPos 0
I =  8917455
number of imo 3356
dfNewJourney 32
lenPos 0
I =  10028091
number of imo 3357
dfNewJourney 30
lenPos 0
I =  10029089
number of imo 3358
dfNewJourney 5
lenPos 0
I =  10030181
number of imo 3359
dfNewJourney 27
lenPos 0
I =  10029533
number of imo 3360
dfNewJourney 21
lenPos 0
I =  10029534
number of imo 3361
dfNewJourney 11
lenPos 0
I =  10028083
number of imo 3362
dfNewJourney 33
lenPos 0
I =  10029540
number of imo 3363
dfNewJourney 21
lenPos 0
I =  10028086
number of imo 3364
dfNewJourney 27
lenPos 0
I =  10033235
number of imo 3365
dfNewJourney 24
lenPos 0
I =  10029817
number of imo 3366
dfNewJourney 7
lenPos 1750
I =  9431288
number of imo 3367
1750
===============
dfNewJourney 9
lenPos 0
I =  10030532
number of imo 3368
dfNewJourney 30
lenPos 0
I =  10047852
number of imo 3369
dfNewJourney 1
lenPos 1822
I =  9277541
number of imo 3370
1822
===============
dfNewJourney 27
lenPos 0
I =  10028527
number of imo 3371
dfNewJourney 31
lenPos 0
I =  10029814
number of imo 3372
dfNewJourney 27
lenPos 0
I =  10015671
number of imo 3373
dfNewJourney 28
lenPos 0
I =  10030343
number of imo 3374
dfNewJourney 25
lenPos 0
I =  10033409
number of imo 3375
dfNewJourney 31
lenPos 0
I =  10027424
number of imo 3376
dfNewJourney 27
lenPos 0
I =  10028800
number of imo 3377
dfNewJourney 7
lenPos 1696
I =  9253076
number of imo 3378
1696
===============
dfNewJourney 29
lenPos 0
I =  10029021
number of imo 3379
dfNewJourney 30
lenPos 0
I =  10031087
number of imo 3380
dfNewJourney 21
lenPos 0
I =  10029273
number of imo 3381
dfNewJourney 29
lenPos 0
I =  10028345
number of imo 3382
dfNewJourney 21
lenPos 1166
I =  9440514
number of imo 3383
1166
===============
dfNewJourney 10
lenPos 764
I =  9455791
number of imo 3384
764
===============
dfNewJourney 1
lenPos 1853
I =  9342085
number of imo 3385
1853
===============
dfNewJourney 6
lenPos 1750
I =  9283253
number of imo 3386
1750
===============
dfNewJourney 3
lenPos 1825
I =  9086356
number of imo 3387
1825
===============
dfNewJourney 14
lenPos 0
I =  10044265
number of imo 3388
dfNewJourney 13
lenPos 0
I =  10035186
number of imo 3389
dfNewJourney 32
lenPos 0
I =  10033473
number of imo 3390
dfNewJourney 1
lenPos 1715
I =  9293959
number of imo 3391
1715
===============
dfNewJourney 27
lenPos 0
I =  10030342
number of imo 3392
dfNewJourney 25
lenPos 0
I =  10029190
number of imo 3393
dfNewJourney 24
lenPos 0
I =  10030855
number of imo 3394
dfNewJourney 34
lenPos 0
I =  10029813
number of imo 3395
dfNewJourney 4
lenPos 0
I =  9309227
number of imo 3396
dfNewJourney 26
lenPos 1204
I =  9528134
number of imo 3397
1204
===============
dfNewJourney 6
lenPos 0
I =  10036533
number of imo 3398
dfNewJourney 14
lenPos 1705
I =  9307085
number of imo 3399
1705
===============
dfNewJourney 6
lenPos 1876
I =  9301419
number of imo 3400
1876
===============
dfNewJourney 10
lenPos 1490
I =  9253246
number of imo 3401
1490
===============
dfNewJourney 1
lenPos 454
I =  9083287
number of imo 3402
454
===============
dfNewJourney 23
lenPos 0
I =  10027425
number of imo 3403
dfNewJourney 13
lenPos 0
I =  10035119
number of imo 3404
dfNewJourney 2
lenPos 0
I =  10029196
number of imo 3405
dfNewJourney 9
lenPos 1432
I =  9196436
number of imo 3406
1432
===============
dfNewJourney 2
lenPos 1609
I =  9231705
number of imo 3407
1609
===============
dfNewJourney 4
lenPos 1875
I =  9353539
number of imo 3408
1875
===============
dfNewJourney 22
lenPos 0
I =  10027876
number of imo 3409
dfNewJourney 38
lenPos 0
I =  10028078
number of imo 3410
dfNewJourney 25
lenPos 0
I =  10006830
number of imo 3411
dfNewJourney 7
lenPos 1764
I =  9376854
number of imo 3412
1764
===============
dfNewJourney 23
lenPos 0
I =  10031086
number of imo 3413
dfNewJourney 18
lenPos 0
I =  10034895
number of imo 3414
dfNewJourney 21
lenPos 0
I =  10028087
number of imo 3415
dfNewJourney 25
lenPos 0
I =  10029230
number of imo 3416
dfNewJourney 6
lenPos 0
I =  10029939
number of imo 3417
dfNewJourney 5
lenPos 0
I =  10031085
number of imo 3418
dfNewJourney 12
lenPos 1781
I =  9380582
number of imo 3419
1781
===============
dfNewJourney 29
lenPos 0
I =  10033474
number of imo 3420
dfNewJourney 23
lenPos 0
I =  10029192
number of imo 3421
dfNewJourney 28
lenPos 0
I =  10029532
number of imo 3422
dfNewJourney 1
lenPos 1771
I =  9288942
number of imo 3423
1771
===============
dfNewJourney 1
lenPos 1838
I =  9403293
number of imo 3424
1838
===============
dfNewJourney 29
lenPos 0
I =  10029974
number of imo 3425
dfNewJourney 7
lenPos 1774
I =  9391282
number of imo 3426
1774
===============
dfNewJourney 25
lenPos 0
I =  10029229
number of imo 3427
dfNewJourney 29
lenPos 0
I =  10015623
number of imo 3428
dfNewJourney 4
lenPos 0
I =  10029197
number of imo 3429
dfNewJourney 31
lenPos 0
I =  10029531
number of imo 3430
dfNewJourney 26
lenPos 0
I =  10043490
number of imo 3431
dfNewJourney 22
lenPos 0
I =  10029266
number of imo 3432
dfNewJourney 12
lenPos 0
I =  10036532
number of imo 3433
dfNewJourney 35
lenPos 0
I =  10033475
number of imo 3434
dfNewJourney 24
lenPos 0
I =  10030341
number of imo 3435
dfNewJourney 8
lenPos 0
I =  10036531
number of imo 3436
dfNewJourney 6
lenPos 1740
I =  9313486
number of imo 3437
1740
===============
dfNewJourney 19
lenPos 0
I =  10031083
number of imo 3438
dfNewJourney 24
lenPos 0
I =  10029780
number of imo 3439
dfNewJourney 22
lenPos 0
I =  10031084
number of imo 3440
dfNewJourney 1
lenPos 1833
I =  9306720
number of imo 3441
1833
===============
dfNewJourney 15
lenPos 0
I =  10036463
number of imo 3442
dfNewJourney 25
lenPos 0
I =  10017743
number of imo 3443
dfNewJourney 2
lenPos 1452
I =  9038830
number of imo 3444
1452
===============
dfNewJourney 8
lenPos 1708
I =  9292591
number of imo 3445
1708
===============
dfNewJourney 10
lenPos 0
I =  10030531
number of imo 3446
dfNewJourney 28
lenPos 0
I =  10047598
number of imo 3447
dfNewJourney 27
lenPos 0
I =  10029191
number of imo 3448
dfNewJourney 29
lenPos 0
I =  10033240
number of imo 3449
dfNewJourney 56
lenPos 0
I =  10045735
number of imo 3450
dfNewJourney 8
lenPos 0
I =  10029777
number of imo 3451
dfNewJourney 24
lenPos 0
I =  10015624
number of imo 3452
dfNewJourney 24
lenPos 0
I =  10017742
number of imo 3453
dfNewJourney 1
lenPos 0
I =  8607828
number of imo 3454
dfNewJourney 12
lenPos 0
I =  10031928
number of imo 3455
dfNewJourney 20
lenPos 0
I =  10033512
number of imo 3456
dfNewJourney 19
lenPos 0
I =  10057164
number of imo 3457
dfNewJourney 22
lenPos 0
I =  10030380
number of imo 3458
dfNewJourney 5
lenPos 1817
I =  9327396
number of imo 3459
1817
===============
dfNewJourney 25
lenPos 0
I =  10033239
number of imo 3460
dfNewJourney 25
lenPos 0
I =  10030379
number of imo 3461
dfNewJourney 23
lenPos 0
I =  10031604
number of imo 3462
dfNewJourney 4
lenPos 1866
I =  9499876
number of imo 3463
1866
===============
dfNewJourney 4
lenPos 0
I =  10035414
number of imo 3464
dfNewJourney 15
lenPos 0
I =  10028801
number of imo 3465
dfNewJourney 28
lenPos 0
I =  10030549
number of imo 3466
dfNewJourney 25
lenPos 0
I =  10033241
number of imo 3467
dfNewJourney 25
lenPos 0
I =  10031431
number of imo 3468
dfNewJourney 37
lenPos 0
I =  10028079
number of imo 3469
dfNewJourney 3
lenPos 1826
I =  9288772
number of imo 3470
1826
===============
dfNewJourney 20
lenPos 0
I =  10033243
number of imo 3471
dfNewJourney 4
lenPos 1834
I =  9165176
number of imo 3472
1834

===============
dfNewJourney 26
lenPos 0
I =  10033238
number of imo 3473
dfNewJourney 22
lenPos 0
I =  10030854
number of imo 3474
dfNewJourney 27
lenPos 0
I =  10033410
number of imo 3475
dfNewJourney 11
lenPos 1831
I =  9377664
number of imo 3476
1831
===============
dfNewJourney 23
lenPos 0
I =  10036462
number of imo 3477
dfNewJourney 28
lenPos 0
I =  10033477
number of imo 3478
dfNewJourney 25
lenPos 0
I =  10030550
number of imo 3479
dfNewJourney 25
lenPos 0
I =  10033242
number of imo 3480
dfNewJourney 11
lenPos 1830
I =  9511533
number of imo 3481
1830
===============
dfNewJourney 29
lenPos 0
I =  10017744
number of imo 3482
dfNewJourney 24
lenPos 0
I =  10033476
number of imo 3483
dfNewJourney 23
lenPos 0
I =  10031935
number of imo 3484
dfNewJourney 13
lenPos 1240
I =  9251535
number of imo 3485
1240
===============
dfNewJourney 12
lenPos 0
I =  10040707
number of imo 3486
dfNewJourney 11
lenPos 0
I =  10034894
number of imo 3487
dfNewJourney 40
lenPos 0
I =  10029389
number of imo 3488
dfNewJourney 1
lenPos 1846
I =  9176929
number of imo 3489
1846
===============
dfNewJourney 2
lenPos 1892
I =  9255282
number of imo 3490
1892
===============
dfNewJourney 27
lenPos 0
I =  10030836
number of imo 3491
dfNewJourney 1
lenPos 1906
I =  9372547
number of imo 3492
1906
===============
dfNewJourney 21
lenPos 0
I =  10041338
number of imo 3493
dfNewJourney 28
lenPos 0
I =  10030340
number of imo 3494
dfNewJourney 10
lenPos 1788
I =  9208124
number of imo 3495
1788
===============
dfNewJourney 2
lenPos 1830
I =  9244441
number of imo 3496
1830
===============
dfNewJourney 4
lenPos 0
I =  10035415
number of imo 3497
dfNewJourney 26
lenPos 0
I =  10008675
number of imo 3498
dfNewJourney 26
lenPos 0
I =  10028346
number of imo 3499
dfNewJourney 27
lenPos 0
I =  10041308
number of imo 3500
dfNewJourney 26
lenPos 0
I =  10035008
number of imo 3501
dfNewJourney 14
lenPos 0
I =  10036464
number of imo 3502
dfNewJourney 1
lenPos 0
I =  8819108
number of imo 3503
dfNewJourney 4
lenPos 1759
I =  9513438
number of imo 3504
1759
===============
dfNewJourney 7
lenPos 0
I =  10035185
number of imo 3505
dfNewJourney 20
lenPos 0
I =  10033530
number of imo 3506
dfNewJourney 8
lenPos 1730
I =  9251573
number of imo 3507
1730
===============
dfNewJourney 16
lenPos 0
I =  10031936
number of imo 3508
dfNewJourney 26
lenPos 0
I =  10031089
number of imo 3509
dfNewJourney 31
lenPos 0
I =  10043482
number of imo 3510
dfNewJourney 32
lenPos 0
I =  10031430
number of imo 3511
dfNewJourney 23
lenPos 0
I =  10040456
number of imo 3512
dfNewJourney 22
lenPos 0
I =  10030347
number of imo 3513
dfNewJourney 23
lenPos 0
I =  10029265
number of imo 3514
dfNewJourney 25
lenPos 0
I =  10027877
number of imo 3515
dfNewJourney 18
lenPos 0
I =  10031933
number of imo 3516
dfNewJourney 21
lenPos 0
I =  10030190
number of imo 3517
dfNewJourney 3
lenPos 1891
I =  9499888
number of imo 3518
1891
===============
dfNewJourney 5
lenPos 0
I =  10028082
number of imo 3519
dfNewJourney 29
lenPos 0
I =  10031088
number of imo 3520
dfNewJourney 13
lenPos 1644
I =  9400837
number of imo 3521
1644
===============
dfNewJourney 29
lenPos 0
I =  10033496
number of imo 3522
dfNewJourney 47
lenPos 0
I =  10062117
number of imo 3523
dfNewJourney 30
lenPos 0
I =  10033495
number of imo 3524
dfNewJourney 30
lenPos 0
I =  10031188
number of imo 3525
dfNewJourney 23
lenPos 0
I =  10030551
number of imo 3526
dfNewJourney 35
lenPos 1002
I =  9509449
number of imo 3527
1002
===============
dfNewJourney 2
lenPos 1385
I =  9310252
number of imo 3528
1385
===============
dfNewJourney 1
lenPos 1645
I =  9308455
number of imo 3529
1645
===============
dfNewJourney 6
lenPos 1752
I =  9301744
number of imo 3530
1752
===============
dfNewJourney 21
lenPos 0
I =  10036751
number of imo 3531
dfNewJourney 21
lenPos 0
I =  10031927
number of imo 3532
dfNewJourney 29
lenPos 0
I =  10029388
number of imo 3533
dfNewJourney 18
lenPos 0
I =  10017745
number of imo 3534
dfNewJourney 2
lenPos 1860
I =  9384136
number of imo 3535
1860
===============
dfNewJourney 5
lenPos 1750
I =  9253064
number of imo 3536
1750
===============
dfNewJourney 16
lenPos 0
I =  10022328
number of imo 3537
dfNewJourney 7
lenPos 0
I =  9012305
number of imo 3538
dfNewJourney 20
lenPos 0
I =  10018385
number of imo 3539
dfNewJourney 15
lenPos 0
I =  10028881
number of imo 3540
dfNewJourney 29
lenPos 0
I =  10030061
number of imo 3541
dfNewJourney 2
lenPos 1737
I =  9228784
number of imo 3542
1737
===============
dfNewJourney 18
lenPos 0
I =  10033511
number of imo 3543
dfNewJourney 9
lenPos 1761
I =  9351062
number of imo 3544
1761
===============
dfNewJourney 16
lenPos 0
I =  10036828
number of imo 3545
dfNewJourney 22
lenPos 0
I =  10030062
number of imo 3546
dfNewJourney 1
lenPos 1747
I =  9271028
number of imo 3547
1747
===============
dfNewJourney 22
lenPos 0
I =  10031934
number of imo 3548
dfNewJourney 4
lenPos 0
I =  10015438
number of imo 3549
dfNewJourney 20
lenPos 0
I =  10029938
number of imo 3550
dfNewJourney 9
lenPos 1801
I =  9295347
number of imo 3551
1801
===============
dfNewJourney 22
lenPos 0
I =  10031202
number of imo 3552
dfNewJourney 12
lenPos 0
I =  10040979
number of imo 3553
dfNewJourney 21
lenPos 0
I =  10036487
number of imo 3554
dfNewJourney 26
lenPos 0
I =  10033497
number of imo 3555
dfNewJourney 22
lenPos 0
I =  10040706
number of imo 3556
dfNewJourney 21
lenPos 0
I =  10030189
number of imo 3557
dfNewJourney 23
lenPos 0
I =  10030552
number of imo 3558
dfNewJourney 22
lenPos 0
I =  10023330
number of imo 3559
dfNewJourney 6
lenPos 0
I =  10030180
number of imo 3560
dfNewJourney 24
lenPos 0
I =  10033244
number of imo 3561
dfNewJourney 13
lenPos 0
I =  10028882
number of imo 3562
dfNewJourney 15
lenPos 0
I =  10035120
number of imo 3563
dfNewJourney 24
lenPos 0
I =  10032032
number of imo 3564
dfNewJourney 23
lenPos 0
I =  10030191
number of imo 3565
dfNewJourney 28
lenPos 0
I =  10030835
number of imo 3566
dfNewJourney 22
lenPos 0
I =  10008700
number of imo 3567
dfNewJourney 20
lenPos 0
I =  10031052
number of imo 3568
dfNewJourney 23
lenPos 0
I =  10030188
number of imo 3569
dfNewJourney 3
lenPos 0
I =  10028081
number of imo 3570
dfNewJourney 22
lenPos 0
I =  10033532
number of imo 3571
dfNewJourney 28
lenPos 0
I =  10045957
number of imo 3572
dfNewJourney 25
lenPos 0
I =  10029193
number of imo 3573
dfNewJourney 19
lenPos 0
I =  10030937
number of imo 3574
dfNewJourney 27
lenPos 0
I =  10040457
number of imo 3575
dfNewJourney 14
lenPos 0
I =  10030183
number of imo 3576
dfNewJourney 18
lenPos 0
I =  10030187
number of imo 3577
dfNewJourney 18
lenPos 0
I =  10017746
number of imo 3578
dfNewJourney 9
lenPos 0
I =  10047555
number of imo 3579
dfNewJourney 22
lenPos 0
I =  10036748
number of imo 3580
dfNewJourney 25
lenPos 0
I =  10033472
number of imo 3581
dfNewJourney 25
lenPos 0
I =  10031082
number of imo 3582
dfNewJourney 24
lenPos 0
I =  10035972
number of imo 3583
dfNewJourney 23
lenPos 0
I =  10041307
number of imo 3584
dfNewJourney 21
lenPos 0
I =  10034772
number of imo 3585
dfNewJourney 4
lenPos 0
I =  10028080
number of imo 3586
dfNewJourney 24
lenPos 0
I =  10033510
number of imo 3587
dfNewJourney 17
lenPos 1867
I =  9333656
number of imo 3588
1867
===============
dfNewJourney 17
lenPos 0
I =  10046193
number of imo 3589
dfNewJourney 19
lenPos 0
I =  10031201
number of imo 3590
dfNewJourney 2
lenPos 1713
I =  9038842
number of imo 3591
1713
===============
dfNewJourney 21
lenPos 0
I =  10029274
number of imo 3592
dfNewJourney 11
lenPos 0
I =  10030179
number of imo 3593
dfNewJourney 7
lenPos 0
I =  10029199
number of imo 3594
dfNewJourney 8
lenPos 1655
I =  9113367
number of imo 3595
1655
===============
dfNewJourney 7
lenPos 1879
I =  9311751
number of imo 3596
1879
===============
dfNewJourney 9
lenPos 0
I =  10047556
number of imo 3597
dfNewJourney 19
lenPos 0
I =  10030182
number of imo 3598
dfNewJourney 1
lenPos 1821
I =  9251547
number of imo 3599
1821
===============
dfNewJourney 20
lenPos 0
I =  10032031
number of imo 3600
dfNewJourney 2
lenPos 1906
I =  9513440
number of imo 3601
1906
===============
dfNewJourney 1
lenPos 0
I =  8814158
number of imo 3602
dfNewJourney 21
lenPos 0
I =  10034771
number of imo 3603
dfNewJourney 7
lenPos 0
I =  10040980
number of imo 3604
dfNewJourney 2
lenPos 0
I =  10101874
number of imo 3605
dfNewJourney 22
lenPos 0
I =  10028388
number of imo 3606
dfNewJourney 2
lenPos 1833
I =  9543512
number of imo 3607
1833

===============
dfNewJourney 16
lenPos 0
I =  10036827
number of imo 3608
dfNewJourney 23
lenPos 0
I =  10030060
number of imo 3609
dfNewJourney 13
lenPos 1633
I =  9322968
number of imo 3610
1633
===============
dfNewJourney 29
lenPos 0
I =  10040705
number of imo 3611
dfNewJourney 24
lenPos 0
I =  10030938
number of imo 3612
dfNewJourney 24
lenPos 0
I =  10033471
number of imo 3613
dfNewJourney 20
lenPos 0
I =  10046252
number of imo 3614
dfNewJourney 23
lenPos 0
I =  10023329
number of imo 3615
dfNewJourney 15
lenPos 0
I =  10041339
number of imo 3616
dfNewJourney 21
lenPos 0
I =  10030853
number of imo 3617
dfNewJourney 24
lenPos 0
I =  10035010
number of imo 3618
dfNewJourney 22
lenPos 0
I =  10031181
number of imo 3619
dfNewJourney 5
lenPos 0
I =  10007589
number of imo 3620
dfNewJourney 21
lenPos 0
I =  10036354
number of imo 3621
dfNewJourney 1
lenPos 0
I =  8607816
number of imo 3622
dfNewJourney 26
lenPos 0
I =  10040703
number of imo 3623
dfNewJourney 14
lenPos 0
I =  10036465
number of imo 3624
dfNewJourney 17
lenPos 0
I =  10029937
number of imo 3625
dfNewJourney 22
lenPos 0
I =  10036353
number of imo 3626
dfNewJourney 24
lenPos 0
I =  10031341
number of imo 3627
dfNewJourney 1
lenPos 1831
I =  9385178
number of imo 3628
1831
===============
dfNewJourney 24
lenPos 0
I =  10031926
number of imo 3629
dfNewJourney 2
lenPos 1360
I =  8814433
number of imo 3630
1360
===============
dfNewJourney 19
lenPos 0
I =  10017747
number of imo 3631
dfNewJourney 26
lenPos 0
I =  10041306
number of imo 3632
dfNewJourney 3
lenPos 0
I =  9009229
number of imo 3633
dfNewJourney 16
lenPos 0
I =  10031200
number of imo 3634
dfNewJourney 1
lenPos 970
I =  9038854
number of imo 3635
970
===============
dfNewJourney 1
lenPos 1073
I =  9125736
number of imo 3636
1073
===============
dfNewJourney 16
lenPos 0
I =  10036750
number of imo 3637
dfNewJourney 1
lenPos 1789
I =  9344813
number of imo 3638
1789
===============
dfNewJourney 6
lenPos 1352
I =  9492270
number of imo 3639
1352
===============
dfNewJourney 1
lenPos 1838
I =  9342774
number of imo 3640
1838
===============
dfNewJourney 3
lenPos 1889
I =  9298715
number of imo 3641
1889
===============
dfNewJourney 17
lenPos 0
I =  10040704
number of imo 3642
dfNewJourney 23
lenPos 0
I =  10043344
number of imo 3643
dfNewJourney 21
lenPos 0
I =  10043345
number of imo 3644
dfNewJourney 15
lenPos 0
I =  10030178
number of imo 3645
dfNewJourney 19
lenPos 0
I =  10030346
number of imo 3646
dfNewJourney 20
lenPos 0
I =  10017748
number of imo 3647
dfNewJourney 19
lenPos 0
I =  10030852
number of imo 3648
dfNewJourney 22
lenPos 0
I =  10031180
number of imo 3649
dfNewJourney 2
lenPos 0
I =  10006202
number of imo 3650
dfNewJourney 23
lenPos 0
I =  10032030
number of imo 3651
dfNewJourney 21
lenPos 0
I =  10030184
number of imo 3652
dfNewJourney 25
lenPos 0
I =  10033501
number of imo 3653
dfNewJourney 8
lenPos 0
I =  10040981
number of imo 3654
dfNewJourney 14
lenPos 0
I =  10033407
number of imo 3655
dfNewJourney 16
lenPos 1801
I =  9538153
number of imo 3656
1801
===============
dfNewJourney 19
lenPos 0
I =  10031053
number of imo 3657
dfNewJourney 20
lenPos 0
I =  10041305
number of imo 3658
dfNewJourney 25
lenPos 0
I =  10029387
number of imo 3659
dfNewJourney 18
lenPos 0
I =  10030185
number of imo 3660
dfNewJourney 16
lenPos 0
I =  10031199
number of imo 3661
dfNewJourney 23
lenPos 0
I =  10042250
number of imo 3662
dfNewJourney 6
lenPos 0
I =  10029930
number of imo 3663
dfNewJourney 25
lenPos 0
I =  10033531
number of imo 3664
dfNewJourney 18
lenPos 0
I =  10032029
number of imo 3665
dfNewJourney 16
lenPos 1780
I =  9329655
number of imo 3666
1780
===============
dfNewJourney 21
lenPos 0
I =  10040931
number of imo 3667
dfNewJourney 18
lenPos 0
I =  10034770
number of imo 3668
dfNewJourney 10
lenPos 0
I =  10029778
number of imo 3669
dfNewJourney 15
lenPos 0
I =  10030065
number of imo 3670
dfNewJourney 23
lenPos 0
I =  10029385
number of imo 3671
dfNewJourney 23
lenPos 0
I =  10041545
number of imo 3672
dfNewJourney 16
lenPos 0
I =  10046192
number of imo 3673
dfNewJourney 13
lenPos 0
I =  10022327
number of imo 3674
dfNewJourney 14
lenPos 0
I =  10041340
number of imo 3675
dfNewJourney 25
lenPos 0
I =  10035068
number of imo 3676
dfNewJourney 15
lenPos 0
I =  10030186
number of imo 3677
dfNewJourney 17
lenPos 0
I =  10036826
number of imo 3678
dfNewJourney 1
lenPos 0
I =  8704353
number of imo 3679
dfNewJourney 23
lenPos 0
I =  10031925
number of imo 3680
dfNewJourney 21
lenPos 0
I =  10029386
number of imo 3681
dfNewJourney 3
lenPos 1843
I =  9552496
number of imo 3682
1843
===============
dfNewJourney 18
lenPos 0
I =  10029645
number of imo 3683
dfNewJourney 3
lenPos 0
I =  10035123
number of imo 3684
dfNewJourney 19
lenPos 0
I =  10034769
number of imo 3685
dfNewJourney 21
lenPos 0
I =  10030059
number of imo 3686
dfNewJourney 22
lenPos 0
I =  10030344
number of imo 3687
dfNewJourney 17
lenPos 0
I =  10048795
number of imo 3688
dfNewJourney 4
lenPos 0
I =  10007569
number of imo 3689
dfNewJourney 15
lenPos 0
I =  10041341
number of imo 3690
dfNewJourney 12
lenPos 0
I =  10040932
number of imo 3691
dfNewJourney 7
lenPos 0
I =  10029929
number of imo 3692
dfNewJourney 13
lenPos 0
I =  10035014
number of imo 3693
dfNewJourney 16
lenPos 0
I =  10035015
number of imo 3694
dfNewJourney 19
lenPos 0
I =  10036749
number of imo 3695
dfNewJourney 20
lenPos 0
I =  10033500
number of imo 3696
dfNewJourney 1
lenPos 0
I =  9108702
number of imo 3697
dfNewJourney 19
lenPos 0
I =  10044367
number of imo 3698
dfNewJourney 21
lenPos 0
I =  10036356
number of imo 3699
dfNewJourney 20
lenPos 0
I =  10030066
number of imo 3700
dfNewJourney 10
lenPos 0
I =  10046253
number of imo 3701
dfNewJourney 24
lenPos 0
I =  10035761
number of imo 3702
dfNewJourney 1
lenPos 0
I =  10046594
number of imo 3703
dfNewJourney 2
lenPos 1811
I =  9288954
number of imo 3704
1811
===============
dfNewJourney 13
lenPos 1820
I =  9223344
number of imo 3705
1820
===============
dfNewJourney 10
lenPos 0
I =  10042587
number of imo 3706
dfNewJourney 17
lenPos 0
I =  10008391
number of imo 3707
dfNewJourney 12
lenPos 0
I =  10045364
number of imo 3708
dfNewJourney 11
lenPos 0
I =  10058692
number of imo 3709
dfNewJourney 15
lenPos 0
I =  10043489
number of imo 3710
dfNewJourney 20
lenPos 0
I =  10033408
number of imo 3711
dfNewJourney 2
lenPos 1870
I =  9598256
number of imo 3712
1870
===============
dfNewJourney 7
lenPos 1595
I =  9313761
number of imo 3713
1595
===============
dfNewJourney 14
lenPos 0
I =  10031351
number of imo 3714
dfNewJourney 20
lenPos 0
I =  10048898
number of imo 3715
dfNewJourney 19
lenPos 0
I =  10017749
number of imo 3716
dfNewJourney 15
lenPos 1676
I =  9162514
number of imo 3717
1676
===============
dfNewJourney 13
lenPos 0
I =  10057504
number of imo 3718
dfNewJourney 18
lenPos 0
I =  10029643
number of imo 3719
dfNewJourney 3
lenPos 756
I =  9108647
number of imo 3720
756
===============
dfNewJourney 2
lenPos 1750
I =  9353541
number of imo 3721
1750
===============
dfNewJourney 19
lenPos 0
I =  10035067
number of imo 3722
dfNewJourney 20
lenPos 0
I =  10034738
number of imo 3723
dfNewJourney 20
lenPos 0
I =  10050408
number of imo 3724
dfNewJourney 19
lenPos 0
I =  10050571
number of imo 3725
dfNewJourney 16
lenPos 0
I =  10058693
number of imo 3726
dfNewJourney 24
lenPos 0
I =  10031182
number of imo 3727
dfNewJourney 19
lenPos 0
I =  10008428
number of imo 3728
dfNewJourney 16
lenPos 0
I =  10030068
number of imo 3729
dfNewJourney 18
lenPos 0
I =  10030067
number of imo 3730
dfNewJourney 7
lenPos 0
I =  10046221
number of imo 3731
dfNewJourney 17
lenPos 0
I =  10047722
number of imo 3732
dfNewJourney 21
lenPos 0
I =  10046347
number of imo 3733
dfNewJourney 12
lenPos 0
I =  10022326
number of imo 3734
dfNewJourney 18
lenPos 0
I =  10032023
number of imo 3735
dfNewJourney 18
lenPos 0
I =  10042251
number of imo 3736
dfNewJourney 1
lenPos 1479
I =  9288019
number of imo 3737
1479
===============
dfNewJourney 18
lenPos 0
I =  10031339
number of imo 3738
dfNewJourney 11
lenPos 0
I =  10029928
number of imo 3739
dfNewJourney 18
lenPos 0
I =  10050403
number of imo 3740
dfNewJourney 9
lenPos 1828
I =  9251585
number of imo 3741
1828

===============
dfNewJourney 11
lenPos 0
I =  10045365
number of imo 3742
dfNewJourney 3
lenPos 1733
I =  9182069
number of imo 3743
1733
===============
dfNewJourney 20
lenPos 0
I =  10030345
number of imo 3744
dfNewJourney 16
lenPos 0
I =  10044368
number of imo 3745
dfNewJourney 6
lenPos 0
I =  10042588
number of imo 3746
dfNewJourney 11
lenPos 0
I =  10045161
number of imo 3747
dfNewJourney 21
lenPos 0
I =  10047732
number of imo 3748
dfNewJourney 3
lenPos 1378
I =  9266774
number of imo 3749
1378
===============
dfNewJourney 16
lenPos 0
I =  10029384
number of imo 3750
dfNewJourney 13
lenPos 0
I =  10031343
number of imo 3751
dfNewJourney 10
lenPos 0
I =  10045362
number of imo 3752
dfNewJourney 20
lenPos 0
I =  10047724
number of imo 3753
dfNewJourney 15
lenPos 0
I =  10028389
number of imo 3754
dfNewJourney 20
lenPos 0
I =  10048899
number of imo 3755
dfNewJourney 13
lenPos 0
I =  10035794
number of imo 3756
dfNewJourney 18
lenPos 0
I =  10032028
number of imo 3757
dfNewJourney 8
lenPos 0
I =  10036736
number of imo 3758
dfNewJourney 13
lenPos 0
I =  10047265
number of imo 3759
dfNewJourney 21
lenPos 0
I =  10057501
number of imo 3760
dfNewJourney 14
lenPos 0
I =  10058662
number of imo 3761
dfNewJourney 6
lenPos 0
I =  10029931
number of imo 3762
dfNewJourney 6
lenPos 1880
I =  9379337
number of imo 3763
1880
===============
dfNewJourney 15
lenPos 0
I =  10062132
number of imo 3764
dfNewJourney 1
lenPos 1245
I =  9275268
number of imo 3765
1245
===============
dfNewJourney 15
lenPos 0
I =  10044779
number of imo 3766
dfNewJourney 16
lenPos 0
I =  10049688
number of imo 3767
dfNewJourney 23
lenPos 0
I =  10029383
number of imo 3768
dfNewJourney 8
lenPos 0
I =  10040325
number of imo 3769
dfNewJourney 11
lenPos 0
I =  10035760
number of imo 3770
dfNewJourney 19
lenPos 0
I =  10036355
number of imo 3771
dfNewJourney 13
lenPos 0
I =  10040933
number of imo 3772
dfNewJourney 15
lenPos 0
I =  10070607
number of imo 3773
dfNewJourney 14
lenPos 0
I =  10056126
number of imo 3774
dfNewJourney 10
lenPos 0
I =  10042031
number of imo 3775
dfNewJourney 14
lenPos 0
I =  10017750
number of imo 3776
dfNewJourney 7
lenPos 0
I =  10042589
number of imo 3777
dfNewJourney 11
lenPos 0
I =  10035016
number of imo 3778
dfNewJourney 17
lenPos 0
I =  10034742
number of imo 3779
dfNewJourney 4
lenPos 0
I =  10034739
number of imo 3780
dfNewJourney 2
lenPos 1896
I =  9492000
number of imo 3781
1896
===============
dfNewJourney 3
lenPos 1763
I =  9259680
number of imo 3782
1763
===============
dfNewJourney 14
lenPos 0
I =  10061395
number of imo 3783
dfNewJourney 9
lenPos 0
I =  10022325
number of imo 3784
dfNewJourney 2
lenPos 1872
I =  9327384
number of imo 3785
1872
===============
dfNewJourney 16
lenPos 0
I =  10057755
number of imo 3786
dfNewJourney 8
lenPos 0
I =  10048793
number of imo 3787
dfNewJourney 13
lenPos 0
I =  10050499
number of imo 3788
dfNewJourney 11
lenPos 0
I =  10032027
number of imo 3789
dfNewJourney 14
lenPos 0
I =  10044778
number of imo 3790
dfNewJourney 14
lenPos 0
I =  10040451
number of imo 3791
dfNewJourney 11
lenPos 0
I =  10050570
number of imo 3792
dfNewJourney 17
lenPos 0
I =  10040702
number of imo 3793
dfNewJourney 15
lenPos 0
I =  10058551
number of imo 3794
dfNewJourney 14
lenPos 0
I =  10046595
number of imo 3795
dfNewJourney 21
lenPos 0
I =  10029380
number of imo 3796
dfNewJourney 4
lenPos 0
I =  10048897
number of imo 3797
dfNewJourney 10
lenPos 0
I =  10048249
number of imo 3798
dfNewJourney 13
lenPos 0
I =  10050500
number of imo 3799
dfNewJourney 11
lenPos 0
I =  10045363
number of imo 3800
dfNewJourney 14
lenPos 0
I =  10042059
number of imo 3801
dfNewJourney 14
lenPos 0
I =  10042029
number of imo 3802
dfNewJourney 14
lenPos 0
I =  10045160
number of imo 3803
dfNewJourney 14
lenPos 0
I =  10044773
number of imo 3804
dfNewJourney 2
lenPos 1879
I =  9228796
number of imo 3805
1879
===============
dfNewJourney 11
lenPos 0
I =  10059743
number of imo 3806
dfNewJourney 12
lenPos 0
I =  10041342
number of imo 3807
dfNewJourney 9
lenPos 0
I =  10050908
number of imo 3808
dfNewJourney 16
lenPos 0
I =  10057498
number of imo 3809
dfNewJourney 2
lenPos 1881
I =  9492050
number of imo 3810
1881
===============
dfNewJourney 21
lenPos 0
I =  10058384
number of imo 3811
dfNewJourney 12
lenPos 0
I =  10044370
number of imo 3812
dfNewJourney 11
lenPos 0
I =  10047269
number of imo 3813
dfNewJourney 15
lenPos 0
I =  10072430
number of imo 3814
dfNewJourney 13
lenPos 0
I =  10075249
number of imo 3815
dfNewJourney 14
lenPos 0
I =  10058385
number of imo 3816
dfNewJourney 16
lenPos 0
I =  10057758
number of imo 3817
dfNewJourney 14
lenPos 0
I =  10040452
number of imo 3818
dfNewJourney 12
lenPos 0
I =  10060680
number of imo 3819
dfNewJourney 11
lenPos 0
I =  10048896
number of imo 3820
dfNewJourney 8
lenPos 0
I =  10061988
number of imo 3821
dfNewJourney 7
lenPos 0
I =  10050574
number of imo 3822
dfNewJourney 15
lenPos 0
I =  10031342
number of imo 3823
dfNewJourney 10
lenPos 0
I =  10034740
number of imo 3824
dfNewJourney 1
lenPos 936
I =  8717233
number of imo 3825
936
===============
dfNewJourney 11
lenPos 0
I =  10050402
number of imo 3826
dfNewJourney 11
lenPos 0
I =  10034768
number of imo 3827
dfNewJourney 16
lenPos 0
I =  10049689
number of imo 3828
dfNewJourney 14
lenPos 0
I =  10050953
number of imo 3829
dfNewJourney 9
lenPos 0
I =  10042032
number of imo 3830
dfNewJourney 11
lenPos 0
I =  10075248
number of imo 3831
dfNewJourney 12
lenPos 0
I =  10048794
number of imo 3832
dfNewJourney 16
lenPos 0
I =  10046220
number of imo 3833
dfNewJourney 12
lenPos 0
I =  9540534
number of imo 3834
dfNewJourney 10
lenPos 0
I =  10036594
number of imo 3835
dfNewJourney 15
lenPos 0
I =  10044369
number of imo 3836
dfNewJourney 11
lenPos 0
I =  10046185
number of imo 3837
dfNewJourney 19
lenPos 0
I =  10050954
number of imo 3838
dfNewJourney 12
lenPos 0
I =  10060866
number of imo 3839
dfNewJourney 13
lenPos 1848
I =  9344019
number of imo 3840
1848
===============
dfNewJourney 7
lenPos 0
I =  10046219
number of imo 3841
dfNewJourney 1
lenPos 1455
I =  8619429
number of imo 3842
1455
===============
dfNewJourney 2
lenPos 1891
I =  9492062
number of imo 3843
1891
===============
dfNewJourney 15
lenPos 0
I =  10048512
number of imo 3844
dfNewJourney 11
lenPos 0
I =  10045080
number of imo 3845
dfNewJourney 14
lenPos 0
I =  10060970
number of imo 3846
dfNewJourney 11
lenPos 0
I =  10044780
number of imo 3847
dfNewJourney 11
lenPos 0
I =  10035795
number of imo 3848
dfNewJourney 16
lenPos 0
I =  10060652
number of imo 3849
dfNewJourney 7
lenPos 0
I =  10031183
number of imo 3850
dfNewJourney 14
lenPos 0
I =  10077604
number of imo 3851
dfNewJourney 12
lenPos 0
I =  10050404
number of imo 3852
dfNewJourney 13
lenPos 0
I =  10034743
number of imo 3853
dfNewJourney 6
lenPos 0
I =  10059738
number of imo 3854
dfNewJourney 7
lenPos 0
I =  10059737
number of imo 3855
dfNewJourney 12
lenPos 0
I =  10057505
number of imo 3856
dfNewJourney 1
lenPos 1774
I =  9566344
number of imo 3857
1774
===============
dfNewJourney 17
lenPos 0
I =  10060971
number of imo 3858
dfNewJourney 3
lenPos 1780
I =  9259692
number of imo 3859
1780
===============
dfNewJourney 5
lenPos 1850
I =  9373137
number of imo 3860
1850
===============
dfNewJourney 9
lenPos 0
I =  10046650
number of imo 3861
dfNewJourney 2
lenPos 1886
I =  9492127
number of imo 3862
1886
===============
dfNewJourney 10
lenPos 0
I =  10060719
number of imo 3863
dfNewJourney 13
lenPos 0
I =  10060653
number of imo 3864
dfNewJourney 1
lenPos 0
I =  10036738
number of imo 3865
dfNewJourney 1
lenPos 1904
I =  9253765
number of imo 3866
1904
===============
dfNewJourney 6
lenPos 0
I =  10036737
number of imo 3867
dfNewJourney 14
lenPos 0
I =  10087127
number of imo 3868
dfNewJourney 10
lenPos 0
I =  10031340
number of imo 3869
dfNewJourney 1
lenPos 0
I =  10034593
number of imo 3870
dfNewJourney 1
lenPos 0
I =  9265641
number of imo 3871
dfNewJourney 3
lenPos 0
I =  10031198
number of imo 3872
dfNewJourney 13
lenPos 0
I =  10048250
number of imo 3873
dfNewJourney 11
lenPos 0
I =  10055950
number of imo 3874
dfNewJourney 7
lenPos 0
I =  10057935
number of imo 3875
dfNewJourney 8
lenPos 1829
I =  9538141
number of imo 3876
1829

===============
dfNewJourney 9
lenPos 0
I =  10058552
number of imo 3877
dfNewJourney 11
lenPos 0
I =  10061396
number of imo 3878
dfNewJourney 13
lenPos 0
I =  10042876
number of imo 3879
dfNewJourney 8
lenPos 0
I =  10045079
number of imo 3880
dfNewJourney 8
lenPos 0
I =  10060016
number of imo 3881
dfNewJourney 10
lenPos 0
I =  10077575
number of imo 3882
dfNewJourney 14
lenPos 0
I =  10050405
number of imo 3883
dfNewJourney 7
lenPos 0
I =  10034741
number of imo 3884
dfNewJourney 11
lenPos 0
I =  10071232
number of imo 3885
dfNewJourney 17
lenPos 0
I =  10048513
number of imo 3886
dfNewJourney 1
lenPos 0
I =  9154232
number of imo 3887
dfNewJourney 9
lenPos 0
I =  10042879
number of imo 3888
dfNewJourney 3
lenPos 1833
I =  9315795
number of imo 3889
1833
===============
dfNewJourney 11
lenPos 0
I =  10048322
number of imo 3890
dfNewJourney 12
lenPos 597
I =  9336464
number of imo 3891
597
===============
dfNewJourney 13
lenPos 0
I =  10058663
number of imo 3892
dfNewJourney 11
lenPos 0
I =  10044258
number of imo 3893
dfNewJourney 14
lenPos 0
I =  10057499
number of imo 3894
dfNewJourney 11
lenPos 0
I =  10060655
number of imo 3895
dfNewJourney 16
lenPos 0
I =  10056671
number of imo 3896
dfNewJourney 9
lenPos 0
I =  10036501
number of imo 3897
dfNewJourney 5
lenPos 0
I =  10070290
number of imo 3898
dfNewJourney 4
lenPos 1742
I =  9231183
number of imo 3899
1742
===============
dfNewJourney 20
lenPos 0
I =  10060654
number of imo 3900
dfNewJourney 2
lenPos 0
I =  10065214
number of imo 3901
dfNewJourney 7
lenPos 0
I =  10041641
number of imo 3902
dfNewJourney 2
lenPos 1858
I =  9220938
number of imo 3903
1858
===============
dfNewJourney 6
lenPos 0
I =  10022324
number of imo 3904
dfNewJourney 11
lenPos 0
I =  10050406
number of imo 3905
dfNewJourney 2
lenPos 1881
I =  9492139
number of imo 3906
1881
===============
dfNewJourney 6
lenPos 0
I =  10050046
number of imo 3907
dfNewJourney 9
lenPos 0
I =  10040882
number of imo 3908
dfNewJourney 14
lenPos 0
I =  10049587
number of imo 3909
dfNewJourney 6
lenPos 1408
I =  9430260
number of imo 3910
1408
===============
dfNewJourney 11
lenPos 0
I =  10042877
number of imo 3911
dfNewJourney 1
lenPos 1614
I =  9158305
number of imo 3912
1614
===============
dfNewJourney 12
lenPos 0
I =  10059546
number of imo 3913
dfNewJourney 9
lenPos 0
I =  10060865
number of imo 3914
dfNewJourney 2
lenPos 1659
I =  9037147
number of imo 3915
1659
===============
dfNewJourney 10
lenPos 0
I =  10055442
number of imo 3916
dfNewJourney 10
lenPos 0
I =  10060020
number of imo 3917
dfNewJourney 2
lenPos 1806
I =  9180126
number of imo 3918
1806
===============
dfNewJourney 3
lenPos 0
I =  10058386
number of imo 3919
dfNewJourney 9
lenPos 0
I =  10059548
number of imo 3920
dfNewJourney 8
lenPos 0
I =  10060656
number of imo 3921
dfNewJourney 12
lenPos 0
I =  10041640
number of imo 3922
dfNewJourney 2
lenPos 0
I =  10048823
number of imo 3923
dfNewJourney 11
lenPos 0
I =  10044257
number of imo 3924
dfNewJourney 9
lenPos 0
I =  10058387
number of imo 3925
dfNewJourney 10
lenPos 0
I =  10048935
number of imo 3926
dfNewJourney 9
lenPos 0
I =  10061397
number of imo 3927
dfNewJourney 11
lenPos 0
I =  10071226
number of imo 3928
dfNewJourney 8
lenPos 0
I =  10056672
number of imo 3929
dfNewJourney 12
lenPos 0
I =  10059744
number of imo 3930
dfNewJourney 8
lenPos 0
I =  10042880
number of imo 3931
dfNewJourney 12
lenPos 0
I =  10103640
number of imo 3932
dfNewJourney 4
lenPos 0
I =  10103392
number of imo 3933
dfNewJourney 6
lenPos 0
I =  10060552
number of imo 3934
dfNewJourney 10
lenPos 0
I =  10059547
number of imo 3935
dfNewJourney 7
lenPos 0
I =  10031350
number of imo 3936
dfNewJourney 11
lenPos 0
I =  10036596
number of imo 3937
dfNewJourney 8
lenPos 0
I =  10058664
number of imo 3938
dfNewJourney 10
lenPos 0
I =  10077562
number of imo 3939
dfNewJourney 1
lenPos 1898
I =  9313436
number of imo 3940
1898
===============
dfNewJourney 13
lenPos 0
I =  10060987
number of imo 3941
dfNewJourney 8
lenPos 0
I =  10048251
number of imo 3942
dfNewJourney 6
lenPos 0
I =  10050575
number of imo 3943
dfNewJourney 10
lenPos 0
I =  10060553
number of imo 3944
dfNewJourney 1
lenPos 0
I =  10070291
number of imo 3945
dfNewJourney 6
lenPos 0
I =  10046649
number of imo 3946
dfNewJourney 10
lenPos 0
I =  10061680
number of imo 3947
dfNewJourney 8
lenPos 0
I =  10072431
number of imo 3948
dfNewJourney 1
lenPos 1799
I =  9351529
number of imo 3949
1799
===============
dfNewJourney 7
lenPos 0
I =  10060988
number of imo 3950
dfNewJourney 8
lenPos 0
I =  10055951
number of imo 3951
dfNewJourney 8
lenPos 0
I =  10028897
number of imo 3952
dfNewJourney 6
lenPos 0
I =  10029922
number of imo 3953
dfNewJourney 7
lenPos 0
I =  10029932
number of imo 3954
dfNewJourney 7
lenPos 0
I =  10060657
number of imo 3955
dfNewJourney 7
lenPos 0
I =  10049588
number of imo 3956
dfNewJourney 2
lenPos 0
I =  10050417
number of imo 3957
dfNewJourney 7
lenPos 0
I =  10057124
number of imo 3958
dfNewJourney 1
lenPos 0
I =  8906822
number of imo 3959
dfNewJourney 8
lenPos 0
I =  10060986
number of imo 3960
dfNewJourney 7
lenPos 0
I =  10048824
number of imo 3961
dfNewJourney 8
lenPos 0
I =  10047133
number of imo 3962
dfNewJourney 7
lenPos 0
I =  10060658
number of imo 3963
dfNewJourney 8
lenPos 0
I =  10055443
number of imo 3964
dfNewJourney 4
lenPos 0
I =  10056698
number of imo 3965
dfNewJourney 7
lenPos 0
I =  10048252
number of imo 3966
dfNewJourney 5
lenPos 0
I =  10082413
number of imo 3967
dfNewJourney 11
lenPos 0
I =  10057123
number of imo 3968
dfNewJourney 5
lenPos 0
I =  10046231
number of imo 3969
dfNewJourney 7
lenPos 0
I =  10034334
number of imo 3970
dfNewJourney 8
lenPos 0
I =  10048253
number of imo 3971
dfNewJourney 5
lenPos 0
I =  10076793
number of imo 3972
dfNewJourney 10
lenPos 0
I =  10061682
number of imo 3973
dfNewJourney 5
lenPos 0
I =  10060989
number of imo 3974
dfNewJourney 5
lenPos 0
I =  10084043
number of imo 3975
dfNewJourney 5
lenPos 0
I =  10087090
number of imo 3976
dfNewJourney 7
lenPos 0
I =  10060681
number of imo 3977
dfNewJourney 7
lenPos 0
I =  10101186
number of imo 3978
dfNewJourney 7
lenPos 0
I =  10060659
number of imo 3979
dfNewJourney 6
lenPos 0
I =  10092078
number of imo 3980
dfNewJourney 5
lenPos 0
I =  10096956
number of imo 3981
dfNewJourney 6
lenPos 0
I =  10087031
number of imo 3982
dfNewJourney 1
lenPos 1812
I =  9014339
number of imo 3983
1812
===============
dfNewJourney 7
lenPos 0
I =  10055952
number of imo 3984
dfNewJourney 4
lenPos 0
I =  10048572
number of imo 3985
dfNewJourney 5
lenPos 0
I =  10041664
number of imo 3986
dfNewJourney 6
lenPos 0
I =  10061230
number of imo 3987
dfNewJourney 4
lenPos 0
I =  10050416
number of imo 3988
dfNewJourney 1
lenPos 0
I =  10029198
number of imo 3989
dfNewJourney 2
lenPos 0
I =  10061989
number of imo 3990
dfNewJourney 3
lenPos 0
I =  10086478
number of imo 3991
dfNewJourney 9
lenPos 0
I =  10092076
number of imo 3992
dfNewJourney 6
lenPos 0
I =  10076792
number of imo 3993
dfNewJourney 3
lenPos 0
I =  10050576
number of imo 3994
dfNewJourney 6
lenPos 0
I =  10048936
number of imo 3995
dfNewJourney 1
lenPos 0
I =  10007601
number of imo 3996
dfNewJourney 6
lenPos 0
I =  10086668
number of imo 3997
dfNewJourney 4
lenPos 0
I =  10096952
number of imo 3998
dfNewJourney 4
lenPos 0
I =  10050047
number of imo 3999
dfNewJourney 2
lenPos 0
I =  10078730
number of imo 4000
dfNewJourney 5
lenPos 0
I =  10049589
number of imo 4001
dfNewJourney 5
lenPos 0
I =  10059545
number of imo 4002
dfNewJourney 6
lenPos 0
I =  10058696
number of imo 4003
dfNewJourney 3
lenPos 0
I =  10061681
number of imo 4004
dfNewJourney 3
lenPos 0
I =  10050048
number of imo 4005
dfNewJourney 5
lenPos 0
I =  10050419
number of imo 4006
dfNewJourney 2
lenPos 1360
I =  9503574
number of imo 4007
1360
===============
dfNewJourney 1
lenPos 0
I =  10050424
number of imo 4008
dfNewJourney 5
lenPos 0
I =  10056699
number of imo 4009
dfNewJourney 6
lenPos 0
I =  10096957
number of imo 4010
dfNewJourney 5
lenPos 0
I =  10082414
number of imo 4011
dfNewJourney 6
lenPos 0
I =  10048321
number of imo 4012
dfNewJourney 2
lenPos 0
I =  10056163
number of imo 4013
dfNewJourney 2
lenPos 1824
I =  9418494
number of imo 4014

1824
===============
dfNewJourney 4
lenPos 0
I =  10061683
number of imo 4015
dfNewJourney 4
lenPos 0
I =  10047134
number of imo 4016
dfNewJourney 2
lenPos 0
I =  10060060
number of imo 4017
dfNewJourney 3
lenPos 0
I =  10050577
number of imo 4018
dfNewJourney 10
lenPos 0
I =  10092099
number of imo 4019
dfNewJourney 4
lenPos 0
I =  10050418
number of imo 4020
dfNewJourney 5
lenPos 0
I =  10082412
number of imo 4021
dfNewJourney 1
lenPos 0
I =  10056162
number of imo 4022
dfNewJourney 4
lenPos 0
I =  10049590
number of imo 4023
dfNewJourney 5
lenPos 0
I =  10061228
number of imo 4024
dfNewJourney 3
lenPos 0
I =  10092100
number of imo 4025
dfNewJourney 2
lenPos 0
I =  10076794
number of imo 4026
dfNewJourney 2
lenPos 0
I =  10082410
number of imo 4027
dfNewJourney 5
lenPos 0
I =  10085940
number of imo 4028
dfNewJourney 4
lenPos 0
I =  10055444
number of imo 4029
dfNewJourney 1
lenPos 0
I =  10056854
number of imo 4030
dfNewJourney 2
lenPos 1849
I =  9410002
number of imo 4031
1849
===============
dfNewJourney 2
lenPos 0
I =  10082411
number of imo 4032
dfNewJourney 2
lenPos 0
I =  10058718
number of imo 4033
dfNewJourney 1
lenPos 0
I =  10086477
number of imo 4034
dfNewJourney 3
lenPos 0
I =  10087032
number of imo 4035
dfNewJourney 2
lenPos 0
I =  10058388
number of imo 4036
dfNewJourney 4
lenPos 0
I =  10048927
number of imo 4037
dfNewJourney 1
lenPos 1886
I =  9255270
number of imo 4038
1886
===============
dfNewJourney 2
lenPos 0
I =  10061229
number of imo 4039
dfNewJourney 2
lenPos 0
I =  10060544
number of imo 4040
dfNewJourney 4
lenPos 0
I =  10086479
number of imo 4041
dfNewJourney 2
lenPos 0
I =  10092125
number of imo 4042
dfNewJourney 5
lenPos 0
I =  10058706
number of imo 4043
dfNewJourney 1
lenPos 0
I =  10082409
number of imo 4044
dfNewJourney 2
lenPos 0
I =  10086667
number of imo 4045
dfNewJourney 1
lenPos 1781
I =  9283514
number of imo 4046
1781
===============
dfNewJourney 2
lenPos 0
I =  10100982
number of imo 4047
dfNewJourney 3
lenPos 0
I =  10060078
number of imo 4048
dfNewJourney 2
lenPos 0
I =  10089620
number of imo 4049
dfNewJourney 3
lenPos 0
I =  10100536
number of imo 4050
dfNewJourney 4
lenPos 0
I =  10076702
number of imo 4051
dfNewJourney 3
lenPos 1730
I =  9241695
number of imo 4052
1730
===============
dfNewJourney 1
lenPos 0
I =  10007576
number of imo 4053
dfNewJourney 2
lenPos 0
I =  10056094
number of imo 4054
dfNewJourney 3
lenPos 0
I =  10069233
number of imo 4055
dfNewJourney 2
lenPos 0
I =  10076703
number of imo 4056
dfNewJourney 3
lenPos 0
I =  10048928
number of imo 4057
dfNewJourney 2
lenPos 1866
I =  9194139
number of imo 4058
1866
===============
dfNewJourney 1
lenPos 0
I =  10079425
number of imo 4059
dfNewJourney 1
lenPos 0
I =  10086476
number of imo 4060
dfNewJourney 1
lenPos 0
I =  10094627
number of imo 4061
dfNewJourney 2
lenPos 0
I =  10076701
number of imo 4062
dfNewJourney 1
lenPos 0
I =  10093360
number of imo 4063
dfNewJourney 1
lenPos 1849
I =  9407407
number of imo 4064
1849
===============
dfNewJourney 2
lenPos 0
I =  10076795
number of imo 4065
dfNewJourney 1
lenPos 1882
I =  9255880
number of imo 4066
1882
===============
dfNewJourney 1
lenPos 1872
I =  9384124
number of imo 4067
1872
===============
dfNewJourney 2
lenPos 0
I =  10061227
number of imo 4068
dfNewJourney 3
lenPos 0
I =  10056704
number of imo 4069
dfNewJourney 2
lenPos 0
I =  10100537
number of imo 4070
dfNewJourney 2
lenPos 0
I =  10056700
number of imo 4071
dfNewJourney 2
lenPos 0
I =  10085025
number of imo 4072
dfNewJourney 2
lenPos 0
I =  10058389
number of imo 4073
dfNewJourney 2
lenPos 0
I =  10049591
number of imo 4074
dfNewJourney 2
lenPos 0
I =  10048573
number of imo 4075
dfNewJourney 1
lenPos 0
I =  10092124
number of imo 4076
dfNewJourney 1
lenPos 0
I =  10058697
number of imo 4077
dfNewJourney 2
lenPos 0
I =  10103761
number of imo 4078
dfNewJourney 1
lenPos 0
I =  10033612
number of imo 4079
dfNewJourney 1
lenPos 0
I =  10088647
number of imo 4080
dfNewJourney 2
lenPos 0
I =  10094636
number of imo 4081
dfNewJourney 1
lenPos 0
I =  10073291
number of imo 4082
dfNewJourney 1
lenPos 0
I =  10104054
number of imo 4083
dfNewJourney 1
lenPos 0
I =  10088648
number of imo 4084
dfNewJourney 1
lenPos 0
I =  10096951
number of imo 4085
dfNewJourney 1
lenPos 0
I =  10061506
number of imo 4086
dfNewJourney 2
lenPos 0
I =  10100986
number of imo 4087
dfNewJourney 2
lenPos 0
I =  10100983
number of imo 4088
dfNewJourney 1
lenPos 1859
I =  9315898
number of imo 4089
1859
===============
dfNewJourney 2
lenPos 0
I =  10078731
number of imo 4090
dfNewJourney 1
lenPos 0
I =  10058705
number of imo 4091
dfNewJourney 1
lenPos 0
I =  10060873
number of imo 4092
dfNewJourney 1
lenPos 0
I =  10069234
number of imo 4093
dfNewJourney 1
lenPos 0
I =  10100987
number of imo 4094
dfNewJourney 1
lenPos 0
I =  10100535
number of imo 4095
dfNewJourney 1
lenPos 0
I =  10050578
number of imo 4096
dfNewJourney 1
lenPos 0
I =  10057125
number of imo 4097
dfNewJourney 1
lenPos 0
I =  10097228
number of imo 4098
dfNewJourney 1
lenPos 0
I =  10089622
number of imo 4099
dfNewJourney 1
lenPos 0
I =  10103755
number of imo 4100
dfNewJourney 1
lenPos 0
I =  10058695
number of imo 4101
dfNewJourney 1
lenPos 0
I =  10056831
number of imo 4102
dfNewJourney 1
lenPos 334
I =  9547673
number of imo 4103
334
===============
dfNewJourney 1
lenPos 0
I =  10100534
number of imo 4104
dfNewJourney 1
lenPos 0
I =  10104055
number of imo 4105
dfNewJourney 1
lenPos 0
I =  10060545
number of imo 4106

# Thrash code.

In [ ]:
dfLegTable.to_excel("Leg Table.xlsx")
dfLegTable

In [12]:
#dfNewPorts = pd.read_csv(r"\Users\Sowaio\Desktop\Research Assistent\RE__[EXTERNAL]_RE__Fairplay_and_AIS_data\portlist.csv")
#dfCorrPorts = pd.read_excel("\\Users\\Sowaio\\Desktop\\Research Assistent\\RE__[EXTERNAL]_RE__Fairplay_and_AIS_data\\new_portCoordinates.xlsx")
#dfPorts = pd.read_csv("\\Users\\Sowaio\\Desktop\\Research Assistent\\RE__[EXTERNAL]_RE__Fairplay_and_AIS_data\\portlist.csv")

In [33]:
#dfCorrPorts(columns={"Ports": "Terminal", })

In [ ]:
startDate = '2013-12-30 05:34:03'
endDate = '2014-01-07 13:30:04'
ImoNr = 9301421

test = dfPos.loc[(dfPos["ais_position_timestamp"].apply(pd.to_datetime) >= startDate) & (dfPos["ais_position_timestamp"].apply(pd.to_datetime) <= endDate) & (dfPos["ship_id"] == ImoNr)]

In [ ]:
endDate = '2014-01-07 13:30:04'
ImoNr = 9301421

test = dfPosNy.loc[(dfPosNy["ship_imo"] == ImoNr)]

TypeError: 'DataFrame' object is not callable

In [ ]:
dfPos.dtypes

In [ ]:
test

In [ ]:
conda install accelerate

In [55]:

test2 = dfPorts['PORT'].unique()

portList = dfCorrPorts["Ports"].unique()
listToAppend = []
i = 0
for port in test2:
    if port not in portList:
        i += 1
        temp = dfPorts.loc[dfPorts["PORT"] == port]
        temp = temp.iloc[0]
        lat, lon = temp['lat'], temp['lon']
        #print(port, i)
        listToAppend.append([port, lat, lon])

newPort = pd.DataFrame(listToAppend, columns = ["Ports", "Latitude", "Longtitude"])
dfPort = pd.concat([dfCorrPorts, newPort], axis = 0)
dfPort

,Unnamed: 0,Unnamed: 0.1,Ports,Latitude,Longtitude,Gruppe
0,0.0,0.0,--,46.314475,11.048029,1.0
1,1.0,1.0,{Unknown Port},51.475426,140.768982,4.0
2,2.0,2.0,ABADAN,34.940645,127.695951,10.0
3,3.0,3.0,ABIDJAN,35.724025,140.004469,9.0
4,4.0,4.0,Abidjan (Banco Bay),5.320357,-4.016107,9.0
...,...,...,...,...,...,...
1581,NaN,NaN,Ash Shihr Terminal,14.674600,49.520833,NaN
1582,NaN,NaN,Bal Haf LNG,13.956700,48.166667,NaN
1583,NaN,NaN,Gulf of Aden Transit Corrido - Yemen,11.841700,45.000000,NaN
1584,NaN,NaN,Red Sea Southern - Yemen,12.618300,43.366667,NaN
1585,NaN,NaN,Rudham Terminal,13.966700,47.916667,NaN

In [25]:
dfPos14_1["ais_position_timestamp"].iloc[0]

Timestamp('2014-01-01 13:01:04')

In [31]:
dfPort.to_excel('UsethisPort.xlsx')

NameError: name 'dfPort' is not defined

In [3]:
dfLegTable = pd.read_csv(r"C:\Users\Sowaio\Desktop\Research Assistent\RE__[EXTERNAL]_RE__Fairplay_and_AIS_data\Leg Table.csv", delimiter = ",")
dfLegTable

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Unnamed: 0.1.1.1.1.1,ImoNr,Leg_id_legs (# of reports),Leg Length (days covered),Avg. Speed-Median,...,Depature_port_latitude,Depature_port_longtitude,Destination_port_latitude,Destination_port_longtitude,Distance to departure port,Distance to destination port,RegionDepa,RegionDest,journey_start_timestamp,journey_end_timestamp
0,0,0.0,0.0,0.0,0.0,67790.0,8320119.0,0.0,8.0,12.716655,...,-25.066658,46.963536,-6.030167,105.938098,NaN,NaN,14.0,15.0,2014-01-01 00:12:45,NaN
1,1,1.0,1.0,1.0,1.0,219249.0,9413561.0,21.0,23.0,9.580121,...,-20.163728,57.504533,404.000000,404.000000,5786.322009,404.000000,14.0,404.0,2014-01-01 00:19:35,NaN
2,2,2.0,2.0,2.0,2.0,428400.0,10007629.0,0.0,20.0,11.613181,...,-36.712699,-72.976679,45.825540,-77.115065,NaN,NaN,18.0,0.0,2014-01-01 00:23:18,NaN
3,3,3.0,3.0,3.0,3.0,74330.0,9317248.0,18.0,18.0,13.936579,...,-39.057994,174.080647,29.862219,121.620387,2.182896,41.926370,10.0,6.0,2014-01-01 00:34:30,NaN
4,4,4.0,4.0,4.0,4.0,387110.0,9301421.0,7.0,7.0,13.671880,...,51.475426,140.768982,34.940645,127.695951,5.806720,1144.176590,25.0,6.0,2014-02-05 12:23:14,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253457,348039,NaN,NaN,NaN,NaN,NaN,9255880.0,1.0,1.0,7.179548,...,404.000000,404.000000,-34.664639,-58.729443,404.000000,6140.419880,404.0,18.0,2019-03-21 12:39:36,NaN
253458,377015,NaN,NaN,NaN,NaN,NaN,9232876.0,0.0,0.0,9.306790,...,40.747568,29.788231,44.176716,28.650760,NaN,NaN,13.0,13.0,2019-03-21 15:31:47,NaN
253459,319318,NaN,NaN,NaN,NaN,NaN,9467756.0,1.0,1.0,12.437860,...,3.297856,99.402835,21.992287,69.242942,2073.418821,47.569065,15.0,24.0,2019-03-21 15:38:01,NaN
253460,381616,NaN,NaN,NaN,NaN,NaN,9337341.0,1.0,1.0,10.471350,...,28.954137,-95.359662,29.387225,-94.992736,65.825678,67.696472,11.0,11.0,2019-03-21 16:46:38,NaN
253461,331017,NaN,NaN,NaN,NaN,NaN,9255282.0,1.0,0.0,4.640526,...,404.000000,404.000000,51.321914,4.320102,404.000000,0.363565,404.0,8.0,2019-03-21 21:35:22,NaN

In [10]:
dfLegTable = dfLegTable.iloc[:, 6:]

In [11]:
dfLegTable

,ImoNr,Leg_id_legs (# of reports),Leg Length (days covered),Avg. Speed-Median,Avg. speed by time weight,std of Speed-Median,# of ME-Power reports,# of valid ME-Power reports,Min_Max_Draft_Normalization,Loading Condition,...,Depature_port_latitude,Depature_port_longtitude,Destination_port_latitude,Destination_port_longtitude,Distance to departure port,Distance to destination port,RegionDepa,RegionDest,journey_start_timestamp,journey_end_timestamp
0,8320119.0,0.0,8.0,12.716655,NaN,NaN,NaN,NaN,NaN,1.0,...,-25.066658,46.963536,-6.030167,105.938098,NaN,NaN,14.0,15.0,2014-01-01 00:12:45,NaN
1,9413561.0,21.0,23.0,9.580121,NaN,NaN,NaN,NaN,NaN,0.0,...,-20.163728,57.504533,404.000000,404.000000,5786.322009,404.000000,14.0,404.0,2014-01-01 00:19:35,NaN
2,10007629.0,0.0,20.0,11.613181,NaN,NaN,NaN,NaN,NaN,1.0,...,-36.712699,-72.976679,45.825540,-77.115065,NaN,NaN,18.0,0.0,2014-01-01 00:23:18,NaN
3,9317248.0,18.0,18.0,13.936579,NaN,NaN,NaN,NaN,NaN,1.0,...,-39.057994,174.080647,29.862219,121.620387,2.182896,41.926370,10.0,6.0,2014-01-01 00:34:30,NaN
4,9301421.0,7.0,7.0,13.671880,NaN,NaN,NaN,NaN,NaN,1.0,...,51.475426,140.768982,34.940645,127.695951,5.806720,1144.176590,25.0,6.0,2014-02-05 12:23:14,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253457,9255880.0,1.0,1.0,7.179548,NaN,NaN,NaN,NaN,NaN,0.0,...,404.000000,404.000000,-34.664639,-58.729443,404.000000,6140.419880,404.0,18.0,2019-03-21 12:39:36,NaN
253458,9232876.0,0.0,0.0,9.306790,NaN,NaN,NaN,NaN,NaN,0.0,...,40.747568,29.788231,44.176716,28.650760,NaN,NaN,13.0,13.0,2019-03-21 15:31:47,NaN
253459,9467756.0,1.0,1.0,12.437860,NaN,NaN,NaN,NaN,NaN,0.0,...,3.297856,99.402835,21.992287,69.242942,2073.418821,47.569065,15.0,24.0,2019-03-21 15:38:01,NaN
253460,9337341.0,1.0,1.0,10.471350,NaN,NaN,NaN,NaN,NaN,0.0,...,28.954137,-95.359662,29.387225,-94.992736,65.825678,67.696472,11.0,11.0,2019-03-21 16:46:38,NaN
253461,9255282.0,1.0,0.0,4.640526,NaN,NaN,NaN,NaN,NaN,1.0,...,404.000000,404.000000,51.321914,4.320102,404.000000,0.363565,404.0,8.0,2019-03-21 21:35:22,NaN

In [17]:
ports = dfLegTable[dfLegTable["Distance to destination port"].isnull().values]
ports = ports["Departure_Port"].unique()

In [29]:
dfNewPorts
dfNewPorts = dfNewPorts.rename(columns={"PORT": "Ports", "lat": "Latitude", "lon": "Longtitude"})
dfNewPorts = dfNewPorts.drop(['COUNTRY', "GeoLocation;"], axis=1)

In [9]:
shipImo = dfPos["ship_imo"].unique() #dfJourney["ship_id"].unique()

dfPosCopy = dfPos.copy()
dfPosCopy["Journey Number"] = ""
dfPosCopy["sailing distance"] = ""

totalLen = len(shipImo)
count = 0 
for i in shipImo:
    count += 1
    dfNewPos = dfPosCopy.loc[(dfPosCopy["ship_id"] == i)]
    #print(dfNewPos)
    dfNewJourney = dfJourney.loc[(dfJourney["ship_id"] == int(i))]
    print("dfNewJourney", len(dfNewJourney))
    lenPos = len(dfNewPos)
    print('lenPos', lenPos)
    done = False
    print("I = ", i, (count/totalLen) * 100 )
    if dfNewPos.empty == True or dfNewJourney.empty == True:
        pass
    else:
        for index, row in dfNewJourney.iterrows():
            startDate = row["journey_start_timestamp"]#.apply(pd.to_datetime)
            endDate = row["journey_end_timestamp"]#.apply(pd.to_datetime)
            journeyID = row['journey_id']
            
            #print(type(startDate), type(endDate))
            dfTestTable = dfNewPos.loc[(dfNewPos["ais_position_timestamp"].apply(pd.to_datetime) >= startDate) & (dfNewPos["ais_position_timestamp"].apply(pd.to_datetime) <= endDate)]
            
            #print(dfTestTable)
            
            preLong = None
            preLat = None
            
            for testIndex, testRow in dfTestTable.iterrows():
                lat = testRow["ais_position_latitude"]
                long = testRow["ais_position_longitude"]
                #print(journeyID)
                
                dfPosCopy.at[testIndex, "Journey Number"] = str(journeyID)
                
                
                if preLong == None and preLat == None:
                    preLong = long
                    preLat = lat
                else:
                    try:
                        dist = distance((preLat, preLong), (lat, long)).miles * 0.868976242
                        preLong = long
                        preLat = lat
                        dfPosCopy.at[index, "sailing distance"] = str(dist)
                    except:
                        dfPosCopy.at[index, "sailing distance"] = "999999"

dfNewJourney 225
lenPos 1808
I =  9301421 0.025163563160543533
dfNewJourney 237
lenPos 1876
I =  9301419 0.050327126321087066
dfNewJourney 182
lenPos 1830
I =  9260081 0.0754906894816306
dfNewJourney 215
lenPos 1710
I =  9301380 0.10065425264217413
dfNewJourney 221
lenPos 1766
I =  9301392 0.12581781580271767
dfNewJourney 206
lenPos 1729
I =  9301407 0.1509813789632612
dfNewJourney 107
lenPos 1611
I =  9281554 0.17614494212380472
dfNewJourney 153
lenPos 1788
I =  9208124 0.20130850528434827
dfNewJourney 190
lenPos 1813
I =  9249130 0.22647206844489182
dfNewJourney 209
lenPos 1876
I =  9208112 0.25163563160543534
dfNewJourney 143
lenPos 1803
I =  9208100 0.27679919476597886
dfNewJourney 224
lenPos 1819
I =  9360415 0.3019627579265224
dfNewJourney 181
lenPos 1823
I =  9360427 0.32712632108706596
dfNewJourney 97
lenPos 1548
I =  9354301 0.35228988424760943
dfNewJourney 125
lenPos 1541
I =  9281566 0.377453447408153
dfNewJourney 205
lenPos 1716
I =  9263203 0.40261701056869653
dfNewJourney 96
lenPos 1742
I =  9354313 0.42778057372924005
dfNewJourney 139
lenPos 1651
I =  9265756 0.45294413688978363
dfNewJourney 172
lenPos 1766
I =  9360441 0.4781077000503271
dfNewJourney 154
lenPos 1774
I =  9319870 0.5032712632108707
dfNewJourney 69
lenPos 1860
I =  9346469 0.5284348263714143
dfNewJourney 189
lenPos 1813
I =  9249128 0.5535983895319577
dfNewJourney 118
lenPos 1830
I =  9346457 0.5787619526925012
dfNewJourney 133
lenPos 1816
I =  9346445 0.6039255158530448
dfNewJourney 259
lenPos 1836
I =  9352298 0.6290890790135883
dfNewJourney 246
lenPos 1819
I =  9352303 0.6542526421741319
dfNewJourney 149
lenPos 1807
I =  9260079 0.6794162053346754
dfNewJourney 16
lenPos 1874
I =  9410882 0.7045797684952189
dfNewJourney 102
lenPos 1824
I =  9346433 0.7297433316557624
dfNewJourney 233
lenPos 1846
I =  9299862 0.754906894816306
dfNewJourney 236
lenPos 1872
I =  9327384 0.7800704579768495
dfNewJourney 117
lenPos 1820
I =  9385142 0.8052340211373931
dfNewJourney 212
lenPos 1872
I =  9314806 0.8303975842979365
dfNewJourney 155
lenPos 1708
I =  9384447 0.8555611474584801
dfNewJourney 220
lenPos 1856
I =  9314818 0.8807247106190236
dfNewJourney 85
lenPos 1740
I =  9550682 0.9058882737795673
dfNewJourney 126
lenPos 1701
I =  9311713 0.9310518369401107
dfNewJourney 236
lenPos 1861
I =  9314820 0.9562154001006542
dfNewJourney 47
lenPos 1312
I =  9150767 0.9813789632611978
dfNewJourney 179
lenPos 1773
I =  9360439 1.0065425264217414
dfNewJourney 97
lenPos 1743
I =  9281580 1.031706089582285
dfNewJourney 108
lenPos 1565
I =  9144067 1.0568696527428285
dfNewJourney 75
lenPos 1629
I =  9409259 1.0820332159033719
dfNewJourney 11
lenPos 1797
I =  9410870 1.1071967790639154
dfNewJourney 66
lenPos 1339
I =  9162502 1.132360342224459
dfNewJourney 53
lenPos 1676
I =  9162514 1.1575239053850024
dfNewJourney 156
lenPos 1854
I =  9418482 1.1826874685455462
dfNewJourney 148
lenPos 1763
I =  9384306 1.2078510317060895
dfNewJourney 45
lenPos 953
I =  9163269 1.2330145948666331
dfNewJourney 32
lenPos 1881
I =  9039121 1.2581781580271767
dfNewJourney 119
lenPos 1856
I =  9276016 1.28334172118772
dfNewJourney 115
lenPos 1679
I =  9276030 1.3085052843482639
dfNewJourney 121
lenPos 1687
I =  9276028 1.3336688475088072
dfNewJourney 143
lenPos 1850
I =  9305855 1.3588324106693508
dfNewJourney 211
lenPos 1728
I =  9301287 1.3839959738298944
dfNewJourney 109
lenPos 1795
I =  9203801 1.4091595369904377
dfNewJourney 249
lenPos 1886
I =  9380477 1.4343231001509815
dfNewJourney 255
lenPos 1890
I =  9380489 1.4594866633115249
dfNewJourney 167
lenPos 1681
I =  9448334 1.4846502264720685
dfNewJourney 75
lenPos 1714
I =  9488413 1.509813789632612
dfNewJourney 129
lenPos 1801
I =  9172193 1.5349773527931554
dfNewJourney 116
lenPos 1814
I =  9246798 1.560140915953699
dfNewJourney 112
lenPos 1801
I =  9246803 1.5853044791142425
dfNewJourney 109
lenPos 1722
I =  9240897 1.6104680422747861
dfNewJourney 114
lenPos 1748
I =  9240885 1.6356316054353295
dfNewJourney 125
lenPos 1819
I =  9250488 1.660795168595873
dfNewJourney 95
lenPos 1362
I =  9250490 1.6859587317564169
dfNewJourney 159
lenPos 1662
I =  9236999 1.7111222949169602
dfNewJourney 126
lenPos 1739
I =  9265407 1.7362858580775038
dfNewJourney 120
lenPos 1705
I =  9288021 1.7614494212380472
dfNewJourney 110
lenPos 1702
I =  9262091 1.7866129843985907
dfNewJourney 122
lenPos 1829
I =  9263693 1.8117765475591345
dfNewJourney 133
lenPos 1342
I =  9215098 1.8369401107196779
dfNewJourney 113
lenPos 1857
I =  9263708 1.8621036738802215
dfNewJourney 195
lenPos 1678
I =  9303728 1.8872672370407648
dfNewJourney 212
lenPos 1840
I =  9303730 1.9124308002013084
dfNewJourney 358
lenPos 1831
I =  9340582 1.9375943633618522
dfNewJourney 151
lenPos 1334
I =  9309978 1.9627579265223956
dfNewJourney 97
lenPos 1212
I =  9341433 1.9879214896829391
dfNewJourney 91
lenPos 1650
I =  9299355 2.0130850528434827
dfNewJourney 118
lenPos 1765
I =  9328132 2.038248616004026
dfNewJourney 190
lenPos 1674
I =  9309980 2.06341217916457
dfNewJourney 115
lenPos 1827
I =  9328144 2.0885757423251134
dfNewJourney 277
lenPos 1893
I =  9183609 2.113739305485657
dfNewJourney 148
lenPos 1537
I =  9282986 2.1389028686462
dfNewJourney 98
lenPos 1848
I =  9247778 2.1640664318067437
dfNewJourney 149
lenPos 1713
I =  9215086 2.1892299949672873
dfNewJourney 116
lenPos 1796
I =  9290646 2.214393558127831
dfNewJourney 200
lenPos 1552
I =  9376816 2.2395571212883745
dfNewJourney 103
lenPos 1740
I =  9375616 2.264720684448918
dfNewJourney 132
lenPos 1875
I =  9375575 2.2898842476094616
dfNewJourney 123
lenPos 1817
I =  9375604 2.3150478107700048
dfNewJourney 144
lenPos 1816
I =  9448310 2.340211373930549
dfNewJourney 138
lenPos 1566
I =  9376828 2.3653749370910924
dfNewJourney 141
lenPos 1807
I =  9390769 2.3905385002516355
dfNewJourney 137
lenPos 1846
I =  9392468 2.415702063412179
dfNewJourney 149
lenPos 1815
I =  9425502 2.4408656265727227
dfNewJourney 91
lenPos 1522
I =  9243320 2.4660291897332662
dfNewJourney 157
lenPos 1672
I =  9133068 2.49119275289381
dfNewJourney 80
lenPos 1702
I =  9116905 2.5163563160543534
dfNewJourney 352
lenPos 1634
I =  9334698 2.541519879214897
dfNewJourney 373
lenPos 1850
I =  9334703 2.56668344237544
dfNewJourney 115
lenPos 1561
I =  9285718 2.5918470055359837
dfNewJourney 175
lenPos 1859
I =  9274628 2.6170105686965277
dfNewJourney 92
lenPos 1852
I =  9285720 2.642174131857071
dfNewJourney 140
lenPos 1757
I =  9285756 2.6673376950176144
dfNewJourney 181
lenPos 1810
I =  9285744 2.692501258178158
dfNewJourney 90
lenPos 1763
I =  9282481 2.7176648213387016
dfNewJourney 183
lenPos 1746
I =  9297357 2.742828384499245
dfNewJourney 158
lenPos 1695
I =  9196709 2.7679919476597887
dfNewJourney 113
lenPos 1730
I =  9311531 2.7931555108203323
dfNewJourney 101
lenPos 1640
I =  9209295 2.8183190739808754
dfNewJourney 72
lenPos 1437
I =  9167150 2.843482637141419
dfNewJourney 84
lenPos 1776
I =  9275660 2.868646200301963
dfNewJourney 148
lenPos 1685
I =  9285835 2.893809763462506
dfNewJourney 149
lenPos 1770
I =  9312925 2.9189733266230498
dfNewJourney 164
lenPos 1805
I =  9299446 2.9441368897835933
dfNewJourney 191
lenPos 1696
I =  9340594 2.969300452944137
dfNewJourney 135
lenPos 1803
I =  9315769 2.9944640161046805
dfNewJourney 174
lenPos 1822
I =  9381500 3.019627579265224
dfNewJourney 224
lenPos 1833
I =  9347308 3.0447911424257676
dfNewJourney 225
lenPos 1874
I =  9353113 3.069954705586311
dfNewJourney 199
lenPos 1830
I =  9353125 3.0951182687468544
dfNewJourney 243
lenPos 1862
I =  9353137 3.120281831907398
dfNewJourney 177
lenPos 1822
I =  9353149 3.1454453950679415
dfNewJourney 187
lenPos 1870
I =  9353084 3.170608958228485
dfNewJourney 103
lenPos 1751
I =  9364215 3.1957725213890287
dfNewJourney 157
lenPos 1874
I =  9387279 3.2209360845495723
dfNewJourney 156
lenPos 1641
I =  9396725 3.246099647710116
dfNewJourney 156
lenPos 1897
I =  9388003 3.271263210870659
dfNewJourney 160
lenPos 1834
I =  9388015 3.2964267740312025
dfNewJourney 114
lenPos 1768
I =  9388027 3.321590337191746
dfNewJourney 181
lenPos 1861
I =  9397212 3.34675390035229
dfNewJourney 86
lenPos 1545
I =  9127667 3.3719174635128337
dfNewJourney 117
lenPos 1749
I =  9411135 3.3970810266733773
dfNewJourney 79
lenPos 1685
I =  9411989 3.4222445898339204

dfNewJourney 159
lenPos 1743
I =  9411991 3.447408152994464
dfNewJourney 125
lenPos 1831
I =  9216913 3.4725717161550076
dfNewJourney 98
lenPos 1818
I =  9216925 3.497735279315551
dfNewJourney 128
lenPos 1631
I =  9237228 3.5228988424760943
dfNewJourney 106
lenPos 1567
I =  9251810 3.548062405636638
dfNewJourney 106
lenPos 1711
I =  9247780 3.5732259687971815
dfNewJourney 107
lenPos 1844
I =  9251822 3.5983895319577255
dfNewJourney 182
lenPos 1730
I =  9251573 3.623553095118269
dfNewJourney 106
lenPos 1495
I =  9247792 3.6487166582788126
dfNewJourney 99
lenPos 1487
I =  9258868 3.6738802214393558
dfNewJourney 225
lenPos 1594
I =  9167148 3.6990437845998994
dfNewJourney 79
lenPos 1442
I =  9113551 3.724207347760443
dfNewJourney 130
lenPos 1800
I =  9266841 3.7493709109209865
dfNewJourney 101
lenPos 1554
I =  9266853 3.7745344740815296
dfNewJourney 115
lenPos 1744
I =  9266865 3.7996980372420732
dfNewJourney 117
lenPos 1765
I =  9266877 3.824861600402617
dfNewJourney 82
lenPos 1828
I =  9275658 3.8500251635631604
dfNewJourney 182
lenPos 1733
I =  9120944 3.8751887267237044
dfNewJourney 118
lenPos 1800
I =  9198094 3.900352289884248
dfNewJourney 108
lenPos 1820
I =  9233234 3.925515853044791
dfNewJourney 126
lenPos 1874
I =  9256016 3.9506794162053347
dfNewJourney 100
lenPos 1780
I =  9234484 3.9758429793658783
dfNewJourney 85
lenPos 1633
I =  9290608 4.001006542526421
dfNewJourney 163
lenPos 1853
I =  9290610 4.026170105686965
dfNewJourney 94
lenPos 1693
I =  9341146 4.051333668847509
dfNewJourney 164
lenPos 1817
I =  9334727 4.076497232008052
dfNewJourney 178
lenPos 1758
I =  9334739 4.101660795168596
dfNewJourney 103
lenPos 1714
I =  9389289 4.12682435832914
dfNewJourney 76
lenPos 1596
I =  9081813 4.151987921489683
dfNewJourney 137
lenPos 1620
I =  9173721 4.177151484650227
dfNewJourney 81
lenPos 1777
I =  9173733 4.20231504781077
dfNewJourney 112
lenPos 1833
I =  9183611 4.227478610971314
dfNewJourney 84
lenPos 1861
I =  9183623 4.252642174131857
dfNewJourney 107
lenPos 1769
I =  9133587 4.2778057372924
dfNewJourney 100
lenPos 1750
I =  9222132 4.302969300452944
dfNewJourney 116
lenPos 1856
I =  9162916 4.3281328636134875
dfNewJourney 95
lenPos 1682
I =  9162928 4.353296426774031
dfNewJourney 109
lenPos 1749
I =  9231511 4.378459989934575
dfNewJourney 92
lenPos 1663
I =  9127693 4.403623553095119
dfNewJourney 189
lenPos 1742
I =  9103843 4.428787116255662
dfNewJourney 120
lenPos 1803
I =  9265366 4.453950679416206
dfNewJourney 17
lenPos 1856
I =  9249099 4.479114242576749
dfNewJourney 130
lenPos 1839
I =  9276561 4.504277805737292
dfNewJourney 153
lenPos 1828
I =  9276573 4.529441368897836
dfNewJourney 131
lenPos 1882
I =  9276585 4.554604932058379
dfNewJourney 96
lenPos 1721
I =  9249104 4.579768495218923
dfNewJourney 147
lenPos 1810
I =  9276597 4.604932058379466
dfNewJourney 141
lenPos 1837
I =  9285861 4.6300956215400095
dfNewJourney 122
lenPos 1763
I =  9249116 4.6552591847005536
dfNewJourney 136
lenPos 1717
I =  9290919 4.680422747861098
dfNewJourney 112
lenPos 1840
I =  9308998 4.705586311021641
dfNewJourney 130
lenPos 1860
I =  9290921 4.730749874182185
dfNewJourney 107
lenPos 1672
I =  9294678 4.755913437342728
dfNewJourney 133
lenPos 1695
I =  9299111 4.781077000503271
dfNewJourney 167
lenPos 1885
I =  9299898 4.806240563663815
dfNewJourney 165
lenPos 1827
I =  9291236 4.831404126824358
dfNewJourney 172
lenPos 1871
I =  9299903 4.856567689984901
dfNewJourney 170
lenPos 1715
I =  9259290 4.881731253145445
dfNewJourney 94
lenPos 1820
I =  9291248 4.9068948163059884
dfNewJourney 134
lenPos 1820
I =  9297321 4.9320583794665325
dfNewJourney 123
lenPos 1827
I =  9294666 4.9572219426270765
dfNewJourney 146
lenPos 1874
I =  9311359 4.98238550578762
dfNewJourney 129
lenPos 1879
I =  9311361 5.007549068948163
dfNewJourney 224
lenPos 1840
I =  9314882 5.032712632108707
dfNewJourney 182
lenPos 1830
I =  9305611 5.05787619526925
dfNewJourney 203
lenPos 1817
I =  9314894 5.083039758429794
dfNewJourney 212
lenPos 1833
I =  9315795 5.108203321590337
dfNewJourney 197
lenPos 1840
I =  9297553 5.13336688475088
dfNewJourney 107
lenPos 1772
I =  9377779 5.158530447911424
dfNewJourney 159
lenPos 1830
I =  9338917 5.183694011071967
dfNewJourney 125
lenPos 1825
I =  9345441 5.208857574232511
dfNewJourney 230
lenPos 1859
I =  9315903 5.234021137393055
dfNewJourney 115
lenPos 1846
I =  9319545 5.2591847005535985
dfNewJourney 107
lenPos 1794
I =  9306562 5.284348263714142
dfNewJourney 167
lenPos 1846
I =  9306574 5.309511826874686
dfNewJourney 134
lenPos 1860
I =  9380831 5.334675390035229
dfNewJourney 122
lenPos 1817
I =  9318008 5.359838953195773
dfNewJourney 165
lenPos 1888
I =  9298507 5.385002516356316
dfNewJourney 135
lenPos 1792
I =  9391517 5.410166079516859
dfNewJourney 130
lenPos 1851
I =  9391529 5.435329642677403
dfNewJourney 154
lenPos 1788
I =  9260031 5.460493205837947
dfNewJourney 141
lenPos 1824
I =  9260043 5.48565676899849
dfNewJourney 143
lenPos 1822
I =  9317951 5.510820332159034
dfNewJourney 113
lenPos 1701
I =  9380398 5.5359838953195775
dfNewJourney 113
lenPos 1807
I =  9380386 5.561147458480121
dfNewJourney 80
lenPos 1701
I =  9383869 5.586311021640665
dfNewJourney 152
lenPos 1791
I =  9380673 5.611474584801208
dfNewJourney 118
lenPos 1705
I =  9307085 5.636638147961751
dfNewJourney 123
lenPos 1837
I =  9307097 5.661801711122295
dfNewJourney 121
lenPos 1843
I =  9307102 5.686965274282838
dfNewJourney 133
lenPos 1835
I =  9382750 5.712128837443382
dfNewJourney 112
lenPos 1681
I =  9384069 5.737292400603926
dfNewJourney 120
lenPos 1862
I =  9382982 5.762455963764469
dfNewJourney 124
lenPos 1866
I =  9382970 5.787619526925012
dfNewJourney 112
lenPos 1841
I =  9307982 5.812783090085556
dfNewJourney 98
lenPos 1852
I =  9307994 5.8379466532460995
dfNewJourney 110
lenPos 1788
I =  9314208 5.8631102164066435
dfNewJourney 118
lenPos 1667
I =  9207728 5.888273779567187
dfNewJourney 121
lenPos 1741
I =  9150315 5.91343734272773
dfNewJourney 91
lenPos 1878
I =  9126003 5.938600905888274
dfNewJourney 103
lenPos 1636
I =  8919049 5.963764469048817
dfNewJourney 112
lenPos 1365
I =  9126015 5.988928032209361
dfNewJourney 112
lenPos 1740
I =  8919037 6.014091595369905
dfNewJourney 247
lenPos 1709
I =  9220914 6.039255158530448
dfNewJourney 220
lenPos 1816
I =  9220926 6.064418721690991
dfNewJourney 180
lenPos 1712
I =  9223851 6.089582284851535
dfNewJourney 102
lenPos 1613
I =  9232022 6.114745848012078
dfNewJourney 220
lenPos 1737
I =  9228784 6.139909411172622
dfNewJourney 105
lenPos 1809
I =  9231690 6.165072974333166
dfNewJourney 150
lenPos 1543
I =  9210919 6.190236537493709
dfNewJourney 96
lenPos 1702
I =  9232034 6.215400100654253
dfNewJourney 340
lenPos 1821
I =  9251547 6.240563663814796
dfNewJourney 127
lenPos 1714
I =  9235696 6.26572722697534
dfNewJourney 92
lenPos 1617
I =  9256236 6.290890790135883
dfNewJourney 248
lenPos 1757
I =  9251559 6.316054353296427
dfNewJourney 297
lenPos 1850
I =  9269403 6.34121791645697
dfNewJourney 222
lenPos 1832
I =  9241803 6.366381479617514
dfNewJourney 199
lenPos 1710
I =  9259927 6.391545042778057
dfNewJourney 124
lenPos 1737
I =  9260809 6.4167086059386005
dfNewJourney 142
lenPos 1838
I =  9241815 6.4418721690991445
dfNewJourney 120
lenPos 1658
I =  9260823 6.467035732259688
dfNewJourney 251
lenPos 1722
I =  9292278 6.492199295420232
dfNewJourney 102
lenPos 1796
I =  9298492 6.517362858580775
dfNewJourney 135
lenPos 1830
I =  9293947 6.542526421741318
dfNewJourney 133
lenPos 1539
I =  9247390 6.567689984901862
dfNewJourney 277
lenPos 1875
I =  9290517 6.592853548062405
dfNewJourney 150
lenPos 1637
I =  9253595 6.618017111222948
dfNewJourney 99
lenPos 1871
I =  9318022 6.643180674383492
dfNewJourney 114
lenPos 1814
I =  9301902 6.668344237544037
dfNewJourney 184
lenPos 1758
I =  9301885 6.69350780070458
dfNewJourney 133
lenPos 1613
I =  9323792 6.718671363865123
dfNewJourney 150
lenPos 1470
I =  9323807 6.7438349270256674
dfNewJourney 126
lenPos 1781
I =  9301914 6.768998490186211
dfNewJourney 144
lenPos 1847
I =  9326524 6.794162053346755
dfNewJourney 123
lenPos 1701
I =  9346859 6.819325616507298
dfNewJourney 144
lenPos 1852
I =  9316608 6.844489179667841
dfNewJourney 139
lenPos 1826
I =  9379313 6.869652742828385

dfNewJourney 127
lenPos 1862
I =  9387580 6.894816305988928
dfNewJourney 133
lenPos 1835
I =  9391488 6.919979869149471
dfNewJourney 178
lenPos 1874
I =  9351634 6.945143432310015
dfNewJourney 132
lenPos 1842
I =  9391490 6.970306995470558
dfNewJourney 257
lenPos 1841
I =  9384112 6.995470558631102
dfNewJourney 181
lenPos 1879
I =  9379325 7.0206341217916455
dfNewJourney 124
lenPos 1839
I =  9391505 7.045797684952189
dfNewJourney 115
lenPos 1598
I =  9489285 7.070961248112733
dfNewJourney 112
lenPos 1616
I =  9489297 7.096124811273276
dfNewJourney 139
lenPos 1715
I =  9417309 7.121288374433819
dfNewJourney 123
lenPos 1808
I =  9326500 7.146451937594363
dfNewJourney 232
lenPos 1872
I =  9384124 7.171615500754906
dfNewJourney 276
lenPos 1860
I =  9384136 7.196779063915451
dfNewJourney 109
lenPos 1838
I =  9396737 7.221942627075995
dfNewJourney 126
lenPos 1875
I =  9396749 7.247106190236538
dfNewJourney 123
lenPos 1458
I =  9346873 7.272269753397081
dfNewJourney 90
lenPos 1596
I =  9346885 7.297433316557625
dfNewJourney 208
lenPos 1817
I =  9416551 7.322596879718168
dfNewJourney 147
lenPos 1720
I =  9417311 7.3477604428787116
dfNewJourney 166
lenPos 1753
I =  9374234 7.372924006039256
dfNewJourney 96
lenPos 1794
I =  9275763 7.398087569199799
dfNewJourney 5
lenPos 1648
I =  9211999 7.423251132360342
dfNewJourney 39
lenPos 1794
I =  9212008 7.448414695520886
dfNewJourney 46
lenPos 719
I =  8623937 7.473578258681429
dfNewJourney 240
lenPos 1547
I =  9198305 7.498741821841973
dfNewJourney 112
lenPos 1659
I =  9201592 7.523905385002516
dfNewJourney 136
lenPos 1782
I =  9183635 7.549068948163059
dfNewJourney 143
lenPos 1848
I =  9396787 7.574232511323603
dfNewJourney 113
lenPos 1834
I =  9397511 7.5993960744841464
dfNewJourney 144
lenPos 1781
I =  9259898 7.6245596376446905
dfNewJourney 96
lenPos 1849
I =  9182045 7.649723200805234
dfNewJourney 128
lenPos 1685
I =  9396385 7.674886763965777
dfNewJourney 170
lenPos 1844
I =  9396000 7.700050327126321
dfNewJourney 106
lenPos 1807
I =  9396751 7.725213890286866
dfNewJourney 106
lenPos 1701
I =  9485629 7.750377453447409
dfNewJourney 77
lenPos 1469
I =  9485631 7.775541016607952
dfNewJourney 119
lenPos 1719
I =  9396763 7.800704579768496
dfNewJourney 131
lenPos 1859
I =  9396775 7.825868142929039
dfNewJourney 165
lenPos 1680
I =  9302657 7.851031706089582
dfNewJourney 252
lenPos 1838
I =  9352195 7.876195269250126
dfNewJourney 70
lenPos 1456
I =  9018684 7.901358832410669
dfNewJourney 205
lenPos 1662
I =  9301299 7.926522395571213
dfNewJourney 155
lenPos 1848
I =  9350850 7.9516859587317565
dfNewJourney 162
lenPos 1858
I =  9350862 7.9768495218923
dfNewJourney 85
lenPos 1495
I =  9231224 8.002013085052843
dfNewJourney 211
lenPos 1803
I =  9301897 8.027176648213388
dfNewJourney 117
lenPos 1765
I =  9356244 8.05234021137393
dfNewJourney 220
lenPos 1691
I =  9357559 8.077503774534474
dfNewJourney 117
lenPos 1846
I =  9318010 8.102667337695017
dfNewJourney 157
lenPos 1876
I =  9318034 8.12783090085556
dfNewJourney 155
lenPos 1779
I =  9376945 8.152994464016103
dfNewJourney 154
lenPos 1385
I =  9310252 8.178158027176648
dfNewJourney 118
lenPos 1707
I =  9346732 8.203321590337191
dfNewJourney 127
lenPos 1710
I =  9380362 8.228485153497735
dfNewJourney 108
lenPos 1771
I =  9346744 8.25364871665828
dfNewJourney 135
lenPos 1756
I =  9373656 8.278812279818823
dfNewJourney 212
lenPos 1846
I =  9380350 8.303975842979366
dfNewJourney 178
lenPos 1834
I =  9380570 8.32913940613991
dfNewJourney 200
lenPos 1840
I =  9377652 8.354302969300454
dfNewJourney 126
lenPos 1736
I =  9380374 8.379466532460997
dfNewJourney 162
lenPos 1788
I =  9307815 8.40463009562154
dfNewJourney 119
lenPos 1129
I =  9187655 8.429793658782083
dfNewJourney 168
lenPos 1528
I =  9187667 8.454957221942628
dfNewJourney 155
lenPos 1136
I =  9187631 8.480120785103171
dfNewJourney 277
lenPos 1557
I =  9187643 8.505284348263714
dfNewJourney 68
lenPos 741
I =  9283760 8.530447911424258
dfNewJourney 298
lenPos 1631
I =  9187629 8.5556114745848
dfNewJourney 175
lenPos 1742
I =  9260029 8.580775037745344
dfNewJourney 128
lenPos 1805
I =  9168647 8.605938600905889
dfNewJourney 121
lenPos 1777
I =  9168635 8.631102164066432
dfNewJourney 166
lenPos 1711
I =  9290830 8.656265727226975
dfNewJourney 123
lenPos 1678
I =  9215256 8.681429290387518
dfNewJourney 126
lenPos 1792
I =  9198563 8.706592853548061
dfNewJourney 74
lenPos 1116
I =  9217448 8.731756416708606
dfNewJourney 42
lenPos 1306
I =  8614467 8.75691997986915
dfNewJourney 130
lenPos 1802
I =  9214305 8.782083543029694
dfNewJourney 67
lenPos 1788
I =  9169512 8.807247106190237
dfNewJourney 285
lenPos 1797
I =  9199127 8.83241066935078
dfNewJourney 95
lenPos 1827
I =  9326873 8.857574232511324
dfNewJourney 119
lenPos 1873
I =  9214317 8.882737795671867
dfNewJourney 98
lenPos 1740
I =  9326897 8.907901358832412
dfNewJourney 123
lenPos 1559
I =  9235062 8.933064921992955
dfNewJourney 334
lenPos 1779
I =  9266243 8.958228485153498
dfNewJourney 250
lenPos 1842
I =  9321689 8.983392048314041
dfNewJourney 126
lenPos 1705
I =  9212371 9.008555611474584
dfNewJourney 89
lenPos 1761
I =  9243318 9.033719174635129
dfNewJourney 102
lenPos 1553
I =  9307786 9.058882737795672
dfNewJourney 115
lenPos 1841
I =  9047764 9.084046300956215
dfNewJourney 134
lenPos 1829
I =  9047491 9.109209864116758
dfNewJourney 138
lenPos 1846
I =  9047752 9.134373427277302
dfNewJourney 96
lenPos 1811
I =  9047506 9.159536990437847
dfNewJourney 113
lenPos 1742
I =  9307798 9.18470055359839
dfNewJourney 128
lenPos 1845
I =  9047518 9.209864116758933
dfNewJourney 118
lenPos 1869
I =  9087013 9.235027679919476
dfNewJourney 130
lenPos 1849
I =  9087025 9.260191243080019
dfNewJourney 128
lenPos 1877
I =  9114232 9.285354806240562
dfNewJourney 86
lenPos 1840
I =  9332614 9.310518369401107
dfNewJourney 134
lenPos 1778
I =  9364239 9.335681932561652
dfNewJourney 89
lenPos 1795
I =  9332626 9.360845495722195
dfNewJourney 101
lenPos 1650
I =  9114244 9.386009058882738
dfNewJourney 131
lenPos 1659
I =  9387671 9.411172622043281
dfNewJourney 126
lenPos 1863
I =  9143207 9.436336185203825
dfNewJourney 109
lenPos 1871
I =  9143219 9.46149974836437
dfNewJourney 114
lenPos 1591
I =  9219264 9.486663311524913
dfNewJourney 75
lenPos 1695
I =  9219276 9.511826874685456
dfNewJourney 109
lenPos 1640
I =  9171503 9.536990437845999
dfNewJourney 66
lenPos 1865
I =  9171498 9.562154001006542
dfNewJourney 114
lenPos 1483
I =  9299147 9.587317564167087
dfNewJourney 128
lenPos 1882
I =  9439773 9.61248112732763
dfNewJourney 137
lenPos 1759
I =  9439802 9.637644690488173
dfNewJourney 67
lenPos 1601
I =  9080493 9.662808253648716
dfNewJourney 122
lenPos 1797
I =  9221657 9.68797181680926
dfNewJourney 103
lenPos 1708
I =  7816551 9.713135379969803
dfNewJourney 75
lenPos 1709
I =  9129940 9.738298943130347
dfNewJourney 17
lenPos 1259
I =  8302416 9.76346250629089
dfNewJourney 94
lenPos 1591
I =  9215048 9.788626069451434
dfNewJourney 193
lenPos 1740
I =  9313486 9.813789632611977
dfNewJourney 123
lenPos 1699
I =  9335094 9.83895319577252
dfNewJourney 99
lenPos 1806
I =  9321938 9.864116758933065
dfNewJourney 111
lenPos 1695
I =  9330599 9.88928032209361
dfNewJourney 129
lenPos 1840
I =  9307346 9.914443885254153
dfNewJourney 143
lenPos 1767
I =  9336414 9.939607448414696
dfNewJourney 160
lenPos 1338
I =  9172727 9.96477101157524
dfNewJourney 135
lenPos 1774
I =  9345659 9.989934574735782
dfNewJourney 120
lenPos 1510
I =  9221683 10.015098137896326
dfNewJourney 100
lenPos 1825
I =  9321172 10.04026170105687
dfNewJourney 108
lenPos 1846
I =  9298662 10.065425264217414
dfNewJourney 177
lenPos 1836
I =  9313498 10.090588827377957
dfNewJourney 83
lenPos 1745
I =  9335135 10.1157523905385
dfNewJourney 178
lenPos 1633
I =  9336426 10.140915953699043
dfNewJourney 101
lenPos 1755
I =  9384992 10.166079516859588
dfNewJourney 104
lenPos 1517
I =  9358917 10.191243080020131
dfNewJourney 86
lenPos 1706
I =  9301029 10.216406643180674
dfNewJourney 167
lenPos 1744
I =  9336402 10.241570206341217
dfNewJourney 124
lenPos 1789
I =  9314909 10.26673376950176
dfNewJourney 193
lenPos 1802
I =  9339636 10.291897332662305
dfNewJourney 152
lenPos 1820
I =  9315771 10.317060895822848
dfNewJourney 145
lenPos 1714
I =  9314911 10.342224458983392

dfNewJourney 115
lenPos 1809
I =  9335147 10.367388022143935
dfNewJourney 77
lenPos 1641
I =  9181534 10.39255158530448
dfNewJourney 137
lenPos 1811
I =  9315056 10.417715148465023
dfNewJourney 269
lenPos 1771
I =  9197715 10.442878711625566
dfNewJourney 136
lenPos 1701
I =  9335109 10.46804227478611
dfNewJourney 76
lenPos 1791
I =  9327023 10.493205837946654
dfNewJourney 162
lenPos 1891
I =  9325908 10.518369401107197
dfNewJourney 95
lenPos 1753
I =  9258600 10.54353296426774
dfNewJourney 117
lenPos 1769
I =  9255945 10.568696527428283
dfNewJourney 103
lenPos 1787
I =  9299123 10.593860090588828
dfNewJourney 87
lenPos 1854
I =  9299135 10.619023653749371
dfNewJourney 132
lenPos 1573
I =  9295036 10.644187216909915
dfNewJourney 71
lenPos 1841
I =  9299159 10.669350780070458
dfNewJourney 99
lenPos 1524
I =  9312456 10.694514343231
dfNewJourney 110
lenPos 1770
I =  9252436 10.719677906391546
dfNewJourney 118
lenPos 1713
I =  9252448 10.744841469552089
dfNewJourney 103
lenPos 1755
I =  9258595 10.770005032712632
dfNewJourney 105
lenPos 1829
I =  9367669 10.795168595873175
dfNewJourney 101
lenPos 1663
I =  9382085 10.820332159033718
dfNewJourney 120
lenPos 1812
I =  9165281 10.845495722194261
dfNewJourney 87
lenPos 1797
I =  9402213 10.870659285354806
dfNewJourney 98
lenPos 1790
I =  9400980 10.89582284851535
dfNewJourney 112
lenPos 1812
I =  9381562 10.920986411675894
dfNewJourney 147
lenPos 1827
I =  9381823 10.946149974836437
dfNewJourney 125
lenPos 1827
I =  9417440 10.97131353799698
dfNewJourney 132
lenPos 1830
I =  9381835 10.996477101157524
dfNewJourney 103
lenPos 1816
I =  9389837 11.021640664318069
dfNewJourney 105
lenPos 1692
I =  9327035 11.046804227478612
dfNewJourney 126
lenPos 1772
I =  9312858 11.071967790639155
dfNewJourney 124
lenPos 1623
I =  9187435 11.097131353799698
dfNewJourney 87
lenPos 1864
I =  9183582 11.122294916960241
dfNewJourney 94
lenPos 1667
I =  9358929 11.147458480120784
dfNewJourney 119
lenPos 1699
I =  9231212 11.17262204328133
dfNewJourney 152
lenPos 1789
I =  9240720 11.197785606441872
dfNewJourney 115
lenPos 1776
I =  9312860 11.222949169602416
dfNewJourney 117
lenPos 1480
I =  9249178 11.248112732762959
dfNewJourney 132
lenPos 1743
I =  9256468 11.273276295923502
dfNewJourney 156
lenPos 1617
I =  9247443 11.298439859084047
dfNewJourney 120
lenPos 1581
I =  9268112 11.32360342224459
dfNewJourney 126
lenPos 1783
I =  9283617 11.348766985405133
dfNewJourney 141
lenPos 1745
I =  9282625 11.373930548565676
dfNewJourney 86
lenPos 1361
I =  9292503 11.39909411172622
dfNewJourney 128
lenPos 1566
I =  9330604 11.424257674886764
dfNewJourney 171
lenPos 1839
I =  9292620 11.449421238047307
dfNewJourney 120
lenPos 1649
I =  9312872 11.474584801207852
dfNewJourney 11
lenPos 1360
I =  8814433 11.499748364368395
dfNewJourney 154
lenPos 1842
I =  9324459 11.524911927528938
dfNewJourney 90
lenPos 1790
I =  9301017 11.550075490689482
dfNewJourney 108
lenPos 1345
I =  9203796 11.575239053850025
dfNewJourney 95
lenPos 1740
I =  9242326 11.60040261701057
dfNewJourney 110
lenPos 1777
I =  9250165 11.625566180171113
dfNewJourney 385
lenPos 1889
I =  9298715 11.650729743331656
dfNewJourney 170
lenPos 1837
I =  9352200 11.675893306492199
dfNewJourney 51
lenPos 1784
I =  8819081 11.701056869652742
dfNewJourney 126
lenPos 1783
I =  9178202 11.726220432813287
dfNewJourney 126
lenPos 1728
I =  9124469 11.75138399597383
dfNewJourney 129
lenPos 1849
I =  9102071 11.776547559134373
dfNewJourney 142
lenPos 1725
I =  9189110 11.801711122294916
dfNewJourney 122
lenPos 1818
I =  9178197 11.82687468545546
dfNewJourney 121
lenPos 1706
I =  9102112 11.852038248616005
dfNewJourney 124
lenPos 1856
I =  9102069 11.877201811776548
dfNewJourney 139
lenPos 1608
I =  9102095 11.90236537493709
dfNewJourney 132
lenPos 1862
I =  9102083 11.927528938097634
dfNewJourney 271
lenPos 1768
I =  9196711 11.952692501258177
dfNewJourney 61
lenPos 1626
I =  9189134 11.977856064418722
dfNewJourney 115
lenPos 1835
I =  9322827 12.003019627579265
dfNewJourney 100
lenPos 1853
I =  9352212 12.02818319073981
dfNewJourney 136
lenPos 1824
I =  9124471 12.053346753900353
dfNewJourney 126
lenPos 1799
I =  9301976 12.078510317060896
dfNewJourney 114
lenPos 1785
I =  9301964 12.10367388022144
dfNewJourney 95
lenPos 1769
I =  9257498 12.128837443381983
dfNewJourney 99
lenPos 1716
I =  9257503 12.154001006542527
dfNewJourney 113
lenPos 1785
I =  8911669 12.17916456970307
dfNewJourney 111
lenPos 1814
I =  9414058 12.204328132863614
dfNewJourney 239
lenPos 1872
I =  9353565 12.229491696024157
dfNewJourney 161
lenPos 1643
I =  9165293 12.2546552591847
dfNewJourney 27
lenPos 591
I =  8644149 12.279818822345243
dfNewJourney 30
lenPos 1292
I =  8644034 12.304982385505788
dfNewJourney 44
lenPos 1191
I =  9101182 12.330145948666331
dfNewJourney 85
lenPos 980
I =  9289154 12.355309511826874
dfNewJourney 130
lenPos 1826
I =  9258014 12.380473074987417
dfNewJourney 151
lenPos 1538
I =  9403475 12.40563663814796
dfNewJourney 169
lenPos 1762
I =  9169548 12.430800201308505
dfNewJourney 73
lenPos 1613
I =  9343998 12.455963764469049
dfNewJourney 138
lenPos 1782
I =  9282522 12.481127327629592
dfNewJourney 127
lenPos 1697
I =  9290309 12.506290890790137
dfNewJourney 93
lenPos 1664
I =  9404948 12.53145445395068
dfNewJourney 146
lenPos 1824
I =  9254927 12.556618017111223
dfNewJourney 98
lenPos 1653
I =  9279757 12.581781580271766
dfNewJourney 129
lenPos 1699
I =  9209283 12.606945143432311
dfNewJourney 108
lenPos 1755
I =  9324289 12.632108706592854
dfNewJourney 55
lenPos 1751
I =  9169536 12.657272269753397
dfNewJourney 120
lenPos 1816
I =  9274484 12.68243583291394
dfNewJourney 102
lenPos 1820
I =  9324320 12.707599396074484
dfNewJourney 135
lenPos 1812
I =  9342217 12.732762959235028
dfNewJourney 149
lenPos 1895
I =  9382073 12.757926522395572
dfNewJourney 108
lenPos 1827
I =  9354519 12.783090085556115
dfNewJourney 119
lenPos 1855
I =  9322384 12.808253648716658
dfNewJourney 105
lenPos 1734
I =  9335044 12.833417211877201
dfNewJourney 150
lenPos 1595
I =  9313761 12.858580775037746
dfNewJourney 89
lenPos 1737
I =  9228320 12.883744338198289
dfNewJourney 169
lenPos 1737
I =  9425265 12.908907901358832
dfNewJourney 127
lenPos 1649
I =  9038880 12.934071464519375
dfNewJourney 95
lenPos 1637
I =  9345623 12.959235027679918
dfNewJourney 104
lenPos 1875
I =  9317248 12.984398590840463
dfNewJourney 87
lenPos 1880
I =  9367671 13.009562154001006
dfNewJourney 320
lenPos 1805
I =  9321861 13.03472571716155
dfNewJourney 121
lenPos 1183
I =  9222699 13.059889280322093
dfNewJourney 112
lenPos 1660
I =  9293155 13.085052843482636
dfNewJourney 99
lenPos 1859
I =  9262912 13.110216406643179
dfNewJourney 256
lenPos 1757
I =  9275995 13.135379969803724
dfNewJourney 106
lenPos 1717
I =  9359894 13.160543532964267
dfNewJourney 135
lenPos 1862
I =  9374533 13.18570709612481
dfNewJourney 67
lenPos 1713
I =  9166558 13.210870659285353
dfNewJourney 72
lenPos 1752
I =  9412177 13.236034222445896
dfNewJourney 130
lenPos 1730
I =  9337418 13.261197785606441
dfNewJourney 255
lenPos 1779
I =  9343780 13.286361348766984
dfNewJourney 136
lenPos 1825
I =  9400849 13.311524911927531
dfNewJourney 102
lenPos 1785
I =  9321201 13.336688475088074
dfNewJourney 135
lenPos 1730
I =  9443877 13.361852038248617
dfNewJourney 165
lenPos 1641
I =  9399868 13.38701560140916
dfNewJourney 114
lenPos 1537
I =  9364227 13.412179164569704
dfNewJourney 137
lenPos 1732
I =  9363792 13.437342727730247
dfNewJourney 158
lenPos 1763
I =  9317078 13.462506290890792
dfNewJourney 152
lenPos 1812
I =  9247895 13.487669854051335
dfNewJourney 124
lenPos 1516
I =  9145841 13.512833417211878
dfNewJourney 90
lenPos 1655
I =  9281891 13.537996980372421
dfNewJourney 175
lenPos 1649
I =  9145853 13.563160543532964
dfNewJourney 109
lenPos 1791
I =  9337406 13.58832410669351
dfNewJourney 109
lenPos 1795
I =  9310161 13.613487669854052
dfNewJourney 121
lenPos 1554
I =  9228318 13.638651233014595
dfNewJourney 103
lenPos 1863
I =  9278698 13.663814796175139
dfNewJourney 109
lenPos 1844
I =  9278624 13.688978359335682
dfNewJourney 131
lenPos 1682
I =  9325843 13.714141922496225
dfNewJourney 218
lenPos 1721
I =  9414228 13.73930548565677
dfNewJourney 116
lenPos 1826
I =  9379519 13.764469048817313

dfNewJourney 277
lenPos 1772
I =  9414216 13.789632611977856
dfNewJourney 135
lenPos 1852
I =  9380051 13.8147961751384
dfNewJourney 188
lenPos 1774
I =  9391282 13.839959738298942
dfNewJourney 98
lenPos 1761
I =  9223722 13.865123301459487
dfNewJourney 216
lenPos 1665
I =  9399870 13.89028686462003
dfNewJourney 99
lenPos 1824
I =  9334571 13.915450427780574
dfNewJourney 155
lenPos 1786
I =  9252400 13.940613990941117
dfNewJourney 197
lenPos 1864
I =  9135547 13.96577755410166
dfNewJourney 196
lenPos 1732
I =  9198159 13.990941117262205
dfNewJourney 248
lenPos 1790
I =  9442550 14.016104680422748
dfNewJourney 160
lenPos 1550
I =  9290294 14.041268243583291
dfNewJourney 88
lenPos 1649
I =  8323393 14.066431806743834
dfNewJourney 168
lenPos 1710
I =  9325817 14.091595369904377
dfNewJourney 100
lenPos 1844
I =  9273832 14.116758933064922
dfNewJourney 115
lenPos 1813
I =  9262900 14.141922496225465
dfNewJourney 130
lenPos 1621
I =  9259197 14.167086059386008
dfNewJourney 119
lenPos 1857
I =  9379894 14.192249622546552
dfNewJourney 95
lenPos 1687
I =  9335068 14.217413185707095
dfNewJourney 150
lenPos 1718
I =  9392389 14.242576748867638
dfNewJourney 136
lenPos 1709
I =  9325855 14.267740312028183
dfNewJourney 123
lenPos 1725
I =  9335056 14.292903875188726
dfNewJourney 144
lenPos 1772
I =  9171321 14.318067438349269
dfNewJourney 100
lenPos 1600
I =  9183312 14.343231001509812
dfNewJourney 124
lenPos 1830
I =  9367683 14.368394564670359
dfNewJourney 103
lenPos 1825
I =  9197155 14.393558127830902
dfNewJourney 205
lenPos 1697
I =  9118630 14.418721690991445
dfNewJourney 256
lenPos 1883
I =  9131371 14.44388525415199
dfNewJourney 192
lenPos 1866
I =  9131369 14.469048817312533
dfNewJourney 0
lenPos 0
I =  8220761 14.494212380473076
dfNewJourney 303
lenPos 1875
I =  9353539 14.51937594363362
dfNewJourney 15
lenPos 1602
I =  8822454 14.544539506794163
dfNewJourney 13
lenPos 1341
I =  8822442 14.569703069954706
dfNewJourney 257
lenPos 1838
I =  9407562 14.59486663311525
dfNewJourney 233
lenPos 1767
I =  9408102 14.620030196275794
dfNewJourney 154
lenPos 1573
I =  9144926 14.645193759436337
dfNewJourney 342
lenPos 1750
I =  9353541 14.67035732259688
dfNewJourney 249
lenPos 1825
I =  9353527 14.695520885757423
dfNewJourney 111
lenPos 1779
I =  9367695 14.720684448917968
dfNewJourney 98
lenPos 1865
I =  9370719 14.745848012078511
dfNewJourney 108
lenPos 1828
I =  9379909 14.771011575239054
dfNewJourney 105
lenPos 1850
I =  9367700 14.796175138399597
dfNewJourney 97
lenPos 1595
I =  9404936 14.82133870156014
dfNewJourney 103
lenPos 1739
I =  9367712 14.846502264720684
dfNewJourney 400
lenPos 1872
I =  9392315 14.871665827881229
dfNewJourney 144
lenPos 1662
I =  9428841 14.896829391041772
dfNewJourney 97
lenPos 1743
I =  9397896 14.921992954202315
dfNewJourney 84
lenPos 1730
I =  9381732 14.947156517362858
dfNewJourney 109
lenPos 1729
I =  9392365 14.972320080523401
dfNewJourney 141
lenPos 1891
I =  9367736 14.997483643683946
dfNewJourney 105
lenPos 1737
I =  9428346 15.02264720684449
dfNewJourney 161
lenPos 1552
I =  9384007 15.047810770005032
dfNewJourney 115
lenPos 1843
I =  9379911 15.072974333165575
dfNewJourney 156
lenPos 1895
I =  9391294 15.098137896326119
dfNewJourney 100
lenPos 1785
I =  9399882 15.123301459486663
dfNewJourney 132
lenPos 1719
I =  9354521 15.148465022647207
dfNewJourney 145
lenPos 1807
I =  9367748 15.17362858580775
dfNewJourney 116
lenPos 1768
I =  9405851 15.198792148968293
dfNewJourney 174
lenPos 1833
I =  9391309 15.223955712128836
dfNewJourney 80
lenPos 1687
I =  9390599 15.249119275289381
dfNewJourney 291
lenPos 1775
I =  9425992 15.274282838449924
dfNewJourney 132
lenPos 1614
I =  9370848 15.299446401610467
dfNewJourney 158
lenPos 1654
I =  9441178 15.32460996477101
dfNewJourney 145
lenPos 1679
I =  9370836 15.349773527931553
dfNewJourney 113
lenPos 1743
I =  9254939 15.374937091092097
dfNewJourney 93
lenPos 1608
I =  9390587 15.400100654252642
dfNewJourney 130
lenPos 1843
I =  9322396 15.425264217413185
dfNewJourney 117
lenPos 1749
I =  9310707 15.450427780573731
dfNewJourney 130
lenPos 1883
I =  9319480 15.475591343734274
dfNewJourney 119
lenPos 1858
I =  9374521 15.500754906894818
dfNewJourney 94
lenPos 1868
I =  9303417 15.52591847005536
dfNewJourney 156
lenPos 1778
I =  9310812 15.551082033215904
dfNewJourney 141
lenPos 1811
I =  9310692 15.576245596376449
dfNewJourney 124
lenPos 1684
I =  9307140 15.601409159536992
dfNewJourney 130
lenPos 1837
I =  9325336 15.626572722697535
dfNewJourney 307
lenPos 1818
I =  9321873 15.651736285858078
dfNewJourney 118
lenPos 1601
I =  9307152 15.676899849018621
dfNewJourney 115
lenPos 1677
I =  9308223 15.702063412179164
dfNewJourney 124
lenPos 1822
I =  9343211 15.72722697533971
dfNewJourney 166
lenPos 1800
I =  9311000 15.752390538500253
dfNewJourney 77
lenPos 1662
I =  9317717 15.777554101660796
dfNewJourney 131
lenPos 1846
I =  9333187 15.802717664821339
dfNewJourney 120
lenPos 1813
I =  9317858 15.827881227981882
dfNewJourney 105
lenPos 1846
I =  9333280 15.853044791142427
dfNewJourney 166
lenPos 1897
I =  9253753 15.87820835430297
dfNewJourney 126
lenPos 1845
I =  9311036 15.903371917463513
dfNewJourney 226
lenPos 1599
I =  9346067 15.928535480624056
dfNewJourney 134
lenPos 1870
I =  9317860 15.9536990437846
dfNewJourney 89
lenPos 1840
I =  9333242 15.978862606945142
dfNewJourney 118
lenPos 1859
I =  9311048 16.004026170105686
dfNewJourney 137
lenPos 1775
I =  9346079 16.02918973326623
dfNewJourney 97
lenPos 1831
I =  9310848 16.054353296426775
dfNewJourney 85
lenPos 1878
I =  9363780 16.07951685958732
dfNewJourney 126
lenPos 1696
I =  9321847 16.10468042274786
dfNewJourney 95
lenPos 1721
I =  9323974 16.129843985908405
dfNewJourney 98
lenPos 1838
I =  9324318 16.155007549068948
dfNewJourney 107
lenPos 1789
I =  9324291 16.18017111222949
dfNewJourney 143
lenPos 1767
I =  9375317 16.205334675390034
dfNewJourney 117
lenPos 1638
I =  9332781 16.230498238550577
dfNewJourney 147
lenPos 1754
I =  9349631 16.25566180171112
dfNewJourney 218
lenPos 1833
I =  9382712 16.280825364871664
dfNewJourney 119
lenPos 1822
I =  9365001 16.305988928032207
dfNewJourney 158
lenPos 1708
I =  9375329 16.331152491192753
dfNewJourney 92
lenPos 1761
I =  9323986 16.356316054353297
dfNewJourney 102
lenPos 1842
I =  9382700 16.38147961751384
dfNewJourney 93
lenPos 1780
I =  9321184 16.406643180674383
dfNewJourney 95
lenPos 1675
I =  9321562 16.431806743834926
dfNewJourney 127
lenPos 1831
I =  9325611 16.45697030699547
dfNewJourney 152
lenPos 1842
I =  9544607 16.482133870156012
dfNewJourney 128
lenPos 1688
I =  9362372 16.50729743331656
dfNewJourney 134
lenPos 1721
I =  9367528 16.532460996477102
dfNewJourney 116
lenPos 1711
I =  9365362 16.557624559637645
dfNewJourney 93
lenPos 1746
I =  9321196 16.58278812279819
dfNewJourney 109
lenPos 1810
I =  9335824 16.60795168595873
dfNewJourney 123
lenPos 1845
I =  9343986 16.633115249119275
dfNewJourney 143
lenPos 1678
I =  9319882 16.65827881227982
dfNewJourney 137
lenPos 1741
I =  9379959 16.683442375440364
dfNewJourney 128
lenPos 1781
I =  9393010 16.708605938600908
dfNewJourney 104
lenPos 1682
I =  9359868 16.73376950176145
dfNewJourney 118
lenPos 1721
I =  9295282 16.758933064921994
dfNewJourney 35
lenPos 1739
I =  9203928 16.784096628082537
dfNewJourney 98
lenPos 1510
I =  9203930 16.80926019124308
dfNewJourney 111
lenPos 1707
I =  9247065 16.834423754403623
dfNewJourney 144
lenPos 1799
I =  9247077 16.859587317564166
dfNewJourney 123
lenPos 1743
I =  9335032 16.88475088072471
dfNewJourney 114
lenPos 1737
I =  9299874 16.909914443885256
dfNewJourney 111
lenPos 1673
I =  9299886 16.9350780070458
dfNewJourney 104
lenPos 1759
I =  9306809 16.960241570206342
dfNewJourney 114
lenPos 1677
I =  9359870 16.985405133366886
dfNewJourney 334
lenPos 1747
I =  9251418 17.01056869652743
dfNewJourney 455
lenPos 1825
I =  9205794 17.035732259687972
dfNewJourney 378
lenPos 1809
I =  9251444 17.060895822848515
dfNewJourney 296
lenPos 1781
I =  9283514 17.086059386009058
dfNewJourney 185
lenPos 1750
I =  9283253 17.1112229491696
dfNewJourney 180
lenPos 1740
I =  9283265 17.136386512330144
dfNewJourney 747
lenPos 1789
I =  9344813 17.161550075490688
dfNewJourney 294
lenPos 1816
I =  9303704 17.186713638651234

dfNewJourney 355
lenPos 1838
I =  9306732 17.211877201811777
dfNewJourney 261
lenPos 1692
I =  9312602 17.23704076497232
dfNewJourney 353
lenPos 1838
I =  9342774 17.262204328132864
dfNewJourney 357
lenPos 1811
I =  9342073 17.287367891293407
dfNewJourney 389
lenPos 1799
I =  9344942 17.31253145445395
dfNewJourney 61
lenPos 1872
I =  9344930 17.337695017614493
dfNewJourney 310
lenPos 1853
I =  9342085 17.362858580775036
dfNewJourney 191
lenPos 1721
I =  9313163 17.38802214393558
dfNewJourney 383
lenPos 1842
I =  9344837 17.413185707096122
dfNewJourney 190
lenPos 1690
I =  9435296 17.438349270256666
dfNewJourney 154
lenPos 1762
I =  9352250 17.463512833417212
dfNewJourney 102
lenPos 1688
I =  9237618 17.488676396577755
dfNewJourney 121
lenPos 1463
I =  9209972 17.5138399597383
dfNewJourney 6
lenPos 701
I =  9167203 17.53900352289884
dfNewJourney 102
lenPos 1461
I =  9308845 17.56416708605939
dfNewJourney 226
lenPos 1850
I =  9334789 17.58933064921993
dfNewJourney 149
lenPos 1826
I =  9315733 17.614494212380475
dfNewJourney 134
lenPos 1752
I =  9321952 17.639657775541018
dfNewJourney 109
lenPos 1515
I =  9388364 17.66482133870156
dfNewJourney 101
lenPos 1724
I =  9388376 17.689984901862104
dfNewJourney 80
lenPos 1705
I =  9401154 17.715148465022647
dfNewJourney 3
lenPos 442
I =  8913617 17.74031202818319
dfNewJourney 126
lenPos 1691
I =  9390161 17.765475591343733
dfNewJourney 124
lenPos 1762
I =  9388948 17.79063915450428
dfNewJourney 140
lenPos 1764
I =  9388924 17.815802717664823
dfNewJourney 184
lenPos 1452
I =  9283746 17.840966280825366
dfNewJourney 542
lenPos 1887
I =  9299941 17.86612984398591
dfNewJourney 113
lenPos 1520
I =  9246138 17.891293407146453
dfNewJourney 147
lenPos 1749
I =  9365374 17.916456970306996
dfNewJourney 139
lenPos 1633
I =  9365386 17.94162053346754
dfNewJourney 47
lenPos 1326
I =  8619443 17.966784096628082
dfNewJourney 24
lenPos 1455
I =  8619429 17.991947659788625
dfNewJourney 54
lenPos 1846
I =  8619455 18.01711122294917
dfNewJourney 92
lenPos 1794
I =  9328170 18.042274786109715
dfNewJourney 143
lenPos 1829
I =  9299733 18.067438349270258
dfNewJourney 114
lenPos 1819
I =  9299745 18.0926019124308
dfNewJourney 113
lenPos 1803
I =  9332315 18.117765475591344
dfNewJourney 100
lenPos 1839
I =  9374272 18.142929038751888
dfNewJourney 108
lenPos 1827
I =  9337523 18.16809260191243
dfNewJourney 121
lenPos 1765
I =  9337511 18.193256165072974
dfNewJourney 132
lenPos 1783
I =  9379818 18.218419728233517
dfNewJourney 141
lenPos 1616
I =  9401025 18.24358329139406
dfNewJourney 160
lenPos 1706
I =  9406362 18.268746854554603
dfNewJourney 120
lenPos 1797
I =  9343340 18.293910417715146
dfNewJourney 141
lenPos 1797
I =  9380506 18.319073980875693
dfNewJourney 127
lenPos 1825
I =  9366263 18.344237544036236
dfNewJourney 151
lenPos 1701
I =  9406374 18.36940110719678
dfNewJourney 122
lenPos 1786
I =  9366275 18.394564670357322
dfNewJourney 111
lenPos 1731
I =  9381756 18.419728233517866
dfNewJourney 109
lenPos 1839
I =  9381768 18.44489179667841
dfNewJourney 140
lenPos 1309
I =  9262417 18.470055359838952
dfNewJourney 132
lenPos 1807
I =  9307334 18.495218922999495
dfNewJourney 170
lenPos 1590
I =  9322449 18.520382486160038
dfNewJourney 114
lenPos 1767
I =  9304590 18.54554604932058
dfNewJourney 112
lenPos 1789
I =  9343352 18.570709612481124
dfNewJourney 124
lenPos 1735
I =  9374284 18.59587317564167
dfNewJourney 194
lenPos 1616
I =  9406348 18.621036738802214
dfNewJourney 105
lenPos 1647
I =  9304825 18.64620030196276
dfNewJourney 122
lenPos 1690
I =  9380518 18.671363865123304
dfNewJourney 128
lenPos 1838
I =  9366287 18.696527428283847
dfNewJourney 120
lenPos 1794
I =  9354911 18.72169099144439
dfNewJourney 116
lenPos 1775
I =  9354909 18.746854554604933
dfNewJourney 113
lenPos 1794
I =  9354894 18.772018117765477
dfNewJourney 85
lenPos 1800
I =  9378618 18.79718168092602
dfNewJourney 136
lenPos 1862
I =  9366299 18.822345244086563
dfNewJourney 138
lenPos 1861
I =  9380520 18.847508807247106
dfNewJourney 103
lenPos 1759
I =  9378620 18.87267237040765
dfNewJourney 110
lenPos 1667
I =  9408762 18.897835933568192
dfNewJourney 137
lenPos 1739
I =  9374296 18.92299949672874
dfNewJourney 83
lenPos 1578
I =  9267364 18.948163059889282
dfNewJourney 101
lenPos 1017
I =  9333254 18.973326623049825
dfNewJourney 145
lenPos 1788
I =  9391426 18.99849018621037
dfNewJourney 205
lenPos 1667
I =  9406350 19.02365374937091
dfNewJourney 125
lenPos 1815
I =  9360324 19.048817312531455
dfNewJourney 175
lenPos 1837
I =  9392327 19.073980875691998
dfNewJourney 103
lenPos 1822
I =  9364588 19.09914443885254
dfNewJourney 139
lenPos 1666
I =  9439539 19.124308002013084
dfNewJourney 155
lenPos 1790
I =  9439541 19.149471565173627
dfNewJourney 209
lenPos 1557
I =  9483736 19.174635128334174
dfNewJourney 125
lenPos 1827
I =  9380049 19.199798691494717
dfNewJourney 134
lenPos 1461
I =  9262429 19.22496225465526
dfNewJourney 114
lenPos 1790
I =  9391438 19.250125817815803
dfNewJourney 138
lenPos 1860
I =  9380532 19.275289380976346
dfNewJourney 248
lenPos 1857
I =  9442158 19.30045294413689
dfNewJourney 150
lenPos 1787
I =  9374301 19.325616507297433
dfNewJourney 129
lenPos 1768
I =  9391440 19.350780070457976
dfNewJourney 114
lenPos 1693
I =  9383962 19.37594363361852
dfNewJourney 110
lenPos 1802
I =  9392779 19.401107196779062
dfNewJourney 162
lenPos 1297
I =  9342097 19.426270759939605
dfNewJourney 116
lenPos 1843
I =  9358307 19.451434323100152
dfNewJourney 110
lenPos 1703
I =  9358319 19.476597886260695
dfNewJourney 95
lenPos 1816
I =  9354179 19.501761449421238
dfNewJourney 125
lenPos 1702
I =  9354258 19.52692501258178
dfNewJourney 165
lenPos 1768
I =  9251523 19.552088575742324
dfNewJourney 113
lenPos 1705
I =  9236365 19.577252138902868
dfNewJourney 122
lenPos 1853
I =  9354260 19.60241570206341
dfNewJourney 112
lenPos 1783
I =  9313474 19.627579265223954
dfNewJourney 146
lenPos 1450
I =  9354272 19.652742828384497
dfNewJourney 164
lenPos 1842
I =  9304368 19.67790639154504
dfNewJourney 177
lenPos 1680
I =  9344124 19.703069954705587
dfNewJourney 75
lenPos 1824
I =  9186625 19.72823351786613
dfNewJourney 128
lenPos 1605
I =  9242223 19.753397081026673
dfNewJourney 122
lenPos 1856
I =  9358321 19.77856064418722
dfNewJourney 99
lenPos 1865
I =  9383895 19.803724207347763
dfNewJourney 109
lenPos 1636
I =  9332810 19.828887770508306
dfNewJourney 137
lenPos 1675
I =  9332834 19.85405133366885
dfNewJourney 120
lenPos 1730
I =  9332028 19.879214896829392
dfNewJourney 111
lenPos 1822
I =  9332169 19.904378459989935
dfNewJourney 134
lenPos 1820
I =  9360336 19.92954202315048
dfNewJourney 157
lenPos 1668
I =  9344136 19.95470558631102
dfNewJourney 107
lenPos 1768
I =  9333785 19.979869149471565
dfNewJourney 110
lenPos 1805
I =  9332171 20.005032712632108
dfNewJourney 92
lenPos 1781
I =  9343338 20.03019627579265
dfNewJourney 94
lenPos 1795
I =  9332183 20.055359838953198
dfNewJourney 120
lenPos 1757
I =  9332303 20.08052340211374
dfNewJourney 174
lenPos 1696
I =  9344148 20.105686965274284
dfNewJourney 159
lenPos 1651
I =  9344150 20.130850528434827
dfNewJourney 77
lenPos 1233
I =  9134713 20.15601409159537
dfNewJourney 300
lenPos 1614
I =  9158305 20.181177654755913
dfNewJourney 170
lenPos 1475
I =  9274082 20.206341217916457
dfNewJourney 46
lenPos 1532
I =  8121173 20.231504781077
dfNewJourney 53
lenPos 803
I =  9125190 20.256668344237543
dfNewJourney 185
lenPos 1461
I =  9187681 20.281831907398086
dfNewJourney 93
lenPos 1715
I =  9123659 20.306995470558633
dfNewJourney 84
lenPos 1739
I =  9123661 20.332159033719176
dfNewJourney 122
lenPos 1277
I =  9143685 20.35732259687972
dfNewJourney 95
lenPos 1723
I =  9172234 20.382486160040262
dfNewJourney 88
lenPos 1670
I =  9172246 20.407649723200805
dfNewJourney 81
lenPos 1531
I =  9172258 20.43281328636135
dfNewJourney 97
lenPos 1727
I =  9172260 20.45797684952189
dfNewJourney 89
lenPos 1558
I =  9172272 20.483140412682435
dfNewJourney 148
lenPos 1703
I =  9308534 20.508303975842978
dfNewJourney 155
lenPos 1789
I =  9264271 20.53346753900352
dfNewJourney 123
lenPos 1866
I =  9179634 20.558631102164064
dfNewJourney 132
lenPos 1817
I =  9253234 20.58379466532461
dfNewJourney 159
lenPos 1815
I =  9253258 20.608958228485154

dfNewJourney 90
lenPos 1784
I =  9298296 20.634121791645697
dfNewJourney 136
lenPos 1809
I =  9308089 20.65928535480624
dfNewJourney 411
lenPos 1837
I =  9298703 20.684448917966783
dfNewJourney 546
lenPos 1865
I =  9298727 20.709612481127326
dfNewJourney 564
lenPos 1861
I =  9298739 20.73477604428787
dfNewJourney 164
lenPos 1826
I =  9299410 20.759939607448416
dfNewJourney 4
lenPos 618
I =  8805004 20.78510317060896
dfNewJourney 97
lenPos 1703
I =  9222170 20.810266733769502
dfNewJourney 112
lenPos 1787
I =  9275725 20.835430296930046
dfNewJourney 250
lenPos 1881
I =  9275737 20.86059386009059
dfNewJourney 117
lenPos 1860
I =  9275749 20.885757423251132
dfNewJourney 111
lenPos 1655
I =  9275751 20.91092098641168
dfNewJourney 94
lenPos 1843
I =  9232591 20.93608454957222
dfNewJourney 128
lenPos 1674
I =  9232618 20.961248112732765
dfNewJourney 115
lenPos 1779
I =  9239628 20.986411675893308
dfNewJourney 119
lenPos 1759
I =  9239630 21.01157523905385
dfNewJourney 135
lenPos 1744
I =  9265873 21.036738802214394
dfNewJourney 106
lenPos 1794
I =  9273624 21.061902365374937
dfNewJourney 30
lenPos 1658
I =  9085390 21.08706592853548
dfNewJourney 95
lenPos 1738
I =  9129952 21.112229491696024
dfNewJourney 143
lenPos 1705
I =  9308819 21.137393054856567
dfNewJourney 93
lenPos 1796
I =  9269245 21.16255661801711
dfNewJourney 90
lenPos 1701
I =  9269257 21.187720181177657
dfNewJourney 99
lenPos 1732
I =  9327413 21.2128837443382
dfNewJourney 127
lenPos 1717
I =  9223318 21.238047307498743
dfNewJourney 149
lenPos 1807
I =  9296119 21.263210870659286
dfNewJourney 150
lenPos 1850
I =  9327425 21.28837443381983
dfNewJourney 248
lenPos 1870
I =  9327437 21.313537996980372
dfNewJourney 169
lenPos 1855
I =  9312901 21.338701560140915
dfNewJourney 142
lenPos 1419
I =  9335915 21.36386512330146
dfNewJourney 132
lenPos 1594
I =  9335903 21.389028686462
dfNewJourney 108
lenPos 1688
I =  9337315 21.414192249622545
dfNewJourney 88
lenPos 1579
I =  9337327 21.43935581278309
dfNewJourney 97
lenPos 1779
I =  9292345 21.464519375943635
dfNewJourney 121
lenPos 1521
I =  9323314 21.489682939104178
dfNewJourney 171
lenPos 1756
I =  9302683 21.51484650226472
dfNewJourney 93
lenPos 1736
I =  9252955 21.540010065425264
dfNewJourney 193
lenPos 1802
I =  9315745 21.565173628585807
dfNewJourney 126
lenPos 1803
I =  9334038 21.59033719174635
dfNewJourney 122
lenPos 1748
I =  9334040 21.615500754906893
dfNewJourney 106
lenPos 1645
I =  9323326 21.640664318067437
dfNewJourney 137
lenPos 1854
I =  9315757 21.66582788122798
dfNewJourney 145
lenPos 1746
I =  9323338 21.690991444388523
dfNewJourney 197
lenPos 1335
I =  9314856 21.71615500754907
dfNewJourney 169
lenPos 1851
I =  9314844 21.741318570709613
dfNewJourney 166
lenPos 1826
I =  9314868 21.766482133870156
dfNewJourney 180
lenPos 1744
I =  9314870 21.7916456970307
dfNewJourney 127
lenPos 1812
I =  9323376 21.816809260191246
dfNewJourney 127
lenPos 1721
I =  9323388 21.84197282335179
dfNewJourney 140
lenPos 1840
I =  9323340 21.867136386512332
dfNewJourney 130
lenPos 1807
I =  9323364 21.892299949672875
dfNewJourney 168
lenPos 1827
I =  9323352 21.917463512833418
dfNewJourney 128
lenPos 1791
I =  9323390 21.94262707599396
dfNewJourney 125
lenPos 1663
I =  9323405 21.967790639154504
dfNewJourney 333
lenPos 1866
I =  9351921 21.992954202315047
dfNewJourney 206
lenPos 1852
I =  9339985 22.01811776547559
dfNewJourney 185
lenPos 1721
I =  9357561 22.043281328636137
dfNewJourney 126
lenPos 1825
I =  9421324 22.06844489179668
dfNewJourney 98
lenPos 1702
I =  9442720 22.093608454957224
dfNewJourney 107
lenPos 1683
I =  9421336 22.118772018117767
dfNewJourney 128
lenPos 1862
I =  9379129 22.14393558127831
dfNewJourney 115
lenPos 1855
I =  9301940 22.169099144438853
dfNewJourney 125
lenPos 1863
I =  9301952 22.194262707599396
dfNewJourney 85
lenPos 1237
I =  9252072 22.21942627075994
dfNewJourney 173
lenPos 1691
I =  9364928 22.244589833920482
dfNewJourney 134
lenPos 1787
I =  9379155 22.269753397081026
dfNewJourney 126
lenPos 1657
I =  9379143 22.29491696024157
dfNewJourney 122
lenPos 1802
I =  9396488 22.320080523402115
dfNewJourney 87
lenPos 1667
I =  9329760 22.34524408656266
dfNewJourney 90
lenPos 1695
I =  9384021 22.3704076497232
dfNewJourney 113
lenPos 1842
I =  9396713 22.395571212883745
dfNewJourney 114
lenPos 1527
I =  9387059 22.420734776044288
dfNewJourney 94
lenPos 1756
I =  9396799 22.44589833920483
dfNewJourney 143
lenPos 1387
I =  8705618 22.471061902365374
dfNewJourney 58
lenPos 1619
I =  8916255 22.496225465525917
dfNewJourney 116
lenPos 1793
I =  9384033 22.52138902868646
dfNewJourney 92
lenPos 1660
I =  9339650 22.546552591847004
dfNewJourney 90
lenPos 1748
I =  9405057 22.57171615500755
dfNewJourney 116
lenPos 1796
I =  9384019 22.596879718168093
dfNewJourney 144
lenPos 1806
I =  9389679 22.622043281328637
dfNewJourney 109
lenPos 1860
I =  9408530 22.64720684448918
dfNewJourney 114
lenPos 1891
I =  9369875 22.672370407649723
dfNewJourney 154
lenPos 1803
I =  9394935 22.697533970810266
dfNewJourney 153
lenPos 1849
I =  9394947 22.72269753397081
dfNewJourney 108
lenPos 1459
I =  9401233 22.747861097131352
dfNewJourney 155
lenPos 1875
I =  9283734 22.773024660291895
dfNewJourney 116
lenPos 1697
I =  9231626 22.79818822345244
dfNewJourney 87
lenPos 1730
I =  9441154 22.82335178661298
dfNewJourney 119
lenPos 1693
I =  9408310 22.84851534977353
dfNewJourney 60
lenPos 1889
I =  9369887 22.87367891293407
dfNewJourney 131
lenPos 1826
I =  9394959 22.898842476094615
dfNewJourney 136
lenPos 1642
I =  9402471 22.92400603925516
dfNewJourney 153
lenPos 1618
I =  9420253 22.949169602415704
dfNewJourney 83
lenPos 1790
I =  9408554 22.974333165576247
dfNewJourney 112
lenPos 1817
I =  9417464 22.99949672873679
dfNewJourney 139
lenPos 1715
I =  9441207 23.024660291897334
dfNewJourney 109
lenPos 1751
I =  9470909 23.049823855057877
dfNewJourney 124
lenPos 1850
I =  9428334 23.07498741821842
dfNewJourney 163
lenPos 1408
I =  9430260 23.100150981378963
dfNewJourney 102
lenPos 1652
I =  9441180 23.125314544539506
dfNewJourney 119
lenPos 1792
I =  9260055 23.15047810770005
dfNewJourney 43
lenPos 1073
I =  9118056 23.175641670860596
dfNewJourney 136
lenPos 1813
I =  9351414 23.20080523402114
dfNewJourney 103
lenPos 1862
I =  9351426 23.225968797181682
dfNewJourney 188
lenPos 1798
I =  9306653 23.251132360342226
dfNewJourney 76
lenPos 1235
I =  9212400 23.27629592350277
dfNewJourney 123
lenPos 1758
I =  9351464 23.301459486663312
dfNewJourney 90
lenPos 1740
I =  9374844 23.326623049823855
dfNewJourney 50
lenPos 1262
I =  9374856 23.351786612984398
dfNewJourney 189
lenPos 1875
I =  9290505 23.37695017614494
dfNewJourney 99
lenPos 1845
I =  9246449 23.402113739305484
dfNewJourney 120
lenPos 1776
I =  9316232 23.427277302466027
dfNewJourney 150
lenPos 1540
I =  9235000 23.452440865626574
dfNewJourney 114
lenPos 1725
I =  9216559 23.477604428787117
dfNewJourney 121
lenPos 1731
I =  9246451 23.50276799194766
dfNewJourney 119
lenPos 1769
I =  9259317 23.527931555108204
dfNewJourney 129
lenPos 1756
I =  9316244 23.553095118268747
dfNewJourney 118
lenPos 1788
I =  9407251 23.57825868142929
dfNewJourney 98
lenPos 1734
I =  9407275 23.603422244589833
dfNewJourney 125
lenPos 1691
I =  9407263 23.628585807750376
dfNewJourney 114
lenPos 1779
I =  9407287 23.65374937091092
dfNewJourney 79
lenPos 1728
I =  9401221 23.678912934071462
dfNewJourney 131
lenPos 1809
I =  9384100 23.70407649723201
dfNewJourney 82
lenPos 1672
I =  9441166 23.729240060392552
dfNewJourney 96
lenPos 1723
I =  9441192 23.754403623553095
dfNewJourney 118
lenPos 1815
I =  9279719 23.77956718671364
dfNewJourney 130
lenPos 1820
I =  9296731 23.80473074987418
dfNewJourney 150
lenPos 1879
I =  9311012 23.829894313034725
dfNewJourney 134
lenPos 1793
I =  9311024 23.855057876195268
dfNewJourney 144
lenPos 1755
I =  9344007 23.88022143935581
dfNewJourney 142
lenPos 1848
I =  9344019 23.905385002516354
dfNewJourney 108
lenPos 1776
I =  9363481 23.930548565676897
dfNewJourney 129
lenPos 1864
I =  9363493 23.955712128837444
dfNewJourney 184
lenPos 1757
I =  9316610 23.980875691997987
dfNewJourney 108
lenPos 1574
I =  9388766 24.00603925515853
dfNewJourney 99
lenPos 1629
I =  9388742 24.031202818319073

dfNewJourney 130
lenPos 1826
I =  9393084 24.05636638147962
dfNewJourney 19
lenPos 734
I =  8420232 24.081529944640163
dfNewJourney 131
lenPos 1670
I =  9470935 24.106693507800706
dfNewJourney 126
lenPos 1660
I =  9446116 24.13185707096125
dfNewJourney 154
lenPos 1547
I =  9388778 24.157020634121793
dfNewJourney 133
lenPos 1617
I =  9470947 24.182184197282336
dfNewJourney 111
lenPos 1802
I =  9290957 24.20734776044288
dfNewJourney 130
lenPos 1590
I =  9402263 24.232511323603422
dfNewJourney 97
lenPos 1642
I =  9282912 24.257674886763965
dfNewJourney 149
lenPos 1635
I =  9392822 24.28283844992451
dfNewJourney 119
lenPos 1880
I =  9403310 24.308002013085055
dfNewJourney 120
lenPos 1693
I =  9299422 24.333165576245598
dfNewJourney 105
lenPos 1479
I =  9315446 24.35832913940614
dfNewJourney 153
lenPos 1823
I =  9388780 24.383492702566684
dfNewJourney 208
lenPos 1591
I =  9350654 24.408656265727227
dfNewJourney 120
lenPos 1804
I =  9296597 24.43381982888777
dfNewJourney 102
lenPos 1703
I =  9273844 24.458983392048314
dfNewJourney 200
lenPos 1457
I =  9284788 24.484146955208857
dfNewJourney 151
lenPos 1670
I =  9408322 24.5093105183694
dfNewJourney 116
lenPos 1664
I =  9457713 24.534474081529943
dfNewJourney 119
lenPos 1858
I =  9197284 24.559637644690486
dfNewJourney 95
lenPos 1817
I =  9506069 24.584801207851033
dfNewJourney 54
lenPos 1136
I =  9180920 24.609964771011576
dfNewJourney 18
lenPos 425
I =  9120918 24.63512833417212
dfNewJourney 154
lenPos 1576
I =  9414503 24.660291897332662
dfNewJourney 133
lenPos 1536
I =  9370850 24.685455460493205
dfNewJourney 63
lenPos 1269
I =  9388792 24.71061902365375
dfNewJourney 87
lenPos 1481
I =  9273246 24.73578258681429
dfNewJourney 98
lenPos 1709
I =  9273650 24.760946149974835
dfNewJourney 104
lenPos 1665
I =  9384564 24.786109713135378
dfNewJourney 67
lenPos 1533
I =  9136058 24.81127327629592
dfNewJourney 77
lenPos 1677
I =  9298818 24.836436839456468
dfNewJourney 204
lenPos 1860
I =  9387255 24.86160040261701
dfNewJourney 123
lenPos 1795
I =  9393096 24.886763965777554
dfNewJourney 134
lenPos 1551
I =  9388807 24.911927528938097
dfNewJourney 144
lenPos 1794
I =  9259173 24.93709109209864
dfNewJourney 111
lenPos 1689
I =  9302970 24.962254655259184
dfNewJourney 119
lenPos 1867
I =  9419723 24.987418218419727
dfNewJourney 159
lenPos 1727
I =  9257802 25.012581781580273
dfNewJourney 77
lenPos 1240
I =  9180982 25.037745344740813
dfNewJourney 166
lenPos 1530
I =  9308120 25.06290890790136
dfNewJourney 255
lenPos 1783
I =  9351531 25.0880724710619
dfNewJourney 339
lenPos 1860
I =  9351543 25.113236034222446
dfNewJourney 124
lenPos 1801
I =  9333278 25.13839959738299
dfNewJourney 74
lenPos 1631
I =  9315458 25.163563160543532
dfNewJourney 193
lenPos 1581
I =  9308132 25.188726723704075
dfNewJourney 277
lenPos 1805
I =  9274329 25.213890286864622
dfNewJourney 129
lenPos 1734
I =  9292357 25.23905385002516
dfNewJourney 110
lenPos 1837
I =  9325831 25.26421741318571
dfNewJourney 238
lenPos 1755
I =  9356751 25.289380976346248
dfNewJourney 153
lenPos 1526
I =  9329409 25.314544539506795
dfNewJourney 36
lenPos 1845
I =  9047386 25.339708102667334
dfNewJourney 11
lenPos 1711
I =  9047398 25.36487166582788
dfNewJourney 187
lenPos 1577
I =  9308144 25.390035228988424
dfNewJourney 145
lenPos 1757
I =  9341445 25.415198792148967
dfNewJourney 104
lenPos 1802
I =  9326902 25.44036235530951
dfNewJourney 118
lenPos 1828
I =  9250751 25.465525918470057
dfNewJourney 194
lenPos 1608
I =  9308156 25.490689481630596
dfNewJourney 45
lenPos 1261
I =  9374868 25.515853044791143
dfNewJourney 177
lenPos 1546
I =  9308170 25.54101660795169
dfNewJourney 190
lenPos 1491
I =  9242479 25.56618017111223
dfNewJourney 119
lenPos 1785
I =  9347310 25.591343734272776
dfNewJourney 93
lenPos 1881
I =  9349198 25.616507297433316
dfNewJourney 90
lenPos 1674
I =  9319674 25.641670860593862
dfNewJourney 61
lenPos 1358
I =  9242481 25.666834423754402
dfNewJourney 184
lenPos 1622
I =  9308168 25.69199798691495
dfNewJourney 112
lenPos 1781
I =  9326914 25.71716155007549
dfNewJourney 69
lenPos 1850
I =  9349203 25.742325113236035
dfNewJourney 115
lenPos 1701
I =  9251028 25.767488676396578
dfNewJourney 104
lenPos 1599
I =  9319686 25.792652239557125
dfNewJourney 153
lenPos 1541
I =  9356763 25.817815802717664
dfNewJourney 92
lenPos 1391
I =  9423906 25.84297936587821
dfNewJourney 115
lenPos 1841
I =  9294288 25.86814292903875
dfNewJourney 329
lenPos 1853
I =  9262584 25.893306492199297
dfNewJourney 65
lenPos 1572
I =  9388730 25.918470055359837
dfNewJourney 120
lenPos 1810
I =  9397456 25.943633618520384
dfNewJourney 93
lenPos 1842
I =  9418119 25.968797181680927
dfNewJourney 135
lenPos 1731
I =  9395379 25.99396074484147
dfNewJourney 140
lenPos 1541
I =  9368223 26.019124308002013
dfNewJourney 113
lenPos 1760
I =  9326926 26.04428787116256
dfNewJourney 193
lenPos 1794
I =  9199828 26.0694514343231
dfNewJourney 101
lenPos 1794
I =  9326938 26.094614997483646
dfNewJourney 125
lenPos 1858
I =  9404223 26.119778560644185
dfNewJourney 111
lenPos 1561
I =  9368235 26.144942123804732
dfNewJourney 215
lenPos 1831
I =  9388704 26.17010568696527
dfNewJourney 118
lenPos 1768
I =  9343194 26.19526925012582
dfNewJourney 125
lenPos 1636
I =  9388754 26.220432813286358
dfNewJourney 146
lenPos 1623
I =  9337339 26.245596376446905
dfNewJourney 90
lenPos 1387
I =  9145425 26.270759939607448
dfNewJourney 72
lenPos 1061
I =  9208136 26.29592350276799
dfNewJourney 171
lenPos 1242
I =  9359624 26.321087065928534
dfNewJourney 185
lenPos 1550
I =  9337303 26.34625062908908
dfNewJourney 138
lenPos 1755
I =  9282297 26.37141419224962
dfNewJourney 143
lenPos 1701
I =  9279721 26.396577755410167
dfNewJourney 107
lenPos 1782
I =  9374337 26.421741318570707
dfNewJourney 129
lenPos 1809
I =  9391531 26.446904881731253
dfNewJourney 167
lenPos 1810
I =  9274678 26.472068444891793
dfNewJourney 87
lenPos 1379
I =  9110183 26.49723200805234
dfNewJourney 115
lenPos 1818
I =  9102100 26.522395571212883
dfNewJourney 105
lenPos 1742
I =  9102124 26.547559134373426
dfNewJourney 79
lenPos 1184
I =  9110638 26.57272269753397
dfNewJourney 94
lenPos 1547
I =  9105085 26.597886260694516
dfNewJourney 85
lenPos 1625
I =  9149249 26.623049823855062
dfNewJourney 75
lenPos 1684
I =  9149213 26.648213387015602
dfNewJourney 99
lenPos 1691
I =  9149225 26.67337695017615
dfNewJourney 67
lenPos 1489
I =  9149251 26.698540513336688
dfNewJourney 90
lenPos 1636
I =  9155767 26.723704076497235
dfNewJourney 56
lenPos 1474
I =  9160530 26.748867639657774
dfNewJourney 190
lenPos 1352
I =  9163271 26.77403120281832
dfNewJourney 119
lenPos 1388
I =  9166417 26.79919476597886
dfNewJourney 62
lenPos 1286
I =  9181857 26.824358329139407
dfNewJourney 117
lenPos 1818
I =  9181869 26.84952189229995
dfNewJourney 154
lenPos 1687
I =  9174608 26.874685455460494
dfNewJourney 147
lenPos 1770
I =  9208473 26.899849018621037
dfNewJourney 34
lenPos 844
I =  9074121 26.925012581781584
dfNewJourney 106
lenPos 1784
I =  9216901 26.950176144942123
dfNewJourney 105
lenPos 1846
I =  9234472 26.97533970810267
dfNewJourney 117
lenPos 1799
I =  9225330 27.00050327126321
dfNewJourney 109
lenPos 1855
I =  9228370 27.025666834423756
dfNewJourney 111
lenPos 1907
I =  9230995 27.050830397584296
dfNewJourney 145
lenPos 1770
I =  9231614 27.075993960744842
dfNewJourney 134
lenPos 1710
I =  9234587 27.101157523905385
dfNewJourney 117
lenPos 1738
I =  9251274 27.12632108706593
dfNewJourney 169
lenPos 1820
I =  9223344 27.15148465022647
dfNewJourney 201
lenPos 1862
I =  9256078 27.17664821338702
dfNewJourney 124
lenPos 1540
I =  9258179 27.201811776547558
dfNewJourney 112
lenPos 1728
I =  9234599 27.226975339708105
dfNewJourney 118
lenPos 1903
I =  9242089 27.252138902868644
dfNewJourney 125
lenPos 1519
I =  9241085 27.27730246602919
dfNewJourney 112
lenPos 1713
I =  9239989 27.30246602918973
dfNewJourney 118
lenPos 1689
I =  9251896 27.327629592350277
dfNewJourney 124
lenPos 1771
I =  9251884 27.352793155510817
dfNewJourney 123
lenPos 1610
I =  9116383 27.377956718671363
dfNewJourney 111
lenPos 1818
I =  9254812 27.403120281831907
dfNewJourney 116
lenPos 1704
I =  9292034 27.42828384499245
dfNewJourney 66
lenPos 1625
I =  9234496 27.453447408152993

dfNewJourney 164
lenPos 1794
I =  9299680 27.47861097131354
dfNewJourney 137
lenPos 1733
I =  9272929 27.50377453447408
dfNewJourney 128
lenPos 1765
I =  9272931 27.528938097634626
dfNewJourney 192
lenPos 1644
I =  9292826 27.554101660795165
dfNewJourney 230
lenPos 1625
I =  9292838 27.579265223955712
dfNewJourney 223
lenPos 1666
I =  9323596 27.60442878711625
dfNewJourney 190
lenPos 1630
I =  9324497 27.6295923502768
dfNewJourney 141
lenPos 1463
I =  9295050 27.65475591343734
dfNewJourney 119
lenPos 1802
I =  9289738 27.679919476597885
dfNewJourney 140
lenPos 1792
I =  9289740 27.70508303975843
dfNewJourney 142
lenPos 1751
I =  9306457 27.730246602918974
dfNewJourney 117
lenPos 1644
I =  9306469 27.75541016607952
dfNewJourney 84
lenPos 1260
I =  9272694 27.78057372924006
dfNewJourney 179
lenPos 1722
I =  9272709 27.805737292400607
dfNewJourney 172
lenPos 1804
I =  9313266 27.830900855561147
dfNewJourney 146
lenPos 1833
I =  9297436 27.856064418721694
dfNewJourney 310
lenPos 1832
I =  9297448 27.881227981882233
dfNewJourney 110
lenPos 1852
I =  9234513 27.90639154504278
dfNewJourney 94
lenPos 1403
I =  9301732 27.93155510820332
dfNewJourney 111
lenPos 1752
I =  9301744 27.956718671363866
dfNewJourney 118
lenPos 1867
I =  9333656 27.98188223452441
dfNewJourney 152
lenPos 1665
I =  9292204 28.007045797684953
dfNewJourney 176
lenPos 1729
I =  9341067 28.032209360845496
dfNewJourney 126
lenPos 1702
I =  9341079 28.057372924006042
dfNewJourney 135
lenPos 1581
I =  9341081 28.082536487166582
dfNewJourney 205
lenPos 1717
I =  9341093 28.10770005032713
dfNewJourney 181
lenPos 1519
I =  9299496 28.132863613487668
dfNewJourney 120
lenPos 1750
I =  9292046 28.158027176648215
dfNewJourney 127
lenPos 1804
I =  9292058 28.183190739808754
dfNewJourney 205
lenPos 1819
I =  9293973 28.2083543029693
dfNewJourney 144
lenPos 1725
I =  9300996 28.233517866129844
dfNewJourney 139
lenPos 1794
I =  9341512 28.258681429290387
dfNewJourney 118
lenPos 1849
I =  9309241 28.28384499245093
dfNewJourney 151
lenPos 1835
I =  9309253 28.309008555611477
dfNewJourney 84
lenPos 1903
I =  9342580 28.334172118772017
dfNewJourney 233
lenPos 1894
I =  9305568 28.359335681932563
dfNewJourney 171
lenPos 1799
I =  9340104 28.384499245093103
dfNewJourney 113
lenPos 1749
I =  9312884 28.40966280825365
dfNewJourney 135
lenPos 1763
I =  9365817 28.43482637141419
dfNewJourney 247
lenPos 1817
I =  9322956 28.459989934574736
dfNewJourney 224
lenPos 1633
I =  9322968 28.485153497735276
dfNewJourney 137
lenPos 1804
I =  9292060 28.510317060895822
dfNewJourney 122
lenPos 1699
I =  9333412 28.535480624056365
dfNewJourney 109
lenPos 1803
I =  9327449 28.56064418721691
dfNewJourney 134
lenPos 1813
I =  9315068 28.58580775037745
dfNewJourney 116
lenPos 1835
I =  9321940 28.610971313538
dfNewJourney 117
lenPos 1857
I =  9315783 28.636134876698538
dfNewJourney 119
lenPos 1818
I =  9333424 28.661298439859085
dfNewJourney 117
lenPos 1755
I =  9333436 28.686462003019624
dfNewJourney 189
lenPos 1828
I =  9365283 28.71162556618017
dfNewJourney 147
lenPos 1866
I =  9299771 28.736789129340718
dfNewJourney 140
lenPos 1586
I =  9344033 28.761952692501257
dfNewJourney 159
lenPos 1854
I =  9225328 28.787116255661804
dfNewJourney 123
lenPos 1705
I =  9316593 28.812279818822343
dfNewJourney 102
lenPos 1828
I =  9315939 28.83744338198289
dfNewJourney 119
lenPos 1830
I =  9315941 28.862606945143433
dfNewJourney 110
lenPos 1828
I =  9328285 28.88777050830398
dfNewJourney 97
lenPos 1855
I =  9328297 28.91293407146452
dfNewJourney 119
lenPos 1809
I =  9327463 28.938097634625066
dfNewJourney 118
lenPos 1818
I =  9327451 28.963261197785606
dfNewJourney 128
lenPos 1833
I =  9325609 28.988424760946153
dfNewJourney 4
lenPos 1138
I =  8711083 29.013588324106692
dfNewJourney 151
lenPos 1456
I =  9167174 29.03875188726724
dfNewJourney 134
lenPos 1748
I =  9214745 29.06391545042778
dfNewJourney 146
lenPos 1674
I =  9338802 29.089079013588325
dfNewJourney 151
lenPos 1849
I =  9410002 29.114242576748868
dfNewJourney 120
lenPos 1773
I =  9410014 29.13940613990941
dfNewJourney 143
lenPos 1799
I =  9339313 29.164569703069954
dfNewJourney 160
lenPos 1808
I =  9339325 29.1897332662305
dfNewJourney 188
lenPos 1879
I =  9339337 29.21489682939104
dfNewJourney 264
lenPos 1780
I =  9329655 29.240060392551587
dfNewJourney 156
lenPos 1751
I =  9329667 29.265223955712127
dfNewJourney 95
lenPos 1762
I =  9314167 29.290387518872674
dfNewJourney 86
lenPos 1687
I =  9314179 29.315551082033213
dfNewJourney 123
lenPos 1457
I =  9183257 29.34071464519376
dfNewJourney 135
lenPos 1691
I =  9340116 29.365878208354303
dfNewJourney 141
lenPos 1500
I =  9374428 29.391041771514846
dfNewJourney 109
lenPos 1800
I =  9390927 29.41620533467539
dfNewJourney 109
lenPos 1622
I =  9390939 29.441368897835936
dfNewJourney 98
lenPos 1584
I =  9403542 29.466532460996476
dfNewJourney 101
lenPos 1608
I =  9389564 29.491696024157022
dfNewJourney 111
lenPos 1622
I =  9426594 29.516859587317562
dfNewJourney 111
lenPos 1588
I =  9406910 29.54202315047811
dfNewJourney 115
lenPos 1800
I =  9358955 29.567186713638648
dfNewJourney 157
lenPos 1652
I =  9340128 29.592350276799195
dfNewJourney 134
lenPos 1524
I =  9374416 29.617513839959734
dfNewJourney 113
lenPos 1747
I =  9379301 29.64267740312028
dfNewJourney 102
lenPos 1736
I =  9379961 29.667840966280824
dfNewJourney 91
lenPos 1752
I =  9314181 29.693004529441367
dfNewJourney 88
lenPos 1588
I =  9396660 29.71816809260191
dfNewJourney 137
lenPos 1667
I =  9239977 29.743331655762457
dfNewJourney 81
lenPos 1727
I =  9314193 29.768495218922997
dfNewJourney 102
lenPos 1739
I =  9334557 29.793658782083543
dfNewJourney 183
lenPos 1786
I =  9388297 29.81882234524409
dfNewJourney 161
lenPos 1854
I =  9390692 29.84398590840463
dfNewJourney 158
lenPos 1789
I =  9323560 29.869149471565176
dfNewJourney 126
lenPos 1771
I =  9361512 29.894313034725716
dfNewJourney 76
lenPos 1799
I =  9334569 29.919476597886263
dfNewJourney 144
lenPos 1845
I =  9339648 29.944640161046802
dfNewJourney 111
lenPos 1741
I =  9361524 29.96980372420735
dfNewJourney 119
lenPos 1826
I =  9382798 29.994967287367892
dfNewJourney 87
lenPos 1527
I =  9396672 30.02013085052844
dfNewJourney 94
lenPos 1492
I =  9417751 30.04529441368898
dfNewJourney 119
lenPos 1674
I =  9396335 30.070457976849525
dfNewJourney 126
lenPos 1735
I =  9325324 30.095621540010065
dfNewJourney 132
lenPos 1840
I =  9374507 30.12078510317061
dfNewJourney 101
lenPos 1663
I =  9407354 30.14594866633115
dfNewJourney 100
lenPos 1616
I =  9417763 30.171112229491698
dfNewJourney 116
lenPos 1597
I =  9430167 30.196275792652237
dfNewJourney 96
lenPos 1856
I =  9407366 30.221439355812784
dfNewJourney 117
lenPos 1684
I =  9215115 30.246602918973327
dfNewJourney 280
lenPos 1733
I =  9430179 30.27176648213387
dfNewJourney 120
lenPos 1440
I =  9487172 30.296930045294413
dfNewJourney 93
lenPos 1655
I =  9419357 30.32209360845496
dfNewJourney 110
lenPos 1744
I =  9382956 30.3472571716155
dfNewJourney 114
lenPos 1650
I =  9382968 30.372420734776046
dfNewJourney 97
lenPos 1723
I =  9419369 30.397584297936586
dfNewJourney 134
lenPos 1784
I =  9422639 30.422747861097132
dfNewJourney 213
lenPos 1871
I =  9413547 30.447911424257672
dfNewJourney 209
lenPos 1876
I =  9413559 30.47307498741822
dfNewJourney 237
lenPos 1751
I =  9178329 30.498238550578762
dfNewJourney 39
lenPos 1139
I =  9182667 30.523402113739305
dfNewJourney 15
lenPos 1241
I =  9081382 30.548565676899848
dfNewJourney 119
lenPos 1833
I =  9351438 30.573729240060395
dfNewJourney 116
lenPos 1801
I =  9351440 30.598892803220934
dfNewJourney 93
lenPos 1772
I =  9185487 30.62405636638148
dfNewJourney 76
lenPos 1818
I =  9185499 30.64921992954202
dfNewJourney 125
lenPos 1719
I =  9242118 30.674383492702567
dfNewJourney 32
lenPos 824
I =  9208485 30.699547055863107
dfNewJourney 127
lenPos 1499
I =  9222168 30.724710619023654
dfNewJourney 125
lenPos 1713
I =  9192741 30.749874182184193
dfNewJourney 71
lenPos 1344
I =  9192765 30.77503774534474
dfNewJourney 115
lenPos 1788
I =  9298313 30.800201308505283
dfNewJourney 94
lenPos 1810
I =  9298325 30.825364871665826
dfNewJourney 138
lenPos 1774
I =  9330343 30.85052843482637
dfNewJourney 102
lenPos 1752
I =  9330355 30.875691997986916

dfNewJourney 41
lenPos 1210
I =  9147253 30.900855561147463
dfNewJourney 89
lenPos 1494
I =  9236731 30.926019124308002
dfNewJourney 114
lenPos 1814
I =  9230971 30.95118268746855
dfNewJourney 143
lenPos 1815
I =  9391361 30.97634625062909
dfNewJourney 181
lenPos 1826
I =  9391373 31.001509813789635
dfNewJourney 164
lenPos 1626
I =  9188764 31.026673376950175
dfNewJourney 139
lenPos 1448
I =  9234680 31.05183694011072
dfNewJourney 170
lenPos 1821
I =  9425497 31.07700050327126
dfNewJourney 153
lenPos 1812
I =  9391385 31.102164066431808
dfNewJourney 40
lenPos 1897
I =  9230426 31.12732762959235
dfNewJourney 171
lenPos 1840
I =  9391397 31.152491192752898
dfNewJourney 136
lenPos 1833
I =  9391402 31.177654755913437
dfNewJourney 159
lenPos 1822
I =  9391414 31.202818319073984
dfNewJourney 119
lenPos 1717
I =  9410648 31.227981882234523
dfNewJourney 133
lenPos 1763
I =  9410650 31.25314544539507
dfNewJourney 138
lenPos 1759
I =  9420851 31.27830900855561
dfNewJourney 86
lenPos 1651
I =  9356438 31.303472571716156
dfNewJourney 206
lenPos 1873
I =  9356426 31.328636134876696
dfNewJourney 112
lenPos 1823
I =  9389318 31.353799698037243
dfNewJourney 255
lenPos 1806
I =  9251664 31.378963261197786
dfNewJourney 247
lenPos 1839
I =  9298181 31.40412682435833
dfNewJourney 167
lenPos 1774
I =  9365623 31.429290387518872
dfNewJourney 178
lenPos 1730
I =  9365635 31.45445395067942
dfNewJourney 363
lenPos 1855
I =  9298789 31.47961751383996
dfNewJourney 116
lenPos 1887
I =  8617093 31.504781077000505
dfNewJourney 19
lenPos 1844
I =  8617079 31.529944640161045
dfNewJourney 30
lenPos 1615
I =  8421171 31.55510820332159
dfNewJourney 23
lenPos 1862
I =  8617081 31.58027176648213
dfNewJourney 131
lenPos 1860
I =  8617108 31.605435329642678
dfNewJourney 96
lenPos 1378
I =  9154957 31.63059889280322
dfNewJourney 101
lenPos 1865
I =  9299367 31.655762455963764
dfNewJourney 238
lenPos 1730
I =  9174373 31.680926019124307
dfNewJourney 206
lenPos 1865
I =  9174385 31.706089582284854
dfNewJourney 123
lenPos 1607
I =  9307932 31.731253145445393
dfNewJourney 115
lenPos 1756
I =  9307944 31.75641670860594
dfNewJourney 120
lenPos 1830
I =  9263174 31.78158027176648
dfNewJourney 142
lenPos 1735
I =  9281578 31.806743834927026
dfNewJourney 78
lenPos 1507
I =  9550694 31.831907398087566
dfNewJourney 96
lenPos 1652
I =  9550709 31.857070961248112
dfNewJourney 97
lenPos 1818
I =  9336505 31.882234524408652
dfNewJourney 152
lenPos 1660
I =  9260005 31.9073980875692
dfNewJourney 264
lenPos 1893
I =  9251640 31.932561650729745
dfNewJourney 238
lenPos 1832
I =  9255488 31.957725213890285
dfNewJourney 236
lenPos 1862
I =  9327360 31.98288877705083
dfNewJourney 168
lenPos 1795
I =  9397559 32.00805234021137
dfNewJourney 204
lenPos 1846
I =  9314832 32.03321590337192
dfNewJourney 218
lenPos 1807
I =  9443425 32.05837946653246
dfNewJourney 214
lenPos 1801
I =  9295347 32.083543029693004
dfNewJourney 216
lenPos 1817
I =  9327396 32.10870659285355
dfNewJourney 138
lenPos 1675
I =  9389320 32.13387015601409
dfNewJourney 115
lenPos 1699
I =  9389332 32.15903371917464
dfNewJourney 200
lenPos 1824
I =  9418494 32.184197282335184
dfNewJourney 164
lenPos 1791
I =  9397535 32.20936084549572
dfNewJourney 201
lenPos 1824
I =  9228813 32.23452440865627
dfNewJourney 236
lenPos 1825
I =  9286047 32.25968797181681
dfNewJourney 114
lenPos 1822
I =  9305867 32.284851534977356
dfNewJourney 229
lenPos 1861
I =  9423449 32.310015098137896
dfNewJourney 171
lenPos 1692
I =  9448322 32.33517866129844
dfNewJourney 127
lenPos 1859
I =  9392482 32.36034222445898
dfNewJourney 176
lenPos 1859
I =  9302669 32.38550578761953
dfNewJourney 142
lenPos 1631
I =  9215103 32.41066935078007
dfNewJourney 124
lenPos 1712
I =  9254070 32.435832913940615
dfNewJourney 74
lenPos 1451
I =  9358400 32.460996477101155
dfNewJourney 113
lenPos 1666
I =  9358412 32.4861600402617
dfNewJourney 119
lenPos 1874
I =  9392470 32.51132360342224
dfNewJourney 115
lenPos 1506
I =  9278507 32.53648716658279
dfNewJourney 65
lenPos 1688
I =  9133070 32.56165072974333
dfNewJourney 212
lenPos 1863
I =  9274630 32.586814292903874
dfNewJourney 64
lenPos 1849
I =  9285732 32.611977856064414
dfNewJourney 127
lenPos 1735
I =  9288760 32.63714141922496
dfNewJourney 146
lenPos 1793
I =  9297345 32.66230498238551
dfNewJourney 160
lenPos 1801
I =  9297371 32.687468545546054
dfNewJourney 96
lenPos 1710
I =  9282479 32.71263210870659
dfNewJourney 156
lenPos 1727
I =  9281932 32.73779567186714
dfNewJourney 184
lenPos 1889
I =  9306641 32.76295923502768
dfNewJourney 180
lenPos 1820
I =  9299434 32.788122798188226
dfNewJourney 126
lenPos 1718
I =  9299458 32.813286361348766
dfNewJourney 199
lenPos 1854
I =  9353101 32.83844992450931
dfNewJourney 227
lenPos 1797
I =  9353096 32.86361348766985
dfNewJourney 116
lenPos 1804
I =  9433901 32.8887770508304
dfNewJourney 132
lenPos 1809
I =  9442017 32.91394061399094
dfNewJourney 134
lenPos 1637
I =  9251561 32.939104177151485
dfNewJourney 138
lenPos 1749
I =  9285706 32.964267740312025
dfNewJourney 129
lenPos 1859
I =  9230098 32.98943130347257
dfNewJourney 55
lenPos 1516
I =  8909472 33.01459486663312
dfNewJourney 106
lenPos 1812
I =  9176773 33.03975842979366
dfNewJourney 113
lenPos 1769
I =  9236248 33.064921992954204
dfNewJourney 128
lenPos 1846
I =  9271406 33.090085556114744
dfNewJourney 130
lenPos 1808
I =  9275969 33.11524911927529
dfNewJourney 127
lenPos 1835
I =  9255684 33.14041268243583
dfNewJourney 112
lenPos 1561
I =  9309007 33.16557624559638
dfNewJourney 215
lenPos 1804
I =  9315800 33.190739808756916
dfNewJourney 122
lenPos 1843
I =  9307827 33.21590337191746
dfNewJourney 88
lenPos 1709
I =  9408542 33.24106693507801
dfNewJourney 130
lenPos 1567
I =  9380661 33.26623049823855
dfNewJourney 116
lenPos 1547
I =  9389071 33.291394061399096
dfNewJourney 113
lenPos 1822
I =  9389095 33.31655762455964
dfNewJourney 124
lenPos 1744
I =  9382762 33.34172118772018
dfNewJourney 115
lenPos 1743
I =  9207716 33.36688475088073
dfNewJourney 91
lenPos 1642
I =  9256248 33.39204831404127
dfNewJourney 217
lenPos 1830
I =  9244441 33.417211877201815
dfNewJourney 147
lenPos 1825
I =  9413688 33.442375440362355
dfNewJourney 172
lenPos 1753
I =  9422005 33.4675390035229
dfNewJourney 205
lenPos 1764
I =  9376854 33.49270256668344
dfNewJourney 172
lenPos 1787
I =  9429182 33.51786612984399
dfNewJourney 123
lenPos 1866
I =  9423736 33.54302969300453
dfNewJourney 197
lenPos 1731
I =  9422835 33.568193256165074
dfNewJourney 112
lenPos 1847
I =  9410911 33.593356819325614
dfNewJourney 190
lenPos 1788
I =  9322944 33.61852038248616
dfNewJourney 183
lenPos 1837
I =  9391945 33.6436839456467
dfNewJourney 80
lenPos 1654
I =  9410894 33.66884750880725
dfNewJourney 135
lenPos 1763
I =  9373668 33.694011071967786
dfNewJourney 161
lenPos 1851
I =  9317949 33.71917463512833
dfNewJourney 269
lenPos 1860
I =  9396024 33.74433819828887
dfNewJourney 145
lenPos 1822
I =  9407457 33.76950176144942
dfNewJourney 104
lenPos 1784
I =  9399911 33.794665324609966
dfNewJourney 158
lenPos 1811
I =  9399935 33.81982888777051
dfNewJourney 153
lenPos 1859
I =  9399923 33.84499245093105
dfNewJourney 137
lenPos 1815
I =  9428360 33.8701560140916
dfNewJourney 59
lenPos 1553
I =  9178317 33.89531957725214
dfNewJourney 142
lenPos 1650
I =  9258480 33.920483140412685
dfNewJourney 184
lenPos 1781
I =  9380582 33.945646703573225
dfNewJourney 208
lenPos 1860
I =  9380594 33.97081026673377
dfNewJourney 102
lenPos 1695
I =  9387695 33.99597382989431
dfNewJourney 107
lenPos 1767
I =  9387712 34.02113739305486
dfNewJourney 114
lenPos 1703
I =  9294551 34.046300956215404
dfNewJourney 94
lenPos 1686
I =  9231468 34.071464519375944
dfNewJourney 122
lenPos 1607
I =  9112222 34.09662808253649
dfNewJourney 78
lenPos 1375
I =  9112234 34.12179164569703
dfNewJourney 76
lenPos 980
I =  9212369 34.14695520885758
dfNewJourney 135
lenPos 1782
I =  9215309 34.172118772018116
dfNewJourney 128
lenPos 1820
I =  9215268 34.19728233517866
dfNewJourney 127
lenPos 1832
I =  9215270 34.2224458983392
dfNewJourney 107
lenPos 1625
I =  9387683 34.24760946149975
dfNewJourney 188
lenPos 1816
I =  9187772 34.27277302466029
dfNewJourney 163
lenPos 1792
I =  9321976 34.297936587820836
dfNewJourney 166
lenPos 1744
I =  9336397 34.323100150981375

dfNewJourney 124
lenPos 1553
I =  9274094 34.34826371414192
dfNewJourney 96
lenPos 1666
I =  9272204 34.37342727730247
dfNewJourney 113
lenPos 1797
I =  9312444 34.39859084046301
dfNewJourney 102
lenPos 1891
I =  9390020 34.423754403623555
dfNewJourney 180
lenPos 1802
I =  9381847 34.4489179667841
dfNewJourney 103
lenPos 1796
I =  9389849 34.47408152994464
dfNewJourney 47
lenPos 1675
I =  9162526 34.49924509310519
dfNewJourney 135
lenPos 1691
I =  9240718 34.52440865626573
dfNewJourney 97
lenPos 1549
I =  9249180 34.549572219426274
dfNewJourney 132
lenPos 1648
I =  9414254 34.574735782586814
dfNewJourney 214
lenPos 1878
I =  9322839 34.59989934574736
dfNewJourney 153
lenPos 1760
I =  9414060 34.6250629089079
dfNewJourney 57
lenPos 1780
I =  9164213 34.65022647206845
dfNewJourney 53
lenPos 1808
I =  9234501 34.675390035228986
dfNewJourney 115
lenPos 1780
I =  9305348 34.70055359838953
dfNewJourney 103
lenPos 1884
I =  9422392 34.72571716155007
dfNewJourney 179
lenPos 1707
I =  9380104 34.75088072471062
dfNewJourney 147
lenPos 1754
I =  9409493 34.77604428787116
dfNewJourney 114
lenPos 1756
I =  9314088 34.801207851031705
dfNewJourney 93
lenPos 1376
I =  9157765 34.826371414192245
dfNewJourney 110
lenPos 1713
I =  9038842 34.85153497735279
dfNewJourney 147
lenPos 1758
I =  9418638 34.87669854051333
dfNewJourney 186
lenPos 1843
I =  9547520 34.90186210367388
dfNewJourney 89
lenPos 1778
I =  9410179 34.927025666834425
dfNewJourney 49
lenPos 1750
I =  9208095 34.95218922999497
dfNewJourney 105
lenPos 1824
I =  9399894 34.97735279315551
dfNewJourney 129
lenPos 1739
I =  9275983 35.00251635631606
dfNewJourney 126
lenPos 1799
I =  9405899 35.0276799194766
dfNewJourney 107
lenPos 1683
I =  9443865 35.052843482637144
dfNewJourney 119
lenPos 1802
I =  9424649 35.07800704579768
dfNewJourney 100
lenPos 1818
I =  9288382 35.10317060895823
dfNewJourney 131
lenPos 1864
I =  9547506 35.12833417211878
dfNewJourney 155
lenPos 1799
I =  9380099 35.153497735279316
dfNewJourney 125
lenPos 1872
I =  9403334 35.17866129843986
dfNewJourney 132
lenPos 1759
I =  9405916 35.2038248616004
dfNewJourney 157
lenPos 1747
I =  9308778 35.22898842476095
dfNewJourney 132
lenPos 1707
I =  9284685 35.25415198792149
dfNewJourney 141
lenPos 1739
I =  9310680 35.279315551082036
dfNewJourney 131
lenPos 1696
I =  9414242 35.304479114242575
dfNewJourney 88
lenPos 1674
I =  9383950 35.32964267740312
dfNewJourney 105
lenPos 1816
I =  9273351 35.35480624056366
dfNewJourney 137
lenPos 1660
I =  9228710 35.37996980372421
dfNewJourney 96
lenPos 1821
I =  9282510 35.40513336688475
dfNewJourney 123
lenPos 1660
I =  9174488 35.430296930045294
dfNewJourney 112
lenPos 1803
I =  9420758 35.455460493205834
dfNewJourney 146
lenPos 1419
I =  9398266 35.48062405636638
dfNewJourney 129
lenPos 1744
I =  9397808 35.50578761952693
dfNewJourney 151
lenPos 1824
I =  9420760 35.53095118268747
dfNewJourney 147
lenPos 1483
I =  9302865 35.556114745848014
dfNewJourney 92
lenPos 1362
I =  9271236 35.58127830900856
dfNewJourney 49
lenPos 1815
I =  6806444 35.6064418721691
dfNewJourney 44
lenPos 1614
I =  8314158 35.63160543532965
dfNewJourney 214
lenPos 1857
I =  9353577 35.656768998490186
dfNewJourney 167
lenPos 1793
I =  9399909 35.68193256165073
dfNewJourney 127
lenPos 1824
I =  9272395 35.70709612481127
dfNewJourney 146
lenPos 1799
I =  9409467 35.73225968797182
dfNewJourney 93
lenPos 1860
I =  9380075 35.75742325113236
dfNewJourney 130
lenPos 1694
I =  9367554 35.782586814292905
dfNewJourney 114
lenPos 1765
I =  9397781 35.807750377453445
dfNewJourney 108
lenPos 1685
I =  9405849 35.83291394061399
dfNewJourney 120
lenPos 1795
I =  9428372 35.85807750377453
dfNewJourney 133
lenPos 1733
I =  9284817 35.88324106693508
dfNewJourney 124
lenPos 1818
I =  9367750 35.90840463009562
dfNewJourney 105
lenPos 1669
I =  9402237 35.933568193256164
dfNewJourney 121
lenPos 1781
I =  9552800 35.958731756416704
dfNewJourney 141
lenPos 1715
I =  9317846 35.98389531957725
dfNewJourney 132
lenPos 1849
I =  9265354 36.00905888273779
dfNewJourney 130
lenPos 1830
I =  9412737 36.03422244589834
dfNewJourney 117
lenPos 1582
I =  9337389 36.05938600905888
dfNewJourney 184
lenPos 1836
I =  9400382 36.08454957221943
dfNewJourney 158
lenPos 1777
I =  9270294 36.10971313537997
dfNewJourney 359
lenPos 1800
I =  9251420 36.134876698540516
dfNewJourney 364
lenPos 1796
I =  9251432 36.160040261701056
dfNewJourney 230
lenPos 1764
I =  9308974 36.1852038248616
dfNewJourney 185
lenPos 1769
I =  9283277 36.21036738802215
dfNewJourney 350
lenPos 1833
I =  9306720 36.23553095118269
dfNewJourney 390
lenPos 1876
I =  9344928 36.260694514343236
dfNewJourney 254
lenPos 1708
I =  9344825 36.285858077503775
dfNewJourney 163
lenPos 1726
I =  9379777 36.31102164066432
dfNewJourney 194
lenPos 1705
I =  9379789 36.33618520382486
dfNewJourney 88
lenPos 1699
I =  9237412 36.36134876698541
dfNewJourney 161
lenPos 1809
I =  9315721 36.38651233014595
dfNewJourney 117
lenPos 1430
I =  9431458 36.411675893306494
dfNewJourney 71
lenPos 1447
I =  9283758 36.436839456467034
dfNewJourney 128
lenPos 1266
I =  9168740 36.46200301962758
dfNewJourney 164
lenPos 1419
I =  9322451 36.48716658278812
dfNewJourney 199
lenPos 1585
I =  9491836 36.51233014594867
dfNewJourney 141
lenPos 1648
I =  9262481 36.53749370910921
dfNewJourney 120
lenPos 1752
I =  9383974 36.56265727226975
dfNewJourney 138
lenPos 1338
I =  9258351 36.58782083543029
dfNewJourney 127
lenPos 1793
I =  9392781 36.61298439859084
dfNewJourney 172
lenPos 1682
I =  9406386 36.638147961751386
dfNewJourney 125
lenPos 1776
I =  9392808 36.663311524911926
dfNewJourney 99
lenPos 1791
I =  9313462 36.68847508807247
dfNewJourney 110
lenPos 1726
I =  9464560 36.71363865123302
dfNewJourney 127
lenPos 1751
I =  9392793 36.73880221439356
dfNewJourney 123
lenPos 1688
I =  9332822 36.763965777554105
dfNewJourney 106
lenPos 1785
I =  9222649 36.789129340714645
dfNewJourney 146
lenPos 1473
I =  9289489 36.81429290387519
dfNewJourney 98
lenPos 1409
I =  9389497 36.83945646703573
dfNewJourney 57
lenPos 579
I =  9189122 36.86462003019628
dfNewJourney 96
lenPos 1457
I =  9292979 36.88978359335682
dfNewJourney 85
lenPos 1834
I =  9232620 36.914947156517364
dfNewJourney 111
lenPos 1834
I =  9273636 36.940110719677904
dfNewJourney 107
lenPos 1769
I =  9286023 36.96527428283845
dfNewJourney 2
lenPos 207
I =  9018426 36.99043784599899
dfNewJourney 101
lenPos 1815
I =  9258674 37.01560140915954
dfNewJourney 487
lenPos 1876
I =  9350642 37.040764972320076
dfNewJourney 129
lenPos 1868
I =  9379131 37.06592853548062
dfNewJourney 142
lenPos 1652
I =  9364930 37.09109209864116
dfNewJourney 56
lenPos 1735
I =  9198771 37.11625566180171
dfNewJourney 104
lenPos 1787
I =  9332638 37.14141922496225
dfNewJourney 169
lenPos 1848
I =  9423724 37.166582788122795
dfNewJourney 196
lenPos 1767
I =  9306677 37.19174635128334
dfNewJourney 179
lenPos 1760
I =  9295335 37.21690991444389
dfNewJourney 158
lenPos 1765
I =  9228849 37.24207347760443
dfNewJourney 99
lenPos 1771
I =  9216547 37.267237040764975
dfNewJourney 74
lenPos 1421
I =  9212412 37.29240060392552
dfNewJourney 111
lenPos 1537
I =  9223265 37.31756416708606
dfNewJourney 154
lenPos 1877
I =  9246475 37.34272773024661
dfNewJourney 172
lenPos 1759
I =  9384095 37.36789129340715
dfNewJourney 104
lenPos 1215
I =  9468815 37.393054856567694
dfNewJourney 190
lenPos 1570
I =  9284805 37.418218419728234
dfNewJourney 126
lenPos 1866
I =  9367724 37.44338198288878
dfNewJourney 178
lenPos 1745
I =  9379038 37.46854554604932
dfNewJourney 175
lenPos 1622
I =  9379040 37.49370910920987
dfNewJourney 165
lenPos 1728
I =  9379052 37.51887267237041
dfNewJourney 104
lenPos 1594
I =  9430272 37.54403623553095
dfNewJourney 113
lenPos 1750
I =  9273387 37.56919979869149
dfNewJourney 122
lenPos 1542
I =  9512185 37.59436336185204
dfNewJourney 175
lenPos 1526
I =  9292589 37.61952692501258
dfNewJourney 95
lenPos 1772
I =  9215050 37.644690488173126
dfNewJourney 135
lenPos 1865
I =  9410909 37.669854051333665
dfNewJourney 152
lenPos 1610
I =  9428865 37.69501761449421
dfNewJourney 72
lenPos 1301
I =  9162007 37.72018117765475
dfNewJourney 179
lenPos 1460
I =  9284790 37.7453447408153
dfNewJourney 116
lenPos 1874
I =  9512757 37.770508303975845

dfNewJourney 103
lenPos 1408
I =  9273052 37.795671867136384
dfNewJourney 137
lenPos 1417
I =  9426441 37.82083543029693
dfNewJourney 208
lenPos 1735
I =  9417000 37.84599899345748
dfNewJourney 152
lenPos 1694
I =  9257010 37.87116255661802
dfNewJourney 224
lenPos 1826
I =  9360453 37.896326119778564
dfNewJourney 107
lenPos 1429
I =  9388728 37.921489682939104
dfNewJourney 132
lenPos 1640
I =  9284374 37.94665324609965
dfNewJourney 142
lenPos 1829
I =  9278650 37.97181680926019
dfNewJourney 96
lenPos 1621
I =  9307920 37.99698037242074
dfNewJourney 15
lenPos 249
I =  8913564 38.022143935581276
dfNewJourney 84
lenPos 1435
I =  9105073 38.04730749874182
dfNewJourney 104
lenPos 1816
I =  9112117 38.07247106190236
dfNewJourney 163
lenPos 1601
I =  9174610 38.09763462506291
dfNewJourney 58
lenPos 1402
I =  9191395 38.12279818822345
dfNewJourney 222
lenPos 1878
I =  9256054 38.147961751383995
dfNewJourney 139
lenPos 1710
I =  9258167 38.173125314544535
dfNewJourney 102
lenPos 1809
I =  9257993 38.19828887770508
dfNewJourney 120
lenPos 1810
I =  9280366 38.22345244086562
dfNewJourney 99
lenPos 1625
I =  9288681 38.24861600402617
dfNewJourney 103
lenPos 1521
I =  9167136 38.27377956718671
dfNewJourney 120
lenPos 1745
I =  9289178 38.298943130347254
dfNewJourney 115
lenPos 1817
I =  9309576 38.3241066935078
dfNewJourney 102
lenPos 1840
I =  9309588 38.34927025666835
dfNewJourney 111
lenPos 1765
I =  9298973 38.37443381982889
dfNewJourney 125
lenPos 1595
I =  9318553 38.399597382989434
dfNewJourney 149
lenPos 1484
I =  9167186 38.42476094614998
dfNewJourney 149
lenPos 1552
I =  9344100 38.44992450931052
dfNewJourney 118
lenPos 1647
I =  9403554 38.47508807247107
dfNewJourney 80
lenPos 1507
I =  9143697 38.50025163563161
dfNewJourney 114
lenPos 1482
I =  9407823 38.52541519879215
dfNewJourney 112
lenPos 1598
I =  9407835 38.55057876195269
dfNewJourney 121
lenPos 1668
I =  9407847 38.57574232511324
dfNewJourney 127
lenPos 1612
I =  9417799 38.60090588827378
dfNewJourney 113
lenPos 1697
I =  9433016 38.626069451434326
dfNewJourney 95
lenPos 1825
I =  9437658 38.651233014594865
dfNewJourney 100
lenPos 1768
I =  9448152 38.67639657775541
dfNewJourney 120
lenPos 1658
I =  9430181 38.70156014091595
dfNewJourney 138
lenPos 1692
I =  9417191 38.7267237040765
dfNewJourney 128
lenPos 1708
I =  9417206 38.75188726723704
dfNewJourney 134
lenPos 1796
I =  9360128 38.777050830397584
dfNewJourney 155
lenPos 1631
I =  9422641 38.802214393558124
dfNewJourney 78
lenPos 1769
I =  9413561 38.82737795671867
dfNewJourney 167
lenPos 1818
I =  9411185 38.85254151987921
dfNewJourney 227
lenPos 1849
I =  9407407 38.87770508303976
dfNewJourney 138
lenPos 1825
I =  9470911 38.902868646200304
dfNewJourney 96
lenPos 1761
I =  9389277 38.92803220936084
dfNewJourney 167
lenPos 1784
I =  9413028 38.95319577252139
dfNewJourney 3
lenPos 997
I =  9422988 38.97835933568194
dfNewJourney 162
lenPos 1776
I =  9389966 39.003522898842476
dfNewJourney 167
lenPos 1524
I =  9241798 39.02868646200302
dfNewJourney 81
lenPos 1755
I =  9280586 39.05385002516356
dfNewJourney 130
lenPos 1754
I =  9271327 39.07901358832411
dfNewJourney 121
lenPos 1870
I =  9351452 39.10417715148465
dfNewJourney 145
lenPos 1753
I =  9247508 39.129340714645195
dfNewJourney 126
lenPos 1759
I =  9386861 39.154504277805735
dfNewJourney 136
lenPos 1739
I =  9402249 39.17966784096628
dfNewJourney 169
lenPos 1873
I =  9274800 39.20483140412682
dfNewJourney 253
lenPos 1800
I =  9251652 39.22999496728737
dfNewJourney 98
lenPos 1670
I =  9277747 39.25515853044791
dfNewJourney 166
lenPos 1813
I =  9384459 39.280322093608454
dfNewJourney 138
lenPos 1768
I =  9397547 39.305485656768994
dfNewJourney 249
lenPos 1794
I =  9274666 39.33064921992954
dfNewJourney 141
lenPos 1790
I =  9255660 39.35581278309008
dfNewJourney 146
lenPos 1702
I =  9465966 39.38097634625063
dfNewJourney 118
lenPos 1726
I =  9465978 39.40613990941117
dfNewJourney 45
lenPos 1680
I =  9143532 39.43130347257171
dfNewJourney 163
lenPos 1590
I =  9214757 39.45646703573226
dfNewJourney 91
lenPos 1437
I =  9299343 39.48163059889281
dfNewJourney 156
lenPos 1769
I =  9423712 39.506794162053346
dfNewJourney 113
lenPos 1823
I =  9318333 39.53195772521389
dfNewJourney 113
lenPos 1824
I =  9290658 39.55712128837444
dfNewJourney 92
lenPos 1628
I =  9319703 39.58228485153498
dfNewJourney 134
lenPos 1883
I =  9210907 39.607448414695526
dfNewJourney 171
lenPos 1784
I =  9274654 39.632611977856065
dfNewJourney 138
lenPos 1636
I =  9288813 39.65777554101661
dfNewJourney 79
lenPos 1510
I =  9167162 39.68293910417715
dfNewJourney 149
lenPos 1814
I =  9312913 39.7081026673377
dfNewJourney 107
lenPos 1815
I =  9387970 39.73326623049824
dfNewJourney 161
lenPos 1873
I =  9381512 39.758429793658784
dfNewJourney 147
lenPos 1802
I =  9412000 39.783593356819324
dfNewJourney 118
lenPos 1428
I =  9434204 39.80875691997987
dfNewJourney 55
lenPos 1399
I =  8917467 39.83392048314041
dfNewJourney 100
lenPos 1785
I =  9401128 39.85908404630096
dfNewJourney 71
lenPos 1653
I =  9120932 39.8842476094615
dfNewJourney 81
lenPos 1474
I =  9081837 39.90941117262204
dfNewJourney 109
lenPos 1743
I =  9200964 39.93457473578258
dfNewJourney 112
lenPos 1831
I =  9236640 39.95973829894313
dfNewJourney 120
lenPos 1852
I =  9282792 39.98490186210367
dfNewJourney 132
lenPos 1812
I =  9298650 40.010065425264216
dfNewJourney 122
lenPos 1775
I =  9308833 40.03522898842476
dfNewJourney 126
lenPos 1793
I =  9308857 40.0603925515853
dfNewJourney 157
lenPos 1833
I =  9346720 40.08555611474585
dfNewJourney 108
lenPos 1752
I =  9379612 40.110719677906395
dfNewJourney 171
lenPos 1852
I =  9405538 40.135883241066935
dfNewJourney 95
lenPos 1764
I =  9389100 40.16104680422748
dfNewJourney 134
lenPos 1846
I =  9405540 40.18621036738802
dfNewJourney 141
lenPos 1840
I =  9405552 40.21137393054857
dfNewJourney 117
lenPos 1786
I =  9395331 40.23653749370911
dfNewJourney 104
lenPos 1586
I =  9239460 40.261701056869654
dfNewJourney 115
lenPos 1776
I =  9239472 40.286864620030194
dfNewJourney 122
lenPos 1820
I =  9433509 40.31202818319074
dfNewJourney 155
lenPos 1856
I =  9436707 40.33719174635128
dfNewJourney 121
lenPos 1852
I =  9378371 40.36235530951183
dfNewJourney 146
lenPos 1665
I =  9437983 40.387518872672366
dfNewJourney 112
lenPos 1814
I =  9416824 40.41268243583291
dfNewJourney 155
lenPos 1702
I =  9417323 40.43784599899346
dfNewJourney 112
lenPos 1601
I =  9434890 40.463009562154
dfNewJourney 188
lenPos 1732
I =  9417335 40.488173125314546
dfNewJourney 132
lenPos 1097
I =  9030591 40.513336688475086
dfNewJourney 169
lenPos 1751
I =  9419448 40.53850025163563
dfNewJourney 190
lenPos 1766
I =  9464352 40.56366381479617
dfNewJourney 176
lenPos 1837
I =  9391957 40.58882737795672
dfNewJourney 175
lenPos 1755
I =  9464364 40.613990941117265
dfNewJourney 139
lenPos 1703
I =  9183295 40.639154504277805
dfNewJourney 151
lenPos 1826
I =  9436678 40.66431806743835
dfNewJourney 104
lenPos 1700
I =  9387700 40.6894816305989
dfNewJourney 101
lenPos 1749
I =  9387724 40.71464519375944
dfNewJourney 101
lenPos 1812
I =  9426312 40.739808756919984
dfNewJourney 113
lenPos 1761
I =  8919051 40.764972320080524
dfNewJourney 100
lenPos 1730
I =  9428970 40.79013588324107
dfNewJourney 121
lenPos 1861
I =  9416836 40.81529944640161
dfNewJourney 134
lenPos 1853
I =  9272668 40.84046300956216
dfNewJourney 113
lenPos 1552
I =  9319698 40.8656265727227
dfNewJourney 129
lenPos 1800
I =  9439797 40.89079013588324
dfNewJourney 131
lenPos 1835
I =  9321964 40.91595369904378
dfNewJourney 156
lenPos 1611
I =  9252307 40.94111726220433
dfNewJourney 138
lenPos 1247
I =  9178056 40.96628082536487
dfNewJourney 116
lenPos 1770
I =  9390032 40.991444388525416
dfNewJourney 75
lenPos 1680
I =  9427471 41.016607951685955
dfNewJourney 126
lenPos 1783
I =  9283629 41.0417715148465
dfNewJourney 136
lenPos 1857
I =  9289518 41.06693507800704
dfNewJourney 106
lenPos 1806
I =  9289520 41.09209864116759
dfNewJourney 93
lenPos 1777
I =  9242338 41.11726220432813
dfNewJourney 99
lenPos 1851
I =  9359375 41.142425767488675
dfNewJourney 151
lenPos 1793
I =  9414072 41.16758933064922
dfNewJourney 145
lenPos 1723
I =  9414084 41.19275289380976
dfNewJourney 127
lenPos 1766
I =  9359363 41.21791645697031

dfNewJourney 106
lenPos 1849
I =  9414292 41.243080020130854
dfNewJourney 117
lenPos 1844
I =  9422407 41.268243583291394
dfNewJourney 102
lenPos 1653
I =  9278686 41.29340714645194
dfNewJourney 101
lenPos 1825
I =  9403346 41.31857070961248
dfNewJourney 136
lenPos 1852
I =  9561370 41.34373427277303
dfNewJourney 121
lenPos 1636
I =  9038828 41.368897835933566
dfNewJourney 130
lenPos 1782
I =  9544592 41.39406139909411
dfNewJourney 113
lenPos 1711
I =  9284726 41.41922496225465
dfNewJourney 131
lenPos 1846
I =  9400394 41.4443885254152
dfNewJourney 112
lenPos 1866
I =  9428683 41.46955208857574
dfNewJourney 259
lenPos 1729
I =  9278715 41.494715651736286
dfNewJourney 112
lenPos 1801
I =  9400801 41.51987921489683
dfNewJourney 124
lenPos 1808
I =  9555319 41.54504277805737
dfNewJourney 123
lenPos 1840
I =  9555307 41.57020634121792
dfNewJourney 128
lenPos 1820
I =  9403322 41.59536990437846
dfNewJourney 201
lenPos 1866
I =  9392391 41.620533467539005
dfNewJourney 83
lenPos 1834
I =  9213909 41.645697030699544
dfNewJourney 139
lenPos 1844
I =  9414278 41.67086059386009
dfNewJourney 149
lenPos 1785
I =  9397793 41.69602415702063
dfNewJourney 129
lenPos 1623
I =  9261762 41.72118772018118
dfNewJourney 240
lenPos 1685
I =  9380087 41.746351283341724
dfNewJourney 148
lenPos 1687
I =  9258363 41.771514846502264
dfNewJourney 121
lenPos 1770
I =  9363467 41.79667840966281
dfNewJourney 89
lenPos 1740
I =  9267948 41.82184197282336
dfNewJourney 139
lenPos 1759
I =  9405928 41.8470055359839
dfNewJourney 147
lenPos 1662
I =  9270749 41.87216909914444
dfNewJourney 137
lenPos 1733
I =  9182069 41.89733266230498
dfNewJourney 126
lenPos 1809
I =  9424651 41.92249622546553
dfNewJourney 135
lenPos 1840
I =  9451460 41.94765978862607
dfNewJourney 155
lenPos 1707
I =  9309502 41.972823351786616
dfNewJourney 66
lenPos 1863
I =  9265689 41.997986914947155
dfNewJourney 152
lenPos 1603
I =  9408126 42.0231504781077
dfNewJourney 191
lenPos 1734
I =  9144914 42.04831404126824
dfNewJourney 182
lenPos 1539
I =  9118628 42.07347760442879
dfNewJourney 163
lenPos 1819
I =  9516222 42.09864116758933
dfNewJourney 145
lenPos 1792
I =  9428384 42.123804730749875
dfNewJourney 130
lenPos 1630
I =  9292577 42.148968293910414
dfNewJourney 189
lenPos 1812
I =  9325348 42.17413185707096
dfNewJourney 144
lenPos 1809
I =  9420710 42.1992954202315
dfNewJourney 166
lenPos 1833
I =  9443853 42.22445898339205
dfNewJourney 243
lenPos 1721
I =  9379985 42.24962254655259
dfNewJourney 118
lenPos 1822
I =  9414280 42.27478610971313
dfNewJourney 125
lenPos 1558
I =  9337391 42.29994967287368
dfNewJourney 138
lenPos 1628
I =  9308986 42.32511323603422
dfNewJourney 127
lenPos 1746
I =  9435569 42.350276799194766
dfNewJourney 187
lenPos 1671
I =  9563251 42.37544036235531
dfNewJourney 135
lenPos 1395
I =  9417165 42.40060392551585
dfNewJourney 101
lenPos 1694
I =  9421403 42.4257674886764
dfNewJourney 43
lenPos 1701
I =  9152832 42.45093105183694
dfNewJourney 127
lenPos 1612
I =  9439670 42.476094614997486
dfNewJourney 114
lenPos 1720
I =  9243021 42.501258178158025
dfNewJourney 124
lenPos 1503
I =  9308443 42.52642174131857
dfNewJourney 115
lenPos 1645
I =  9432672 42.55158530447911
dfNewJourney 134
lenPos 1853
I =  9251286 42.57674886763966
dfNewJourney 99
lenPos 1626
I =  9237802 42.601912430800205
dfNewJourney 129
lenPos 1736
I =  9164677 42.627075993960744
dfNewJourney 143
lenPos 1768
I =  9387956 42.65223955712129
dfNewJourney 99
lenPos 1714
I =  9378632 42.67740312028183
dfNewJourney 221
lenPos 1707
I =  9226140 42.70256668344238
dfNewJourney 156
lenPos 1618
I =  9413779 42.72773024660292
dfNewJourney 109
lenPos 1795
I =  9387918 42.752893809763464
dfNewJourney 131
lenPos 1862
I =  9387920 42.778057372924
dfNewJourney 316
lenPos 1851
I =  9274305 42.80322093608455
dfNewJourney 160
lenPos 1546
I =  9262493 42.82838449924509
dfNewJourney 114
lenPos 1880
I =  9464326 42.853548062405636
dfNewJourney 115
lenPos 1645
I =  9221011 42.87871162556618
dfNewJourney 82
lenPos 1513
I =  9398278 42.90387518872672
dfNewJourney 122
lenPos 1599
I =  9389502 42.92903875188727
dfNewJourney 100
lenPos 1627
I =  9389514 42.954202315047816
dfNewJourney 96
lenPos 1701
I =  9458808 42.979365878208355
dfNewJourney 110
lenPos 1715
I =  9389526 43.0045294413689
dfNewJourney 120
lenPos 1471
I =  9399349 43.02969300452944
dfNewJourney 126
lenPos 1396
I =  9224568 43.05485656768999
dfNewJourney 143
lenPos 1490
I =  9253246 43.08002013085053
dfNewJourney 78
lenPos 1192
I =  9265861 43.105183694011075
dfNewJourney 112
lenPos 1812
I =  9273088 43.130347257171614
dfNewJourney 94
lenPos 1831
I =  9332640 43.15551082033216
dfNewJourney 163
lenPos 1791
I =  9428815 43.1806743834927
dfNewJourney 107
lenPos 1862
I =  9418133 43.20583794665325
dfNewJourney 102
lenPos 1834
I =  9478638 43.23100150981379
dfNewJourney 135
lenPos 1853
I =  9440485 43.25616507297433
dfNewJourney 152
lenPos 1846
I =  9478614 43.28132863613487
dfNewJourney 94
lenPos 1841
I =  9435909 43.30649219929542
dfNewJourney 101
lenPos 1852
I =  9435894 43.33165576245596
dfNewJourney 112
lenPos 1807
I =  9476812 43.356819325616506
dfNewJourney 106
lenPos 1535
I =  9430313 43.381982888777046
dfNewJourney 138
lenPos 1835
I =  9467794 43.40714645193759
dfNewJourney 171
lenPos 1801
I =  9462354 43.43231001509814
dfNewJourney 159
lenPos 1769
I =  9478688 43.45747357825868
dfNewJourney 109
lenPos 1551
I =  9440497 43.482637141419225
dfNewJourney 161
lenPos 1866
I =  9431381 43.50780070457977
dfNewJourney 61
lenPos 1622
I =  9456070 43.53296426774031
dfNewJourney 162
lenPos 1828
I =  9436020 43.55812783090086
dfNewJourney 126
lenPos 1596
I =  9478690 43.5832913940614
dfNewJourney 81
lenPos 1502
I =  9569994 43.608454957221944
dfNewJourney 146
lenPos 1366
I =  9187760 43.63361852038249
dfNewJourney 69
lenPos 1836
I =  9276004 43.65878208354303
dfNewJourney 143
lenPos 1803
I =  9302671 43.68394564670358
dfNewJourney 99
lenPos 1815
I =  9279733 43.70910920986412
dfNewJourney 127
lenPos 1828
I =  9363479 43.734272773024664
dfNewJourney 129
lenPos 1846
I =  9426295 43.7594363361852
dfNewJourney 192
lenPos 1750
I =  9253064 43.78459989934575
dfNewJourney 0
lenPos 0
I =  9635810 43.80976346250629
dfNewJourney 66
lenPos 1647
I =  9121194 43.834927025666836
dfNewJourney 50
lenPos 1527
I =  9156591 43.860090588827376
dfNewJourney 124
lenPos 1779
I =  9393101 43.88525415198792
dfNewJourney 181
lenPos 1535
I =  9007752 43.91041771514846
dfNewJourney 111
lenPos 1778
I =  9402328 43.93558127830901
dfNewJourney 177
lenPos 1721
I =  9379064 43.96074484146955
dfNewJourney 108
lenPos 1835
I =  9402316 43.985908404630095
dfNewJourney 133
lenPos 1857
I =  9197296 44.01107196779064
dfNewJourney 191
lenPos 1848
I =  9257022 44.03623553095118
dfNewJourney 121
lenPos 1839
I =  9278662 44.06139909411173
dfNewJourney 136
lenPos 1813
I =  9561368 44.086562657272275
dfNewJourney 207
lenPos 1801
I =  9360465 44.111726220432814
dfNewJourney 226
lenPos 1795
I =  9417012 44.13688978359336
dfNewJourney 156
lenPos 1699
I =  9288796 44.1620533467539
dfNewJourney 208
lenPos 1355
I =  9110640 44.18721690991445
dfNewJourney 78
lenPos 1269
I =  9105114 44.21238047307499
dfNewJourney 223
lenPos 1429
I =  9163283 44.23754403623553
dfNewJourney 165
lenPos 1725
I =  9254915 44.26270759939607
dfNewJourney 193
lenPos 1862
I =  9256066 44.28787116255662
dfNewJourney 124
lenPos 1729
I =  9256901 44.31303472571716
dfNewJourney 123
lenPos 1688
I =  9241073 44.338198288877706
dfNewJourney 167
lenPos 1652
I =  9295048 44.363361852038246
dfNewJourney 239
lenPos 1479
I =  9288019 44.38852541519879
dfNewJourney 110
lenPos 1793
I =  9272503 44.41368897835933
dfNewJourney 123
lenPos 1784
I =  9323962 44.43885254151988
dfNewJourney 143
lenPos 1843
I =  9318541 44.46401610468042
dfNewJourney 146
lenPos 1733
I =  9306782 44.489179667840965
dfNewJourney 47
lenPos 1725
I =  9120994 44.514343231001504
dfNewJourney 95
lenPos 1750
I =  9448164 44.53950679416205
dfNewJourney 148
lenPos 1720
I =  9417218 44.5646703573226
dfNewJourney 102
lenPos 1805
I =  9417220 44.58983392048314
dfNewJourney 258
lenPos 1807
I =  9407378 44.614997483643684
dfNewJourney 92
lenPos 1850
I =  9407380 44.64016104680423
dfNewJourney 96
lenPos 1652
I =  9360130 44.66532460996477

dfNewJourney 94
lenPos 1740
I =  9413573 44.69048817312532
dfNewJourney 100
lenPos 1688
I =  9283796 44.715651736285864
dfNewJourney 1
lenPos 404
I =  9422990 44.7408152994464
dfNewJourney 5
lenPos 1067
I =  9486908 44.76597886260695
dfNewJourney 106
lenPos 1819
I =  9343209 44.79114242576749
dfNewJourney 132
lenPos 1769
I =  9494668 44.816305988928036
dfNewJourney 160
lenPos 1776
I =  9418121 44.841469552088576
dfNewJourney 172
lenPos 1739
I =  9436719 44.86663311524912
dfNewJourney 109
lenPos 1781
I =  9402770 44.89179667840966
dfNewJourney 108
lenPos 1860
I =  9402782 44.91696024157021
dfNewJourney 130
lenPos 1857
I =  9402794 44.94212380473075
dfNewJourney 92
lenPos 1824
I =  9422512 44.967287367891295
dfNewJourney 104
lenPos 1893
I =  9258466 44.992450931051835
dfNewJourney 120
lenPos 1672
I =  9192753 45.01761449421238
dfNewJourney 154
lenPos 1664
I =  9259886 45.04277805737292
dfNewJourney 107
lenPos 1743
I =  9327011 45.06794162053347
dfNewJourney 113
lenPos 1492
I =  9247493 45.09310518369401
dfNewJourney 170
lenPos 1776
I =  9420863 45.118268746854554
dfNewJourney 139
lenPos 1827
I =  9470985 45.1434323100151
dfNewJourney 145
lenPos 1827
I =  9470997 45.16859587317564
dfNewJourney 115
lenPos 1688
I =  9331153 45.19375943633619
dfNewJourney 151
lenPos 1687
I =  9396086 45.21892299949673
dfNewJourney 307
lenPos 1838
I =  9403293 45.24408656265727
dfNewJourney 121
lenPos 1776
I =  9405904 45.26925012581782
dfNewJourney 119
lenPos 1771
I =  9367530 45.29441368897836
dfNewJourney 177
lenPos 1715
I =  9263198 45.319577252138906
dfNewJourney 248
lenPos 1819
I =  9204764 45.344740815299446
dfNewJourney 261
lenPos 1875
I =  9464376 45.36990437845999
dfNewJourney 152
lenPos 1689
I =  9396098 45.39506794162053
dfNewJourney 199
lenPos 1831
I =  9259991 45.42023150478108
dfNewJourney 131
lenPos 1809
I =  9466013 45.44539506794162
dfNewJourney 134
lenPos 1806
I =  9466001 45.470558631102165
dfNewJourney 206
lenPos 1858
I =  9431264 45.495722194262704
dfNewJourney 136
lenPos 1704
I =  9254240 45.52088575742325
dfNewJourney 105
lenPos 1727
I =  9283710 45.54604932058379
dfNewJourney 90
lenPos 1683
I =  9306639 45.57121288374434
dfNewJourney 99
lenPos 1837
I =  9210892 45.59637644690488
dfNewJourney 91
lenPos 1809
I =  9133082 45.621540010065424
dfNewJourney 155
lenPos 1795
I =  9282508 45.64670357322596
dfNewJourney 135
lenPos 1808
I =  9286061 45.67186713638651
dfNewJourney 104
lenPos 1827
I =  9288758 45.69703069954706
dfNewJourney 121
lenPos 1745
I =  9434228 45.722194262707596
dfNewJourney 240
lenPos 1823
I =  9398723 45.74735782586814
dfNewJourney 202
lenPos 1769
I =  9426207 45.77252138902869
dfNewJourney 196
lenPos 1821
I =  9453963 45.79768495218923
dfNewJourney 101
lenPos 1722
I =  9461659 45.822848515349776
dfNewJourney 104
lenPos 1708
I =  9261657 45.84801207851032
dfNewJourney 73
lenPos 1155
I =  9144782 45.87317564167086
dfNewJourney 112
lenPos 1804
I =  9308821 45.89833920483141
dfNewJourney 195
lenPos 1846
I =  9297541 45.92350276799195
dfNewJourney 166
lenPos 1887
I =  9358541 45.948666331152495
dfNewJourney 137
lenPos 1744
I =  9389083 45.973829894313035
dfNewJourney 108
lenPos 1788
I =  9412452 45.99899345747358
dfNewJourney 118
lenPos 1795
I =  9419137 46.02415702063412
dfNewJourney 160
lenPos 1861
I =  9405564 46.04932058379467
dfNewJourney 104
lenPos 1779
I =  9395329 46.07448414695521
dfNewJourney 170
lenPos 1800
I =  9439204 46.099647710115754
dfNewJourney 142
lenPos 1850
I =  9388209 46.12481127327629
dfNewJourney 125
lenPos 1846
I =  9326512 46.14997483643684
dfNewJourney 271
lenPos 1843
I =  9436680 46.17513839959738
dfNewJourney 121
lenPos 1664
I =  9439383 46.200301962757926
dfNewJourney 127
lenPos 1531
I =  9439395 46.225465525918466
dfNewJourney 237
lenPos 1771
I =  9439400 46.25062908907901
dfNewJourney 120
lenPos 1847
I =  9472751 46.27579265223956
dfNewJourney 156
lenPos 1797
I =  9453030 46.3009562154001
dfNewJourney 201
lenPos 1824
I =  9419450 46.326119778560646
dfNewJourney 191
lenPos 1680
I =  9437672 46.35128334172119
dfNewJourney 110
lenPos 1723
I =  9437684 46.37644690488173
dfNewJourney 180
lenPos 1758
I =  9457024 46.40161046804228
dfNewJourney 124
lenPos 1832
I =  9428358 46.42677403120282
dfNewJourney 87
lenPos 1766
I =  9428982 46.451937594363365
dfNewJourney 79
lenPos 1725
I =  9428994 46.477101157523904
dfNewJourney 106
lenPos 1684
I =  9326861 46.50226472068445
dfNewJourney 114
lenPos 1632
I =  9326885 46.52742828384499
dfNewJourney 358
lenPos 1817
I =  9266267 46.55259184700554
dfNewJourney 113
lenPos 1848
I =  9439785 46.57775541016608
dfNewJourney 155
lenPos 1762
I =  9283784 46.602918973326624
dfNewJourney 47
lenPos 1480
I =  9105906 46.62808253648716
dfNewJourney 97
lenPos 1773
I =  9321160 46.65324609964771
dfNewJourney 213
lenPos 1851
I =  9336842 46.67840966280825
dfNewJourney 120
lenPos 1758
I =  9298674 46.703573225968796
dfNewJourney 111
lenPos 1712
I =  9272199 46.728736789129336
dfNewJourney 289
lenPos 1807
I =  9438860 46.75390035228988
dfNewJourney 186
lenPos 1788
I =  9438858 46.77906391545042
dfNewJourney 136
lenPos 1840
I =  9447732 46.80422747861097
dfNewJourney 128
lenPos 1820
I =  9447744 46.829391041771515
dfNewJourney 146
lenPos 1794
I =  9385831 46.854554604932055
dfNewJourney 122
lenPos 1862
I =  9425540 46.8797181680926
dfNewJourney 122
lenPos 1761
I =  9486934 46.90488173125315
dfNewJourney 221
lenPos 1865
I =  9226970 46.93004529441369
dfNewJourney 165
lenPos 1862
I =  9247455 46.955208857574235
dfNewJourney 159
lenPos 1728
I =  9297412 46.98037242073478
dfNewJourney 87
lenPos 1818
I =  9113147 47.00553598389532
dfNewJourney 111
lenPos 1701
I =  9359387 47.03069954705587
dfNewJourney 109
lenPos 1830
I =  9359399 47.05586311021641
dfNewJourney 76
lenPos 1619
I =  9290634 47.081026673376954
dfNewJourney 122
lenPos 1720
I =  9370707 47.10619023653749
dfNewJourney 241
lenPos 1703
I =  9450789 47.13135379969804
dfNewJourney 109
lenPos 1673
I =  9278674 47.15651736285858
dfNewJourney 160
lenPos 1834
I =  9335836 47.181680926019126
dfNewJourney 173
lenPos 1886
I =  9298777 47.206844489179666
dfNewJourney 132
lenPos 1803
I =  9441855 47.23200805234021
dfNewJourney 118
lenPos 1872
I =  9288289 47.25717161550075
dfNewJourney 110
lenPos 1784
I =  9263916 47.2823351786613
dfNewJourney 95
lenPos 1833
I =  9422237 47.30749874182184
dfNewJourney 130
lenPos 1761
I =  9414266 47.332662304982385
dfNewJourney 305
lenPos 1789
I =  9472737 47.357825868142925
dfNewJourney 57
lenPos 1452
I =  9200744 47.38298943130347
dfNewJourney 211
lenPos 1866
I =  9353589 47.40815299446402
dfNewJourney 27
lenPos 676
I =  8822466 47.43331655762456
dfNewJourney 186
lenPos 1689
I =  9475935 47.458480120785104
dfNewJourney 156
lenPos 1699
I =  9236975 47.48364368394565
dfNewJourney 131
lenPos 1816
I =  9561382 47.50880724710619
dfNewJourney 78
lenPos 1760
I =  9381744 47.53397081026674
dfNewJourney 136
lenPos 1766
I =  9451288 47.55913437342728
dfNewJourney 128
lenPos 1797
I =  9420617 47.584297936587824
dfNewJourney 109
lenPos 1860
I =  9422225 47.60946149974836
dfNewJourney 53
lenPos 1802
I =  9232709 47.63462506290891
dfNewJourney 250
lenPos 1812
I =  9435571 47.65978862606945
dfNewJourney 244
lenPos 1736
I =  9435583 47.684952189229996
dfNewJourney 133
lenPos 1796
I =  9435600 47.710115752390536
dfNewJourney 170
lenPos 1642
I =  9313175 47.73527931555108
dfNewJourney 168
lenPos 1716
I =  9401647 47.76044287871162
dfNewJourney 136
lenPos 1736
I =  9379791 47.78560644187217
dfNewJourney 183
lenPos 1670
I =  9379806 47.81077000503271
dfNewJourney 230
lenPos 1740
I =  9563275 47.835933568193255
dfNewJourney 226
lenPos 1625
I =  9583299 47.861097131353795
dfNewJourney 82
lenPos 1594
I =  9417177 47.88626069451434
dfNewJourney 121
lenPos 1732
I =  9232917 47.91142425767489
dfNewJourney 37
lenPos 1810
I =  9414802 47.93658782083543
dfNewJourney 238
lenPos 1825
I =  9414826 47.961751383995974
dfNewJourney 82
lenPos 1768
I =  9467720 47.986914947156514
dfNewJourney 229
lenPos 1814
I =  9414838 48.01207851031706
dfNewJourney 198
lenPos 1835
I =  9399818 48.03724207347761
dfNewJourney 138
lenPos 1739
I =  9388936 48.06240563663815
dfNewJourney 131
lenPos 1779
I =  9565637 48.08756919979869
dfNewJourney 81
lenPos 1772
I =  9299757 48.11273276295924

dfNewJourney 117
lenPos 1636
I =  9221023 48.13789632611978
dfNewJourney 108
lenPos 1748
I =  9304588 48.163059889280326
dfNewJourney 138
lenPos 1744
I =  9288370 48.188223452440866
dfNewJourney 131
lenPos 1759
I =  9336517 48.21338701560141
dfNewJourney 143
lenPos 1390
I =  9390721 48.23855057876195
dfNewJourney 110
lenPos 1812
I =  9455052 48.2637141419225
dfNewJourney 135
lenPos 1767
I =  9387932 48.28887770508304
dfNewJourney 131
lenPos 1819
I =  9387944 48.314041268243585
dfNewJourney 55
lenPos 1546
I =  9084516 48.339204831404125
dfNewJourney 110
lenPos 1788
I =  9440033 48.36436839456467
dfNewJourney 132
lenPos 1864
I =  9425526 48.38953195772521
dfNewJourney 121
lenPos 1849
I =  9440136 48.41469552088576
dfNewJourney 135
lenPos 1787
I =  9425538 48.4398590840463
dfNewJourney 404
lenPos 1855
I =  9490296 48.465022647206844
dfNewJourney 102
lenPos 1760
I =  9458822 48.49018621036738
dfNewJourney 100
lenPos 1524
I =  9399363 48.51534977352793
dfNewJourney 4
lenPos 1903
I =  9125205 48.54051333668848
dfNewJourney 133
lenPos 1735
I =  9402483 48.56567689984902
dfNewJourney 116
lenPos 1815
I =  9402495 48.59084046300956
dfNewJourney 79
lenPos 1880
I =  9467811 48.61600402617011
dfNewJourney 103
lenPos 1853
I =  9467809 48.64116758933065
dfNewJourney 80
lenPos 1747
I =  9440473 48.666331152491196
dfNewJourney 97
lenPos 1862
I =  9564671 48.691494715651736
dfNewJourney 142
lenPos 1757
I =  9422524 48.71665827881228
dfNewJourney 153
lenPos 1798
I =  9470959 48.74182184197282
dfNewJourney 193
lenPos 1827
I =  9423750 48.76698540513337
dfNewJourney 96
lenPos 1864
I =  9293985 48.79214896829391
dfNewJourney 110
lenPos 1838
I =  9478705 48.817312531454455
dfNewJourney 108
lenPos 1373
I =  9478717 48.842476094614995
dfNewJourney 123
lenPos 1713
I =  9451692 48.86763965777554
dfNewJourney 66
lenPos 1800
I =  9457763 48.89280322093608
dfNewJourney 281
lenPos 1811
I =  9490301 48.91796678409663
dfNewJourney 246
lenPos 1842
I =  9490313 48.943130347257174
dfNewJourney 186
lenPos 1693
I =  9250907 48.968293910417714
dfNewJourney 99
lenPos 1820
I =  9465980 48.99345747357826
dfNewJourney 192
lenPos 1712
I =  9417024 49.0186210367388
dfNewJourney 95
lenPos 1729
I =  9192260 49.04378459989935
dfNewJourney 127
lenPos 1504
I =  9430284 49.068948163059886
dfNewJourney 172
lenPos 1833
I =  9444508 49.09411172622043
dfNewJourney 84
lenPos 1736
I =  9389978 49.11927528938097
dfNewJourney 37
lenPos 1801
I =  9180102 49.14443885254152
dfNewJourney 90
lenPos 1715
I =  9289776 49.169602415702066
dfNewJourney 266
lenPos 1732
I =  9274317 49.194765978862605
dfNewJourney 147
lenPos 1809
I =  9289764 49.21992954202315
dfNewJourney 140
lenPos 1779
I =  9289788 49.2450931051837
dfNewJourney 92
lenPos 1604
I =  9263643 49.27025666834424
dfNewJourney 83
lenPos 1791
I =  9429039 49.295420231504785
dfNewJourney 176
lenPos 1786
I =  9256298 49.320583794665325
dfNewJourney 95
lenPos 1818
I =  9397468 49.34574735782587
dfNewJourney 165
lenPos 1079
I =  9359636 49.37091092098641
dfNewJourney 158
lenPos 1560
I =  9257723 49.39607448414696
dfNewJourney 12
lenPos 1263
I =  9105061 49.4212380473075
dfNewJourney 117
lenPos 1730
I =  9256913 49.446401610468044
dfNewJourney 124
lenPos 1644
I =  9256937 49.47156517362858
dfNewJourney 70
lenPos 1214
I =  9174622 49.49672873678913
dfNewJourney 177
lenPos 1710
I =  9282558 49.52189229994967
dfNewJourney 109
lenPos 1650
I =  9337212 49.54705586311022
dfNewJourney 88
lenPos 1820
I =  9418573 49.572219426270756
dfNewJourney 143
lenPos 1806
I =  9440526 49.5973829894313
dfNewJourney 93
lenPos 1717
I =  9440538 49.62254655259184
dfNewJourney 111
lenPos 1864
I =  9407392 49.64771011575239
dfNewJourney 217
lenPos 1867
I =  9511521 49.672873678912936
dfNewJourney 333
lenPos 1669
I =  9413676 49.698037242073475
dfNewJourney 259
lenPos 1435
I =  9416381 49.72320080523402
dfNewJourney 118
lenPos 1791
I =  9425318 49.74836436839457
dfNewJourney 78
lenPos 1857
I =  9460136 49.77352793155511
dfNewJourney 292
lenPos 1492
I =  9372858 49.798691494715655
dfNewJourney 137
lenPos 1870
I =  9568031 49.823855057876195
dfNewJourney 173
lenPos 1760
I =  9459230 49.84901862103674
dfNewJourney 140
lenPos 1852
I =  9568043 49.87418218419728
dfNewJourney 165
lenPos 1710
I =  9344112 49.89934574735783
dfNewJourney 161
lenPos 1811
I =  9425564 49.92450931051837
dfNewJourney 132
lenPos 1809
I =  9289532 49.949672873678914
dfNewJourney 236
lenPos 1577
I =  9408138 49.97483643683945
dfNewJourney 158
lenPos 1776
I =  9433808 50.0
dfNewJourney 206
lenPos 1759
I =  9143673 50.02516356316055
dfNewJourney 131
lenPos 1747
I =  9465992 50.05032712632109
dfNewJourney 138
lenPos 1867
I =  9333682 50.075490689481626
dfNewJourney 175
lenPos 1781
I =  9236755 50.10065425264217
dfNewJourney 145
lenPos 1703
I =  9145437 50.12581781580272
dfNewJourney 156
lenPos 1840
I =  9288734 50.150981378963266
dfNewJourney 248
lenPos 1811
I =  9288954 50.1761449421238
dfNewJourney 76
lenPos 1774
I =  9277723 50.201308505284345
dfNewJourney 114
lenPos 1790
I =  9277797 50.22647206844489
dfNewJourney 120
lenPos 1839
I =  9290579 50.25163563160544
dfNewJourney 89
lenPos 1525
I =  9212395 50.27679919476598
dfNewJourney 141
lenPos 1802
I =  9230854 50.301962757926525
dfNewJourney 121
lenPos 1767
I =  9288849 50.327126321087064
dfNewJourney 128
lenPos 1847
I =  9278064 50.35228988424761
dfNewJourney 150
lenPos 1577
I =  9292606 50.37745344740815
dfNewJourney 158
lenPos 1725
I =  9285859 50.4026170105687
dfNewJourney 99
lenPos 1156
I =  9085388 50.427780573729244
dfNewJourney 22
lenPos 1823
I =  9079183 50.45294413688979
dfNewJourney 86
lenPos 1802
I =  9387281 50.47810770005032
dfNewJourney 104
lenPos 1681
I =  9434216 50.50327126321087
dfNewJourney 185
lenPos 1820
I =  9453987 50.52843482637142
dfNewJourney 240
lenPos 1833
I =  9453999 50.55359838953196
dfNewJourney 172
lenPos 1690
I =  9126273 50.578761952692496
dfNewJourney 142
lenPos 1575
I =  9258870 50.60392551585304
dfNewJourney 84
lenPos 1757
I =  9259329 50.62908907901359
dfNewJourney 125
lenPos 1795
I =  9254850 50.654252642174136
dfNewJourney 103
lenPos 1758
I =  9455739 50.67941620533467
dfNewJourney 111
lenPos 1523
I =  9081825 50.704579768495215
dfNewJourney 117
lenPos 1794
I =  9176761 50.72974333165576
dfNewJourney 107
lenPos 1822
I =  9254862 50.75490689481631
dfNewJourney 156
lenPos 1852
I =  9305051 50.78007045797685
dfNewJourney 148
lenPos 1829
I =  9348479 50.805234021137395
dfNewJourney 149
lenPos 1816
I =  9338905 50.830397584297934
dfNewJourney 153
lenPos 1855
I =  9330472 50.85556114745848
dfNewJourney 112
lenPos 1815
I =  9281853 50.88072471061902
dfNewJourney 181
lenPos 1781
I =  9414022 50.90588827377957
dfNewJourney 170
lenPos 1812
I =  9414034 50.931051836940114
dfNewJourney 105
lenPos 1785
I =  9419151 50.95621540010066
dfNewJourney 271
lenPos 1832
I =  9242443 50.98137896326119
dfNewJourney 138
lenPos 1578
I =  9293961 51.00654252642174
dfNewJourney 202
lenPos 1880
I =  9379337 51.031706089582286
dfNewJourney 120
lenPos 1800
I =  9436343 51.05686965274283
dfNewJourney 209
lenPos 1811
I =  9446427 51.08203321590338
dfNewJourney 260
lenPos 1816
I =  9396012 51.10719677906391
dfNewJourney 163
lenPos 1845
I =  9587817 51.13236034222446
dfNewJourney 145
lenPos 1765
I =  9587829 51.157523905385005
dfNewJourney 127
lenPos 1718
I =  9436941 51.18268746854555
dfNewJourney 84
lenPos 1791
I =  9429003 51.207851031706085
dfNewJourney 78
lenPos 1777
I =  9461831 51.23301459486663
dfNewJourney 194
lenPos 1722
I =  9172715 51.25817815802718
dfNewJourney 95
lenPos 1750
I =  9258612 51.283341721187725
dfNewJourney 129
lenPos 1815
I =  9447756 51.30850528434826
dfNewJourney 97
lenPos 1852
I =  9486922 51.333668847508804
dfNewJourney 364
lenPos 1866
I =  9499876 51.35883241066935
dfNewJourney 111
lenPos 1782
I =  9262194 51.3839959738299
dfNewJourney 103
lenPos 1650
I =  9281009 51.40915953699044
dfNewJourney 135
lenPos 1851
I =  9292967 51.43432310015098
dfNewJourney 130
lenPos 1854
I =  9291640 51.45948666331152
dfNewJourney 125
lenPos 1763
I =  9281425 51.48465022647207
dfNewJourney 122
lenPos 1757
I =  9213296 51.50981378963261
dfNewJourney 89
lenPos 1806
I =  9571038 51.534977352793156
dfNewJourney 136
lenPos 1452
I =  9038830 51.5601409159537

dfNewJourney 105
lenPos 970
I =  9038854 51.58530447911425
dfNewJourney 87
lenPos 1705
I =  9038878 51.61046804227478
dfNewJourney 107
lenPos 1836
I =  9272400 51.63563160543533
dfNewJourney 73
lenPos 1349
I =  9202388 51.660795168595875
dfNewJourney 135
lenPos 1787
I =  9284697 51.68595873175642
dfNewJourney 321
lenPos 1796
I =  9426300 51.711122294916954
dfNewJourney 128
lenPos 1659
I =  9303649 51.7362858580775
dfNewJourney 133
lenPos 1647
I =  9314105 51.76144942123805
dfNewJourney 119
lenPos 1713
I =  9399260 51.786612984398595
dfNewJourney 177
lenPos 1657
I =  9255244 51.81177654755913
dfNewJourney 204
lenPos 1816
I =  9442562 51.836940110719674
dfNewJourney 117
lenPos 1794
I =  9310850 51.86210367388022
dfNewJourney 98
lenPos 1826
I =  9324306 51.88726723704077
dfNewJourney 113
lenPos 1698
I =  9306811 51.91243080020131
dfNewJourney 117
lenPos 1770
I =  9295270 51.93759436336185
dfNewJourney 104
lenPos 1690
I =  9359882 51.96275792652239
dfNewJourney 125
lenPos 1737
I =  9435612 51.98792148968294
dfNewJourney 177
lenPos 1721
I =  9401659 52.01308505284348
dfNewJourney 68
lenPos 1341
I =  9173642 52.038248616004026
dfNewJourney 28
lenPos 1688
I =  9034547 52.06341217916457
dfNewJourney 125
lenPos 1637
I =  9258686 52.08857574232512
dfNewJourney 78
lenPos 1747
I =  9467732 52.11373930548565
dfNewJourney 113
lenPos 1807
I =  9467768 52.1389028686462
dfNewJourney 91
lenPos 1808
I =  9467770 52.164066431806745
dfNewJourney 111
lenPos 1814
I =  9467744 52.18922999496729
dfNewJourney 34
lenPos 1388
I =  9138604 52.21439355812784
dfNewJourney 98
lenPos 1724
I =  9240407 52.23955712128837
dfNewJourney 142
lenPos 1822
I =  9239654 52.26472068444892
dfNewJourney 89
lenPos 1735
I =  9242211 52.289884247609464
dfNewJourney 58
lenPos 1327
I =  8103432 52.31504781077001
dfNewJourney 25
lenPos 1456
I =  8121161 52.34021137393054
dfNewJourney 35
lenPos 936
I =  8717233 52.36537493709109
dfNewJourney 110
lenPos 1695
I =  9458834 52.39053850025164
dfNewJourney 184
lenPos 1344
I =  9292981 52.41570206341218
dfNewJourney 147
lenPos 1779
I =  9248849 52.440865626572716
dfNewJourney 72
lenPos 1844
I =  9252943 52.46602918973326
dfNewJourney 140
lenPos 1768
I =  9264283 52.49119275289381
dfNewJourney 99
lenPos 1790
I =  9298301 52.516356316054356
dfNewJourney 134
lenPos 1866
I =  9308091 52.541519879214896
dfNewJourney 96
lenPos 1601
I =  9232606 52.56668344237544
dfNewJourney 115
lenPos 1814
I =  9265885 52.59184700553598
dfNewJourney 99
lenPos 1642
I =  9252060 52.61701056869653
dfNewJourney 81
lenPos 1812
I =  9329758 52.64217413185707
dfNewJourney 81
lenPos 1746
I =  9556181 52.667337695017615
dfNewJourney 130
lenPos 1747
I =  9424596 52.69250125817816
dfNewJourney 115
lenPos 1833
I =  9569841 52.71766482133871
dfNewJourney 105
lenPos 1829
I =  9456915 52.74282838449924
dfNewJourney 113
lenPos 1774
I =  9456927 52.76799194765979
dfNewJourney 124
lenPos 1704
I =  9240847 52.793155510820334
dfNewJourney 0
lenPos 0
I =  9589815 52.81831907398088
dfNewJourney 138
lenPos 1816
I =  9587831 52.84348263714141
dfNewJourney 131
lenPos 1739
I =  9260263 52.86864620030196
dfNewJourney 121
lenPos 1639
I =  9223253 52.89380976346251
dfNewJourney 166
lenPos 1748
I =  9288928 52.91897332662305
dfNewJourney 118
lenPos 1689
I =  9253325 52.944136889783586
dfNewJourney 111
lenPos 1837
I =  9388302 52.96930045294413
dfNewJourney 101
lenPos 1867
I =  9242156 52.99446401610468
dfNewJourney 116
lenPos 1368
I =  9111632 53.019627579265226
dfNewJourney 110
lenPos 1858
I =  9466025 53.044791142425765
dfNewJourney 187
lenPos 1763
I =  9111644 53.06995470558631
dfNewJourney 138
lenPos 1784
I =  9311725 53.09511826874685
dfNewJourney 155
lenPos 1721
I =  9123192 53.1202818319074
dfNewJourney 119
lenPos 1492
I =  9327009 53.14544539506794
dfNewJourney 123
lenPos 1769
I =  9430296 53.170608958228485
dfNewJourney 122
lenPos 1757
I =  9105102 53.19577252138903
dfNewJourney 99
lenPos 1533
I =  9149237 53.22093608454958
dfNewJourney 114
lenPos 1540
I =  9165542 53.246099647710125
dfNewJourney 148
lenPos 1626
I =  9259707 53.27126321087066
dfNewJourney 134
lenPos 1747
I =  9254903 53.296426774031204
dfNewJourney 111
lenPos 1835
I =  9280354 53.32159033719175
dfNewJourney 124
lenPos 1864
I =  9333400 53.3467539003523
dfNewJourney 104
lenPos 1770
I =  9299769 53.37191746351283
dfNewJourney 108
lenPos 1854
I =  9338814 53.397081026673376
dfNewJourney 124
lenPos 1810
I =  9291250 53.42224458983392
dfNewJourney 132
lenPos 1826
I =  9288772 53.44740815299447
dfNewJourney 113
lenPos 1855
I =  9460576 53.472571716155
dfNewJourney 106
lenPos 1755
I =  9577056 53.49773527931555
dfNewJourney 0
lenPos 0
I =  9637117 53.522898842476096
dfNewJourney 182
lenPos 1799
I =  9399612 53.54806240563664
dfNewJourney 126
lenPos 1790
I =  9577070 53.573225968797175
dfNewJourney 127
lenPos 1788
I =  9577082 53.59838953195772
dfNewJourney 120
lenPos 1837
I =  9577094 53.62355309511827
dfNewJourney 97
lenPos 1825
I =  9573672 53.648716658278815
dfNewJourney 99
lenPos 1572
I =  9270490 53.673880221439354
dfNewJourney 111
lenPos 1765
I =  9270488 53.6990437845999
dfNewJourney 113
lenPos 1674
I =  9273442 53.72420734776044
dfNewJourney 81
lenPos 1807
I =  9482847 53.74937091092099
dfNewJourney 291
lenPos 1904
I =  9253765 53.77453447408153
dfNewJourney 357
lenPos 1884
I =  9311505 53.799698037242074
dfNewJourney 26
lenPos 1603
I =  8617055 53.82486160040262
dfNewJourney 12
lenPos 1344
I =  9038751 53.85002516356317
dfNewJourney 66
lenPos 1279
I =  9117480 53.8751887267237
dfNewJourney 50
lenPos 923
I =  9117507 53.900352289884246
dfNewJourney 111
lenPos 1847
I =  9426283 53.92551585304479
dfNewJourney 209
lenPos 1849
I =  9543500 53.95067941620534
dfNewJourney 136
lenPos 1825
I =  9555292 53.97584297936587
dfNewJourney 136
lenPos 1793
I =  9299563 54.00100654252642
dfNewJourney 116
lenPos 1613
I =  8117093 54.026170105686965
dfNewJourney 70
lenPos 1630
I =  9044499 54.05133366884751
dfNewJourney 134
lenPos 1796
I =  9433810 54.076497232008045
dfNewJourney 167
lenPos 1834
I =  9482603 54.10166079516859
dfNewJourney 95
lenPos 1853
I =  9336490 54.12682435832914
dfNewJourney 178
lenPos 1861
I =  9274616 54.151987921489685
dfNewJourney 113
lenPos 1740
I =  9510462 54.177151484650224
dfNewJourney 141
lenPos 1685
I =  9229362 54.20231504781077
dfNewJourney 110
lenPos 1492
I =  9410533 54.22747861097131
dfNewJourney 117
lenPos 1795
I =  9448724 54.25264217413186
dfNewJourney 90
lenPos 1745
I =  9277785 54.277805737292404
dfNewJourney 123
lenPos 1746
I =  9297369 54.30296930045294
dfNewJourney 126
lenPos 1751
I =  9288825 54.32813286361349
dfNewJourney 135
lenPos 1739
I =  9288837 54.35329642677404
dfNewJourney 84
lenPos 1738
I =  9288265 54.37845998993458
dfNewJourney 107
lenPos 1663
I =  9258882 54.403623553095116
dfNewJourney 95
lenPos 1757
I =  9240172 54.42878711625566
dfNewJourney 136
lenPos 1859
I =  9386536 54.45395067941621
dfNewJourney 171
lenPos 1834
I =  9259915 54.479114242576756
dfNewJourney 288
lenPos 1795
I =  9295311 54.50427780573729
dfNewJourney 295
lenPos 1831
I =  9385178 54.529441368897835
dfNewJourney 107
lenPos 1783
I =  9419553 54.55460493205838
dfNewJourney 153
lenPos 1579
I =  9198290 54.57976849521893
dfNewJourney 147
lenPos 1757
I =  9420629 54.60493205837946
dfNewJourney 97
lenPos 1410
I =  9183300 54.63009562154001
dfNewJourney 148
lenPos 1789
I =  9222704 54.655259184700554
dfNewJourney 103
lenPos 1711
I =  9258478 54.6804227478611
dfNewJourney 139
lenPos 1807
I =  9215294 54.705586311021634
dfNewJourney 93
lenPos 1671
I =  9417452 54.73074987418218
dfNewJourney 108
lenPos 1805
I =  9389863 54.75591343734273
dfNewJourney 128
lenPos 1725
I =  9292515 54.781077000503274
dfNewJourney 32
lenPos 1301
I =  9111175 54.80624056366381
dfNewJourney 154
lenPos 1850
I =  9380063 54.83140412682436
dfNewJourney 80
lenPos 1521
I =  9038866 54.8565676899849
dfNewJourney 161
lenPos 1697
I =  9425552 54.881731253145446
dfNewJourney 119
lenPos 1760
I =  9341940 54.906894816305986
dfNewJourney 130
lenPos 1745
I =  9425514 54.93205837946653
dfNewJourney 143
lenPos 1775
I =  9382061 54.95722194262708
dfNewJourney 125
lenPos 1728
I =  9337901 54.982385505787626
dfNewJourney 192
lenPos 1700
I =  9508160 55.00754906894816

dfNewJourney 133
lenPos 1731
I =  9399272 55.032712632108705
dfNewJourney 12
lenPos 1793
I =  9432218 55.05787619526925
dfNewJourney 267
lenPos 1795
I =  9353591 55.0830397584298
dfNewJourney 129
lenPos 1752
I =  9459292 55.10820332159033
dfNewJourney 130
lenPos 1753
I =  9524982 55.13336688475088
dfNewJourney 131
lenPos 1757
I =  9435595 55.158530447911424
dfNewJourney 267
lenPos 1793
I =  9414814 55.18369401107197
dfNewJourney 113
lenPos 1651
I =  9414840 55.2088575742325
dfNewJourney 133
lenPos 1737
I =  9329784 55.23402113739305
dfNewJourney 131
lenPos 1834
I =  9565649 55.2591847005536
dfNewJourney 141
lenPos 1666
I =  9387138 55.28434826371414
dfNewJourney 118
lenPos 1443
I =  9398280 55.30951182687468
dfNewJourney 125
lenPos 1762
I =  9457268 55.33467539003523
dfNewJourney 118
lenPos 1516
I =  8808513 55.35983895319577
dfNewJourney 94
lenPos 1542
I =  9458858 55.385002516356316
dfNewJourney 97
lenPos 1502
I =  9399351 55.41016607951686
dfNewJourney 121
lenPos 1758
I =  9248837 55.4353296426774
dfNewJourney 102
lenPos 1798
I =  9282998 55.46049320583795
dfNewJourney 78
lenPos 1665
I =  9283679 55.485656768998496
dfNewJourney 176
lenPos 1804
I =  9476135 55.51082033215904
dfNewJourney 127
lenPos 1833
I =  9418145 55.535983895319575
dfNewJourney 95
lenPos 1619
I =  9179127 55.56114745848012
dfNewJourney 149
lenPos 1762
I =  9436018 55.58631102164067
dfNewJourney 109
lenPos 1814
I =  9271951 55.611474584801215
dfNewJourney 138
lenPos 1735
I =  9459280 55.63663814796175
dfNewJourney 165
lenPos 1725
I =  9484077 55.661801711122294
dfNewJourney 94
lenPos 1841
I =  9258026 55.68696527428284
dfNewJourney 129
lenPos 1658
I =  9457385 55.71212883744339
dfNewJourney 95
lenPos 1755
I =  9295086 55.73729240060392
dfNewJourney 199
lenPos 1735
I =  9417892 55.76245596376447
dfNewJourney 140
lenPos 1730
I =  9538440 55.78761952692501
dfNewJourney 145
lenPos 1860
I =  9523287 55.81278309008556
dfNewJourney 222
lenPos 1763
I =  9422201 55.83794665324609
dfNewJourney 143
lenPos 1832
I =  9573684 55.86311021640664
dfNewJourney 88
lenPos 1795
I =  9256626 55.888273779567186
dfNewJourney 135
lenPos 1375
I =  9288277 55.91343734272773
dfNewJourney 128
lenPos 1682
I =  9256925 55.93860090588827
dfNewJourney 104
lenPos 1743
I =  9256858 55.96376446904882
dfNewJourney 117
lenPos 1742
I =  9298961 55.98892803220936
dfNewJourney 137
lenPos 1741
I =  9339301 56.014091595369905
dfNewJourney 6
lenPos 1025
I =  9486910 56.039255158530445
dfNewJourney 86
lenPos 1750
I =  9390173 56.06441872169099
dfNewJourney 122
lenPos 1494
I =  9411290 56.08958228485154
dfNewJourney 105
lenPos 1530
I =  9487184 56.114745848012085
dfNewJourney 104
lenPos 1843
I =  9460564 56.13990941117262
dfNewJourney 354
lenPos 1738
I =  9416393 56.165072974333164
dfNewJourney 128
lenPos 1744
I =  9487249 56.19023653749371
dfNewJourney 156
lenPos 1695
I =  9455818 56.21540010065426
dfNewJourney 42
lenPos 1143
I =  9164536 56.24056366381479
dfNewJourney 120
lenPos 1722
I =  9580390 56.265727226975336
dfNewJourney 73
lenPos 1471
I =  9117492 56.29089079013588
dfNewJourney 141
lenPos 1836
I =  9459254 56.31605435329643
dfNewJourney 142
lenPos 1795
I =  9459242 56.34121791645696
dfNewJourney 107
lenPos 1788
I =  9388314 56.36638147961751
dfNewJourney 166
lenPos 1822
I =  9263186 56.391545042778056
dfNewJourney 104
lenPos 1754
I =  9277761 56.4167086059386
dfNewJourney 117
lenPos 1857
I =  9506693 56.44187216909915
dfNewJourney 136
lenPos 1839
I =  9528043 56.46703573225969
dfNewJourney 166
lenPos 1868
I =  9288746 56.49219929542023
dfNewJourney 158
lenPos 1793
I =  9306940 56.517362858580775
dfNewJourney 313
lenPos 1869
I =  9255268 56.54252642174132
dfNewJourney 155
lenPos 1804
I =  9232448 56.56768998490186
dfNewJourney 119
lenPos 1886
I =  9256028 56.59285354806241
dfNewJourney 76
lenPos 1653
I =  9250543 56.618017111222954
dfNewJourney 135
lenPos 1691
I =  9171357 56.6431806743835
dfNewJourney 120
lenPos 1742
I =  9436006 56.668344237544034
dfNewJourney 155
lenPos 1809
I =  9451733 56.69350780070458
dfNewJourney 295
lenPos 1894
I =  9304643 56.71867136386513
dfNewJourney 211
lenPos 1831
I =  9074420 56.743834927025674
dfNewJourney 119
lenPos 1680
I =  9283722 56.768998490186206
dfNewJourney 115
lenPos 1811
I =  9277735 56.79416205334675
dfNewJourney 75
lenPos 1803
I =  9461843 56.8193256165073
dfNewJourney 129
lenPos 1810
I =  9459266 56.844489179667846
dfNewJourney 198
lenPos 1833
I =  9543512 56.86965274282838
dfNewJourney 102
lenPos 1598
I =  9170432 56.894816305988925
dfNewJourney 108
lenPos 1630
I =  9232905 56.91997986914947
dfNewJourney 123
lenPos 1818
I =  9467756 56.94514343231002
dfNewJourney 138
lenPos 1837
I =  9402809 56.97030699547055
dfNewJourney 27
lenPos 1360
I =  8117158 56.9954705586311
dfNewJourney 146
lenPos 1828
I =  9293210 57.020634121791645
dfNewJourney 105
lenPos 1568
I =  9313448 57.04579768495219
dfNewJourney 133
lenPos 1834
I =  9577068 57.07096124811273
dfNewJourney 131
lenPos 1821
I =  9573658 57.09612481127328
dfNewJourney 125
lenPos 1513
I =  9246463 57.12128837443382
dfNewJourney 85
lenPos 1707
I =  9192258 57.146451937594364
dfNewJourney 122
lenPos 1764
I =  9451707 57.1716155007549
dfNewJourney 141
lenPos 1834
I =  9215282 57.19677906391545
dfNewJourney 120
lenPos 1799
I =  9256638 57.221942627076
dfNewJourney 66
lenPos 1750
I =  9431288 57.24710619023654
dfNewJourney 46
lenPos 454
I =  9083287 57.272269753397076
dfNewJourney 116
lenPos 1537
I =  9282443 57.29743331655762
dfNewJourney 97
lenPos 1775
I =  9266762 57.32259687971817
dfNewJourney 198
lenPos 1846
I =  9301005 57.347760442878716
dfNewJourney 108
lenPos 1868
I =  9573660 57.37292400603925
dfNewJourney 81
lenPos 1907
I =  9564384 57.398087569199795
dfNewJourney 144
lenPos 1839
I =  9487251 57.42325113236034
dfNewJourney 94
lenPos 1854
I =  9573696 57.44841469552089
dfNewJourney 141
lenPos 1882
I =  9309423 57.473578258681435
dfNewJourney 90
lenPos 1871
I =  9584102 57.49874182184197
dfNewJourney 123
lenPos 1738
I =  9411317 57.523905385002514
dfNewJourney 109
lenPos 1832
I =  9277759 57.54906894816306
dfNewJourney 111
lenPos 1756
I =  9277773 57.57423251132361
dfNewJourney 256
lenPos 1816
I =  9298193 57.59939607448415
dfNewJourney 280
lenPos 1889
I =  9204776 57.62455963764469
dfNewJourney 266
lenPos 1881
I =  9255490 57.649723200805234
dfNewJourney 233
lenPos 1855
I =  9327372 57.67488676396578
dfNewJourney 146
lenPos 1779
I =  9384435 57.70005032712632
dfNewJourney 189
lenPos 1874
I =  9261396 57.72521389028687
dfNewJourney 7
lenPos 1010
I =  9145413 57.75037745344741
dfNewJourney 285
lenPos 1895
I =  9327401 57.77554101660796
dfNewJourney 167
lenPos 1786
I =  9228801 57.80070457976849
dfNewJourney 154
lenPos 1749
I =  9236743 57.82586814292904
dfNewJourney 123
lenPos 1806
I =  9470131 57.851031706089586
dfNewJourney 143
lenPos 1792
I =  9229350 57.87619526925013
dfNewJourney 154
lenPos 1610
I =  9247479 57.901358832410665
dfNewJourney 163
lenPos 1820
I =  9247481 57.92652239557121
dfNewJourney 166
lenPos 1666
I =  9248796 57.95168595873176
dfNewJourney 146
lenPos 1750
I =  9252967 57.976849521892305
dfNewJourney 150
lenPos 1783
I =  9252979 58.00201308505284
dfNewJourney 114
lenPos 1592
I =  9255842 58.027176648213384
dfNewJourney 155
lenPos 1766
I =  9255672 58.05234021137393
dfNewJourney 197
lenPos 1730
I =  9241695 58.07750377453448
dfNewJourney 176
lenPos 1742
I =  9282821 58.10266733769501
dfNewJourney 259
lenPos 1821
I =  9286059 58.12783090085556
dfNewJourney 140
lenPos 1801
I =  9290361 58.1529944640161
dfNewJourney 181
lenPos 1839
I =  9290438 58.17815802717665
dfNewJourney 216
lenPos 1805
I =  9261401 58.20332159033719
dfNewJourney 194
lenPos 1708
I =  9292591 58.228485153497736
dfNewJourney 485
lenPos 1906
I =  9236987 58.253648716658276
dfNewJourney 101
lenPos 1844
I =  9237008 58.27881227981882
dfNewJourney 155
lenPos 1688
I =  9251406 58.30397584297936
dfNewJourney 137
lenPos 1411
I =  9306938 58.32913940613991
dfNewJourney 108
lenPos 1645
I =  9278519 58.354302969300456
dfNewJourney 161
lenPos 1731
I =  9431276 58.379466532461
dfNewJourney 167
lenPos 1737
I =  9302126 58.404630095621535
dfNewJourney 143
lenPos 1589
I =  9288930 58.42979365878208
dfNewJourney 126
lenPos 1424
I =  9302114 58.45495722194263

dfNewJourney 166
lenPos 1731
I =  9295323 58.480120785103175
dfNewJourney 475
lenPos 1795
I =  9293337 58.50528434826371
dfNewJourney 146
lenPos 1808
I =  9274642 58.530447911424254
dfNewJourney 386
lenPos 1890
I =  9305556 58.5556114745848
dfNewJourney 589
lenPos 1893
I =  9235892 58.58077503774535
dfNewJourney 412
lenPos 1886
I =  9255270 58.605938600905894
dfNewJourney 483
lenPos 1892
I =  9255282 58.63110216406643
dfNewJourney 457
lenPos 1901
I =  9255294 58.65626572722697
dfNewJourney 182
lenPos 1700
I =  9282493 58.68142929038752
dfNewJourney 92
lenPos 1808
I =  9278052 58.70659285354807
dfNewJourney 260
lenPos 1825
I =  9247168 58.731756416708606
dfNewJourney 114
lenPos 1818
I =  9281920 58.756919979869146
dfNewJourney 87
lenPos 1811
I =  9288356 58.78208354302969
dfNewJourney 135
lenPos 1697
I =  9306665 58.80724710619024
dfNewJourney 243
lenPos 1843
I =  9313527 58.83241066935078
dfNewJourney 175
lenPos 1748
I =  9126285 58.857574232511325
dfNewJourney 136
lenPos 1646
I =  9443140 58.88273779567187
dfNewJourney 126
lenPos 1715
I =  9443152 58.90790135883242
dfNewJourney 149
lenPos 1851
I =  9461673 58.93306492199295
dfNewJourney 80
lenPos 1728
I =  9259599 58.9582284851535
dfNewJourney 162
lenPos 1662
I =  9248801 58.983392048314045
dfNewJourney 120
lenPos 1746
I =  9455741 59.00855561147459
dfNewJourney 182
lenPos 1806
I =  9180126 59.033719174635124
dfNewJourney 128
lenPos 1855
I =  9103831 59.05888273779567
dfNewJourney 59
lenPos 1560
I =  9221891 59.08404630095622
dfNewJourney 145
lenPos 1736
I =  9239927 59.109209864116764
dfNewJourney 131
lenPos 1754
I =  9239939 59.134373427277296
dfNewJourney 143
lenPos 1781
I =  9232450 59.15953699043784
dfNewJourney 152
lenPos 1833
I =  9252371 59.18470055359839
dfNewJourney 140
lenPos 1831
I =  9255696 59.209864116758936
dfNewJourney 132
lenPos 1860
I =  9288693 59.23502767991947
dfNewJourney 175
lenPos 1865
I =  9288708 59.260191243080016
dfNewJourney 174
lenPos 1841
I =  9288710 59.28535480624056
dfNewJourney 184
lenPos 1858
I =  9288722 59.31051836940111
dfNewJourney 189
lenPos 1811
I =  9305609 59.33568193256165
dfNewJourney 162
lenPos 1857
I =  9305623 59.360845495722195
dfNewJourney 240
lenPos 1859
I =  9315898 59.386009058882735
dfNewJourney 194
lenPos 1808
I =  9240706 59.41117262204328
dfNewJourney 82
lenPos 1755
I =  9379624 59.43633618520382
dfNewJourney 132
lenPos 1772
I =  9391311 59.46149974836437
dfNewJourney 150
lenPos 1564
I =  9411197 59.486663311524914
dfNewJourney 111
lenPos 1635
I =  9439199 59.51182687468546
dfNewJourney 115
lenPos 1848
I =  9296195 59.53699043784599
dfNewJourney 264
lenPos 1858
I =  9220938 59.56215400100654
dfNewJourney 284
lenPos 1807
I =  9220940 59.58731756416709
dfNewJourney 188
lenPos 1742
I =  9231183 59.612481127327634
dfNewJourney 211
lenPos 1609
I =  9231705 59.63764469048818
dfNewJourney 147
lenPos 1666
I =  9246786 59.66280825364871
dfNewJourney 263
lenPos 1842
I =  9253777 59.68797181680926
dfNewJourney 209
lenPos 1844
I =  9253129 59.713135379969806
dfNewJourney 266
lenPos 1771
I =  9288942 59.73829894313035
dfNewJourney 169
lenPos 1859
I =  9293997 59.763462506290885
dfNewJourney 223
lenPos 1765
I =  9294123 59.78862606945143
dfNewJourney 190
lenPos 1610
I =  9250153 59.81378963261198
dfNewJourney 147
lenPos 1426
I =  9299214 59.838953195772525
dfNewJourney 121
lenPos 1715
I =  9293959 59.864116758933065
dfNewJourney 460
lenPos 1867
I =  9292280 59.889280322093605
dfNewJourney 258
lenPos 1799
I =  9351529 59.91444388525415
dfNewJourney 460
lenPos 1850
I =  9373137 59.9396074484147
dfNewJourney 276
lenPos 1814
I =  9436692 59.96477101157524
dfNewJourney 82
lenPos 1535
I =  9544281 59.989934574735784
dfNewJourney 146
lenPos 1827
I =  9472763 60.01509813789633
dfNewJourney 174
lenPos 1737
I =  9278480 60.04026170105688
dfNewJourney 288
lenPos 1867
I =  9179347 60.06542526421741
dfNewJourney 127
lenPos 1665
I =  9158161 60.09058882737796
dfNewJourney 128
lenPos 1746
I =  9171345 60.1157523905385
dfNewJourney 84
lenPos 1730
I =  9471329 60.14091595369905
dfNewJourney 66
lenPos 1295
I =  9185279 60.16607951685958
dfNewJourney 0
lenPos 59
I =  9108142 60.19124308002013
dfNewJourney 131
lenPos 1846
I =  9528031 60.216406643180676
dfNewJourney 150
lenPos 1844
I =  9407445 60.24157020634122
dfNewJourney 122
lenPos 1688
I =  9261619 60.266733769501755
dfNewJourney 162
lenPos 1788
I =  9309382 60.2918973326623
dfNewJourney 194
lenPos 1847
I =  9595125 60.31706089582285
dfNewJourney 125
lenPos 1840
I =  9528380 60.342224458983395
dfNewJourney 158
lenPos 1791
I =  9231901 60.36738802214393
dfNewJourney 145
lenPos 1527
I =  9233208 60.392551585304474
dfNewJourney 214
lenPos 1690
I =  9396323 60.41771514846502
dfNewJourney 216
lenPos 1831
I =  9377664 60.44287871162557
dfNewJourney 213
lenPos 1791
I =  9260017 60.46804227478611
dfNewJourney 153
lenPos 1830
I =  9172870 60.493205837946654
dfNewJourney 246
lenPos 1866
I =  9321677 60.51836940110719
dfNewJourney 99
lenPos 1790
I =  9524762 60.54353296426774
dfNewJourney 97
lenPos 1712
I =  8808525 60.56869652742828
dfNewJourney 246
lenPos 1868
I =  9372561 60.59386009058883
dfNewJourney 311
lenPos 1842
I =  9372559 60.61902365374937
dfNewJourney 266
lenPos 1906
I =  9372547 60.64418721690992
dfNewJourney 86
lenPos 1702
I =  9171838 60.66935078007047
dfNewJourney 200
lenPos 1866
I =  9194139 60.694514343231
dfNewJourney 144
lenPos 1854
I =  9252292 60.719677906391546
dfNewJourney 145
lenPos 1798
I =  9339624 60.74484146955209
dfNewJourney 86
lenPos 1073
I =  9125736 60.77000503271264
dfNewJourney 120
lenPos 1693
I =  9335123 60.79516859587317
dfNewJourney 111
lenPos 1480
I =  9255933 60.82033215903372
dfNewJourney 105
lenPos 1836
I =  9391476 60.845495722194265
dfNewJourney 100
lenPos 1868
I =  9413523 60.87065928535481
dfNewJourney 99
lenPos 1760
I =  9389851 60.895822848515344
dfNewJourney 292
lenPos 1831
I =  9466130 60.92098641167589
dfNewJourney 78
lenPos 1723
I =  9461855 60.94614997483644
dfNewJourney 257
lenPos 1820
I =  9209130 60.971313537996984
dfNewJourney 180
lenPos 1761
I =  9312846 60.996477101157524
dfNewJourney 199
lenPos 1875
I =  9238052 61.02164066431806
dfNewJourney 207
lenPos 1882
I =  9255880 61.04680422747861
dfNewJourney 93
lenPos 1896
I =  9233806 61.07196779063916
dfNewJourney 100
lenPos 1819
I =  9233818 61.097131353799696
dfNewJourney 152
lenPos 1817
I =  9281011 61.12229491696024
dfNewJourney 241
lenPos 1761
I =  9206671 61.14745848012079
dfNewJourney 238
lenPos 1841
I =  9291262 61.172622043281336
dfNewJourney 47
lenPos 1496
I =  9222560 61.19778560644187
dfNewJourney 109
lenPos 1570
I =  9218181 61.222949169602416
dfNewJourney 174
lenPos 1625
I =  9413004 61.24811273276296
dfNewJourney 155
lenPos 1644
I =  9400837 61.27327629592351
dfNewJourney 143
lenPos 1665
I =  9296810 61.29843985908404
dfNewJourney 71
lenPos 1334
I =  9154000 61.32360342224459
dfNewJourney 125
lenPos 1564
I =  9279587 61.348766985405135
dfNewJourney 140
lenPos 1666
I =  9420631 61.37393054856568
dfNewJourney 121
lenPos 1647
I =  9568500 61.399094111726214
dfNewJourney 117
lenPos 1790
I =  9271377 61.42425767488676
dfNewJourney 148
lenPos 1625
I =  9165762 61.44942123804731
dfNewJourney 275
lenPos 1761
I =  9351062 61.474584801207854
dfNewJourney 314
lenPos 1794
I =  9408114 61.499748364368386
dfNewJourney 246
lenPos 1744
I =  9353606 61.52491192752893
dfNewJourney 136
lenPos 1795
I =  9392377 61.55007549068948
dfNewJourney 222
lenPos 1750
I =  9412995 61.57523905385003
dfNewJourney 125
lenPos 1881
I =  9581447 61.600402617010566
dfNewJourney 166
lenPos 1828
I =  9512173 61.62556618017111
dfNewJourney 192
lenPos 1814
I =  9063108 61.65072974333165
dfNewJourney 314
lenPos 1703
I =  9232711 61.6758933064922
dfNewJourney 300
lenPos 1728
I =  9245706 61.70105686965274
dfNewJourney 324
lenPos 1792
I =  9245691 61.726220432813285
dfNewJourney 289
lenPos 1735
I =  9259757 61.75138399597383
dfNewJourney 313
lenPos 1803
I =  9259769 61.77654755913438
dfNewJourney 265
lenPos 1747
I =  9271028 61.801711122294925
dfNewJourney 135
lenPos 1817
I =  9308962 61.82687468545546
dfNewJourney 277
lenPos 1772
I =  9312614 61.852038248616005
dfNewJourney 0
lenPos 0
I =  9584114 61.87720181177655
dfNewJourney 244
lenPos 1797
I =  9037123 61.9023653749371

dfNewJourney 194
lenPos 1645
I =  9308455 61.92752893809763
dfNewJourney 193
lenPos 1696
I =  9509035 61.95269250125818
dfNewJourney 550
lenPos 1851
I =  9536026 61.977856064418724
dfNewJourney 448
lenPos 1834
I =  9536014 62.00301962757927
dfNewJourney 189
lenPos 1746
I =  9596363 62.0281831907398
dfNewJourney 214
lenPos 1731
I =  9596375 62.05334675390035
dfNewJourney 79
lenPos 1388
I =  9173654 62.078510317060896
dfNewJourney 55
lenPos 1241
I =  9168439 62.10367388022144
dfNewJourney 384
lenPos 1828
I =  9251585 62.12883744338198
dfNewJourney 168
lenPos 1748
I =  9271365 62.15400100654252
dfNewJourney 123
lenPos 1520
I =  9247821 62.17916456970307
dfNewJourney 145
lenPos 1646
I =  9247833 62.204328132863616
dfNewJourney 187
lenPos 1856
I =  9259185 62.229491696024155
dfNewJourney 109
lenPos 1568
I =  9299599 62.2546552591847
dfNewJourney 160
lenPos 1775
I =  9304356 62.27981882234525
dfNewJourney 173
lenPos 1644
I =  9188477 62.304982385505795
dfNewJourney 126
lenPos 1508
I =  9224570 62.33014594866633
dfNewJourney 113
lenPos 1696
I =  9276688 62.355309511826874
dfNewJourney 115
lenPos 1801
I =  9271834 62.38047307498742
dfNewJourney 136
lenPos 1781
I =  9262924 62.40563663814797
dfNewJourney 142
lenPos 1720
I =  9436666 62.4308002013085
dfNewJourney 118
lenPos 1806
I =  9412464 62.45596376446905
dfNewJourney 80
lenPos 1677
I =  9433585 62.48112732762959
dfNewJourney 219
lenPos 1853
I =  9290828 62.50629089079014
dfNewJourney 140
lenPos 1820
I =  9235701 62.53145445395067
dfNewJourney 128
lenPos 1732
I =  9482550 62.55661801711122
dfNewJourney 137
lenPos 1801
I =  9278492 62.581781580271766
dfNewJourney 99
lenPos 1807
I =  9252187 62.60694514343231
dfNewJourney 138
lenPos 1601
I =  9228837 62.632108706592845
dfNewJourney 171
lenPos 1742
I =  9305532 62.65727226975339
dfNewJourney 119
lenPos 1262
I =  9267027 62.68243583291394
dfNewJourney 96
lenPos 1634
I =  9520869 62.707599396074485
dfNewJourney 121
lenPos 1601
I =  9484089 62.732762959235025
dfNewJourney 203
lenPos 1744
I =  9422196 62.75792652239557
dfNewJourney 134
lenPos 1560
I =  9253478 62.78309008555611
dfNewJourney 176
lenPos 1696
I =  9253076 62.80825364871666
dfNewJourney 110
lenPos 1783
I =  9273260 62.833417211877205
dfNewJourney 167
lenPos 1795
I =  9576753 62.858580775037744
dfNewJourney 128
lenPos 1621
I =  9284386 62.88374433819829
dfNewJourney 204
lenPos 1553
I =  9198082 62.90890790135884
dfNewJourney 167
lenPos 1806
I =  9482627 62.934071464519384
dfNewJourney 442
lenPos 1872
I =  9490325 62.95923502767992
dfNewJourney 95
lenPos 1413
I =  9306627 62.98439859084046
dfNewJourney 163
lenPos 1655
I =  9113367 63.00956215400101
dfNewJourney 177
lenPos 1848
I =  9212474 63.03472571716156
dfNewJourney 83
lenPos 1641
I =  9112753 63.05988928032209
dfNewJourney 125
lenPos 1621
I =  9112129 63.085052843482636
dfNewJourney 61
lenPos 1787
I =  9112131 63.11021640664318
dfNewJourney 116
lenPos 1294
I =  9256860 63.13537996980373
dfNewJourney 96
lenPos 1591
I =  9116371 63.16054353296426
dfNewJourney 105
lenPos 1237
I =  9247974 63.18570709612481
dfNewJourney 134
lenPos 1792
I =  9232888 63.210870659285355
dfNewJourney 127
lenPos 1818
I =  9270517 63.2360342224459
dfNewJourney 132
lenPos 1627
I =  9270529 63.26119778560644
dfNewJourney 131
lenPos 1790
I =  9258002 63.28636134876698
dfNewJourney 108
lenPos 1577
I =  9267132 63.31152491192753
dfNewJourney 195
lenPos 1794
I =  9299707 63.336688475088074
dfNewJourney 103
lenPos 1720
I =  9266750 63.361852038248614
dfNewJourney 92
lenPos 1220
I =  9289166 63.38701560140916
dfNewJourney 80
lenPos 1669
I =  9116632 63.41217916456971
dfNewJourney 176
lenPos 1725
I =  9144794 63.437342727730254
dfNewJourney 160
lenPos 1742
I =  9310525 63.462506290890786
dfNewJourney 171
lenPos 1711
I =  9306794 63.48766985405133
dfNewJourney 225
lenPos 1869
I =  9312896 63.51283341721188
dfNewJourney 109
lenPos 1671
I =  9188776 63.53799698037243
dfNewJourney 205
lenPos 1833
I =  9511387 63.56316054353296
dfNewJourney 217
lenPos 1830
I =  9511533 63.588324106693506
dfNewJourney 182
lenPos 1827
I =  9522324 63.61348766985405
dfNewJourney 190
lenPos 1829
I =  9199713 63.6386512330146
dfNewJourney 140
lenPos 1776
I =  9411305 63.66381479617513
dfNewJourney 82
lenPos 1859
I =  9482861 63.68897835933568
dfNewJourney 116
lenPos 1839
I =  9494670 63.714141922496225
dfNewJourney 97
lenPos 1674
I =  9514169 63.73930548565677
dfNewJourney 95
lenPos 1826
I =  9573701 63.764469048817304
dfNewJourney 110
lenPos 1875
I =  9592226 63.78963261197785
dfNewJourney 91
lenPos 1714
I =  9189952 63.8147961751384
dfNewJourney 138
lenPos 1877
I =  9309435 63.839959738298944
dfNewJourney 146
lenPos 1753
I =  9259903 63.86512330145949
dfNewJourney 201
lenPos 1879
I =  9311751 63.89028686462003
dfNewJourney 226
lenPos 1873
I =  9331141 63.91545042778057
dfNewJourney 243
lenPos 1851
I =  9255517 63.94061399094112
dfNewJourney 164
lenPos 1865
I =  9524994 63.96577755410166
dfNewJourney 135
lenPos 1827
I =  9473717 63.9909411172622
dfNewJourney 125
lenPos 1851
I =  9527403 64.01610468042274
dfNewJourney 146
lenPos 1792
I =  9290490 64.04126824358329
dfNewJourney 62
lenPos 1667
I =  9212383 64.06643180674384
dfNewJourney 209
lenPos 1851
I =  9595137 64.09159536990437
dfNewJourney 155
lenPos 1846
I =  9176929 64.11675893306492
dfNewJourney 134
lenPos 1378
I =  9266774 64.14192249622546
dfNewJourney 108
lenPos 1731
I =  9409479 64.16708605938601
dfNewJourney 388
lenPos 1789
I =  9203992 64.19224962254656
dfNewJourney 122
lenPos 1712
I =  9243033 64.2174131857071
dfNewJourney 144
lenPos 1747
I =  9328168 64.24257674886763
dfNewJourney 90
lenPos 1579
I =  9308950 64.26774031202818
dfNewJourney 106
lenPos 1704
I =  9221671 64.29290387518873
dfNewJourney 212
lenPos 1730
I =  9518892 64.31806743834927
dfNewJourney 142
lenPos 1791
I =  9413016 64.34323100150982
dfNewJourney 112
lenPos 1680
I =  9229427 64.36839456467037
dfNewJourney 89
lenPos 1799
I =  9469687 64.3935581278309
dfNewJourney 134
lenPos 1678
I =  9296822 64.41872169099145
dfNewJourney 86
lenPos 1805
I =  9482859 64.443885254152
dfNewJourney 107
lenPos 1846
I =  9540807 64.46904881731254
dfNewJourney 135
lenPos 1861
I =  9448712 64.49421238047307
dfNewJourney 411
lenPos 1891
I =  9499888 64.51937594363362
dfNewJourney 168
lenPos 1767
I =  9457749 64.54453950679417
dfNewJourney 111
lenPos 1689
I =  9570008 64.56970306995471
dfNewJourney 213
lenPos 1831
I =  9399624 64.59486663311525
dfNewJourney 120
lenPos 1724
I =  9455806 64.62003019627579
dfNewJourney 88
lenPos 1649
I =  9489027 64.64519375943634
dfNewJourney 106
lenPos 1794
I =  9185516 64.67035732259689
dfNewJourney 253
lenPos 1791
I =  9231171 64.69552088575742
dfNewJourney 94
lenPos 1674
I =  9290311 64.72068444891796
dfNewJourney 187
lenPos 1566
I =  9295062 64.74584801207851
dfNewJourney 173
lenPos 1784
I =  9566356 64.77101157523906
dfNewJourney 303
lenPos 1819
I =  9288368 64.79617513839959
dfNewJourney 160
lenPos 1048
I =  9239642 64.82133870156014
dfNewJourney 99
lenPos 1625
I =  9178068 64.84650226472068
dfNewJourney 126
lenPos 1719
I =  9411329 64.87166582788123
dfNewJourney 123
lenPos 1484
I =  9213325 64.89682939104178
dfNewJourney 147
lenPos 1691
I =  9487263 64.92199295420231
dfNewJourney 150
lenPos 1841
I =  9222376 64.94715651736286
dfNewJourney 0
lenPos 1052
I =  8413447 64.9723200805234
dfNewJourney 191
lenPos 1803
I =  9472622 64.99748364368395
dfNewJourney 207
lenPos 1882
I =  9352315 65.02264720684448
dfNewJourney 138
lenPos 1675
I =  9285847 65.04781077000503
dfNewJourney 204
lenPos 1799
I =  9453975 65.07297433316558
dfNewJourney 117
lenPos 1796
I =  9461661 65.09813789632612
dfNewJourney 185
lenPos 1732
I =  9235725 65.12330145948665
dfNewJourney 146
lenPos 1818
I =  9232876 65.1484650226472
dfNewJourney 155
lenPos 1684
I =  9235713 65.17362858580775
dfNewJourney 92
lenPos 1801
I =  9250531 65.1987921489683
dfNewJourney 165
lenPos 1851
I =  9297333 65.22395571212883
dfNewJourney 97
lenPos 1730
I =  9283306 65.24911927528937
dfNewJourney 247
lenPos 1879
I =  9228796 65.27428283844992
dfNewJourney 481
lenPos 1898
I =  9313436 65.29944640161047
dfNewJourney 167
lenPos 1681
I =  9288863 65.32460996477101
dfNewJourney 179
lenPos 1654
I =  9466142 65.34977352793156

dfNewJourney 106
lenPos 1813
I =  9282041 65.37493709109211
dfNewJourney 125
lenPos 1786
I =  9499371 65.40010065425264
dfNewJourney 250
lenPos 1706
I =  9278727 65.42526421741319
dfNewJourney 309
lenPos 1734
I =  9353553 65.45042778057373
dfNewJourney 147
lenPos 1599
I =  9354492 65.47559134373428
dfNewJourney 352
lenPos 1814
I =  9283526 65.50075490689483
dfNewJourney 377
lenPos 1820
I =  9303699 65.52591847005536
dfNewJourney 0
lenPos 0
I =  9615444 65.5510820332159
dfNewJourney 196
lenPos 1617
I =  9295074 65.57624559637645
dfNewJourney 190
lenPos 1774
I =  9566344 65.601409159537
dfNewJourney 80
lenPos 1769
I =  9264570 65.62657272269753
dfNewJourney 93
lenPos 1625
I =  9402469 65.65173628585808
dfNewJourney 105
lenPos 1548
I =  9213301 65.67689984901862
dfNewJourney 147
lenPos 1679
I =  9213313 65.70206341217917
dfNewJourney 112
lenPos 1682
I =  9298272 65.7272269753397
dfNewJourney 185
lenPos 1783
I =  9337341 65.75239053850025
dfNewJourney 113
lenPos 1675
I =  9233313 65.7775541016608
dfNewJourney 194
lenPos 1814
I =  9518907 65.80271766482134
dfNewJourney 216
lenPos 1821
I =  9587843 65.82788122798188
dfNewJourney 135
lenPos 1708
I =  9482562 65.85304479114242
dfNewJourney 110
lenPos 1592
I =  9251456 65.87820835430297
dfNewJourney 97
lenPos 1569
I =  9520857 65.90337191746352
dfNewJourney 125
lenPos 1526
I =  9572264 65.92853548062405
dfNewJourney 139
lenPos 1706
I =  9250892 65.9536990437846
dfNewJourney 94
lenPos 1584
I =  9308948 65.97886260694514
dfNewJourney 82
lenPos 1177
I =  9283289 66.00402617010569
dfNewJourney 81
lenPos 1708
I =  9289752 66.02918973326624
dfNewJourney 180
lenPos 1792
I =  9576765 66.05435329642677
dfNewJourney 96
lenPos 1832
I =  9247986 66.07951685958732
dfNewJourney 101
lenPos 1651
I =  9275402 66.10468042274786
dfNewJourney 96
lenPos 1352
I =  9236729 66.12984398590841
dfNewJourney 156
lenPos 1807
I =  9299692 66.15500754906894
dfNewJourney 135
lenPos 1782
I =  9487275 66.18017111222949
dfNewJourney 141
lenPos 1799
I =  9433846 66.20533467539003
dfNewJourney 164
lenPos 1794
I =  9178044 66.23049823855058
dfNewJourney 70
lenPos 1394
I =  9524920 66.25566180171111
dfNewJourney 128
lenPos 1749
I =  9565730 66.28082536487166
dfNewJourney 139
lenPos 1843
I =  9552496 66.3059889280322
dfNewJourney 126
lenPos 1853
I =  9528392 66.33115249119275
dfNewJourney 146
lenPos 1746
I =  9265744 66.35631605435329
dfNewJourney 118
lenPos 1712
I =  9253313 66.38147961751383
dfNewJourney 115
lenPos 1721
I =  9457593 66.40664318067438
dfNewJourney 126
lenPos 1750
I =  9242120 66.43180674383493
dfNewJourney 109
lenPos 1735
I =  9205873 66.45697030699547
dfNewJourney 120
lenPos 1802
I =  9157777 66.48213387015602
dfNewJourney 28
lenPos 1544
I =  9147447 66.50729743331655
dfNewJourney 324
lenPos 1906
I =  9513440 66.5324609964771
dfNewJourney 119
lenPos 1823
I =  9260067 66.55762455963765
dfNewJourney 131
lenPos 1883
I =  9470284 66.58278812279819
dfNewJourney 147
lenPos 1815
I =  9433834 66.60795168595874
dfNewJourney 158
lenPos 1861
I =  9473729 66.63311524911929
dfNewJourney 0
lenPos 0
I =  9538452 66.65827881227982
dfNewJourney 108
lenPos 1861
I =  9540819 66.68344237544036
dfNewJourney 42
lenPos 1114
I =  9071818 66.70860593860091
dfNewJourney 172
lenPos 1846
I =  9592252 66.73376950176146
dfNewJourney 146
lenPos 1370
I =  9038892 66.75893306492199
dfNewJourney 229
lenPos 1722
I =  9582439 66.78409662808254
dfNewJourney 111
lenPos 1726
I =  9514171 66.80926019124308
dfNewJourney 0
lenPos 0
I =  9538464 66.83442375440363
dfNewJourney 94
lenPos 1622
I =  9433597 66.85958731756416
dfNewJourney 131
lenPos 1882
I =  9470272 66.88475088072471
dfNewJourney 100
lenPos 1826
I =  9470258 66.90991444388526
dfNewJourney 92
lenPos 1755
I =  9496032 66.9350780070458
dfNewJourney 54
lenPos 1803
I =  9233349 66.96024157020634
dfNewJourney 75
lenPos 1619
I =  9283291 66.98540513336688
dfNewJourney 127
lenPos 1542
I =  9431290 67.01056869652743
dfNewJourney 120
lenPos 1756
I =  9457608 67.03573225968798
dfNewJourney 112
lenPos 1835
I =  9528366 67.06089582284852
dfNewJourney 155
lenPos 1838
I =  9577109 67.08605938600905
dfNewJourney 131
lenPos 1703
I =  9459008 67.1112229491696
dfNewJourney 112
lenPos 1723
I =  9419541 67.13638651233015
dfNewJourney 61
lenPos 1603
I =  8909460 67.1615500754907
dfNewJourney 127
lenPos 1864
I =  9479838 67.18671363865123
dfNewJourney 89
lenPos 1766
I =  9402225 67.21187720181177
dfNewJourney 142
lenPos 1820
I =  9462897 67.23704076497232
dfNewJourney 117
lenPos 1602
I =  9329318 67.26220432813287
dfNewJourney 132
lenPos 1772
I =  9260275 67.2873678912934
dfNewJourney 329
lenPos 1888
I =  9523835 67.31253145445395
dfNewJourney 212
lenPos 1780
I =  9259692 67.3376950176145
dfNewJourney 123
lenPos 1864
I =  9489895 67.36285858077504
dfNewJourney 118
lenPos 1660
I =  9176656 67.38802214393557
dfNewJourney 126
lenPos 1841
I =  9590905 67.41318570709612
dfNewJourney 235
lenPos 1773
I =  9257814 67.43834927025667
dfNewJourney 17
lenPos 1428
I =  7396238 67.46351283341721
dfNewJourney 67
lenPos 1781
I =  9241827 67.48867639657774
dfNewJourney 161
lenPos 1810
I =  9489039 67.51383995973829
dfNewJourney 152
lenPos 1706
I =  9472634 67.53900352289884
dfNewJourney 133
lenPos 1573
I =  9234678 67.56416708605938
dfNewJourney 157
lenPos 1684
I =  9443164 67.58933064921993
dfNewJourney 119
lenPos 1719
I =  9489194 67.61449421238048
dfNewJourney 134
lenPos 1772
I =  9346861 67.63965777554102
dfNewJourney 150
lenPos 1855
I =  9516959 67.66482133870156
dfNewJourney 97
lenPos 1507
I =  9228722 67.6899849018621
dfNewJourney 22
lenPos 988
I =  8618891 67.71514846502265
dfNewJourney 150
lenPos 1696
I =  9295098 67.7403120281832
dfNewJourney 126
lenPos 1782
I =  9479840 67.76547559134374
dfNewJourney 130
lenPos 1661
I =  9543524 67.79063915450428
dfNewJourney 0
lenPos 0
I =  9622021 67.81580271766482
dfNewJourney 20
lenPos 1825
I =  9086356 67.84096628082537
dfNewJourney 135
lenPos 1570
I =  9289506 67.86612984398592
dfNewJourney 252
lenPos 1786
I =  9270555 67.89129340714645
dfNewJourney 158
lenPos 1809
I =  9412036 67.916456970307
dfNewJourney 177
lenPos 1691
I =  9576777 67.94162053346754
dfNewJourney 46
lenPos 1616
I =  9040455 67.96678409662809
dfNewJourney 20
lenPos 756
I =  9108647 67.99194765978862
dfNewJourney 190
lenPos 1763
I =  9259680 68.01711122294917
dfNewJourney 35
lenPos 1834
I =  9165176 68.04227478610972
dfNewJourney 117
lenPos 1775
I =  9528378 68.06743834927026
dfNewJourney 109
lenPos 1245
I =  9275268 68.09260191243081
dfNewJourney 108
lenPos 1399
I =  9117478 68.11776547559134
dfNewJourney 105
lenPos 1695
I =  9394040 68.14292903875189
dfNewJourney 112
lenPos 1810
I =  9577032 68.16809260191243
dfNewJourney 49
lenPos 1293
I =  9080508 68.19325616507298
dfNewJourney 149
lenPos 1840
I =  9568172 68.21841972823351
dfNewJourney 171
lenPos 1514
I =  9568512 68.24358329139406
dfNewJourney 144
lenPos 1432
I =  9196436 68.2687468545546
dfNewJourney 125
lenPos 1793
I =  9568184 68.29391041771515
dfNewJourney 55
lenPos 1284
I =  9180097 68.31907398087569
dfNewJourney 69
lenPos 1265
I =  9455789 68.34423754403623
dfNewJourney 183
lenPos 1422
I =  9284594 68.36940110719678
dfNewJourney 92
lenPos 1795
I =  9276690 68.39456467035733
dfNewJourney 122
lenPos 1601
I =  9293002 68.41972823351786
dfNewJourney 106
lenPos 1714
I =  9572276 68.4448917966784
dfNewJourney 156
lenPos 1584
I =  9431305 68.47005535983895
dfNewJourney 85
lenPos 1563
I =  9266372 68.4952189229995
dfNewJourney 103
lenPos 840
I =  9137583 68.52038248616003
dfNewJourney 76
lenPos 1473
I =  9247883 68.54554604932058
dfNewJourney 122
lenPos 1824
I =  9580405 68.57070961248112
dfNewJourney 68
lenPos 1308
I =  9313424 68.59587317564167
dfNewJourney 294
lenPos 1759
I =  9513438 68.6210367388022
dfNewJourney 131
lenPos 1794
I =  9434230 68.64620030196275
dfNewJourney 85
lenPos 1224
I =  9258894 68.6713638651233
dfNewJourney 51
lenPos 1239
I =  9147435 68.69652742828384
dfNewJourney 111
lenPos 1762
I =  9473054 68.72169099144439
dfNewJourney 356
lenPos 1771
I =  9296559 68.74685455460494
dfNewJourney 147
lenPos 1482
I =  9209300 68.77201811776547
dfNewJourney 157
lenPos 1563
I =  9568495 68.79718168092602
dfNewJourney 166
lenPos 1843
I =  9543536 68.82234524408656

dfNewJourney 475
lenPos 1863
I =  9536038 68.84750880724711
dfNewJourney 0
lenPos 0
I =  9538476 68.87267237040766
dfNewJourney 119
lenPos 1758
I =  9298284 68.8978359335682
dfNewJourney 132
lenPos 1738
I =  9422536 68.92299949672874
dfNewJourney 85
lenPos 1806
I =  9422548 68.94816305988928
dfNewJourney 130
lenPos 1803
I =  9543548 68.97332662304983
dfNewJourney 134
lenPos 1602
I =  9529346 68.99849018621038
dfNewJourney 249
lenPos 1786
I =  9431317 69.02365374937091
dfNewJourney 105
lenPos 1589
I =  9226011 69.04881731253145
dfNewJourney 143
lenPos 1579
I =  9299719 69.073980875692
dfNewJourney 113
lenPos 1883
I =  9592238 69.09914443885255
dfNewJourney 75
lenPos 1763
I =  9457610 69.12430800201308
dfNewJourney 87
lenPos 1103
I =  9275256 69.14947156517363
dfNewJourney 144
lenPos 1786
I =  9565754 69.17463512833417
dfNewJourney 89
lenPos 1727
I =  9422550 69.19979869149472
dfNewJourney 266
lenPos 1822
I =  9277541 69.22496225465527
dfNewJourney 34
lenPos 1103
I =  8801527 69.2501258178158
dfNewJourney 115
lenPos 1768
I =  9543550 69.27528938097635
dfNewJourney 0
lenPos 0
I =  9622033 69.3004529441369
dfNewJourney 117
lenPos 1464
I =  9509891 69.32561650729744
dfNewJourney 43
lenPos 1254
I =  9032666 69.35078007045797
dfNewJourney 141
lenPos 1671
I =  9259264 69.37594363361852
dfNewJourney 122
lenPos 1846
I =  9333670 69.40110719677907
dfNewJourney 185
lenPos 1850
I =  9592264 69.42627075993961
dfNewJourney 101
lenPos 1837
I =  9522128 69.45143432310014
dfNewJourney 14
lenPos 1390
I =  8805470 69.47659788626069
dfNewJourney 111
lenPos 1701
I =  9488011 69.50176144942124
dfNewJourney 171
lenPos 1126
I =  9255830 69.52692501258178
dfNewJourney 111
lenPos 1863
I =  9592240 69.55208857574232
dfNewJourney 107
lenPos 1738
I =  9581667 69.57725213890286
dfNewJourney 119
lenPos 1806
I =  9581679 69.60241570206341
dfNewJourney 117
lenPos 1802
I =  9461697 69.62757926522396
dfNewJourney 231
lenPos 1736
I =  9251676 69.65274282838449
dfNewJourney 108
lenPos 1781
I =  9583653 69.67790639154504
dfNewJourney 127
lenPos 1827
I =  9420643 69.70306995470558
dfNewJourney 181
lenPos 1619
I =  9509906 69.72823351786613
dfNewJourney 142
lenPos 1738
I =  9540821 69.75339708102666
dfNewJourney 99
lenPos 1823
I =  9470260 69.77856064418721
dfNewJourney 141
lenPos 1715
I =  9288851 69.80372420734776
dfNewJourney 95
lenPos 1397
I =  9313450 69.8288877705083
dfNewJourney 22
lenPos 1450
I =  9284582 69.85405133366885
dfNewJourney 135
lenPos 1785
I =  9484912 69.8792148968294
dfNewJourney 39
lenPos 1371
I =  8717245 69.90437845998994
dfNewJourney 164
lenPos 1778
I =  9536820 69.92954202315047
dfNewJourney 183
lenPos 1799
I =  9288916 69.95470558631102
dfNewJourney 128
lenPos 1399
I =  9290660 69.97986914947157
dfNewJourney 5
lenPos 1280
I =  8413502 70.00503271263212
dfNewJourney 143
lenPos 1847
I =  9577111 70.03019627579266
dfNewJourney 108
lenPos 1735
I =  9580417 70.0553598389532
dfNewJourney 127
lenPos 1898
I =  9552501 70.08052340211374
dfNewJourney 94
lenPos 1668
I =  9532159 70.10568696527429
dfNewJourney 111
lenPos 1669
I =  9282053 70.13085052843483
dfNewJourney 1
lenPos 1172
I =  8508292 70.15601409159537
dfNewJourney 147
lenPos 1659
I =  9037147 70.18117765475591
dfNewJourney 128
lenPos 1789
I =  9565699 70.20634121791646
dfNewJourney 118
lenPos 1830
I =  9583665 70.231504781077
dfNewJourney 96
lenPos 1721
I =  9595008 70.25666834423755
dfNewJourney 238
lenPos 1277
I =  9298820 70.28183190739809
dfNewJourney 98
lenPos 1683
I =  9568196 70.30699547055863
dfNewJourney 0
lenPos 0
I =  9647485 70.33215903371918
dfNewJourney 0
lenPos 0
I =  9611620 70.35732259687973
dfNewJourney 68
lenPos 866
I =  9038749 70.38248616004026
dfNewJourney 111
lenPos 1860
I =  9601833 70.4076497232008
dfNewJourney 130
lenPos 1820
I =  9592276 70.43281328636135
dfNewJourney 118
lenPos 1846
I =  9461685 70.4579768495219
dfNewJourney 108
lenPos 1772
I =  9531636 70.48314041268243
dfNewJourney 0
lenPos 0
I =  9636644 70.50830397584298
dfNewJourney 107
lenPos 1279
I =  9508732 70.53346753900352
dfNewJourney 237
lenPos 1829
I =  9538141 70.55863110216407
dfNewJourney 133
lenPos 1857
I =  9484895 70.5837946653246
dfNewJourney 0
lenPos 0
I =  9622045 70.60895822848515
dfNewJourney 309
lenPos 1766
I =  8914532 70.6341217916457
dfNewJourney 229
lenPos 1812
I =  9014339 70.65928535480624
dfNewJourney 125
lenPos 1833
I =  9521435 70.68444891796678
dfNewJourney 106
lenPos 1725
I =  9473066 70.70961248112732
dfNewJourney 243
lenPos 1801
I =  9552472 70.73477604428787
dfNewJourney 112
lenPos 1785
I =  9577123 70.75993960744842
dfNewJourney 179
lenPos 1841
I =  9592288 70.78510317060895
dfNewJourney 86
lenPos 1688
I =  9459709 70.8102667337695
dfNewJourney 85
lenPos 1619
I =  9488023 70.83543029693004
dfNewJourney 110
lenPos 1661
I =  9524774 70.86059386009059
dfNewJourney 108
lenPos 1501
I =  9110482 70.88575742325112
dfNewJourney 0
lenPos 0
I =  9609914 70.91092098641167
dfNewJourney 103
lenPos 1725
I =  9593414 70.93608454957221
dfNewJourney 136
lenPos 1652
I =  9455703 70.96124811273276
dfNewJourney 110
lenPos 1853
I =  9489900 70.98641167589331
dfNewJourney 123
lenPos 1865
I =  9561930 71.01157523905385
dfNewJourney 71
lenPos 1826
I =  9482873 71.03673880221439
dfNewJourney 133
lenPos 1653
I =  9455820 71.06190236537493
dfNewJourney 120
lenPos 1840
I =  9541306 71.08706592853548
dfNewJourney 102
lenPos 1792
I =  9489209 71.11222949169603
dfNewJourney 85
lenPos 1568
I =  9595010 71.13739305485657
dfNewJourney 107
lenPos 1784
I =  9510682 71.16255661801712
dfNewJourney 148
lenPos 1792
I =  9536832 71.18772018117765
dfNewJourney 87
lenPos 1710
I =  9512484 71.2128837443382
dfNewJourney 113
lenPos 1804
I =  9577044 71.23804730749875
dfNewJourney 0
lenPos 0
I =  9607629 71.2632108706593
dfNewJourney 95
lenPos 1767
I =  9531648 71.28837443381984
dfNewJourney 119
lenPos 1879
I =  9594664 71.31353799698037
dfNewJourney 0
lenPos 0
I =  9636084 71.33870156014092
dfNewJourney 101
lenPos 1695
I =  9601194 71.36386512330147
dfNewJourney 104
lenPos 1730
I =  9532161 71.38902868646201
dfNewJourney 116
lenPos 1756
I =  9459010 71.41419224962254
dfNewJourney 255
lenPos 1762
I =  9564578 71.43935581278309
dfNewJourney 402
lenPos 1870
I =  9598256 71.46451937594364
dfNewJourney 251
lenPos 1828
I =  9566150 71.48968293910418
dfNewJourney 240
lenPos 1708
I =  9566162 71.51484650226472
dfNewJourney 437
lenPos 1773
I =  9536040 71.54001006542526
dfNewJourney 0
lenPos 0
I =  9611644 71.56517362858581
dfNewJourney 209
lenPos 1730
I =  9576789 71.59033719174636
dfNewJourney 174
lenPos 1840
I =  9592290 71.61550075490689
dfNewJourney 0
lenPos 0
I =  9622057 71.64066431806744
dfNewJourney 0
lenPos 0
I =  9611632 71.66582788122798
dfNewJourney 12
lenPos 1183
I =  8619431 71.69099144438853
dfNewJourney 178
lenPos 1801
I =  9538153 71.71615500754906
dfNewJourney 381
lenPos 1878
I =  9598268 71.74131857070961
dfNewJourney 0
lenPos 0
I =  9629926 71.76648213387016
dfNewJourney 87
lenPos 1689
I =  9604380 71.7916456970307
dfNewJourney 79
lenPos 1770
I =  9456939 71.81680926019123
dfNewJourney 316
lenPos 1733
I =  9486958 71.84197282335178
dfNewJourney 97
lenPos 1875
I =  9459060 71.86713638651233
dfNewJourney 433
lenPos 1896
I =  9492000 71.89229994967287
dfNewJourney 403
lenPos 1881
I =  9492050 71.91746351283341
dfNewJourney 91
lenPos 1744
I =  9594872 71.94262707599395
dfNewJourney 0
lenPos 0
I =  9607710 71.9677906391545
dfNewJourney 127
lenPos 1717
I =  9459022 71.99295420231505
dfNewJourney 176
lenPos 1856
I =  9592305 72.01811776547558
dfNewJourney 123
lenPos 1752
I =  9296585 72.04328132863613
dfNewJourney 0
lenPos 0
I =  9611670 72.06844489179667
dfNewJourney 117
lenPos 1714
I =  9596997 72.09360845495722
dfNewJourney 0
lenPos 0
I =  9608867 72.11877201811777
dfNewJourney 135
lenPos 1878
I =  9527855 72.14393558127831
dfNewJourney 111
lenPos 1706
I =  9459034 72.16909914443886
dfNewJourney 0
lenPos 0
I =  9638264 72.19426270759939
dfNewJourney 107
lenPos 1619
I =  9489065 72.21942627075994
dfNewJourney 0
lenPos 0
I =  9611656 72.24458983392049
dfNewJourney 0
lenPos 0
I =  9614062 72.26975339708103
dfNewJourney 122
lenPos 1652
I =  9480150 72.29491696024158
dfNewJourney 0
lenPos 0
I =  9629952 72.32008052340211
dfNewJourney 0
lenPos 0
I =  9629940 72.34524408656266
dfNewJourney 138
lenPos 1789
I =  9447768 72.3704076497232

dfNewJourney 86
lenPos 1815
I =  9589932 72.39557121288375
dfNewJourney 152
lenPos 1826
I =  9537927 72.4207347760443
dfNewJourney 88
lenPos 1793
I =  9505819 72.44589833920483
dfNewJourney 0
lenPos 0
I =  9629938 72.47106190236538
dfNewJourney 0
lenPos 0
I =  9642019 72.49622546552592
dfNewJourney 95
lenPos 1871
I =  9539573 72.52138902868647
dfNewJourney 380
lenPos 1891
I =  9492062 72.546552591847
dfNewJourney 0
lenPos 0
I =  9631383 72.57171615500755
dfNewJourney 0
lenPos 0
I =  9629964 72.5968797181681
dfNewJourney 0
lenPos 0
I =  9607643 72.62204328132864
dfNewJourney 112
lenPos 1823
I =  9592680 72.64720684448918
dfNewJourney 0
lenPos 0
I =  9657442 72.67237040764972
dfNewJourney 91
lenPos 1788
I =  9539561 72.69753397081027
dfNewJourney 103
lenPos 1786
I =  9590711 72.72269753397082
dfNewJourney 125
lenPos 1851
I =  9516258 72.74786109713135
dfNewJourney 0
lenPos 0
I =  9636632 72.7730246602919
dfNewJourney 130
lenPos 1811
I =  9589944 72.79818822345244
dfNewJourney 0
lenPos 0
I =  9614074 72.82335178661299
dfNewJourney 406
lenPos 1886
I =  9492127 72.84851534977352
dfNewJourney 101
lenPos 1767
I =  9489077 72.87367891293407
dfNewJourney 0
lenPos 0
I =  9611668 72.89884247609461
dfNewJourney 1
lenPos 1754
I =  8014758 72.92400603925516
dfNewJourney 127
lenPos 1813
I =  9459072 72.9491696024157
dfNewJourney 134
lenPos 1869
I =  9521447 72.97433316557624
dfNewJourney 0
lenPos 0
I =  9617442 72.99949672873679
dfNewJourney 93
lenPos 1842
I =  9539585 73.02466029189733
dfNewJourney 38
lenPos 532
I =  9426946 73.04982385505787
dfNewJourney 0
lenPos 0
I =  9652911 73.07498741821841
dfNewJourney 0
lenPos 0
I =  9641091 73.10015098137896
dfNewJourney 117
lenPos 1870
I =  9489912 73.1253145445395
dfNewJourney 0
lenPos 0
I =  9642899 73.15047810770004
dfNewJourney 101
lenPos 1638
I =  9489089 73.17564167086059
dfNewJourney 0
lenPos 0
I =  9614086 73.20080523402113
dfNewJourney 86
lenPos 1784
I =  9590723 73.22596879718168
dfNewJourney 0
lenPos 0
I =  9611694 73.25113236034223
dfNewJourney 0
lenPos 0
I =  9648776 73.27629592350277
dfNewJourney 0
lenPos 0
I =  9629548 73.3014594866633
dfNewJourney 400
lenPos 1881
I =  9492139 73.32662304982385
dfNewJourney 0
lenPos 0
I =  9617454 73.3517866129844
dfNewJourney 0
lenPos 0
I =  9607734 73.37695017614494
dfNewJourney 84
lenPos 1665
I =  9505821 73.40211373930549
dfNewJourney 0
lenPos 0
I =  9629550 73.42727730246604
dfNewJourney 79
lenPos 1736
I =  9478729 73.45244086562658
dfNewJourney 0
lenPos 0
I =  9610808 73.47760442878712
dfNewJourney 110
lenPos 1591
I =  9461934 73.50276799194766
dfNewJourney 0
lenPos 0
I =  9644433 73.52793155510821
dfNewJourney 102
lenPos 1854
I =  9539597 73.55309511826876
dfNewJourney 0
lenPos 0
I =  9642904 73.57825868142929
dfNewJourney 153
lenPos 1842
I =  9458016 73.60342224458984
dfNewJourney 0
lenPos 0
I =  9636694 73.62858580775038
dfNewJourney 117
lenPos 1844
I =  9419735 73.65374937091093
dfNewJourney 111
lenPos 1830
I =  9459084 73.67891293407146
dfNewJourney 0
lenPos 0
I =  9650573 73.70407649723201
dfNewJourney 98
lenPos 1525
I =  9489091 73.72924006039256
dfNewJourney 260
lenPos 1832
I =  9568469 73.7544036235531
dfNewJourney 0
lenPos 0
I =  9629562 73.77956718671363
dfNewJourney 0
lenPos 0
I =  9645762 73.80473074987418
dfNewJourney 0
lenPos 0
I =  9638551 73.82989431303473
dfNewJourney 0
lenPos 0
I =  9624067 73.85505787619527
dfNewJourney 0
lenPos 0
I =  9642916 73.88022143935581
dfNewJourney 125
lenPos 1741
I =  9539913 73.90538500251635
dfNewJourney 0
lenPos 0
I =  9629495 73.9305485656769
dfNewJourney 0
lenPos 0
I =  9607722 73.95571212883745
dfNewJourney 97
lenPos 1900
I =  9596260 73.98087569199798
dfNewJourney 142
lenPos 1883
I =  9540833 74.00603925515853
dfNewJourney 0
lenPos 0
I =  9642071 74.03120281831907
dfNewJourney 0
lenPos 0
I =  9633501 74.05636638147962
dfNewJourney 103
lenPos 1868
I =  9592692 74.08152994464015
dfNewJourney 126
lenPos 1722
I =  9597147 74.1066935078007
dfNewJourney 0
lenPos 0
I =  9655913 74.13185707096125
dfNewJourney 174
lenPos 1848
I =  9459096 74.15702063412179
dfNewJourney 0
lenPos 0
I =  9617959 74.18218419728233
dfNewJourney 0
lenPos 0
I =  9629574 74.20734776044287
dfNewJourney 0
lenPos 0
I =  9617571 74.23251132360342
dfNewJourney 0
lenPos 0
I =  9629691 74.25767488676397
dfNewJourney 112
lenPos 1839
I =  9594884 74.2828384499245
dfNewJourney 0
lenPos 0
I =  9658379 74.30800201308504
dfNewJourney 0
lenPos 0
I =  9642928 74.33316557624559
dfNewJourney 0
lenPos 0
I =  9638563 74.35832913940614
dfNewJourney 106
lenPos 1684
I =  9489106 74.38349270256668
dfNewJourney 0
lenPos 0
I =  9667928 74.40865626572723
dfNewJourney 0
lenPos 0
I =  9635755 74.43381982888778
dfNewJourney 0
lenPos 0
I =  9610810 74.45898339204831
dfNewJourney 0
lenPos 0
I =  9661235 74.48414695520886
dfNewJourney 82
lenPos 1875
I =  9595632 74.5093105183694
dfNewJourney 0
lenPos 0
I =  9622069 74.53447408152995
dfNewJourney 0
lenPos 0
I =  9637129 74.5596376446905
dfNewJourney 0
lenPos 0
I =  9607631 74.58480120785104
dfNewJourney 108
lenPos 1868
I =  9596272 74.60996477101158
dfNewJourney 0
lenPos 0
I =  9628532 74.63512833417212
dfNewJourney 0
lenPos 0
I =  9639402 74.66029189733267
dfNewJourney 0
lenPos 0
I =  9667930 74.68545546049322
dfNewJourney 0
lenPos 0
I =  9624079 74.71061902365375
dfNewJourney 127
lenPos 1854
I =  9461702 74.7357825868143
dfNewJourney 111
lenPos 1891
I =  9487469 74.76094614997484
dfNewJourney 0
lenPos 0
I =  9661247 74.78610971313539
dfNewJourney 0
lenPos 0
I =  9629706 74.81127327629592
dfNewJourney 88
lenPos 1786
I =  9602710 74.83643683945647
dfNewJourney 0
lenPos 0
I =  9613965 74.86160040261701
dfNewJourney 113
lenPos 1875
I =  9539925 74.88676396577756
dfNewJourney 0
lenPos 0
I =  9645774 74.9119275289381
dfNewJourney 0
lenPos 0
I =  9645786 74.93709109209864
dfNewJourney 0
lenPos 0
I =  9635767 74.96225465525919
dfNewJourney 134
lenPos 1850
I =  9515917 74.98741821841973
dfNewJourney 0
lenPos 0
I =  9664720 75.01258178158027
dfNewJourney 0
lenPos 0
I =  9648192 75.03774534474081
dfNewJourney 0
lenPos 0
I =  9609639 75.06290890790136
dfNewJourney 0
lenPos 0
I =  9607954 75.0880724710619
dfNewJourney 89
lenPos 1849
I =  9594896 75.11323603422244
dfNewJourney 112
lenPos 1874
I =  9487471 75.13839959738299
dfNewJourney 0
lenPos 0
I =  9667942 75.16356316054353
dfNewJourney 0
lenPos 0
I =  9642930 75.18872672370408
dfNewJourney 246
lenPos 1828
I =  9581423 75.21389028686461
dfNewJourney 121
lenPos 1748
I =  9489118 75.23905385002516
dfNewJourney 0
lenPos 0
I =  9635779 75.2642174131857
dfNewJourney 0
lenPos 0
I =  9629718 75.28938097634625
dfNewJourney 0
lenPos 0
I =  9645798 75.31454453950678
dfNewJourney 88
lenPos 1775
I =  9602722 75.33970810266733
dfNewJourney 0
lenPos 0
I =  9642942 75.36487166582788
dfNewJourney 0
lenPos 0
I =  9672478 75.39003522898842
dfNewJourney 0
lenPos 0
I =  9654555 75.41519879214896
dfNewJourney 220
lenPos 1765
I =  9487483 75.4403623553095
dfNewJourney 0
lenPos 0
I =  9609641 75.46552591847005
dfNewJourney 0
lenPos 0
I =  9657064 75.4906894816306
dfNewJourney 106
lenPos 1770
I =  9570101 75.51585304479114
dfNewJourney 180
lenPos 1892
I =  9581693 75.54101660795169
dfNewJourney 0
lenPos 0
I =  9635781 75.56618017111222
dfNewJourney 0
lenPos 0
I =  9644225 75.59134373427277
dfNewJourney 113
lenPos 1819
I =  9489924 75.61650729743332
dfNewJourney 0
lenPos 0
I =  9656890 75.64167086059386
dfNewJourney 146
lenPos 1719
I =  9536923 75.66683442375441
dfNewJourney 94
lenPos 1689
I =  9476824 75.69199798691496
dfNewJourney 0
lenPos 0
I =  9635808 75.7171615500755
dfNewJourney 0
lenPos 0
I =  9659660 75.74232511323603
dfNewJourney 0
lenPos 0
I =  9674763 75.76748867639658
dfNewJourney 82
lenPos 1764
I =  9595644 75.79265223955713
dfNewJourney 0
lenPos 0
I =  9669653 75.81781580271767
dfNewJourney 0
lenPos 0
I =  9689158 75.84297936587821
dfNewJourney 90
lenPos 1859
I =  9594901 75.86814292903875
dfNewJourney 0
lenPos 0
I =  9617648 75.8933064921993
dfNewJourney 0
lenPos 0
I =  9649225 75.91847005535985
dfNewJourney 0
lenPos 0
I =  9654567 75.94363361852038
dfNewJourney 0
lenPos 0
I =  9669665 75.96879718168093
dfNewJourney 0
lenPos 0
I =  9675494 75.99396074484147
dfNewJourney 0
lenPos 0
I =  9669938 76.01912430800202
dfNewJourney 0
lenPos 0
I =  9659672 76.04428787116255
dfNewJourney 0
lenPos 0
I =  9652014 76.0694514343231
dfNewJourney 0
lenPos 0
I =  9660657 76.09461499748365
dfNewJourney 0
lenPos 0

I =  9654581 76.11977856064419
dfNewJourney 0
lenPos 0
I =  9656022 76.14494212380473
dfNewJourney 0
lenPos 0
I =  9675509 76.17010568696527
dfNewJourney 188
lenPos 1769
I =  9538165 76.19526925012582
dfNewJourney 0
lenPos 0
I =  9674713 76.22043281328637
dfNewJourney 149
lenPos 1421
I =  9509918 76.2455963764469
dfNewJourney 0
lenPos 0
I =  9654579 76.27075993960744
dfNewJourney 0
lenPos 0
I =  9669940 76.29592350276799
dfNewJourney 0
lenPos 0
I =  9689160 76.32108706592854
dfNewJourney 0
lenPos 0
I =  9637076 76.34625062908907
dfNewJourney 0
lenPos 0
I =  9660358 76.37141419224962
dfNewJourney 0
lenPos 0
I =  9635822 76.39657775541016
dfNewJourney 0
lenPos 0
I =  9654775 76.42174131857071
dfNewJourney 0
lenPos 0
I =  9637088 76.44690488173124
dfNewJourney 0
lenPos 0
I =  9635834 76.47206844489179
dfNewJourney 0
lenPos 0
I =  9674775 76.49723200805234
dfNewJourney 108
lenPos 1878
I =  9596258 76.52239557121288
dfNewJourney 110
lenPos 1812
I =  9233973 76.54755913437342
dfNewJourney 0
lenPos 0
I =  9644237 76.57272269753396
dfNewJourney 124
lenPos 1414
I =  9494682 76.59788626069451
dfNewJourney 0
lenPos 0
I =  9611682 76.62304982385506
dfNewJourney 116
lenPos 1786
I =  9257711 76.6482133870156
dfNewJourney 145
lenPos 1752
I =  9270737 76.67337695017615
dfNewJourney 279
lenPos 1774
I =  9063110 76.6985405133367
dfNewJourney 105
lenPos 1583
I =  9397755 76.72370407649723
dfNewJourney 146
lenPos 1579
I =  9396373 76.74886763965777
dfNewJourney 34
lenPos 758
I =  8906602 76.77403120281832
dfNewJourney 65
lenPos 1083
I =  8103420 76.79919476597887
dfNewJourney 1
lenPos 10
I =  9044504 76.82435832913941
dfNewJourney 65
lenPos 1686
I =  9412775 76.84952189229996
dfNewJourney 0
lenPos 0
I =  9669873 76.8746854554605
dfNewJourney 0
lenPos 0
I =  9642083 76.89984901862104
dfNewJourney 152
lenPos 1682
I =  9538177 76.92501258178159
dfNewJourney 0
lenPos 0
I =  9674725 76.95017614494213
dfNewJourney 0
lenPos 0
I =  9682318 76.97533970810267
dfNewJourney 0
lenPos 0
I =  9635846 77.00050327126321
dfNewJourney 0
lenPos 0
I =  9654787 77.02566683442376
dfNewJourney 0
lenPos 0
I =  9669914 77.0508303975843
dfNewJourney 0
lenPos 0
I =  9660360 77.07599396074484
dfNewJourney 85
lenPos 1436
I =  8011304 77.10115752390539
dfNewJourney 9
lenPos 1360
I =  9503574 77.12632108706593
dfNewJourney 0
lenPos 0
I =  9635858 77.15148465022648
dfNewJourney 0
lenPos 0
I =  9682320 77.17664821338701
dfNewJourney 0
lenPos 0
I =  9683336 77.20181177654756
dfNewJourney 0
lenPos 0
I =  9681106 77.2269753397081
dfNewJourney 0
lenPos 0
I =  9665803 77.25213890286865
dfNewJourney 73
lenPos 1547
I =  9539523 77.27730246602918
dfNewJourney 83
lenPos 1240
I =  9251535 77.30246602918973
dfNewJourney 134
lenPos 1708
I =  9447770 77.32762959235028
dfNewJourney 0
lenPos 0
I =  9670937 77.35279315551082
dfNewJourney 0
lenPos 0
I =  9669885 77.37795671867136
dfNewJourney 0
lenPos 0
I =  9681118 77.4031202818319
dfNewJourney 0
lenPos 0
I =  9669926 77.42828384499245
dfNewJourney 0
lenPos 0
I =  9657038 77.453447408153
dfNewJourney 0
lenPos 0
I =  9682332 77.47861097131353
dfNewJourney 111
lenPos 1617
I =  9480162 77.50377453447408
dfNewJourney 96
lenPos 1603
I =  9416408 77.52893809763462
dfNewJourney 0
lenPos 0
I =  9677313 77.55410166079517
dfNewJourney 0
lenPos 0
I =  9688336 77.5792652239557
dfNewJourney 5
lenPos 115
I =  8601812 77.60442878711625
dfNewJourney 0
lenPos 0
I =  9683984 77.6295923502768
dfNewJourney 0
lenPos 0
I =  9681120 77.65475591343734
dfNewJourney 0
lenPos 0
I =  9688348 77.67991947659789
dfNewJourney 0
lenPos 0
I =  9686857 77.70508303975842
dfNewJourney 0
lenPos 0
I =  9653446 77.73024660291897
dfNewJourney 0
lenPos 0
I =  9655975 77.75541016607951
dfNewJourney 0
lenPos 0
I =  9682344 77.78057372924006
dfNewJourney 0
lenPos 0
I =  9656034 77.80573729240061
dfNewJourney 0
lenPos 0
I =  9692832 77.83090085556114
dfNewJourney 0
lenPos 0
I =  9686699 77.85606441872169
dfNewJourney 0
lenPos 0
I =  9670949 77.88122798188223
dfNewJourney 0
lenPos 0
I =  9689134 77.90639154504278
dfNewJourney 0
lenPos 0
I =  9676515 77.93155510820333
dfNewJourney 0
lenPos 0
I =  9686704 77.95671867136387
dfNewJourney 0
lenPos 0
I =  9694464 77.98188223452442
dfNewJourney 0
lenPos 0
I =  9683348 78.00704579768495
dfNewJourney 0
lenPos 0
I =  9682356 78.0322093608455
dfNewJourney 0
lenPos 0
I =  9686869 78.05737292400605
dfNewJourney 0
lenPos 0
I =  9656046 78.08253648716659
dfNewJourney 0
lenPos 0
I =  9685190 78.10770005032713
dfNewJourney 0
lenPos 0
I =  9681390 78.13286361348767
dfNewJourney 0
lenPos 0
I =  9607966 78.15802717664822
dfNewJourney 0
lenPos 0
I =  9682368 78.18319073980877
dfNewJourney 0
lenPos 0
I =  9686871 78.2083543029693
dfNewJourney 0
lenPos 0
I =  9664770 78.23351786612984
dfNewJourney 0
lenPos 0
I =  9686716 78.25868142929039
dfNewJourney 0
lenPos 0
I =  9676527 78.28384499245094
dfNewJourney 0
lenPos 0
I =  9682370 78.30900855561147
dfNewJourney 0
lenPos 0
I =  9683350 78.33417211877202
dfNewJourney 0
lenPos 0
I =  9681405 78.35933568193256
dfNewJourney 0
lenPos 0
I =  9681132 78.38449924509311
dfNewJourney 0
lenPos 0
I =  9685205 78.40966280825364
dfNewJourney 0
lenPos 0
I =  9686883 78.43482637141419
dfNewJourney 0
lenPos 0
I =  9669897 78.45998993457474
dfNewJourney 0
lenPos 0
I =  9617650 78.48515349773528
dfNewJourney 0
lenPos 0
I =  9694476 78.51031706089582
dfNewJourney 0
lenPos 0
I =  9688829 78.53548062405636
dfNewJourney 0
lenPos 0
I =  9655987 78.56064418721691
dfNewJourney 0
lenPos 0
I =  9688386 78.58580775037746
dfNewJourney 0
lenPos 0
I =  9692844 78.61097131353799
dfNewJourney 0
lenPos 0
I =  9696553 78.63613487669853
dfNewJourney 0
lenPos 0
I =  9682459 78.66129843985908
dfNewJourney 0
lenPos 0
I =  9686728 78.68646200301963
dfNewJourney 0
lenPos 0
I =  9697430 78.71162556618016
dfNewJourney 0
lenPos 0
I =  9681144 78.7367891293407
dfNewJourney 0
lenPos 0
I =  9657040 78.76195269250125
dfNewJourney 0
lenPos 0
I =  9682382 78.7871162556618
dfNewJourney 89
lenPos 1582
I =  9266475 78.81227981882235
dfNewJourney 0
lenPos 0
I =  9723007 78.83744338198288
dfNewJourney 0
lenPos 0
I =  9689146 78.86260694514343
dfNewJourney 0
lenPos 0
I =  9682394 78.88777050830397
dfNewJourney 0
lenPos 0
I =  9688374 78.91293407146452
dfNewJourney 0
lenPos 0
I =  9688831 78.93809763462507
dfNewJourney 0
lenPos 0
I =  9690834 78.96326119778561
dfNewJourney 0
lenPos 0
I =  9691723 78.98842476094615
dfNewJourney 0
lenPos 0
I =  9690793 79.01358832410669
dfNewJourney 0
lenPos 0
I =  9686730 79.03875188726724
dfNewJourney 0
lenPos 0
I =  9696761 79.06391545042779
dfNewJourney 0
lenPos 0
I =  9656058 79.08907901358833
dfNewJourney 0
lenPos 0
I =  9664782 79.11424257674888
dfNewJourney 0
lenPos 0
I =  9697612 79.13940613990941
dfNewJourney 0
lenPos 0
I =  9688350 79.16456970306996
dfNewJourney 0
lenPos 0
I =  9682409 79.1897332662305
dfNewJourney 0
lenPos 0
I =  9691735 79.21489682939105
dfNewJourney 0
lenPos 0
I =  9692856 79.24006039255158
dfNewJourney 0
lenPos 0
I =  9690846 79.26522395571213
dfNewJourney 0
lenPos 0
I =  9607174 79.29038751887268
dfNewJourney 0
lenPos 0
I =  9667461 79.31555108203322
dfNewJourney 0
lenPos 0
I =  9697624 79.34071464519376
dfNewJourney 0
lenPos 0
I =  9681845 79.3658782083543
dfNewJourney 0
lenPos 0
I =  9686974 79.39104177151485
dfNewJourney 0
lenPos 0
I =  9696565 79.4162053346754
dfNewJourney 0
lenPos 0
I =  9682461 79.44136889783593
dfNewJourney 0
lenPos 0
I =  9642095 79.46653246099648
dfNewJourney 0
lenPos 0
I =  9696577 79.49169602415702
dfNewJourney 0
lenPos 0
I =  9692129 79.51685958731757
dfNewJourney 0
lenPos 0
I =  9707845 79.5420231504781
dfNewJourney 0
lenPos 0
I =  9696589 79.56718671363865
dfNewJourney 4
lenPos 1093
I =  9198783 79.5923502767992
dfNewJourney 0
lenPos 0
I =  9681156 79.61751383995974
dfNewJourney 0
lenPos 0
I =  9706463 79.64267740312027
dfNewJourney 0
lenPos 0
I =  9683362 79.66784096628082
dfNewJourney 0
lenPos 0
I =  9688362 79.69300452944137
dfNewJourney 0
lenPos 0
I =  9733674 79.71816809260191
dfNewJourney 0
lenPos 0
I =  9690808 79.74333165576245
dfNewJourney 0
lenPos 0
I =  9686754 79.768495218923
dfNewJourney 0
lenPos 0
I =  9697442 79.79365878208354
dfNewJourney 0
lenPos 0
I =  9706475 79.81882234524409
dfNewJourney 0
lenPos 0
I =  9714068 79.84398590840463
dfNewJourney 0
lenPos 0
I =  9683374 79.86914947156517
dfNewJourney 0
lenPos 0
I =  9686742 79.89431303472571
dfNewJourney 58
lenPos 1092

I =  9299721 79.91947659788626
dfNewJourney 0
lenPos 0
I =  9664794 79.9446401610468
dfNewJourney 0
lenPos 0
I =  9690810 79.96980372420734
dfNewJourney 0
lenPos 0
I =  9683386 79.99496728736788
dfNewJourney 0
lenPos 0
I =  9714056 80.02013085052843
dfNewJourney 0
lenPos 0
I =  9714501 80.04529441368898
dfNewJourney 0
lenPos 0
I =  9669902 80.07045797684953
dfNewJourney 0
lenPos 0
I =  9708760 80.09562154001006
dfNewJourney 102
lenPos 1352
I =  9492270 80.1207851031706
dfNewJourney 0
lenPos 0
I =  9610389 80.14594866633115
dfNewJourney 0
lenPos 0
I =  9686766 80.1711122294917
dfNewJourney 0
lenPos 0
I =  9686986 80.19627579265224
dfNewJourney 0
lenPos 0
I =  9676125 80.22143935581279
dfNewJourney 0
lenPos 0
I =  9714513 80.24660291897334
dfNewJourney 0
lenPos 0
I =  9723019 80.27176648213387
dfNewJourney 0
lenPos 0
I =  9711547 80.29693004529442
dfNewJourney 0
lenPos 0
I =  9717761 80.32209360845496
dfNewJourney 0
lenPos 0
I =  9696694 80.34725717161551
dfNewJourney 4
lenPos 71
I =  6329044 80.37242073477604
dfNewJourney 0
lenPos 0
I =  9683398 80.39758429793659
dfNewJourney 0
lenPos 0
I =  9694646 80.42274786109714
dfNewJourney 0
lenPos 0
I =  9707388 80.44791142425768
dfNewJourney 0
lenPos 0
I =  9657052 80.47307498741822
dfNewJourney 0
lenPos 0
I =  9733686 80.49823855057876
dfNewJourney 0
lenPos 0
I =  9694189 80.52340211373931
dfNewJourney 0
lenPos 0
I =  9692131 80.54856567689986
dfNewJourney 0
lenPos 0
I =  9696773 80.57372924006039
dfNewJourney 0
lenPos 0
I =  9702194 80.59889280322093
dfNewJourney 0
lenPos 0
I =  9707390 80.62405636638148
dfNewJourney 0
lenPos 0
I =  9681857 80.64921992954203
dfNewJourney 0
lenPos 0
I =  9706839 80.67438349270256
dfNewJourney 0
lenPos 0
I =  9690614 80.6995470558631
dfNewJourney 0
lenPos 0
I =  9696682 80.72471061902365
dfNewJourney 0
lenPos 0
I =  9705885 80.7498741821842
dfNewJourney 0
lenPos 0
I =  9681168 80.77503774534473
dfNewJourney 0
lenPos 0
I =  9690822 80.80020130850528
dfNewJourney 0
lenPos 0
I =  9692296 80.82536487166583
dfNewJourney 0
lenPos 0
I =  9683403 80.85052843482637
dfNewJourney 0
lenPos 0
I =  9667473 80.87569199798692
dfNewJourney 0
lenPos 0
I =  9607186 80.90085556114745
dfNewJourney 0
lenPos 0
I =  9711559 80.926019124308
dfNewJourney 0
lenPos 0
I =  9692478 80.95118268746855
dfNewJourney 2
lenPos 282
I =  8308795 80.97634625062909
dfNewJourney 2
lenPos 1186
I =  9402536 81.00150981378962
dfNewJourney 0
lenPos 0
I =  9707857 81.02667337695017
dfNewJourney 0
lenPos 0
I =  9704465 81.05183694011072
dfNewJourney 0
lenPos 0
I =  9711456 81.07700050327126
dfNewJourney 0
lenPos 0
I =  9707261 81.1021640664318
dfNewJourney 0
lenPos 0
I =  9692301 81.12732762959234
dfNewJourney 0
lenPos 0
I =  9700342 81.15249119275289
dfNewJourney 0
lenPos 0
I =  9681170 81.17765475591344
dfNewJourney 0
lenPos 0
I =  9697210 81.20281831907398
dfNewJourney 0
lenPos 0
I =  9711561 81.22798188223453
dfNewJourney 0
lenPos 0
I =  9676137 81.25314544539506
dfNewJourney 0
lenPos 0
I =  9725603 81.27830900855561
dfNewJourney 0
lenPos 0
I =  9711573 81.30347257171616
dfNewJourney 0
lenPos 0
I =  9746205 81.3286361348767
dfNewJourney 0
lenPos 0
I =  9707273 81.35379969803725
dfNewJourney 0
lenPos 0
I =  9690626 81.3789632611978
dfNewJourney 0
lenPos 0
I =  9697595 81.40412682435833
dfNewJourney 0
lenPos 0
I =  9708617 81.42929038751888
dfNewJourney 0
lenPos 0
I =  9705897 81.45445395067942
dfNewJourney 0
lenPos 0
I =  9707807 81.47961751383997
dfNewJourney 0
lenPos 0
I =  9692313 81.5047810770005
dfNewJourney 0
lenPos 0
I =  9696711 81.52994464016105
dfNewJourney 0
lenPos 0
I =  9702209 81.5551082033216
dfNewJourney 0
lenPos 0
I =  9696709 81.58027176648214
dfNewJourney 0
lenPos 0
I =  9687942 81.60543532964267
dfNewJourney 0
lenPos 0
I =  9694658 81.63059889280322
dfNewJourney 0
lenPos 0
I =  9719771 81.65576245596377
dfNewJourney 0
lenPos 0
I =  9719745 81.68092601912431
dfNewJourney 0
lenPos 0
I =  9694191 81.70608958228485
dfNewJourney 0
lenPos 0
I =  9719769 81.7312531454454
dfNewJourney 0
lenPos 0
I =  9707819 81.75641670860594
dfNewJourney 0
lenPos 0
I =  9706425 81.78158027176649
dfNewJourney 0
lenPos 0
I =  9683415 81.80674383492702
dfNewJourney 0
lenPos 0
I =  9692143 81.83190739808757
dfNewJourney 0
lenPos 0
I =  9708203 81.85707096124811
dfNewJourney 0
lenPos 0
I =  9719757 81.88223452440866
dfNewJourney 0
lenPos 0
I =  9727534 81.90739808756919
dfNewJourney 0
lenPos 0
I =  9655602 81.93256165072974
dfNewJourney 0
lenPos 0
I =  9733698 81.95772521389028
dfNewJourney 0
lenPos 0
I =  9692325 81.98288877705083
dfNewJourney 0
lenPos 0
I =  9704477 82.00805234021138
dfNewJourney 0
lenPos 0
I =  9697600 82.03321590337191
dfNewJourney 0
lenPos 0
I =  9693056 82.05837946653246
dfNewJourney 0
lenPos 0
I =  9725615 82.083543029693
dfNewJourney 0
lenPos 0
I =  9717773 82.10870659285355
dfNewJourney 0
lenPos 0
I =  9708552 82.13387015601408
dfNewJourney 0
lenPos 0
I =  9692246 82.15903371917463
dfNewJourney 0
lenPos 0
I =  9700469 82.18419728233518
dfNewJourney 0
lenPos 0
I =  9688415 82.20936084549572
dfNewJourney 0
lenPos 0
I =  9726619 82.23452440865626
dfNewJourney 0
lenPos 0
I =  9746229 82.2596879718168
dfNewJourney 0
lenPos 0
I =  9704776 82.28485153497735
dfNewJourney 0
lenPos 0
I =  9692337 82.3100150981379
dfNewJourney 0
lenPos 0
I =  9727560 82.33517866129844
dfNewJourney 0
lenPos 0
I =  9711468 82.36034222445898
dfNewJourney 0
lenPos 0
I =  9732228 82.38550578761952
dfNewJourney 0
lenPos 0
I =  9705902 82.41066935078007
dfNewJourney 0
lenPos 0
I =  9664809 82.43583291394062
dfNewJourney 0
lenPos 0
I =  9701554 82.46099647710116
dfNewJourney 0
lenPos 0
I =  9692258 82.48616004026171
dfNewJourney 0
lenPos 0
I =  9761451 82.51132360342226
dfNewJourney 0
lenPos 0
I =  9706437 82.53648716658279
dfNewJourney 0
lenPos 0
I =  9708215 82.56165072974333
dfNewJourney 0
lenPos 0
I =  9707869 82.58681429290388
dfNewJourney 0
lenPos 0
I =  9708148 82.61197785606443
dfNewJourney 0
lenPos 0
I =  9607198 82.63714141922496
dfNewJourney 0
lenPos 0
I =  9708629 82.6623049823855
dfNewJourney 0
lenPos 0
I =  9667485 82.68746854554605
dfNewJourney 0
lenPos 0
I =  9704441 82.7126321087066
dfNewJourney 0
lenPos 0
I =  9733703 82.73779567186713
dfNewJourney 0
lenPos 0
I =  9712852 82.76295923502768
dfNewJourney 0
lenPos 0
I =  9725627 82.78812279818823
dfNewJourney 0
lenPos 0
I =  9706841 82.81328636134877
dfNewJourney 0
lenPos 0
I =  9683427 82.8384499245093
dfNewJourney 0
lenPos 0
I =  9717785 82.86361348766985
dfNewJourney 0
lenPos 0
I =  9697222 82.8887770508304
dfNewJourney 0
lenPos 0
I =  9727546 82.91394061399095
dfNewJourney 0
lenPos 0
I =  9705914 82.93910417715148
dfNewJourney 0
lenPos 0
I =  9708071 82.96426774031202
dfNewJourney 0
lenPos 0
I =  9692349 82.98943130347257
dfNewJourney 0
lenPos 0
I =  9693812 83.01459486663312
dfNewJourney 0
lenPos 0
I =  9727558 83.03975842979366
dfNewJourney 0
lenPos 0
I =  9737151 83.0649219929542
dfNewJourney 0
lenPos 0
I =  9693068 83.09008555611474
dfNewJourney 0
lenPos 0
I =  9717503 83.11524911927529
dfNewJourney 0
lenPos 0
I =  9708564 83.14041268243584
dfNewJourney 0
lenPos 0
I =  9708227 83.16557624559637
dfNewJourney 0
lenPos 0
I =  9692351 83.19073980875692
dfNewJourney 0
lenPos 0
I =  9697234 83.21590337191746
dfNewJourney 0
lenPos 0
I =  9704453 83.24106693507801
dfNewJourney 0
lenPos 0
I =  9688427 83.26623049823854
dfNewJourney 0
lenPos 0
I =  9708150 83.29139406139909
dfNewJourney 29
lenPos 764
I =  9455791 83.31655762455964
dfNewJourney 0
lenPos 0
I =  9607203 83.34172118772018
dfNewJourney 0
lenPos 0
I =  9700471 83.36688475088071
dfNewJourney 0
lenPos 0
I =  9697636 83.39204831404126
dfNewJourney 0
lenPos 0
I =  9682239 83.41721187720181
dfNewJourney 0
lenPos 0
I =  9694359 83.44237544036235
dfNewJourney 0
lenPos 0
I =  9712292 83.4675390035229
dfNewJourney 0
lenPos 0
I =  9692155 83.49270256668345
dfNewJourney 0
lenPos 0
I =  9725639 83.51786612984398
dfNewJourney 0
lenPos 0
I =  9722613 83.54302969300453
dfNewJourney 0
lenPos 0
I =  9746231 83.56819325616507
dfNewJourney 0
lenPos 0
I =  9701566 83.59335681932562
dfNewJourney 0
lenPos 0
I =  9700213 83.61852038248617
dfNewJourney 0
lenPos 0
I =  9727572 83.64368394564671
dfNewJourney 0
lenPos 0
I =  9692363 83.66884750880725
dfNewJourney 0
lenPos 0
I =  9726487 83.6940110719678
dfNewJourney 0
lenPos 0
I =  9667497 83.71917463512834
dfNewJourney 0
lenPos 0
I =  9773301 83.74433819828889
dfNewJourney 0
lenPos 0
I =  9763332 83.76950176144942
dfNewJourney 0
lenPos 0
I =  9697648 83.79466532460997
dfNewJourney 0
lenPos 0
I =  9723289 83.81982888777051
dfNewJourney 0
lenPos 0
I =  9726580 83.84499245093106
dfNewJourney 0
lenPos 0
I =  9708083 83.87015601409159
dfNewJourney 0
lenPos 0
I =  9722625 83.89531957725214

dfNewJourney 0
lenPos 0
I =  9735579 83.92048314041268
dfNewJourney 0
lenPos 0
I =  9682241 83.94564670357323
dfNewJourney 0
lenPos 0
I =  9692375 83.97081026673376
dfNewJourney 0
lenPos 0
I =  9704788 83.99597382989431
dfNewJourney 0
lenPos 0
I =  9708576 84.02113739305486
dfNewJourney 0
lenPos 0
I =  9712307 84.0463009562154
dfNewJourney 0
lenPos 0
I =  9732230 84.07146451937595
dfNewJourney 0
lenPos 0
I =  9717266 84.09662808253648
dfNewJourney 0
lenPos 0
I =  9708239 84.12179164569703
dfNewJourney 0
lenPos 0
I =  9709776 84.14695520885758
dfNewJourney 0
lenPos 0
I =  9702211 84.17211877201812
dfNewJourney 0
lenPos 0
I =  9697985 84.19728233517866
dfNewJourney 0
lenPos 0
I =  9718741 84.2224458983392
dfNewJourney 0
lenPos 0
I =  9729271 84.24760946149975
dfNewJourney 0
lenPos 0
I =  9700225 84.2727730246603
dfNewJourney 0
lenPos 0
I =  9696242 84.29793658782083
dfNewJourney 0
lenPos 0
I =  9707871 84.32310015098138
dfNewJourney 0
lenPos 0
I =  9732773 84.34826371414192
dfNewJourney 76
lenPos 1204
I =  9528134 84.37342727730247
dfNewJourney 0
lenPos 0
I =  9692387 84.398590840463
dfNewJourney 0
lenPos 0
I =  9727584 84.42375440362355
dfNewJourney 0
lenPos 0
I =  9712319 84.4489179667841
dfNewJourney 0
lenPos 0
I =  9749386 84.47408152994464
dfNewJourney 0
lenPos 0
I =  9666077 84.49924509310517
dfNewJourney 0
lenPos 0
I =  9693070 84.52440865626572
dfNewJourney 0
lenPos 0
I =  9706061 84.54957221942627
dfNewJourney 0
lenPos 0
I =  9712840 84.57473578258681
dfNewJourney 0
lenPos 0
I =  9700483 84.59989934574736
dfNewJourney 0
lenPos 0
I =  9697246 84.62506290890789
dfNewJourney 86
lenPos 1166
I =  9440514 84.65022647206844
dfNewJourney 0
lenPos 0
I =  9718404 84.67539003522899
dfNewJourney 0
lenPos 0
I =  9694361 84.70055359838953
dfNewJourney 0
lenPos 0
I =  9735581 84.72571716155008
dfNewJourney 0
lenPos 0
I =  9718416 84.75088072471063
dfNewJourney 0
lenPos 0
I =  9702223 84.77604428787117
dfNewJourney 0
lenPos 0
I =  9718753 84.8012078510317
dfNewJourney 0
lenPos 0
I =  9732785 84.82637141419225
dfNewJourney 0
lenPos 0
I =  9686637 84.8515349773528
dfNewJourney 0
lenPos 0
I =  9686649 84.87669854051335
dfNewJourney 0
lenPos 0
I =  9708588 84.90186210367388
dfNewJourney 0
lenPos 0
I =  9746059 84.92702566683442
dfNewJourney 0
lenPos 0
I =  9706073 84.95218922999497
dfNewJourney 0
lenPos 0
I =  9683001 84.97735279315552
dfNewJourney 0
lenPos 0
I =  9751406 85.00251635631605
dfNewJourney 0
lenPos 0
I =  9726592 85.0276799194766
dfNewJourney 0
lenPos 0
I =  9735593 85.05284348263714
dfNewJourney 0
lenPos 0
I =  9712321 85.07800704579769
dfNewJourney 0
lenPos 0
I =  9718765 85.10317060895822
dfNewJourney 0
lenPos 0
I =  9732797 85.12833417211877
dfNewJourney 0
lenPos 0
I =  9713844 85.15349773527932
dfNewJourney 0
lenPos 0
I =  9773143 85.17866129843986
dfNewJourney 0
lenPos 0
I =  9726451 85.20382486160041
dfNewJourney 0
lenPos 0
I =  9719692 85.22898842476094
dfNewJourney 0
lenPos 0
I =  9721918 85.25415198792149
dfNewJourney 0
lenPos 0
I =  9718777 85.27931555108204
dfNewJourney 0
lenPos 0
I =  9718428 85.30447911424258
dfNewJourney 0
lenPos 0
I =  9735608 85.32964267740311
dfNewJourney 0
lenPos 0
I =  9725598 85.35480624056366
dfNewJourney 0
lenPos 0
I =  9746255 85.37996980372421
dfNewJourney 0
lenPos 0
I =  9767235 85.40513336688475
dfNewJourney 0
lenPos 0
I =  9741815 85.43029693004529
dfNewJourney 0
lenPos 0
I =  9723291 85.45546049320583
dfNewJourney 0
lenPos 0
I =  9721920 85.48062405636638
dfNewJourney 0
lenPos 0
I =  9712864 85.50578761952693
dfNewJourney 0
lenPos 0
I =  9718789 85.53095118268746
dfNewJourney 0
lenPos 0
I =  9728435 85.556114745848
dfNewJourney 0
lenPos 0
I =  9710488 85.58127830900855
dfNewJourney 0
lenPos 0
I =  9703320 85.6064418721691
dfNewJourney 0
lenPos 0
I =  9683013 85.63160543532963
dfNewJourney 0
lenPos 0
I =  9730933 85.65676899849018
dfNewJourney 0
lenPos 0
I =  9746061 85.68193256165073
dfNewJourney 0
lenPos 0
I =  9746243 85.70709612481127
dfNewJourney 0
lenPos 0
I =  9746073 85.73225968797182
dfNewJourney 0
lenPos 0
I =  9724582 85.75742325113237
dfNewJourney 0
lenPos 0
I =  9713856 85.7825868142929
dfNewJourney 0
lenPos 0
I =  9735610 85.80775037745344
dfNewJourney 0
lenPos 0
I =  9696254 85.83291394061399
dfNewJourney 0
lenPos 0
I =  9709984 85.85807750377454
dfNewJourney 0
lenPos 0
I =  9726475 85.88324106693508
dfNewJourney 0
lenPos 0
I =  9704790 85.90840463009563
dfNewJourney 0
lenPos 0
I =  9719707 85.93356819325616
dfNewJourney 0
lenPos 0
I =  9749398 85.95873175641671
dfNewJourney 0
lenPos 0
I =  9666089 85.98389531957726
dfNewJourney 0
lenPos 0
I =  9710191 86.0090588827378
dfNewJourney 0
lenPos 0
I =  9718430 86.03422244589834
dfNewJourney 0
lenPos 0
I =  9621596 86.05938600905888
dfNewJourney 0
lenPos 0
I =  9732242 86.08454957221943
dfNewJourney 0
lenPos 0
I =  9657806 86.10971313537998
dfNewJourney 0
lenPos 0
I =  9749324 86.13487669854051
dfNewJourney 0
lenPos 0
I =  9693082 86.16004026170106
dfNewJourney 0
lenPos 0
I =  9732802 86.1852038248616
dfNewJourney 0
lenPos 0
I =  9683025 86.21036738802215
dfNewJourney 0
lenPos 0
I =  9753674 86.2355309511827
dfNewJourney 0
lenPos 0
I =  9746267 86.26069451434323
dfNewJourney 0
lenPos 0
I =  9732814 86.28585807750378
dfNewJourney 0
lenPos 0
I =  9722637 86.31102164066432
dfNewJourney 0
lenPos 0
I =  9730945 86.33618520382487
dfNewJourney 0
lenPos 0
I =  9732034 86.3613487669854
dfNewJourney 0
lenPos 0
I =  9722584 86.38651233014595
dfNewJourney 0
lenPos 0
I =  9721906 86.4116758933065
dfNewJourney 0
lenPos 0
I =  9725299 86.43683945646704
dfNewJourney 0
lenPos 0
I =  9712876 86.46200301962757
dfNewJourney 0
lenPos 0
I =  9746176 86.48716658278812
dfNewJourney 0
lenPos 0
I =  9726463 86.51233014594867
dfNewJourney 0
lenPos 0
I =  9724594 86.53749370910921
dfNewJourney 0
lenPos 0
I =  9685463 86.56265727226975
dfNewJourney 0
lenPos 0
I =  9800374 86.58782083543029
dfNewJourney 0
lenPos 0
I =  9697997 86.61298439859084
dfNewJourney 0
lenPos 0
I =  9721891 86.63814796175139
dfNewJourney 0
lenPos 0
I =  9735634 86.66331152491192
dfNewJourney 0
lenPos 0
I =  9753791 86.68847508807247
dfNewJourney 0
lenPos 0
I =  9752797 86.71363865123301
dfNewJourney 0
lenPos 0
I =  9725316 86.73880221439356
dfNewJourney 0
lenPos 0
I =  9719719 86.76396577755409
dfNewJourney 0
lenPos 0
I =  9680073 86.78912934071464
dfNewJourney 0
lenPos 0
I =  9735622 86.81429290387518
dfNewJourney 0
lenPos 0
I =  9718064 86.83945646703573
dfNewJourney 0
lenPos 0
I =  9683037 86.86462003019628
dfNewJourney 0
lenPos 0
I =  9729283 86.88978359335681
dfNewJourney 63
lenPos 1002
I =  9509449 86.91494715651736
dfNewJourney 0
lenPos 0
I =  9726607 86.9401107196779
dfNewJourney 0
lenPos 0
I =  9735646 86.96527428283845
dfNewJourney 0
lenPos 0
I =  9718844 86.990437845999
dfNewJourney 0
lenPos 0
I =  9703332 87.01560140915954
dfNewJourney 0
lenPos 0
I =  9776250 87.04076497232009
dfNewJourney 0
lenPos 0
I =  9724013 87.06592853548062
dfNewJourney 0
lenPos 0
I =  9737515 87.09109209864117
dfNewJourney 0
lenPos 0
I =  9719238 87.11625566180172
dfNewJourney 0
lenPos 0
I =  9737527 87.14141922496226
dfNewJourney 0
lenPos 0
I =  9749336 87.1665827881228
dfNewJourney 0
lenPos 0
I =  9710490 87.19174635128334
dfNewJourney 0
lenPos 0
I =  9718856 87.21690991444389
dfNewJourney 0
lenPos 0
I =  9621601 87.24207347760444
dfNewJourney 0
lenPos 0
I =  9739288 87.26723704076498
dfNewJourney 0
lenPos 0
I =  9683049 87.29240060392551
dfNewJourney 0
lenPos 0
I =  9732254 87.31756416708606
dfNewJourney 0
lenPos 0
I =  9732826 87.34272773024661
dfNewJourney 0
lenPos 0
I =  9747326 87.36789129340715
dfNewJourney 0
lenPos 0
I =  9725304 87.39305485656769
dfNewJourney 0
lenPos 0
I =  9732046 87.41821841972823
dfNewJourney 0
lenPos 0
I =  9717278 87.44338198288878
dfNewJourney 0
lenPos 0
I =  9722596 87.46854554604933
dfNewJourney 0
lenPos 0
I =  9698006 87.49370910920986
dfNewJourney 0
lenPos 0
I =  9718868 87.5188726723704
dfNewJourney 0
lenPos 0
I =  9695834 87.54403623553095
dfNewJourney 0
lenPos 0
I =  9704805 87.5691997986915
dfNewJourney 0
lenPos 0
I =  9731729 87.59436336185203
dfNewJourney 0
lenPos 0
I =  9718076 87.61952692501258
dfNewJourney 0
lenPos 0
I =  9718870 87.64469048817313
dfNewJourney 0
lenPos 0
I =  9717101 87.66985405133367
dfNewJourney 0
lenPos 0
I =  9737101 87.6950176144942
dfNewJourney 0
lenPos 0
I =  9753686 87.72018117765475
dfNewJourney 0
lenPos 0
I =  9724075 87.7453447408153
dfNewJourney 0
lenPos 0
I =  9737747 87.77050830397584
dfNewJourney 0
lenPos 0
I =  9724025 87.79567186713638
dfNewJourney 0
lenPos 0
I =  9709788 87.82083543029692
dfNewJourney 0
lenPos 0
I =  9734408 87.84599899345747
dfNewJourney 0
lenPos 0
I =  9779795 87.87116255661802
dfNewJourney 0
lenPos 0
I =  9760495 87.89632611977855
dfNewJourney 0
lenPos 0
I =  9752084 87.9214896829391
dfNewJourney 0
lenPos 0
I =  9768734 87.94665324609964
dfNewJourney 0
lenPos 0
I =  9683051 87.97181680926019
dfNewJourney 0
lenPos 0

I =  9718882 87.99698037242074
dfNewJourney 0
lenPos 0
I =  9719721 88.02214393558128
dfNewJourney 0
lenPos 0
I =  9728411 88.04730749874182
dfNewJourney 0
lenPos 0
I =  9732979 88.07247106190236
dfNewJourney 0
lenPos 0
I =  9718791 88.09763462506291
dfNewJourney 0
lenPos 0
I =  9747338 88.12279818822346
dfNewJourney 0
lenPos 0
I =  9722649 88.147961751384
dfNewJourney 0
lenPos 0
I =  9685475 88.17312531454455
dfNewJourney 0
lenPos 0
I =  9749348 88.19828887770508
dfNewJourney 0
lenPos 0
I =  9645401 88.22345244086563
dfNewJourney 0
lenPos 0
I =  9726621 88.24861600402618
dfNewJourney 0
lenPos 0
I =  9761944 88.27377956718672
dfNewJourney 0
lenPos 0
I =  9746188 88.29894313034727
dfNewJourney 0
lenPos 0
I =  9718088 88.3241066935078
dfNewJourney 0
lenPos 0
I =  9724611 88.34927025666835
dfNewJourney 0
lenPos 0
I =  9740419 88.3744338198289
dfNewJourney 0
lenPos 0
I =  9724087 88.39959738298944
dfNewJourney 0
lenPos 0
I =  9717113 88.42476094614997
dfNewJourney 0
lenPos 0
I =  9737759 88.44992450931052
dfNewJourney 0
lenPos 0
I =  9718806 88.47508807247107
dfNewJourney 0
lenPos 0
I =  9724609 88.50025163563161
dfNewJourney 0
lenPos 0
I =  9718818 88.52541519879215
dfNewJourney 0
lenPos 0
I =  9731731 88.55057876195269
dfNewJourney 0
lenPos 0
I =  9745902 88.57574232511324
dfNewJourney 0
lenPos 0
I =  9645413 88.60090588827379
dfNewJourney 0
lenPos 0
I =  9717280 88.62606945143432
dfNewJourney 0
lenPos 0
I =  9729245 88.65123301459487
dfNewJourney 0
lenPos 0
I =  9747364 88.67639657775541
dfNewJourney 0
lenPos 0
I =  9698018 88.70156014091596
dfNewJourney 0
lenPos 0
I =  9746279 88.72672370407649
dfNewJourney 0
lenPos 0
I =  9697909 88.75188726723704
dfNewJourney 0
lenPos 0
I =  9768746 88.77705083039758
dfNewJourney 0
lenPos 0
I =  9761956 88.80221439355813
dfNewJourney 0
lenPos 0
I =  9722766 88.82737795671866
dfNewJourney 0
lenPos 0
I =  9680085 88.85254151987921
dfNewJourney 0
lenPos 0
I =  9719240 88.87770508303976
dfNewJourney 0
lenPos 0
I =  9749362 88.9028686462003
dfNewJourney 0
lenPos 0
I =  9693018 88.92803220936084
dfNewJourney 0
lenPos 0
I =  9753698 88.95319577252138
dfNewJourney 0
lenPos 0
I =  9759850 88.97835933568193
dfNewJourney 0
lenPos 0
I =  9752096 89.00352289884248
dfNewJourney 0
lenPos 0
I =  9760213 89.02868646200301
dfNewJourney 0
lenPos 0
I =  9724336 89.05385002516356
dfNewJourney 0
lenPos 0
I =  9718090 89.0790135883241
dfNewJourney 0
lenPos 0
I =  9732266 89.10417715148465
dfNewJourney 0
lenPos 0
I =  9731743 89.1293407146452
dfNewJourney 0
lenPos 0
I =  9749350 89.15450427780573
dfNewJourney 0
lenPos 0
I =  9724532 89.17966784096627
dfNewJourney 0
lenPos 0
I =  9732682 89.20483140412682
dfNewJourney 0
lenPos 0
I =  9680097 89.22999496728737
dfNewJourney 0
lenPos 0
I =  9752010 89.25515853044791
dfNewJourney 0
lenPos 0
I =  9759886 89.28032209360846
dfNewJourney 0
lenPos 0
I =  9760500 89.30548565676901
dfNewJourney 0
lenPos 0
I =  9717125 89.33064921992954
dfNewJourney 0
lenPos 0
I =  9731755 89.35581278309009
dfNewJourney 0
lenPos 0
I =  9755725 89.38097634625063
dfNewJourney 0
lenPos 0
I =  9747340 89.40613990941118
dfNewJourney 0
lenPos 0
I =  9745926 89.43130347257173
dfNewJourney 0
lenPos 0
I =  9718820 89.45646703573226
dfNewJourney 0
lenPos 0
I =  9693824 89.4816305988928
dfNewJourney 0
lenPos 0
I =  9710206 89.50679416205335
dfNewJourney 0
lenPos 0
I =  9724348 89.5319577252139
dfNewJourney 0
lenPos 0
I =  9760225 89.55712128837443
dfNewJourney 0
lenPos 0
I =  9683063 89.58228485153498
dfNewJourney 0
lenPos 0
I =  9724673 89.60744841469553
dfNewJourney 0
lenPos 0
I =  9685891 89.63261197785607
dfNewJourney 0
lenPos 0
I =  9717137 89.6577755410166
dfNewJourney 0
lenPos 0
I =  9732278 89.68293910417715
dfNewJourney 0
lenPos 0
I =  9724623 89.7081026673377
dfNewJourney 0
lenPos 0
I =  9755050 89.73326623049824
dfNewJourney 0
lenPos 0
I =  9749374 89.75842979365878
dfNewJourney 0
lenPos 0
I =  9718832 89.78359335681932
dfNewJourney 0
lenPos 0
I =  9753703 89.80875691997987
dfNewJourney 0
lenPos 0
I =  9779587 89.83392048314042
dfNewJourney 0
lenPos 0
I =  9717292 89.85908404630095
dfNewJourney 0
lenPos 0
I =  9752022 89.8842476094615
dfNewJourney 0
lenPos 0
I =  9732694 89.90941117262204
dfNewJourney 0
lenPos 0
I =  9718894 89.93457473578259
dfNewJourney 0
lenPos 0
I =  9722170 89.95973829894312
dfNewJourney 0
lenPos 0
I =  9746190 89.98490186210367
dfNewJourney 0
lenPos 0
I =  9740574 90.01006542526422
dfNewJourney 0
lenPos 0
I =  9728423 90.03522898842476
dfNewJourney 0
lenPos 0
I =  9747376 90.0603925515853
dfNewJourney 0
lenPos 0
I =  9747352 90.08555611474584
dfNewJourney 0
lenPos 0
I =  9749532 90.11071967790639
dfNewJourney 0
lenPos 0
I =  9752101 90.13588324106694
dfNewJourney 0
lenPos 0
I =  9792008 90.16104680422747
dfNewJourney 0
lenPos 0
I =  9732929 90.18621036738801
dfNewJourney 0
lenPos 0
I =  9749441 90.21137393054856
dfNewJourney 0
lenPos 0
I =  9724544 90.23653749370911
dfNewJourney 0
lenPos 0
I =  9737010 90.26170105686965
dfNewJourney 0
lenPos 0
I =  9767338 90.2868646200302
dfNewJourney 0
lenPos 0
I =  9683075 90.31202818319073
dfNewJourney 0
lenPos 0
I =  9747089 90.33719174635128
dfNewJourney 0
lenPos 0
I =  9708772 90.36235530951183
dfNewJourney 0
lenPos 0
I =  9728239 90.38751887267237
dfNewJourney 0
lenPos 0
I =  9752034 90.41268243583292
dfNewJourney 0
lenPos 0
I =  9773040 90.43784599899347
dfNewJourney 0
lenPos 0
I =  9731781 90.46300956215401
dfNewJourney 0
lenPos 0
I =  9724556 90.48817312531455
dfNewJourney 0
lenPos 0
I =  9724685 90.51333668847509
dfNewJourney 0
lenPos 0
I =  9766190 90.53850025163564
dfNewJourney 0
lenPos 0
I =  9737022 90.56366381479619
dfNewJourney 0
lenPos 0
I =  9773739 90.58882737795672
dfNewJourney 0
lenPos 0
I =  9732931 90.61399094111727
dfNewJourney 0
lenPos 0
I =  9749544 90.63915450427781
dfNewJourney 0
lenPos 0
I =  9619531 90.66431806743836
dfNewJourney 0
lenPos 0
I =  9757254 90.68948163059889
dfNewJourney 0
lenPos 0
I =  9719252 90.71464519375944
dfNewJourney 0
lenPos 0
I =  9719886 90.73980875691998
dfNewJourney 0
lenPos 0
I =  9790361 90.76497232008053
dfNewJourney 0
lenPos 0
I =  9759915 90.79013588324106
dfNewJourney 0
lenPos 0
I =  9737371 90.81529944640161
dfNewJourney 0
lenPos 0
I =  9693020 90.84046300956216
dfNewJourney 0
lenPos 0
I =  9724726 90.8656265727227
dfNewJourney 0
lenPos 0
I =  9773052 90.89079013588324
dfNewJourney 0
lenPos 0
I =  9779939 90.91595369904378
dfNewJourney 0
lenPos 0
I =  9719264 90.94111726220433
dfNewJourney 0
lenPos 0
I =  9776755 90.96628082536488
dfNewJourney 0
lenPos 0
I =  9619543 90.99144438852541
dfNewJourney 0
lenPos 0
I =  9772010 91.01660795168596
dfNewJourney 0
lenPos 0
I =  9779941 91.0417715148465
dfNewJourney 0
lenPos 0
I =  9740586 91.06693507800705
dfNewJourney 0
lenPos 0
I =  9680102 91.09209864116758
dfNewJourney 0
lenPos 0
I =  9778674 91.11726220432813
dfNewJourney 0
lenPos 0
I =  9724697 91.14242576748867
dfNewJourney 0
lenPos 0
I =  9755062 91.16758933064922
dfNewJourney 0
lenPos 0
I =  9730335 91.19275289380975
dfNewJourney 0
lenPos 0
I =  9759898 91.2179164569703
dfNewJourney 0
lenPos 0
I =  9812743 91.24308002013085
dfNewJourney 0
lenPos 0
I =  9730880 91.2682435832914
dfNewJourney 0
lenPos 0
I =  9766205 91.29340714645193
dfNewJourney 0
lenPos 0
I =  9724570 91.31857070961247
dfNewJourney 0
lenPos 0
I =  9792010 91.34373427277302
dfNewJourney 0
lenPos 0
I =  9786231 91.36889783593357
dfNewJourney 0
lenPos 0
I =  9683087 91.39406139909411
dfNewJourney 0
lenPos 0
I =  9785689 91.41922496225465
dfNewJourney 0
lenPos 0
I =  9783411 91.44438852541519
dfNewJourney 0
lenPos 0
I =  9767340 91.46955208857574
dfNewJourney 0
lenPos 0
I =  9722182 91.49471565173629
dfNewJourney 0
lenPos 0
I =  9724350 91.51987921489683
dfNewJourney 0
lenPos 0
I =  9776470 91.54504277805738
dfNewJourney 0
lenPos 0
I =  9759927 91.57020634121793
dfNewJourney 0
lenPos 0
I =  9724702 91.59536990437846
dfNewJourney 0
lenPos 0
I =  9790373 91.620533467539
dfNewJourney 0
lenPos 0
I =  9757967 91.64569703069955
dfNewJourney 0
lenPos 0
I =  9732709 91.6708605938601
dfNewJourney 0
lenPos 0
I =  9743825 91.69602415702064
dfNewJourney 0
lenPos 0
I =  9772034 91.72118772018118
dfNewJourney 0
lenPos 0
I =  9752046 91.74635128334172
dfNewJourney 0

lenPos 0
I =  9759795 91.77151484650227
dfNewJourney 0
lenPos 0
I =  9785691 91.79667840966282
dfNewJourney 0
lenPos 0
I =  9742211 91.82184197282335
dfNewJourney 0
lenPos 0
I =  9812755 91.8470055359839
dfNewJourney 0
lenPos 0
I =  9776767 91.87216909914444
dfNewJourney 0
lenPos 0
I =  9772022 91.89733266230499
dfNewJourney 0
lenPos 0
I =  9774343 91.92249622546552
dfNewJourney 0
lenPos 0
I =  9773741 91.94765978862607
dfNewJourney 0
lenPos 0
I =  9776236 91.97282335178662
dfNewJourney 0
lenPos 0
I =  9729221 91.99798691494716
dfNewJourney 0
lenPos 0
I =  9816191 92.0231504781077
dfNewJourney 0
lenPos 0
I =  9777931 92.04831404126824
dfNewJourney 0
lenPos 0
I =  9790787 92.07347760442879
dfNewJourney 0
lenPos 0
I =  9747106 92.09864116758934
dfNewJourney 0
lenPos 0
I =  9749556 92.12380473074987
dfNewJourney 0
lenPos 0
I =  9780251 92.14896829391041
dfNewJourney 0
lenPos 0
I =  9772046 92.17413185707096
dfNewJourney 0
lenPos 0
I =  9739264 92.19929542023151
dfNewJourney 0
lenPos 0
I =  9786243 92.22445898339204
dfNewJourney 0
lenPos 0
I =  9731793 92.24962254655259
dfNewJourney 0
lenPos 0
I =  9802152 92.27478610971313
dfNewJourney 0
lenPos 0
I =  9759800 92.29994967287368
dfNewJourney 0
lenPos 0
I =  9747584 92.32511323603421
dfNewJourney 0
lenPos 0
I =  9797383 92.35027679919476
dfNewJourney 0
lenPos 0
I =  9795103 92.3754403623553
dfNewJourney 0
lenPos 0
I =  9793272 92.40060392551585
dfNewJourney 0
lenPos 0
I =  9737383 92.42576748867639
dfNewJourney 0
lenPos 0
I =  9744893 92.45093105183693
dfNewJourney 0
lenPos 0
I =  9724714 92.47609461499748
dfNewJourney 0
lenPos 0
I =  9794719 92.50125817815803
dfNewJourney 0
lenPos 0
I =  9797723 92.52642174131857
dfNewJourney 0
lenPos 0
I =  9778727 92.55158530447912
dfNewJourney 0
lenPos 0
I =  9763851 92.57674886763965
dfNewJourney 0
lenPos 0
I =  9772058 92.6019124308002
dfNewJourney 0
lenPos 0
I =  9744908 92.62707599396074
dfNewJourney 0
lenPos 0
I =  9740421 92.65223955712129
dfNewJourney 0
lenPos 0
I =  9759939 92.67740312028184
dfNewJourney 0
lenPos 0
I =  9783423 92.70256668344238
dfNewJourney 0
lenPos 0
I =  9737096 92.72773024660293
dfNewJourney 0
lenPos 0
I =  9788394 92.75289380976346
dfNewJourney 0
lenPos 0
I =  9785706 92.77805737292401
dfNewJourney 0
lenPos 0
I =  9766229 92.80322093608456
dfNewJourney 0
lenPos 0
I =  9795115 92.8283844992451
dfNewJourney 0
lenPos 0
I =  9777943 92.85354806240564
dfNewJourney 0
lenPos 0
I =  9801079 92.87871162556618
dfNewJourney 0
lenPos 0
I =  9729233 92.90387518872673
dfNewJourney 0
lenPos 0
I =  9779977 92.92903875188728
dfNewJourney 0
lenPos 0
I =  9785718 92.95420231504781
dfNewJourney 0
lenPos 0
I =  9793375 92.97936587820836
dfNewJourney 0
lenPos 0
I =  9815850 93.0045294413689
dfNewJourney 0
lenPos 0
I =  9680114 93.02969300452945
dfNewJourney 0
lenPos 0
I =  9765017 93.05485656768998
dfNewJourney 0
lenPos 0
I =  9747118 93.08002013085053
dfNewJourney 0
lenPos 0
I =  9790799 93.10518369401107
dfNewJourney 0
lenPos 0
I =  9737395 93.13034725717162
dfNewJourney 0
lenPos 0
I =  9766217 93.15551082033215
dfNewJourney 0
lenPos 0
I =  9779953 93.1806743834927
dfNewJourney 0
lenPos 0
I =  9799862 93.20583794665325
dfNewJourney 0
lenPos 0
I =  9784611 93.2310015098138
dfNewJourney 0
lenPos 0
I =  9780263 93.25616507297433
dfNewJourney 0
lenPos 0
I =  9785720 93.28132863613487
dfNewJourney 0
lenPos 0
I =  9779965 93.30649219929542
dfNewJourney 0
lenPos 0
I =  9749611 93.33165576245597
dfNewJourney 0
lenPos 0
I =  9773753 93.3568193256165
dfNewJourney 0
lenPos 0
I =  9797735 93.38198288877705
dfNewJourney 0
lenPos 0
I =  9798868 93.40714645193759
dfNewJourney 0
lenPos 0
I =  9743837 93.43231001509814
dfNewJourney 0
lenPos 0
I =  9724568 93.45747357825867
dfNewJourney 0
lenPos 0
I =  9793387 93.48263714141922
dfNewJourney 0
lenPos 0
I =  9794721 93.50780070457976
dfNewJourney 0
lenPos 0
I =  9797254 93.53296426774031
dfNewJourney 0
lenPos 0
I =  9773923 93.55812783090084
dfNewJourney 0
lenPos 0
I =  9765029 93.58329139406139
dfNewJourney 0
lenPos 0
I =  9739276 93.60845495722194
dfNewJourney 0
lenPos 0
I =  9810501 93.63361852038248
dfNewJourney 0
lenPos 0
I =  9782613 93.65878208354303
dfNewJourney 0
lenPos 0
I =  9788435 93.68394564670356
dfNewJourney 29
lenPos 597
I =  9336464 93.70910920986411
dfNewJourney 0
lenPos 0
I =  9786138 93.73427277302466
dfNewJourney 0
lenPos 0
I =  9779989 93.7594363361852
dfNewJourney 0
lenPos 0
I =  9797981 93.78459989934575
dfNewJourney 0
lenPos 0
I =  9797395 93.8097634625063
dfNewJourney 0
lenPos 0
I =  9794410 93.83492702566684
dfNewJourney 0
lenPos 0
I =  9793284 93.86009058882738
dfNewJourney 0
lenPos 0
I =  9796731 93.88525415198792
dfNewJourney 0
lenPos 0
I =  9730878 93.91041771514847
dfNewJourney 0
lenPos 0
I =  9790995 93.93558127830902
dfNewJourney 0
lenPos 0
I =  9797747 93.96074484146956
dfNewJourney 0
lenPos 0
I =  9764491 93.9859084046301
dfNewJourney 0
lenPos 0
I =  9801524 94.01107196779064
dfNewJourney 0
lenPos 0
I =  9740469 94.03623553095119
dfNewJourney 0
lenPos 0
I =  9749453 94.06139909411174
dfNewJourney 0
lenPos 0
I =  9785732 94.08656265727227
dfNewJourney 0
lenPos 0
I =  9799874 94.11172622043281
dfNewJourney 0
lenPos 0
I =  9801081 94.13688978359336
dfNewJourney 0
lenPos 0
I =  9764506 94.16205334675391
dfNewJourney 0
lenPos 0
I =  9772060 94.18721690991444
dfNewJourney 0
lenPos 0
I =  9794422 94.21238047307499
dfNewJourney 0
lenPos 0
I =  9796743 94.23754403623553
dfNewJourney 0
lenPos 0
I =  9794159 94.26270759939608
dfNewJourney 0
lenPos 0
I =  9763863 94.28787116255661
dfNewJourney 0
lenPos 0
I =  9737400 94.31303472571716
dfNewJourney 0
lenPos 0
I =  9791315 94.3381982888777
dfNewJourney 0
lenPos 0
I =  9760550 94.36336185203825
dfNewJourney 0
lenPos 0
I =  9797266 94.38852541519879
dfNewJourney 0
lenPos 0
I =  9797759 94.41368897835933
dfNewJourney 0
lenPos 0
I =  9787168 94.43885254151988
dfNewJourney 0
lenPos 0
I =  9783368 94.46401610468043
dfNewJourney 0
lenPos 0
I =  9749025 94.48917966784096
dfNewJourney 0
lenPos 0
I =  9783007 94.5143432310015
dfNewJourney 0
lenPos 0
I =  9760548 94.53950679416205
dfNewJourney 0
lenPos 0
I =  9720081 94.5646703573226
dfNewJourney 0
lenPos 0
I =  9791004 94.58983392048313
dfNewJourney 0
lenPos 0
I =  9804124 94.61499748364368
dfNewJourney 0
lenPos 0
I =  9796901 94.64016104680422
dfNewJourney 0
lenPos 0
I =  9798870 94.66532460996477
dfNewJourney 0
lenPos 0
I =  9794434 94.69048817312532
dfNewJourney 0
lenPos 0
I =  9824473 94.71565173628585
dfNewJourney 0
lenPos 0
I =  9778296 94.7408152994464
dfNewJourney 0
lenPos 0
I =  9783899 94.76597886260694
dfNewJourney 0
lenPos 0
I =  9815458 94.79114242576749
dfNewJourney 0
lenPos 0
I =  9810214 94.81630598892804
dfNewJourney 0
lenPos 0
I =  9740471 94.84146955208857
dfNewJourney 0
lenPos 0
I =  9801093 94.86663311524912
dfNewJourney 0
lenPos 0
I =  9747120 94.89179667840966
dfNewJourney 0
lenPos 0
I =  9757979 94.91696024157021
dfNewJourney 0
lenPos 0
I =  9810226 94.94212380473076
dfNewJourney 0
lenPos 0
I =  9791157 94.9672873678913
dfNewJourney 0
lenPos 0
I =  9721504 94.99245093105185
dfNewJourney 0
lenPos 0
I =  9808314 95.01761449421238
dfNewJourney 0
lenPos 0
I =  9792199 95.04277805737293
dfNewJourney 0
lenPos 0
I =  9797400 95.06794162053347
dfNewJourney 0
lenPos 0
I =  9794446 95.09310518369402
dfNewJourney 0
lenPos 0
I =  9760574 95.11826874685455
dfNewJourney 0
lenPos 0
I =  9821299 95.1434323100151
dfNewJourney 0
lenPos 0
I =  9787912 95.16859587317565
dfNewJourney 0
lenPos 0
I =  9783370 95.1937594363362
dfNewJourney 0
lenPos 0
I =  9795048 95.21892299949673
dfNewJourney 0
lenPos 0
I =  9773765 95.24408656265727
dfNewJourney 0
lenPos 0
I =  9728241 95.26925012581782
dfNewJourney 0
lenPos 0
I =  9810513 95.29441368897837
dfNewJourney 0
lenPos 0
I =  9797993 95.3195772521389
dfNewJourney 0
lenPos 0
I =  9792204 95.34474081529945
dfNewJourney 0
lenPos 0
I =  9796925 95.36990437845999
dfNewJourney 0
lenPos 0
I =  9808326 95.39506794162054
dfNewJourney 0
lenPos 0
I =  9788447 95.42023150478107
dfNewJourney 0
lenPos 0
I =  9821691 95.44539506794162
dfNewJourney 0
lenPos 0
I =  9798935 95.47055863110216
dfNewJourney 0
lenPos 0
I =  9747132 95.49572219426271
dfNewJourney 0
lenPos 0
I =  9798002 95.52088575742324
dfNewJourney 0
lenPos 0
I =  9752395 95.54604932058379
dfNewJourney 0
lenPos 0
I =  9792840 95.57121288374434
dfNewJourney 0
lenPos 0
I =  9760562 95.59637644690488
dfNewJourney 0
lenPos 0
I =  9820544 95.62154001006542
dfNewJourney 0
lenPos 0
I =  9795050 95.64670357322596
dfNewJourney 0
lenPos 0
I =  9781279 95.67186713638651
dfNewJourney 0
lenPos 0
I =  9798088 95.69703069954706
dfNewJourney 0
lenPos 0
I =  9798959 95.72219426270759
dfNewJourney 0
lenPos 0
I =  9814155 95.74735782586814
dfNewJourney 37
lenPos 334
I =  9547673 95.77252138902868

dfNewJourney 0
lenPos 0
I =  9783916 95.79768495218923
dfNewJourney 0
lenPos 0
I =  9774563 95.82284851534978
dfNewJourney 0
lenPos 0
I =  9786140 95.84801207851031
dfNewJourney 0
lenPos 0
I =  9699866 95.87317564167085
dfNewJourney 0
lenPos 0
I =  9821706 95.8983392048314
dfNewJourney 0
lenPos 0
I =  9796913 95.92350276799195
dfNewJourney 0
lenPos 0
I =  9798961 95.94866633115248
dfNewJourney 0
lenPos 0
I =  9800180 95.97382989431303
dfNewJourney 0
lenPos 0
I =  9787170 95.99899345747357
dfNewJourney 0
lenPos 0
I =  9756274 96.02415702063412
dfNewJourney 0
lenPos 0
I =  9791169 96.04932058379467
dfNewJourney 0
lenPos 0
I =  9827944 96.07448414695521
dfNewJourney 0
lenPos 0
I =  9814143 96.09964771011576
dfNewJourney 0
lenPos 0
I =  9820295 96.1248112732763
dfNewJourney 0
lenPos 0
I =  9783019 96.14997483643684
dfNewJourney 0
lenPos 0
I =  9821847 96.17513839959739
dfNewJourney 0
lenPos 0
I =  9792852 96.20030196275793
dfNewJourney 0
lenPos 0
I =  9820283 96.22546552591848
dfNewJourney 0
lenPos 0
I =  9798973 96.25062908907901
dfNewJourney 0
lenPos 0
I =  9783928 96.27579265223956
dfNewJourney 0
lenPos 0
I =  9814167 96.3009562154001
dfNewJourney 0
lenPos 0
I =  9798076 96.32611977856065
dfNewJourney 0
lenPos 0
I =  9796937 96.35128334172119
dfNewJourney 0
lenPos 0
I =  9783382 96.37644690488173
dfNewJourney 0
lenPos 0
I =  9827566 96.40161046804228
dfNewJourney 0
lenPos 0
I =  9788473 96.42677403120283
dfNewJourney 0
lenPos 0
I =  9787924 96.45193759436336
dfNewJourney 0
lenPos 0
I =  9790610 96.4771011575239
dfNewJourney 0
lenPos 0
I =  9777412 96.50226472068445
dfNewJourney 0
lenPos 0
I =  9832547 96.527428283845
dfNewJourney 0
lenPos 0
I =  9800192 96.55259184700553
dfNewJourney 0
lenPos 0
I =  9792864 96.57775541016608
dfNewJourney 0
lenPos 0
I =  9787182 96.60291897332662
dfNewJourney 0
lenPos 0
I =  9732395 96.62808253648717
dfNewJourney 0
lenPos 0
I =  9828144 96.6532460996477
dfNewJourney 0
lenPos 0
I =  9829409 96.67840966280825
dfNewJourney 0
lenPos 0
I =  9793997 96.7035732259688
dfNewJourney 0
lenPos 0
I =  9786152 96.72873678912934
dfNewJourney 0
lenPos 0
I =  9829899 96.75390035228988
dfNewJourney 0
lenPos 0
I =  9788564 96.77906391545042
dfNewJourney 0
lenPos 0
I =  9826720 96.80422747861097
dfNewJourney 0
lenPos 0
I =  9794836 96.82939104177152
dfNewJourney 0
lenPos 0
I =  9783631 96.85455460493206
dfNewJourney 0
lenPos 0
I =  9817470 96.8797181680926
dfNewJourney 0
lenPos 0
I =  9829904 96.90488173125314
dfNewJourney 0
lenPos 0
I =  9832559 96.93004529441369
dfNewJourney 0
lenPos 0
I =  9789257 96.95520885757423
dfNewJourney 0
lenPos 0
I =  9831309 96.98037242073477
dfNewJourney 0
lenPos 0
I =  9774575 97.00553598389531
dfNewJourney 0
lenPos 0
I =  9783394 97.03069954705586
dfNewJourney 0
lenPos 0
I =  9820300 97.05586311021641
dfNewJourney 0
lenPos 0
I =  9828156 97.08102667337695
dfNewJourney 0
lenPos 0
I =  9831191 97.10619023653749
dfNewJourney 0
lenPos 0
I =  9808156 97.13135379969803
dfNewJourney 0
lenPos 0
I =  9802164 97.15651736285858
dfNewJourney 0
lenPos 0
I =  9791171 97.18168092601913
dfNewJourney 30
lenPos 217
I =  9547685 97.20684448917967
dfNewJourney 0
lenPos 0
I =  9815604 97.23200805234022
dfNewJourney 0
lenPos 0
I =  9783992 97.25717161550077
dfNewJourney 0
lenPos 0
I =  9781281 97.2823351786613
dfNewJourney 0
lenPos 0
I =  9827578 97.30749874182185
dfNewJourney 0
lenPos 0
I =  9814179 97.33266230498239
dfNewJourney 0
lenPos 0
I =  9791860 97.35782586814294
dfNewJourney 0
lenPos 0
I =  9826574 97.38298943130347
dfNewJourney 0
lenPos 0
I =  9831294 97.40815299446402
dfNewJourney 0
lenPos 0
I =  9794848 97.43331655762456
dfNewJourney 0
lenPos 0
I =  9798014 97.45848012078511
dfNewJourney 0
lenPos 0
I =  9790646 97.48364368394564
dfNewJourney 0
lenPos 0
I =  9815616 97.50880724710619
dfNewJourney 0
lenPos 0
I =  9831206 97.53397081026674
dfNewJourney 0
lenPos 0
I =  9787936 97.55913437342728
dfNewJourney 0
lenPos 0
I =  9788485 97.58429793658782
dfNewJourney 0
lenPos 0
I =  9826732 97.60946149974836
dfNewJourney 0
lenPos 0
I =  9833723 97.63462506290891
dfNewJourney 0
lenPos 0
I =  9829411 97.65978862606946
dfNewJourney 0
lenPos 0
I =  9800568 97.68495218922999
dfNewJourney 0
lenPos 0
I =  9778301 97.71011575239054
dfNewJourney 0
lenPos 11
I =  8100909 97.73527931555108
dfNewJourney 0
lenPos 0
I =  9793856 97.76044287871163
dfNewJourney 0
lenPos 0
I =  9834337 97.78560644187216
dfNewJourney 0
lenPos 0
I =  9788588 97.81077000503271
dfNewJourney 0
lenPos 0
I =  9788540 97.83593356819325
dfNewJourney 0
lenPos 0
I =  9818058 97.8610971313538
dfNewJourney 0
lenPos 0
I =  9786164 97.88626069451435
dfNewJourney 0
lenPos 0
I =  9838228 97.91142425767488
dfNewJourney 0
lenPos 0
I =  9783904 97.93658782083543
dfNewJourney 0
lenPos 0
I =  9802176 97.96175138399597
dfNewJourney 0
lenPos 0
I =  9820312 97.98691494715652
dfNewJourney 0
lenPos 0
I =  9828912 98.01207851031705
dfNewJourney 0
lenPos 0
I =  9777424 98.0372420734776
dfNewJourney 0
lenPos 0
I =  9793868 98.06240563663815
dfNewJourney 0
lenPos 0
I =  9792046 98.0875691997987
dfNewJourney 0
lenPos 0
I =  9820324 98.11273276295923
dfNewJourney 0
lenPos 0
I =  9795062 98.13789632611977
dfNewJourney 0
lenPos 0
I =  9783409 98.16305988928032
dfNewJourney 0
lenPos 0
I =  9830288 98.18822345244087
dfNewJourney 0
lenPos 0
I =  9820336 98.2133870156014
dfNewJourney 0
lenPos 0
I =  9817315 98.23855057876195
dfNewJourney 0
lenPos 0
I =  9827059 98.26371414192249
dfNewJourney 17
lenPos 127
I =  9547697 98.28887770508304
dfNewJourney 0
lenPos 0
I =  9808168 98.31404126824359
dfNewJourney 0
lenPos 0
I =  9821859 98.33920483140413
dfNewJourney 0
lenPos 0
I =  9833735 98.36436839456468
dfNewJourney 0
lenPos 0
I =  9787948 98.38953195772521
dfNewJourney 0
lenPos 0
I =  9826897 98.41469552088576
dfNewJourney 0
lenPos 0
I =  9790658 98.4398590840463
dfNewJourney 0
lenPos 0
I =  9801976 98.46502264720685
dfNewJourney 0
lenPos 0
I =  9790608 98.4901862103674
dfNewJourney 0
lenPos 0
I =  9834349 98.51534977352793
dfNewJourney 0
lenPos 0
I =  9828895 98.54051333668848
dfNewJourney 0
lenPos 0
I =  9830290 98.56567689984902
dfNewJourney 0
lenPos 0
I =  9838230 98.59084046300957
dfNewJourney 0
lenPos 0
I =  9786176 98.6160040261701
dfNewJourney 0
lenPos 0
I =  9838242 98.64116758933065
dfNewJourney 0
lenPos 0
I =  9814181 98.6663311524912
dfNewJourney 0
lenPos 0
I =  9788590 98.69149471565174
dfNewJourney 0
lenPos 0
I =  9823041 98.71665827881228
dfNewJourney 0
lenPos 0
I =  9836440 98.74182184197282
dfNewJourney 0
lenPos 0
I =  9796494 98.76698540513337
dfNewJourney 0
lenPos 0
I =  9794850 98.79214896829392
dfNewJourney 0
lenPos 0
I =  9834155 98.81731253145445
dfNewJourney 0
lenPos 0
I =  9799678 98.842476094615
dfNewJourney 0
lenPos 0
I =  9830252 98.86763965777554
dfNewJourney 0
lenPos 0
I =  9829095 98.89280322093609
dfNewJourney 0
lenPos 0
I =  9814193 98.91796678409662
dfNewJourney 0
lenPos 0
I =  9838254 98.94313034725717
dfNewJourney 0
lenPos 0
I =  9843780 98.96829391041771
dfNewJourney 0
lenPos 0
I =  9836452 98.99345747357826
dfNewJourney 0
lenPos 0
I =  9849265 99.01862103673881
dfNewJourney 0
lenPos 0
I =  9798351 99.04378459989934
dfNewJourney 0
lenPos 0
I =  9828900 99.06894816305989
dfNewJourney 0
lenPos 0
I =  9788497 99.09411172622043
dfNewJourney 0
lenPos 0
I =  9829459 99.11927528938098
dfNewJourney 0
lenPos 0
I =  9826902 99.14443885254151
dfNewJourney 1
lenPos 45
I =  9547702 99.16960241570206
dfNewJourney 0
lenPos 0
I =  9790622 99.1947659788626
dfNewJourney 0
lenPos 0
I =  9849291 99.21992954202315
dfNewJourney 0
lenPos 0
I =  9847231 99.24509310518368
dfNewJourney 0
lenPos 0
I =  9795074 99.27025666834423
dfNewJourney 0
lenPos 0
I =  9784001 99.29542023150478
dfNewJourney 0
lenPos 0
I =  9829100 99.32058379466532
dfNewJourney 0
lenPos 0
I =  9829447 99.34574735782587
dfNewJourney 0
lenPos 0
I =  9796975 99.3709109209864
dfNewJourney 0
lenPos 0
I =  9788552 99.39607448414695
dfNewJourney 0
lenPos 0
I =  9793870 99.4212380473075
dfNewJourney 0
lenPos 0
I =  9783930 99.44640161046804
dfNewJourney 0
lenPos 0
I =  9798363 99.47156517362859
dfNewJourney 0
lenPos 0
I =  9804033 99.49672873678914
dfNewJourney 0
lenPos 0
I =  9789269 99.52189229994968
dfNewJourney 0
lenPos 0
I =  9799680 99.54705586311022
dfNewJourney 0
lenPos 0
I =  9803364 99.57221942627076
dfNewJourney 0
lenPos 0
I =  9798349 99.59738298943131
dfNewJourney 0
lenPos 0
I =  9843560 99.62254655259186
dfNewJourney 0
lenPos 0
I =  9831696 99.64771011575239
dfNewJourney 0
lenPos 0
I =  9800300 99.67287367891294

dfNewJourney 0
lenPos 0
I =  9829461 99.69803724207348
dfNewJourney 0
lenPos 0
I =  9829746 99.72320080523403
dfNewJourney 0
lenPos 0
I =  9801988 99.74836436839456
dfNewJourney 0
lenPos 0
I =  9834868 99.77352793155511
dfNewJourney 0
lenPos 0
I =  9786188 99.79869149471565
dfNewJourney 0
lenPos 0
I =  9804837 99.8238550578762
dfNewJourney 0
lenPos 0
I =  9834870 99.84901862103673
dfNewJourney 0
lenPos 0
I =  9836036 99.87418218419728
dfNewJourney 0
lenPos 0
I =  9829473 99.89934574735783
dfNewJourney 0
lenPos 0
I =  9798375 99.92450931051837
dfNewJourney 0
lenPos 0
I =  9843572 99.9496728736789
dfNewJourney 0
lenPos 0
I =  9847451 99.97483643683945
dfNewJourney 0
lenPos 0
I =  9833656 100.0

In [11]:
dfSAFE = dfPosCopy.copy()
len(dfPosCopy)

6050012

In [16]:
test = dfSAFE["Journey Number"].dropna()

test.count()

6050012

In [12]:
dfSAFE.to_csv("testPos.csv", sep = ";")

In [5]:
dfPos = dfPos.replace(".", ",", regex = True).astype(str)

dfPos

,ais_position_latitude,ais_position_longitude,ais_position_timestamp,ship_imo,nav_status_desc
0,51.455,140.92503,2014-01-01 13:01:04,9301421,",,,,,,,,,"
1,51.46248,140.90523000000002,2014-01-02 12:31:21,9301421,",,,,,,"
2,48.74732,140.77492,2014-01-03 22:18:59,9301421,",,,,,,,,,,,,,,,,,,,,,,"
3,43.20852,136.17353,2014-01-04 23:34:08,9301421,",,,,,,,,,,,,,,,,,,,,,,"
4,38.53695,132.4811,2014-01-05 21:30:08,9301421,",,,,,,,,,,,,,,,,,,,,,,"
...,...,...,...,...,...
6050007,35.50135,129.39545,2019-03-20 07:32:20,9847451,",,,,,,,"
6050008,35.50128,129.39549,2019-03-21 23:57:39,9847451,",,,,,,,"
6050009,35.50134,129.39543999999998,2019-03-22 06:25:58,9847451,",,,,,,,"
6050010,32.05095,120.42295,2019-03-21 07:40:57,9833656,",,,,,,,"
6050011,32.05092,120.42295,2019-03-22 07:50:20,9833656,",,,,,,,"